### PR TITLE
Print Azure Core Test Name Before Running

### PR DESCRIPTION
**Pull request by alzimmermsft**
This PR adds a before each test task to print the name of the currently running test. This will enable easier test debugging if a test we to hang in our build and validation pipelines.

### CODE REVIEW

**Comment by mitchdenny** [comment]
I'm surprised that there isn't a configuration to do this for the test runner?

**Comment by alzimmermsft** [comment]
> 
> 
> I'm surprised that there isn't a configuration to do this for the test runner?

JUnit 4 has `RunListener` and JUnit 5 has a `TestExecutionListener`. The `TestExecutionListener` is an interface where the implementing class could be added to tests via an annotation or presented as an SPI that will be hooked up implicitly. I can take a quick dive into what it would take to get a proper listener for the JUnit 5 tests.

**Comment by alzimmermsft** [comment]
Closing in favor of #10313

**Pull request closed without merging**
