### PR TITLE
channelAcquisitionExceptionForWrites

### PR DESCRIPTION
**Pull request by xinlian12**
**Issue:**
For write operation failed with ChannelAcquisition timeout exception, no cross region retry is attempted. 

**Fix:**

- Using ChannelAcquisitionException for channel acquisition timeout situation
- Extends ChannelAcquisitionException of ChannelException
- ChannelException is retriableException, which will be retried by ClientRetryPolicy

### CODE REVIEW

**Review by FabianMeiswinkel — APPROVED** [review]
LGTM

**Comment by xinlian12** [comment]
Tested locally for the following tests:
readFeedDocumentsAfterSplit
readFeedDocumentsAfterSplit_maxScaleCount
createItem_withBulk_split
createItem_withCacheRefresh

**Comment by xinlian12** [comment]
tryGetAddress_repeatedlySetUnhealthyStatus_forceRefresh - flaky tests

**Pull request merged**
