### PR TITLE
Fix unexpected `UnknownFormatConversionException`

### PR DESCRIPTION
**Pull request by bvc3at**
In `String::format` `%1` will raise `UnknownFormatConversionException` which will hide intended exception with it's description

### CODE REVIEW

**Comment by praries880** [comment]
@bvc3at Thanks for the suggested fix. Unfortunately we cant merge this fizx in straight away... as the SDK is generated from the swagger specs.  

@anuchandy Can you take a look at this and see if we need to fix it in the autorest generator?

**Comment by anuchandy** [comment]
Looping in @giakas (Girish Akasapu) from media-service team owning media SDKs.

**Comment by anuchandy** [comment]
The legacy media SDK is no longer actively maintained. It is recommended to switch to new media v3 SDK that has more functionalities. New SDK versions can be found here: https://search.maven.org/search?q=azure-mgmt-media

**Pull request closed without merging**
