### PR TITLE
Aggregate reporting rework

### PR DESCRIPTION
**Pull request by mitchdenny**
There are a bunch of dangling issues resulting from the POM restructuring referenced in this issue: #11197 

The aggregate pipeline is running and passing but isn't generating everything we expect it to, or isn't generating it in the right place. This PR aims to try and tackle all of these issues.

### CODE REVIEW

**Comment by JonathanGiles** [comment]
@mitchdenny What should we do with this PR?

**Comment by mitchdenny** [comment]
I'm happy to close it if you are concerned about leaving it hanging around. Unfortunately I haven't had a chance to come back and work on this one.

**Pull request closed without merging**
