### PR TITLE
fix Microsoft Azure Batch Readme issue

### PR DESCRIPTION
**Pull request by Melanie-Ma**
Fix the issue #18805

@scottaddie , @joshfree , @bgklein and @jongio  for notification

### CODE REVIEW

**Comment by v-xuto** [comment]
@jongio - Can you help ping the corresponding person to review this PR?

**Comment by jongio** [comment]
@joshfree - Who should review this?

**Comment by v-xuto** [comment]
@joshfree - Could you help us review this PR?

**Review by JonathanGiles — APPROVED** [review]

**Pull request merged**
