### PR TITLE
Support JDBC to authenticate with azure identity token credentials 

### PR DESCRIPTION
**Pull request by backwind1233**
# Description

Support Azure hosted PostgreSQL and MySQL services authenticating with Azure AD.

# All SDK Contribution checklist:
- [ ] **The pull request does not introduce [breaking changes]**
- [x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [x] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [x] Pull request includes test coverage for the included changes.

## Feature Checklist
- [x] In JdbcPropertiesBeanPostProcessor, check if users use Azure managed MySql or PostgreSql with password, if so, add a log to remind users use credential-free features.
- [x] 5 new artifacts libraries
   - azure-identity-providers-core
   - azure-identity-providers-jdbc-mysql
   - azure-identity-providers-jdbc-postgresql
   - spring-cloud-azure-starter-jdbc-mysql
   - spring-cloud-azure-starter-jdbc-postgresql

## Related issues:
- [x] #29777
- [x] #29776
- [x] #29219
- [x] #29775
- [x] #29780

### CODE REVIEW

**Comment by backwind1233** [comment]
> **API change check**
> 
> APIView has identified API level changes in this PR and created following API reviews.
> 
> [azure-identity-providers-core](https://apiview.dev/Assemblies/Review/f4e12996a179489db30f294aa11e8301) [azure-identity-providers-jdbc-mysql](https://apiview.dev/Assemblies/Review/82563e244e35448bb144a4529e463409) [azure-identity-providers-jdbc-postgresql](https://apiview.dev/Assemblies/Review/b9ba5683233c4e17907bef74c5630302) [spring-cloud-azure-autoconfigure](https://apiview.dev/Assemblies/Review/2c5dacc3fa924f1b84f088dc006b5d5a) [spring-cloud-azure-starter-jdbc-mysql](https://apiview.dev/Assemblies/Review/5c62a211fd834355bd4a5e245fcf08e2) [spring-cloud-azure-starter-jdbc-postgresql](https://apiview.dev/Assemblies/Review/157c3d9a3bff4825bce8b0cc5c5d3405)

@JonathanGiles @srnagar   Could you help review these API reviews.

**Comment by JonathanGiles** [comment]
> > **API change check**
> > APIView has identified API level changes in this PR and created following API reviews.
> > [azure-identity-providers-core](https://apiview.dev/Assemblies/Review/f4e12996a179489db30f294aa11e8301) [azure-identity-providers-jdbc-mysql](https://apiview.dev/Assemblies/Review/82563e244e35448bb144a4529e463409) [azure-identity-providers-jdbc-postgresql](https://apiview.dev/Assemblies/Review/b9ba5683233c4e17907bef74c5630302) [spring-cloud-azure-autoconfigure](https://apiview.dev/Assemblies/Review/2c5dacc3fa924f1b84f088dc006b5d5a) [spring-cloud-azure-starter-jdbc-mysql](https://apiview.dev/Assemblies/Review/5c62a211fd834355bd4a5e245fcf08e2) [spring-cloud-azure-starter-jdbc-postgresql](https://apiview.dev/Assemblies/Review/157c3d9a3bff4825bce8b0cc5c5d3405)
> 
> @JonathanGiles @srnagar Could you help review these API reviews.

I've left comments on all of them for minor improvements to the maven name / description. For [this](https://apiview.dev/Assemblies/Review/2c5dacc3fa924f1b84f088dc006b5d5a) APIView, are you able to get a good setup with the previous GA release and this new version as revisions, so that they can be diffed? Thanks.

**Comment by backwind1233** [comment]
> > > **API change check**
> > > APIView has identified API level changes in this PR and created following API reviews.
> > > [azure-identity-providers-core](https://apiview.dev/Assemblies/Review/f4e12996a179489db30f294aa11e8301) [azure-identity-providers-jdbc-mysql](https://apiview.dev/Assemblies/Review/82563e244e35448bb144a4529e463409) [azure-identity-providers-jdbc-postgresql](https://apiview.dev/Assemblies/Review/b9ba5683233c4e17907bef74c5630302) [spring-cloud-azure-autoconfigure](https://apiview.dev/Assemblies/Review/2c5dacc3fa924f1b84f088dc006b5d5a) [spring-cloud-azure-starter-jdbc-mysql](https://apiview.dev/Assemblies/Review/5c62a211fd834355bd4a5e245fcf08e2) [spring-cloud-azure-starter-jdbc-postgresql](https://apiview.dev/Assemblies/Review/157c3d9a3bff4825bce8b0cc5c5d3405)
> > 
> > 
> > @JonathanGiles
> >             
> >             Jonathan Giles
> >             FTE @srnagar
> >             
> >             Srikanta Nagaraja
> >             FTE Could you help review these API reviews.
> 
> I've left comments on all of them for minor improvements to the maven name / description. For [this](https://apiview.dev/Assemblies/Review/2c5dacc3fa924f1b84f088dc006b5d5a) APIView, are you able to get a good setup with the previous GA release and this new version as revisions, so that they can be diffed? Thanks.

@JonathanGiles Thank you. I will update.

Before that, I have two things need your help.

1. About artifacts in the [folder](https://github.com/Azure/azure-sdk-for-java/tree/release/spring-cloud-azure-4.4.0/sdk/jdbc) `sdk/jdbc`.
- azure-identity-providers-core
- azure-identity-providers-jdbc-mysql
- azure-identity-providers-jdbc-postgresql
Now we named and put there artifacts as described in the [issue](https://github.com/Azure/azure-sdk/issues/4402#issuecomment-1168279232).
Can we rename put these three libraries to other folders as the table shows below?

|Artifact Name(from --> to)| Folder(from --> to)|
|--|--|
| azure-identity-providers-core --> azure-identity-providers-extension |`sdk/jdbc` --> `sdk/identity`|
| azure-identity-providers-jdbc-mysql  |`sdk/jdbc` --> `sdk/mysql`|
| azure-identity-providers-jdbc-postgresql |`sdk/jdbc` --> `sdk/postgresql`|

**Comment by JonathanGiles** [comment]
For question 1 above, I suggest asking someone like @JimSuplizio or @hallipr.
For question 2 above, I suggest @g2vinay and @billwert confirming they are happy with them.

**Comment by g2vinay** [comment]
@backwind1233 
Here are some changes which can be done:
1. Description of `azure.clientCertificatePath` should mention `PEM/PFX`
2. The `azure.cacheEnabled` field, I assume this refers to persistence token cache, as in memory caching is enabled by default. so, we can consider naming this `azure.persistenceTokenCacheEnabled` and also update its description, that tokens will be securely persisted to disk and reused across multiple process runs.

**Comment by backwind1233** [comment]
> [azure-identity-providers-core](https://apiview.dev/Assemblies/Review/f4e12996a179489db30f294aa11e8301)
> [azure-identity-providers-jdbc-mysql](https://apiview.dev/Assemblies/Review/82563e244e35448bb144a4529e463409)
> [azure-identity-providers-jdbc-postgresql](https://apiview.dev/Assemblies/Review/b9ba5683233c4e17907bef74c5630302)
> [spring-cloud-azure-autoconfigure](https://apiview.dev/Assemblies/Review/2c5dacc3fa924f1b84f088dc006b5d5a)
> [spring-cloud-azure-starter-jdbc-mysql](https://apiview.dev/Assemblies/Review/5c62a211fd834355bd4a5e245fcf08e2)
> [spring-cloud-azure-starter-jdbc-postgresql](https://apiview.dev/Assemblies/Review/157c3d9a3bff4825bce8b0cc5c5d3405)


Hi @JonathanGiles, could you help these API reviews again?
[azure-identity-providers-core](https://apiview.dev/Assemblies/Review/f4e12996a179489db30f294aa11e8301?diffRevisionId=5fc79828ccc845e388bb791f0bbd2879&doc=False&diffOnly=False&revisionId=9bc779c050424fdab258cd05a1ba6a8c)
[azure-identity-providers-jdbc-mysql](https://apiview.dev/Assemblies/Review/82563e244e35448bb144a4529e463409?diffRevisionId=46711762f56749dab613a175ddcb0d51&doc=False&diffOnly=False&revisionId=2db3351539ad4fa9a4d18b434b687af4)
[azure-identity-providers-jdbc-postgresql](https://apiview.dev/Assemblies/Review/b9ba5683233c4e17907bef74c5630302?diffRevisionId=6c8a14b7ccd545cbb172661df23a1602&doc=False&diffOnly=False&revisionId=f9595291a6d046bba4254a3840c4b22a)
[spring-cloud-azure-starter-jdbc-mysql](https://apiview.dev/Assemblies/Review/5c62a211fd834355bd4a5e245fcf08e2?diffRevisionId=da16a3bc8d274cbab931d1addb9cc46a&doc=False&diffOnly=False&revisionId=7365de4130e246edadd9cade3a491748)
[spring-cloud-azure-starter-jdbc-postgresql](https://apiview.dev/Assemblies/Review/157c3d9a3bff4825bce8b0cc5c5d3405?diffRevisionId=7edbcabc2b7b4fcabc335deea93b97cc&doc=False&diffOnly=False&revisionId=87f597592ca14f90ad1e3f2304e5d6ec)
[spring-cloud-azure-autoconfigure](https://apiview.dev/Assemblies/Review/0d9e4c897a184f388b8e353b38176319?diffRevisionId=3b648f7c1a75490789ee7cd78f588ee4&doc=False&diffOnly=False&revisionId=bc034784db464f4ca5b0e95c7bac511d)

**Comment by backwind1233** [comment]
Hi @hallipr, could you give me some suggestions about this?

**Context**
we have three artifacts in the folder [sdk/jdbc](https://github.com/Azure/azure-sdk-for-java/tree/release/spring-cloud-azure-4.4.0/sdk/jdbc).
- azure-identity-providers-core
- azure-identity-providers-jdbc-mysql
- azure-identity-providers-jdbc-postgresql
we named and put there artifacts in the folder `sdk/jdbc` as described in the [issue](https://github.com/Azure/azure-sdk/issues/4402#issuecomment-1168279232).

but since there are folders `mysql`,`postgresql`,`identity` already in the Azure/azure-sdk-for-java repo,

**Question** 
So we are wondering whether it's possible to put these artifacts in the three folders instead of createing a jdbc folder and put them in it, could you give me some suggetions?

|Artifact Name(from --> to)|	Folder(from --> to)|
|--|--|
|azure-identity-providers-core --> azure-identity-providers-extension	|sdk/jdbc --> sdk/identity|
|azure-identity-providers-jdbc-mysql	|sdk/jdbc --> sdk/mysql|
|azure-identity-providers-jdbc-postgresql	|sdk/jdbc --> sdk/postgresql|

**Review by jsquire — CHANGES_REQUESTED** [review]
Please rebase to ensure that the only files included with this pull request are those that you're making changes to.   There are many unrelated files included that should not be.

**Comment by backwind1233** [comment]
> @jsquire Thank you, I will create another PR.

**Comment by backwind1233** [comment]
> > **Question** So we are wondering whether it's possible to put these artifacts in the three folders instead of createing a jdbc folder and put them in it, could you give me some suggetions?
> 
> @backwind1233 Zhihao Guo FTE, We can add them as additional artifacts to the existing folders & ci.yml files pending ArchBoard review. Wes suggests that we "try to locate them with whatever makes the most sense to ship together ... or whichever thing they are most tightly coupled with."

@hallipr Thank you for you reply, we will consider about it.

**Comment by backwind1233** [comment]
Closing this PR, we will release beta version instead of GA version, will create another PR.

**Pull request closed without merging**
