### PR TITLE
Update Java build pipeline

### PR DESCRIPTION
**Pull request by weshaggard**
- Clean-up variable names based on new guidelines
- Publish shipping assets alone into a "packages" artifact

PTAL @bsiegel @JonathanGiles 

cc @Azure/azure-sdk-eng 

Once this change goes in I'll update the java release pipeline to account for the artifact name change.

### CODE REVIEW

**Comment by JonathanGiles** [comment]
Looks good to me. Would appreciate if this could be re-merged once #2955 is merged?

**Comment by weshaggard** [comment]
>Would appreciate if this could be re-merged once #2955 is merged?

Sure I'm not in any particular rush I'll wait until after your change merges.

**Comment by weshaggard** [comment]
FYI @g2vinay

**Comment by weshaggard** [comment]
I filed https://github.com/Azure/azure-sdk-for-java/issues/2963 to track the test failure that keeps happening for the batch live test run.

**Pull request merged**
