### PR TITLE
[Storage] Can tests be faster?

### PR DESCRIPTION
**Pull request by kasobol-msft**
Yes they can.
Before: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=868791&view=results
After: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=868771&view=results
Please disregard some Mac outliers, we'll deal with them here https://github.com/Azure/azure-sdk/issues/2791

There are some flaky tests in the suite, they've been a problem for a while and it seems this parallelization doesn't affect them much.

Before:
image

After:
image

### CODE REVIEW

**Review by gapra-msft — APPROVED** [review]

**Review by alzimmermsft — APPROVED** [review]

**Comment by kasobol-msft** [comment]
For the record. We figured that major improvement here is `-T 1C` flag. The JUnit flags are not effective on Spock. So we either migrate to Spock 2.0 (which is non-trivial effort) or we migrate to JUnit to take advantage.

**Pull request merged**
