### PR TITLE
Update Contact Repository flaky integration test

### PR DESCRIPTION
**Pull request by kushagraThapar**
* Fixes ContactRepositoryIT flaky test by merging `SingleResponseRepositoryIT` into `ContactRepositoryIT`

### CODE REVIEW

**Comment by zhoufenqin** [comment]
> * Fixes ContactRepositoryIT flaky test
> * Decoupled `Contact` from SingleResponseRepositoryIT
> * Created new entity `SingleResponseEntity` and new repository `SingleResponseRepository` for `SingleResponseRepositoryIT`

@kushagraThapar  the `Contract` and `SingleResponseEntity` are similar, why we need this two similar tests?

**Comment by kushagraThapar** [comment]
> > * Fixes ContactRepositoryIT flaky test
> > * Decoupled `Contact` from SingleResponseRepositoryIT
> > * Created new entity `SingleResponseEntity` and new repository `SingleResponseRepository` for `SingleResponseRepositoryIT`
> 
> @kushagraThapar the `Contract` and `SingleResponseEntity` are similar, why we need this two similar tests?

Yeah, that's a valid point. SingleResponseRepositoryIT solely focuses on making sure the single result queries work fine, but I guess I can merge them into one test - and that way we don't need SingleResponseEntity, SingleResponseRepositoryIT and SingleResponseRepository classes.

**Pull request merged**
