### PR TITLE
fixed invalid version

### PR DESCRIPTION
**Pull request by moderakh**
causes build failure on the benchmark.

also adds Kushagra's PR:
https://github.com/Azure/azure-sdk-for-java/pull/15137

### CODE REVIEW

**Review by kushagraThapar — APPROVED** [review]
Thanks @moderakh  - looks good to me.

**Review by saragluna — APPROVED** [review]
LGTM.

**Comment by conniey** [comment]
@kushagraThapar @saragluna @moderakh Hey, before you squash and merge your PR, can you clean up your optional squash and merge message? It is not immediately obvious to me what this PR actually does. We are trying to be better about our repo hygiene.
For example, when I check the history of our repository, using `git log -n 10`... this is what I see.

image

In addition, please put a meaningful PR name.

**Comment by kushagraThapar** [comment]
@conniey  - Sure Connie, we usually do that, this was a corner case, where we had to release a hotfix very urgently. We will take care of this in future :)

**Pull request merged**
