### PR TITLE
FaultInjectionFix-WarmUpFlow

### PR DESCRIPTION
**Pull request by xinlian12**
Issue:
Currently `FaultInjectionServerError.Connection_Delay` is not be applied to warm up flow

Fix:
`Connection_Delay` to also apply on warm up flow

### CODE REVIEW

**Review by FabianMeiswinkel — APPROVED** [review]
LGTM

**Comment by xinlian12** [comment]
Tested the following tests locally:
pkVersion readFeedDocumentsAfterSplit
createItem_withBulk_split

**Pull request merged**
