### PR TITLE
Update Jackson, Netty, and Reactor Versions

### PR DESCRIPTION
**Pull request by alzimmermsft**
* Jackson -> 2.12.5
* Gson -> 2.8.8
* Netty -> 4.1.68.Final
* Netty tcnative -> 2.0.43.Final
* Reactor Core -> 3.4.10
* Reactor Netty -> 1.0.11

### CODE REVIEW

**Review by lmolkova — APPROVED** [review]
Can you also update one in the test matrix? https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/supported-version-matrix.json 

I'll try to update the version script to do it too

**Comment by alzimmermsft** [comment]
> Can you also update one in the test matrix? https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/supported-version-matrix.json
> 
> I'll try to update the version script to do it too

For that, do we want to use the latest patch version in the minor version or the earliest patch version? The merged code should generally be at the latest, or close to it, and that would cover the latest patch version in the currently targeted minor version.

**Comment by lmolkova** [comment]
> For that, do we want to use the latest patch version in the minor version or the earliest patch version? The merged code should generally be at the latest, or close to it, and that would cover the latest patch version in the currently targeted minor version.

I think for each supported major.minor, the matrix should have the latest patch, i.e. `2.12.4": "jackson2_12` -> `2.12.5": "jackson2_12`. I  assume patch bar is relatively high and it contains an important fix. If patch 0 has a critical issue, we de-facto can't support it

**Comment by kushagraThapar** [comment]
@alzimmermsft  - can we please also run cosmos CI - just to make sure things look good from functional point of view.

**Comment by kushagraThapar** [comment]
@alzimmermsft  - for future, I would love to see the list of updated dependencies in the description - it will make these version update PR reviews easier. 
I will update the description of this PR.

**Review by mssfang — APPROVED** [review]

**Review by weidongxu-microsoft — APPROVED** [review]

**Review by haolingdong-msft — APPROVED** [review]

**Pull request merged**
