### PR TITLE
Fixed for complete native support for remaining azure-resourcemanager libs

### PR DESCRIPTION
**Pull request by v-hongli1**
# Description

Please add an informative description that covers that changes made by the pull request and link all relevant issues.

If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.

# All SDK Contribution checklist:
- [ ] **The pull request does not introduce [breaking changes]**
- [ ] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [ ] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Review by weidongxu-microsoft — COMMENTED** [review]
The json file depends on the Java files generated via codegen.

Are you sure there is not even a single new file added, or old file removed/renamed?

**Comment by v-hongli1** [comment]
@weidongxu-microsoft 
There is no `new file added, or old file removed/renamed` in the parts submitted.

**Review by weidongxu-microsoft — APPROVED** [review]

**Comment by weidongxu-microsoft** [comment]
> @weidongxu-microsoft The situation as `adding new files, or deleting/renaming old files` not found in the submitted section.

No. I mean is there any such case when you "generate" the code (but not included in submit).

**Comment by v-hongli1** [comment]
> > @weidongxu-microsoft The situation as `adding new files, or deleting/renaming old files` not found in the submitted section.
> 
> No. I mean is there any such case when you "generate" the code (but not included in submit).

I have confirmed the generated codes one by one, and no such situation occurs except for `monitor`.

**Review by weidongxu-microsoft — APPROVED** [review]

**Review by XiaofeiCao — APPROVED** [review]

**Pull request merged**
