### PR TITLE
ChangeMaxMicroBatchInterval

### PR DESCRIPTION
**Pull request by xinlian12**
Please reference PR https://github.com/Azure/azure-sdk-for-java/pull/25897 for more context.

**This PR contains the change target for MaxMicroBatchInterval. Changes included:**
1. After getting the complete signal, Change the max micro batch interval from 1000ms to 100ms.
Did not change to use 100ms constant as it may cause too much noise for spark.
Please refer to the test results and 
.net SDK also use 100ms by default: https://github.com/Azure/azure-cosmos-dotnet-v3/blob/c8935ac2f864fb829f5d941dda07c74aec86a677/Microsoft.Azure.Cosmos/src/Batch/BatchAsyncStreamer.cs#L24

2. Cancel scheduled batch flush tasks after whole batch completed.
Each time container.executeBulkExecutors, a new background task is scheduled for batch flush. But after the batch finishes, the scheduled tasks never got cancelled. 

**Local Tests:**
<div style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; direction: ltr;">

SDK version | Total time | Concurrency | Doc size | Total Items
-- | -- | -- | -- | --
Master | 98923 | 1 | 1.8MB | 1000
Master + Flush interval 100 constant | 98251 | 1 | 1.8MB | 1000
Master + Flush interval first 1000 then 100 | 89469 | 1 | 1.8MB | 1000
Master + Flush interval 100 constant | 78714 | 2 | 1.8MB | 1000
Master + Flush interval first 1000 then 100 | 77717 | 2 | 1.8MB | 1000
4.16.0 | 77720 | 2 | 1.8MB | 1000

</div>

<div style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; direction: ltr;">

SDK version | Total time | Concurrency | Doc size | Total Items
-- | -- | -- | -- | --
Master | 175547 | 1 | 122KB | 10000
Master + Flush interval 100 constant | 169766 | 1 | 122KB | 10000
Master + Flush interval first 1000 then 100 | 149775 | 1 | 122KB | 10000
Master + Flush interval 100 constant | 82311 | 2 | 122KB | 10000
Master + Flush interval first 1000 then 100 | 83884 | 2 | 122KB | 10000
4.16.0 | 95191 | 2 | 122KB | 10000

</div>

<div style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; direction: ltr;">

SDK version | Total time | Concurrency | Doc size | Total Items
-- | -- | -- | -- | --
Master | 79223 | 1 | 61KB | 10000
Master + Flush interval 100 constant | 72712 | 1 | 61KB | 10000
Master + Flush interval first 1000 then 100 | 72210 | 1 | 61KB | 10000
Master + Flush interval 100 constant | 36558 | 2 | 61KB | 10000
Master + Flush interval first 1000 then 100 | 42501 | 2 | 61KB | 10000
4.16.0 | 40224 | 2 | 61KB | 10000

</div>

<div style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; direction: ltr;">

SDK version | Total time | Concurrency | Doc size | Total Items
-- | -- | -- | -- | --
Master | 7078 | 1 | <1KB | 10000
Master + Flush interval 100 constant | 7237 | 1 | <1KB | 10000
Master + Flush interval first 1000 then 100 | 7176 | 1 | <1KB | 10000
Master + Flush interval 100 constant | 4932 | 2 | <1KB | 10000
Master + Flush interval first 1000 then 100 | 5313 | 2 | <1KB | 10000
4.16.0 | 4855 | 2 | <1KB | 10000

</div>

### CODE REVIEW

**Review by kushagraThapar — APPROVED** [review]
LGTM

**Review by FabianMeiswinkel — APPROVED** [review]
LGTM

**Review by kushagraThapar — APPROVED** [review]
LGTM

**Comment by xinlian12** [comment]
Failed tests: should create exactly 5 times more partitions than with Default for Aggressive
Tested locally passed
and this PR does not touch any logic relates to decide the partitions

**Pull request merged**
