### PR TITLE
Cosmos: fix checkstyle

### PR DESCRIPTION
**Pull request by ChenTanyi**

### CODE REVIEW

**Comment by weidongxu-microsoft** [comment]
The `ConnectorOffer` is put back in enum.

**Comment by ChenTanyi** [comment]
@weidongxu-microsoft Yes, it is back in compile fix commit.

**Comment by ChenTanyi** [comment]
cosmos was suppressed by https://github.com/azure/azure-sdk-for-java/blob/7b0fcde/eng/code-quality-reports/src/main/resources/checkstyle/checkstyle-suppressions.xml#L390

**Comment by ChenTanyi** [comment]
remove suppress in https://github.com/Azure/azure-sdk-for-java/pull/9955

**Pull request merged**
