### PR TITLE
Annotated query paging and sorting

### PR DESCRIPTION
**Pull request by Blackbaud-MikeLueders**
This adds support for using Pageable and Sort parameters to methods annotated with @Query.  I specifically didn't add Pageable support to the reactive piece (i tend to agree with the accepted answer here https://stackoverflow.com/questions/46384618/how-apply-pagination-in-reactive-spring-data, that paging is not necessarily compatible with the reactive model), though i did add support for reactive sorting.

### CODE REVIEW

**Review by kushagraThapar — COMMENTED** [review]
@Blackbaud-MikeLueders thanks your contribution, the changes look good to me overall. 

However, one concern I have is re-using `Address` entity in both `AddressRepositoryIT` and `PageableAddressRepositoryIT` - as the testing framework executes these tests in parallel, so using the same entity in two integration tests makes it messy (as they both will operate on the same container in cosmosdb), which can sometimes create flakiness in the tests, as one of them tries to save all, then delete all, while the other integration test class is running some tests. That was the sole purpose of having different entities for different integration tests. 
So let's think about it before deleting `PageableAddress` entity class.

**Comment by Blackbaud-MikeLueders** [comment]
@kushagraThapar Are you sure the tests are run in parallel?  There are only two instances of forkCount being configured in the surefire plugin, sdk/parents/azure-client-sdk-parent/pom.xml which sets forkCount to 1 and sdk/servicebus/microsoft-azure-servicebus/pom.xml which sets forkCount to 15 and I assume the cosmos tests are using the sdk/parents/azure-client-sdk-parent/pom.xml configuration.  That said, you raise a good point - even if they aren't currently run in parallel, I wouldn't want to introduce anything that would prevent them from being in the future.  

However, it's not at all obvious that each integration test must define its own entity and cannot rely on shared entities and I can see other people making this same mistake in the future.  How would you feel about introducing a locking mechanism for the integration tests such that they would not interfere with each other if run in parallel (not as part of this change but as a separate PR)?

**Comment by kushagraThapar** [comment]
> @kushagraThapar Are you sure the tests are run in parallel? There are only two instances of forkCount being configured in the surefire plugin, sdk/parents/azure-client-sdk-parent/pom.xml which sets forkCount to 1 and sdk/servicebus/microsoft-azure-servicebus/pom.xml which sets forkCount to 15 and I assume the cosmos tests are using the sdk/parents/azure-client-sdk-parent/pom.xml configuration. That said, you raise a good point - even if they aren't currently run in parallel, I wouldn't want to introduce anything that would prevent them from being in the future.
> 
> However, it's not at all obvious that each integration test must define its own entity and cannot rely on shared entities and I can see other people making this same mistake in the future. How would you feel about introducing a locking mechanism for the integration tests such that they would not interfere with each other if run in parallel (not as part of this change but as a separate PR)? In addition, the current test naming strategy can be confusing b/c it is oriented around the test entity name rather than what is being tested. For example, `PageablePersonRepositoryIT` is actually testing paged findAll queries while `PageableAddressRepositoryIT` is testing paged find queries. And then there's `PageableMemoRepositoryIT` which also tests paged findAll queries but also offsets and limits (it looks to me like there are duplicate tests between this and PageablePersonRepositoryIT). For someone not intimately familiar with the project, it makes figuring out where to add a new test fairly difficult. Would you be opposed to reorganizing the test by their behavior rather than the entity they operate on?

I agree to both the locking mechanism for parallel tests run (only if locking doesn't slows down things), and definitely renaming to have better identification of tests. We don't need to make those changes as part of this PR. So we are good on this PR, I will just kick in the live integration tests to make sure they pass before I merge it in.

**Review by kushagraThapar — APPROVED** [review]
LGTM, thanks @Blackbaud-MikeLueders

**Comment by luissalgadofreire** [comment]
Thanks for the mention, @kushagraThapar.

> Worth discussing these changes here with the requirement - #19138
> 
> > This adds support for using Pageable and Sort parameters to methods annotated with @query. I specifically didn't add Pageable support to the reactive piece (i tend to agree with the accepted answer here https://stackoverflow.com/questions/46384618/how-apply-pagination-in-reactive-spring-data, that paging is not necessarily compatible with the reactive model), though i did add support for reactive sorting.
> 
> I agree that reactive concept should not have pagination as it does not inlines with reactive model.
> @luissalgadofreire - Worth discussing your issue here - #19138

Not sure if you  suggested discussing here on the ticket I opened. If need be, I can transpose my comments there.

** Pagination in Reactive **

Before making the suggestion, I researched the topic a bit and also came by that stackoverflow [accepted answer](https://stackoverflow.com/questions/46384618/how-apply-pagination-in-reactive-spring-data). It defends that reactive should not approach pagination in the same manner as  imperative, it does not exactly defend there should be no pagination.

** Performance of OFFSET LIMIT in Cosmos DB**

In the [docs](https://docs.microsoft.com/en-us/azure/cosmos-db/sql-query-offset-limit), the following is said regarding performance of OFFSET LIMIT which leads to using `skip` and `take` (typical reactive style operations), which is what @Blackbaud-MikeLueders is suggesting:

> When OFFSET LIMIT is used in conjunction with an ORDER BY clause, **the result set is produced by doing skip and take on the ordered values**. If no ORDER BY clause is used, it will result in a deterministic order of values.
> 
> ...
> 
> Both the OFFSET count and the LIMIT count are required in the OFFSET LIMIT clause. If an optional ORDER BY clause is used, the result set is produced by doing the skip over the ordered values. Otherwise, the query will return a fixed order of values.
> **The RU charge of a query with OFFSET LIMIT will increase as the number of terms being offset increases**. **For queries that have multiple pages of results, we typically recommend using continuation tokens**. Continuation tokens are a "bookmark" for the place where the query can later resume. If you use OFFSET LIMIT, there is no "bookmark". If you wanted to return the query's next page, you would have to start from the beginning.
> You should use OFFSET LIMIT for cases when you would like to skip items entirely and save client resources. For example, you should use OFFSET LIMIT if you want to skip to the 1000th query result and have no need to view results 1 through 999. On the backend, OFFSET LIMIT still loads each item, including those that are skipped. The performance advantage is a savings in client resources by avoiding processing items that are not needed.

It is suggested that "*for queries that have multiple pages of results, we typically recommend using continuation tokens*".

Base on the docs, a solution with continuation tokens is advisable for pagination. 

** Pagination in the Java SDK **

Azure's Java SDK does have a [way to paginate in a reactive style](https://docs.microsoft.com/en-us/azure/developer/java/sdk/pagination#observe-pages). That would be `PagedFlux`:

> Observe pages
> 
> The following example shows how the PagedFlux API lets you observe each page asynchronously, again by using a byPage() API and by providing a consumer, error consumer, and a completion consumer.
> 
> ```
> asyncClient.listSecrets().byPage()
>   .subscribe(page -> {
>           System.out.println("Response code: " + page.getStatusCode());
>           System.out.println("Continuation Token: " + page.getContinuationToken());
>           page.getElements().forEach(secret -> System.out.println("Secret value: " + secret))
>       },
>       ex -> System.out.println("Error listing pages with secret: " + ex.getMessage()),
>       () -> System.out.println("Successfully listed all pages with secret"));
> ```

** Pagination in the Cosmos DB Java SDK **

Cosmos DB Java SDK also has a way to paginate: [CosmosPagedFlux](https://docs.microsoft.com/en-us/java/api/com.azure.cosmos.util.cosmospagedflux.bypage?view=azure-java-stable) and its `byPage` method.

** ReactiveCosmosRepository does not make use of the above facilities to provide the same feature

In the end, it would be nice to use something that the Java SDK already offers from inside `ReactiveCosmosRepository`. Something like:

```
@NoRepositoryBean
public interface ReactiveCosmosDerivedRepository<T, K> extends ReactiveCosmosRepository<T, K> {

    CosmosPagedFlux<T> findAllByIsDeleted(boolean b);

}
```

Pagination would then simply amount to using the `byPage` method of the returned CosmosPagedFlux instance.

It's a matter of using a feature that already exists in the Java SDK and integrating it into Spring Data Cosmos.

**Comment by Blackbaud-MikeLueders** [comment]
@luissalgadofreire i commented on the original issue, that's probably where the discussion should be focused

**Pull request merged**
