### PR TITLE
Correcting parameter order workload identity

### PR DESCRIPTION
**Pull request by sergiommarcial**
# Description

Please add an informative description that covers that changes made by the pull request and link all relevant issues.

If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.

# All SDK Contribution checklist:
- [X] **The pull request does not introduce [breaking changes]**
- [ ] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [X] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [X] Title of the pull request is clear and informative.
- [X] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [X] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Comment by billwert** [comment]
Hello @sergiommarcial! Can you help me understand the need for this change?

**Comment by sergiommarcial** [comment]
> Hello @sergiommarcial! Can you help me understand the need for this change?

Of course, while using the library it took me a while to figure it out why I was getting a 400 error when executing the call to the v2/oath endpoint when I noticed that it was setting the client id not the tenant id in the URL, after some digging I found this in this code

[clientId](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/identity/azure-identity/src/main/java/com/azure/identity/WorkloadIdentityCredential.java#L66) the library is expecting 

```java
WorkloadIdentityCredential(String tenantId, String clientId, String federatedTokenFilePath, IdentityClientOptions identityClientOptions) 
```

but here https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/identity/azure-identity/src/main/java/com/azure/identity/WorkloadIdentityCredentialBuilder.java#L75 the `clientId` is sent first

```java
 WorkloadIdentityCredential(clientId, tenantId, tokenFilePath, identityClientOptions.clone());
```

**Comment by billwert** [comment]
That's a great catch! Thank you!

Instead of this fix I think a better fix is to change the call in `WorkloadIdentityCredentialBuilder` to match the existing parameters. As `WorkloadIdentityCredential`'s constructor is public changing the order of the parameters would be breaking.

Would you mind swapping this PR to do that instead?

cc: @g2vinay

**Comment by sergiommarcial** [comment]
> That's a great catch! Thank you!
> 
> Instead of this fix I think a better fix is to change the call in `WorkloadIdentityCredentialBuilder` to match the existing parameters. As `WorkloadIdentityCredential`'s constructor is public changing the order of the parameters would be breaking.
> 
> Would you mind swapping this PR to do that instead?
> 
> cc: @g2vinay

I was doing that but most of the functions have `clientid` first so to avoid confusion I did it like this, I don't mind changing it tho

**Comment by billwert** [comment]
> > That's a great catch! Thank you!
> > Instead of this fix I think a better fix is to change the call in `WorkloadIdentityCredentialBuilder` to match the existing parameters. As `WorkloadIdentityCredential`'s constructor is public changing the order of the parameters would be breaking.
> > Would you mind swapping this PR to do that instead?
> > cc: @g2vinay
> 
> I was doing that but most of the functions have `clientid` first so to avoid confusion I did it like this, I don't mind changing it tho

Sadly we're not consistent on this across the library - you can find plenty of examples either way. Thanks for catching this!

**Comment by sergiommarcial** [comment]
> 9eec1b1

Comment addressed with [9eec1b1](https://github.com/Azure/azure-sdk-for-java/pull/34721/commits/9eec1b1816e53ee1c90f9c4715ddf2251c2b086a)

**Review by billwert — APPROVED** [review]

**Pull request merged**
