### PR TITLE
azure-mgmt-utility uses Java 8 without declaring

### PR DESCRIPTION
**Pull request by sideshowcoder**
`import java.util.function.Predicate' which is used in the tests like
`resource-management/azure-mgmt-utility/src/test/java/com/microsoft/azure/utility/compute/VMImagesTests.java`
is not available in Java 1.6.

Alternatively the guave libraries could be used, but that would have
been a bigger change.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@sideshowcoder__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by jianghaolu** [comment]
@xindzhan 

I think being able to support 1.6 would be ideal.

**Comment by sideshowcoder** [comment]
@jianghaolu makes sense especially as the Java 8 features are only used in the tests, worth fixing up so as a new import in eclipse currently does not compile without changing the Java Version by hand...

**Comment by jianghaolu** [comment]
Hi @sideshowcoder 

We are closing this since we are moving to the new 1.0.0 SDK. The utility library is gone. However, the SDK itself will be "convenient" as we build in all these convenience.

I invited you to take a look at this repo: https://github.com/microsoft/azure-shortcuts-for-java as it is our experiment / prototype of our upcoming 1.0.0 SDK. The production code in development is living in `master` branch already so feel free to jump in and try and even yell.

And we will target Java 1.7.

And thanks for contributing BTW. 

-Jianghao

**Pull request closed without merging**
