### PR TITLE
Use APIs that don't compile a Pattern each call

### PR DESCRIPTION
**Pull request by alzimmermsft**
Use APIs that don't compile a `Pattern` on each call (String.replaceAll, String.replaceFirst, String.split [when split String is > 1 character]). Uncertain if the changed code is in a hot path but the overall reduction of using `Pattern.compile` should improve performance a good deal.

### CODE REVIEW

**Review by kushagraThapar — APPROVED** [review]
LGTM, thanks a lot @alzimmermsft - worth running full live CI on this PR. 
Wondering, how did you find these string pattern issues ?

**Comment by alzimmermsft** [comment]
> 

Just prior experience with doing performance improvements in `azure-core` and reading through source code for Java versions.

**Pull request merged**
