### PR TITLE
Fix javadoc package groups

### PR DESCRIPTION
**Pull request by srnagar**
Updated a couple of core packages that were in "Other group" and removed test packages.

### CODE REVIEW

**Comment by weshaggard** [comment]
@srnagar this looks like it started to cause some build issues: 

```
[ERROR] Error occurred during initialization of VM, trying to use an empty MAVEN_OPTS...
[ERROR] MavenInvocationException: Error when invoking Maven, consult the invoker log file: /home/vsts/work/1/s/sdk/core/azure-core-http-netty/target/invoker/maven-javadoc-plugin503788307.txt
[ERROR] Error fetching link: /home/vsts/work/1/s/sdk/core/azure-core-test/target/apidocs. Ignored it.
[ERROR] Error fetching link: /home/vsts/work/1/s/sdk/core/azure-core-test/target/apidocs. Ignored it.
```
Looking at the context of that log:
```
M2_HOME=d:\bin\Tools\apache-maven-3.6.0\bin\..
MAVEN_OPTS=-Xmx3072m -Dorg.slf4j.simpleLogger.defaultLogLevel=error -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
JAVA_HOME=C:\Program Files\Zulu\zulu-8
JAVA_OPTS=null

 

[INFO] Scanning for projects...
[INFO] Inspecting build with total of 1 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO] 
[INFO] ---------------------< com.azure:azure-core-test >----------------------
[INFO] Building Microsoft Azure Java Core Test Library 1.0.0-preview.7
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] >>> maven-javadoc-plugin:3.1.1:javadoc (default-cli) > generate-sources @ azure-core-test >>>
[WARNING] The POM for com.azure:azure-core:jar:1.0.0-preview.7 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.075 s
[INFO] Finished at: 2019-10-21T10:15:25-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project azure-core-test: Could not resolve dependencies for project com.azure:azure-core-test:jar:1.0.0-preview.7: Failure to find com.azure:azure-core:jar:1.0.0-preview.7 in https://oss.sonatype.org/content/repositories/snapshots/ was cached in the local repository, resolution will not be reattempted until the update interval of ossrh has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

It would appear as though we cannot exclude the azure-core-test stuff.

**Comment by srnagar** [comment]
@weshaggard The test javadoc errors are ignored. The real error that caused the build failure is 

```[ERROR] Failed to execute goal on project azure-core-test: Could not resolve dependencies for project com.azure:azure-core-test:jar:1.0.0-preview.7: Failure to find com.azure:azure-core:jar:1.0.0-preview.7 in https://oss.sonatype.org/content/repositories/snapshots/ was cached in the local repository, resolution will not be reattempted until the update interval of ossrh has elapsed or updates are forced -> [Help 1]```

For some reason, the azure-core jar was not found.

**Comment by JimSuplizio** [comment]
> @weshaggard The test javadoc errors are ignored. The real error that caused the build failure is
> 
> `[ERROR] Failed to execute goal on project azure-core-test: Could not resolve dependencies for project com.azure:azure-core-test:jar:1.0.0-preview.7: Failure to find com.azure:azure-core:jar:1.0.0-preview.7 in https://oss.sonatype.org/content/repositories/snapshots/ was cached in the local repository, resolution will not be reattempted until the update interval of ossrh has elapsed or updates are forced -> [Help 1]`
> 
> For some reason, the azure-core jar was not found. Can you please give me the link to the failed build? I will look into it.

The [keyvault CI ](https://dev.azure.com/azure-sdk/public/_build/results?buildId=161410&view=logs&j=9d510ff3-53a8-5192-bd2d-466ce830bc13)is currently outright failing because of this but the Build Java 8 and Build Java LTS tasks for [other pipelines](https://dev.azure.com/azure-sdk/public/_build/results?buildId=161379&view=logs&j=9d510ff3-53a8-5192-bd2d-466ce830bc13) are also showing a similar failure but passing their builds. In both cases this started showing up after this PR was submitted. It's a bit odd that none of the CI builds were triggered with the change to pom.client.xml

**Comment by weshaggard** [comment]
>@weshaggard The test javadoc errors are ignored. 

Even if they are ignored they still cause errors to show up in the build logs and we should get that cleaned up.

**Comment by srnagar** [comment]
KeyVault issue is fixed in this PR - https://github.com/Azure/azure-sdk-for-java/pull/5963

I will look into the errors that are ignored.

**Pull request merged**
