### PR TITLE
Test Spring integration tests

### PR DESCRIPTION
**Pull request by moarychan**
# Description

There's some difference between the main and spring boot 3 branches, this PR is to test those changes to see whether are needed or optional.

Corresponding changes in this PR: https://github.com/Azure/azure-sdk-for-java/pull/32512

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [ ] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [x] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [ ] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Comment by moarychan** [comment]
Hi @backwind1233  please help check, thanks!

**Comment by backwind1233** [comment]
I think https://github.com/moarychan/azure-sdk-for-java/blob/3bcc5ba06ba20e9f176d74c69e06151a0d754d6f/sdk/spring/spring-cloud-azure-integration-tests/pom.xml#L115 is the keypoint, could this be removed?

**Comment by backwind1233** [comment]
I don't understand the PR context here "Test IT configuration."
Could you explain more?

**Comment by backwind1233** [comment]
I added this [commit](https://github.com/Azure/azure-sdk-for-java/pull/32531/commits/d1a98ee7664c5b4b1be83ea81017138cf4443f05), let's check the result.

**Comment by moarychan** [comment]
> @moarychan I think [this](https://github.com/moarychan/azure-sdk-for-java/blob/3bcc5ba06ba20e9f176d74c69e06151a0d754d6f/sdk/spring/spring-cloud-azure-integration-tests/pom.xml#L115-L122) is the key point,
> 
> ```
>    
>     
>     <dependency>
>       <groupId>com.h2database</groupId>
>       <artifactId>h2</artifactId>
>       <scope>test</scope>
>     </dependency>
> ```
> 
> could this be removed also?

No, will encounter the `Failed to determaie a suitable driver class`

**Comment by backwind1233** [comment]
> @moarychan I added this [commit](https://github.com/Azure/azure-sdk-for-java/pull/32531/commits/d1a98ee7664c5b4b1be83ea81017138cf4443f05), let's check the result.

This commit has been reverted. @moarychan

**Review by backwind1233 — APPROVED** [review]
LGTM

**Comment by saragluna** [comment]
So @moarychan @backwind1233, what the reason of removing the h2 configuration?

**Pull request merged**
