### PR TITLE
Add Analyze From Source to Core CI

### LINKED ISSUE #21637: Investigate a From Source Analyze CI Job
Investigate adding another CI job which performs linting analyzing using From Source SDK builds. A commonly seen issue is that an SDK has API changes which another SDK uses but the current Analyze job only validates linting for the SDKs in the service group. An example would be azure-core adds a new API which triggers a RevApi warning which can be safely ignored but the API is also used by azure-search-documents, azure-search-documents won't have any RevApi issues when linting because it doesn't see the new azure-core changes but once azure-core releases and azure-search-documents takes the dependency it too begins having RevApi linting issues.

### PR DESCRIPTION
**Pull request by alzimmermsft**
Fixes #21637

This PR introduces a new job to the Core CI run which performs linting using `From Source` builds. The purpose of the new job is to catch scenarios where new functionality into Core which leads to dependent libraries having linting errors, mainly RevApi.

### CODE REVIEW

**Comment by benbp** [comment]
I like splitting them out, this is great.

I haven't looked too closely, but is the project list/source checkout stuff common enough that it could be shared?

**Comment by alzimmermsft** [comment]
> I like splitting them out, this is great.
> 
> I haven't looked too closely, but is the project list/source checkout stuff common enough that it could be shared?

Yes, I think project list and source checkout should be converted into a stand-alone step. I believe it would be best to re-tool the [initialize-test-environment.yml](https://github.com/Azure/azure-sdk-for-java/blob/main/eng/pipelines/templates/steps/initialize-test-environment.yml), could be a simple as a renaming.

**Comment by alzimmermsft** [comment]
Closing this PR as the From Source linting won't be too much of a value add as it will run against unreleased version of SDKs which are always beta and won't catch the cases laid out by the issue.

**Pull request closed without merging**
