### PR TITLE
deviceupdate, enable jacoco after GA

### PR DESCRIPTION
**Pull request by weidongxu-microsoft**
# Description

Please add an informative description that covers that changes made by the pull request and link all relevant issues.

If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.

# All SDK Contribution checklist:
- [ ] **The pull request does not introduce [breaking changes]**
- [ ] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [ ] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Comment by weidongxu-microsoft** [comment]
[WARNING] Rule violated for bundle azure-iot-deviceupdate: lines covered ratio is 0.28, but expected minimum is 0.40
[WARNING] Rule violated for bundle azure-iot-deviceupdate: branches covered ratio is 0.13, but expected minimum is 0.30

**Comment by weidongxu-microsoft** [comment]
@vcolin7 

Do we generally require GAed SDK to enable Jacoco?

I assume we can use lower number, say 0.2 and 0.1. David can see if he want to improve later.

PS: in initial pom.xml (at first DPG) Jacoco is disabled as there is all disabled test cases that was auto-generated for dev reference.

**Comment by weidongxu-microsoft** [comment]
test coverage is required https://github.com/Azure/azure-sdk-for-java/wiki/Getting-Started-Guidance#before-ga

**Comment by weidongxu-microsoft** [comment]
@dpokluda Note the enabling of SDK test coverage for GA packages. Your target would be 0.4

**Review by dpokluda — APPROVED** [review]

**Review by haolingdong-msft — APPROVED** [review]

**Pull request merged**
