### PR TITLE
Removed generic IO exception condition in network failure. Replaced with specific exceptions. Included in unit testing

### PR DESCRIPTION
**Pull request by kushagraThapar**
* Removed generic IO exception condition in network failure. Replaced with specific exceptions. Included in unit testing

### CODE REVIEW

**Review by FabianMeiswinkel — APPROVED** [review]
LGTM - thanks

**Review by milismsft — APPROVED** [review]

**Comment by FabianMeiswinkel** [comment]
Forcing merge to be able to include in hotfix 4.7.0 - tests failed due to test flakiness - unrelated to changes in this PR

**Pull request merged**
