### PR TITLE
Fixing Pagintation When Retrieving a Page Other Than the First Page

### PR DESCRIPTION
**Pull request by trande4884**
# Description

Fixing pagination via the Spring SDK when PageRequest and CosmosPageRequest are used with a page other than the first page. Updated/fixed unit tests.

If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [x] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Review by FabianMeiswinkel — APPROVED** [review]
LGTM

**Review by kushagraThapar — CHANGES_REQUESTED** [review]
LGTM @trande4884 , great work.
However, we should add more tests for this.

**Comment by trande4884** [comment]
> LGTM @trande4884 , great work. However, we should add more tests for this.

@kushagraThapar I added some more tests. Let me know if there are any other specific cases you want covered.

**Review by kushagraThapar — APPROVED** [review]
Thanks for adding the tests @trande4884 , awesome work!

**Pull request merged**
