### PR TITLE
Upgrade Jackson and JaCoCo dependencies to next version

### PR DESCRIPTION
**Pull request by srnagar**
Newer versions of Jackson and Jacoco jars are available. This change is to switch to the latest version.

### CODE REVIEW

**Comment by JimSuplizio** [comment]
@srnagar, I'm fine being on more recent versions of things but I am curious as to why we're updating. Is there any particular reason that we're updating the dependency versions?

**Comment by srnagar** [comment]
@JimSuplizio MSAL is one of the libraries that we depend on they have upgraded to the newer version of Jackon and we want to be in sync with the latest transitive versions used by any of our direct dependencies.

For JaCoCo, it's just an internal dependency that provides better test coverage reporting.

**Comment by kushagraThapar** [comment]
Failed CIs are known issues, flaky tests. Change looks good to me.

**Pull request merged**
