### PR TITLE
fixed SampleCheckpointStore claimOwnership lookup

### PR DESCRIPTION
**Pull request by rayevan**
# Description

SampleCheckpointStore claimOwnership get call to partitionOwnershipMap missing prefix and separator

# All SDK Contribution checklist:
- [X] **The pull request does not introduce [breaking changes]**
- [x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [X] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [X] Title of the pull request is clear and informative.
- [X] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [X] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Review by conniey — APPROVED** [review]
LGTM.  Thank you!

**Comment by conniey** [comment]
@rayevan Whenever you can address this CLA bot post, we can auto-merge it in. :D Thanks! https://github.com/Azure/azure-sdk-for-java/pull/38004#issuecomment-1919721597

**Comment by rayevan** [comment]
@microsoft-github-policy-service agree

**Pull request merged**
