### PR TITLE
 Fixed issue that prevented creating while providing an `AzureNamedKeyCredential` as the sole form of authentication.

### PR DESCRIPTION
**Pull request by vcolin7**
Fixes: #22384.

### CODE REVIEW

**Comment by alzimmermsft** [comment]
Should Tables follow a similar pattern that Storage uses where other credentials are nulled if a new credential type is passed? AKA if I set a valid connection string, then set a SAS token the connection string based credential will be removed.

**Comment by vcolin7** [comment]
>
>
> Should Tables follow a similar pattern that Storage uses where other credentials are nulled if a new credential type is passed? AKA if I set a valid connection string, then set a SAS token the connection string based credential will be removed.

@alzimmermsft That's the original design we had but @srnagar suggested we went with letting users set whatever values they want and throwing if configuration is invalid when calling build methods.

That means that as of today, since users can call `connectionString()` to pass endpoint and authentication information, it can be used in conjunction with the `endpoint()` and `credential()` methods and we have to validate the information passed matches what's in the connection string. This definitely makes it so we have to make more than a few checks under the hood, but one could argue it provides some more builder setup options while keeping transparency on what settings are being used when building a client, as opposed to implicitly making a parameter `null` when setting something else. I think that as long as we keep error messages clear enough this should be alright.

Changing this behavior would also probably be a breaking change, right @srnagar?

**Review by alzimmermsft — CHANGES_REQUESTED** [review]
The internal build helper method needs to call this API: https://github.com/Azure/azure-sdk-for-java/blob/2337588dd5ab63404e83c5bfd990c49212718238/sdk/tables/azure-data-tables/src/main/java/com/azure/data/tables/BuilderHelper.java#L130

**Comment by vcolin7** [comment]
> 
> 
> The internal build helper method needs to call this API:
> 
> https://github.com/Azure/azure-sdk-for-java/blob/2337588dd5ab63404e83c5bfd990c49212718238/sdk/tables/azure-data-tables/src/main/java/com/azure/data/tables/BuilderHelper.java#L130

We call it in the builders before calling `buildPipeline()`.

**Comment by vcolin7** [comment]
Closing in favor of using #22492.

**Pull request closed without merging**
