### PR TITLE
Remove algorithm string from encryptionKeyWrapMetadata and converting MicrosoftDataEncryptionException to CosmosException

### LINKED ISSUE #20374: Azure Cosmos Encryption - always throw CosmosException
Azure-Cosmos-Encryption module should always throw some type of CosmosException. 
* Discussion - https://github.com/Azure/azure-sdk-for-java/pull/19218#discussion_r597309833

### LINKED ISSUE #20376: Azure Cosmos Client Encryption : Adds support to expose Type in EncryptionKeyWrapMetadata constructor
* Port the corresponding .Net SDK change - https://github.com/Azure/azure-cosmos-dotnet-v3/pull/2283

### LINKED ISSUE #20875: Encryption create item throw error for nested object array field encryption
Encryption create item throw error for nested object array field encryption

Issue is on version [1.0.0-beta.2](https://mvnrepository.com/artifact/com.azure/azure-cosmos-encryption/1.0.0-beta.2)

### PR DESCRIPTION
**Pull request by simplynaveen20**
Remove algorithm string from EncryptionKeyWrapMetadata and converting MicrosoftDataEncryptionException to CosmosException.
Also fixing bug around encryption create item throw error for nested object array field encryption.
This will also increase the encryption length from 1024 to max 8000 which AAP java support at this time.

closes #20374 
closes #https://github.com/Azure/azure-sdk-for-java/issues/20899
closed #20875
Note: Need to a add test around Plaintext, once I verify this from .NET crew

### CODE REVIEW

**Review by kushagraThapar — COMMENTED** [review]
I would like to see no usage of `BridgeInternal` in Encryption project, can we achieve that ?

**Comment by simplynaveen20** [comment]
> I would like to see no usage of `BridgeInternal` in Encryption project, can we achieve that ?

Removing BridgeInternal need  CosmosBuilderAccessor for all the bridge internal usages, or redesigning Cosmos project itself , and it is not in scope of this PR. We need to brainstorm separately

**Review by kushagraThapar — APPROVED** [review]
Changes look good to me.

**Review by FabianMeiswinkel — APPROVED** [review]
LGTM

**Pull request merged**
