### PR TITLE
Fixing regression in cosmos release pipeline preventing to release just Cosmos Spark connector (all uber jars)

### PR DESCRIPTION
**Pull request by FabianMeiswinkel**
Failing pipeline with an attempt to release a hotfix for the Cosmos SPark connector - https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1645729&view=logs&j=da35a07f-f2a0-5802-21eb-2343f475d719&t=34af0aeb-d45b-5f1f-a2b5-80bfd46eb73c

The new release pipeline prevents us from just releasing the two spark jars (because they are both uber-jars)

### CODE REVIEW

**Review by kirankumarkolli — APPROVED** [review]

**Comment by JimSuplizio** [comment]
/CC: @alzimmermsft 
@FabianMeiswinkel I don't believe allowing an empty list is the correct change. I think the correct change, which I'll be making, is to remove the Where-Object -Not "uberJar" and skip checking for any uberJar libraries inside of the script. The script should fail if the list being passed in is empty.

**Pull request merged**
