### PR TITLE
update json-smart to 2.4.2

### PR DESCRIPTION
**Pull request by backwind1233**
For [issue Update net.minidev:json-smart in com.azure.spring:azure-spring-boot to v2.4.x ](https://github.com/Azure/azure-sdk-for-java/issues/20611)
Please don't merge before @yiliuTo finishing spring release.

Reminder: @yiliuTo @chenrujun  I also changed spring_managed_external_dependencies.txt

### CODE REVIEW

**Comment by chenrujun** [comment]
spring-boot-2.4.5 still using 2.3. 
Related PR: https://github.com/Azure/azure-sdk-for-java/pull/20721/files#diff-3813fa7f30abaf4f8f3f06486d039e8beee30250fef5c7ddb8de42eda07fd300L70

**Comment by chenrujun** [comment]
spring-boot-2.5.0-RC1 are using 2.4.2. https://github.com/Azure/azure-sdk-for-java/pull/20010/files#diff-3813fa7f30abaf4f8f3f06486d039e8beee30250fef5c7ddb8de42eda07fd300L70

**Comment by backwind1233** [comment]
Wait to upgrade spring boot, which will upgrade json-smart together

**Comment by chenrujun** [comment]
Closing this PR, because the version in master branch already updated: https://github.com/Azure/azure-sdk-for-java/blob/96e8d627470e7dd21df7bc4a1fe7c3a5ff48dbde/eng/versioning/external_dependencies.txt#L70

**Pull request closed without merging**
