### PR TITLE
Change diagnostic-id spelling to comply with other languages

### PR DESCRIPTION
**Pull request by lmolkova**
.NET (track1, 2), Java, and Python ServiceBus and EventHub SDKs spell `Diagnostic-Id`, and java uses `diagnostic-id`  which causes context propagation between different languages to break. https://github.com/Azure/azure-sdk-for-net/issues/22775

Since tracing support is still in preview (both with the plugin and through application insights agent) and we presumably don't have a lot of customers using it, making behavior-breaking change in Java before GA is more preffereable than making all other languages support `diagnostic-id` spelling.

### CODE REVIEW

**Review by alzimmermsft — APPROVED** [review]
Do any of the other names need to be changed as well? This may run into RevApi issues as a public property is changing value.

**Comment by lmolkova** [comment]
> Do any of the other names need to be changed as well? 

nope, just this one, other names are not used beyond Java SDKs 

> This may run into RevApi issues as a public property is changing value.

 Is there a way/review process to bypass it? Even though it's defined in azure-core, it's never used without tracing enabled

Yeah, this is what [happened](https://dev.azure.com/azure-sdk/public/_build/results?buildId=1011885&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=ba3cf43a-b2bf-50f9-f95f-93049ca44ad1&l=370).

**Comment by alzimmermsft** [comment]
@lmolkova, this is achievable with a RevApi suppression, but before that let's see if @JonathanGiles and @srnagar are okay with this change.

**Comment by JonathanGiles** [comment]
Make the change!

**Comment by srnagar** [comment]
Given that this context is only used when tracing is enabled and the core-tracing library is still in preview, I am fine with making the change to this constant which fixes actually fixes a bug.

**Pull request merged**
