### PR TITLE
Move msi-auth-token-provider-jar to sdk/identity

### PR DESCRIPTION
**Pull request by mitchdenny**
This PR moves the stand-alone library that was in ```authroization/msi-auth-token-provider-jar``` to ```sdk/identity/microsoft-azure-authentication-msi-token-provider```. My proposal is that we build this with the identity library since its a rough analogue to what ```azure-identity``` is - but for track 1 library scenarios.

### CODE REVIEW

**Comment by mitchdenny** [comment]
Referencing parent POM tidy up issue for tracking purposes: #4289

**Comment by JonathanGiles** [comment]
Yes, to @weshaggard's comment, I would like @schaabs to weigh in on this before merging.

**Comment by schaabs** [comment]
I'd really prefer not to move any track 1 authentication classes into identity.  The plan is to move all the client libraries onto the Track 2 TokenCredential and the track 1 credential types while possibly still supported will be deprecated in favor of the credential types in azure-identity.  Having track 1 credential types in here will end up being confusing as it will seem there are multiple ways of authenticating with MSI.

**Comment by mitchdenny** [comment]
Had a chat with @weshaggard - we aren't going to die on this hill :)

I'll relocate it to the authorization folder under SDK so that we keep the status quo - though I'll register my passing protest on this one since it literally does exactly the same thing that ```ManagedIdentityCredential``` does ;)

**Comment by mitchdenny** [comment]
OK - so with that done - could I get an approval or two and I can merge this in (once the builds pass).

**Pull request merged**
