### PR TITLE
Fixing bulk save implementation to populate audit data.

### LINKED ISSUE #39226: [BUG] Recent versions no longer set audit data when saving multiple entities with partition keys
**Describe the bug**
There seems to be a regression between 3.18 and 3.42. I believe it also exists in the latest 5.x version.

In 3.18, SimpleCosmosRepository.saveAll():

```
public <S extends T> Iterable<S> saveAll(Iterable<S> entities) {
        Assert.notNull(entities, "Iterable entities should not be null");

        final List<S> savedEntities = new ArrayList<>();
        entities.forEach(entity -> {
            final S savedEntity = this.save(entity);
            savedEntities.add(savedEntity);
        });

        return savedEntities;
    }
```
By calling save() on each entity of the Iterable passed, any auditing information was filled in (ie, @CreatedBy, @LastModifiedBy, etc).

But in 3.48:

```
public <S extends T> Iterable<S> saveAll(Iterable<S> entities) {
        Assert.notNull(entities, "Iterable entities should not be null");

        if (information.getPartitionKeyFieldName() != null) {
            return operation.insertAll(this.information, entities);
        } else {
            final List<S> savedEntities = new ArrayList<>();
            entities.forEach(entity -> {
                final S savedEntity = this.save(entity);
                savedEntities.add(savedEntity);
            });

            return savedEntities;
        }
    }
```
If there's a partition key, operation.insertAll(this.information, entities) does not add auditing information.

**To Reproduce**
See https://github.com/Blackbaud-JasonBodnar/cosmos-sql-bug/blob/v5.x/src/test/groovy/com/example/cosmossqlbug/TestEntityRepositorySpec.groovy#L28

***Code Snippet***
```
public <S extends T> Iterable<S> saveAll(Iterable<S> entities) {
        Assert.notNull(entities, "Iterable entities should not be null");

        if (information.getPartitionKeyFieldName() != null) {
            return operation.insertAll(this.information, entities);
        } else {
            final List<S> savedEntities = new ArrayList<>();
            entities.forEach(entity -> {
                final S savedEntity = this.save(entity);
                savedEntities.add(savedEntity);
            });

            return savedEntities;
        }
    }
```

**Expected behavior**
Any annotated fields will be populated with audit data.

**Setup (please complete the following information):**
 - Library/Libraries: com.azure:azure-spring-data-cosmos:3.42.0
 - Java version: 17
 - Frameworks: Springboot

**Additional context**

Originally reported when trying to find a solution for https://github.com/Azure/azure-sdk-for-java/issues/38691 but it should be its own bug.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

### PR DESCRIPTION
**Pull request by trande4884**
# Description

Fixes #39226 and #39562 

When bulk save was implemented, we stopped populating audit data. The gap has been fixed and unit tests added so this does not happen again.

If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [x] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Review by kushagraThapar — COMMENTED** [review]
Overall changes look good to me, however, I wonder what will be the behavior in case of errors in bulk operation?

**Review by kushagraThapar — APPROVED** [review]

**Comment by trande4884** [comment]
java - spring - tests ran manually due to current issues: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3707258&view=results

**Pull request merged**
