### PR TITLE
Sync eng/common directory with azure-sdk-tools repository for Tools PR 1365

### PR DESCRIPTION
**Pull request by kushagraThapar**
* Sync eng/common directory with azure-sdk-tools repository for Tools PR 1365

### CODE REVIEW

**Comment by kushagraThapar** [comment]
> Azure Pipelines could not run because the pipeline triggers exclude this branch/path.

@weshaggard  - looks like on this one, we might have to run the cosmos ci pipeline manually to verify the changes. I don't have permission to run the java - cosmos - ci manually, so need your help on this one too.

**Comment by weshaggard** [comment]
@kushagraThapar the best way to test these is not to file a PR yet, as the automation process will create those automatically once you approve that step. Instead it is recommended that you go into Azure DevOps directly and queue a build pointing at the branch created. 

I triggered one here https://dev.azure.com/azure-sdk/public/_build/results?buildId=717283&view=results.

**Comment by kushagraThapar** [comment]
> @kushagraThapar the best way to test these is not to file a PR yet, as the automation process will create those automatically once you approve that step. Instead it is recommended that you go into Azure DevOps directly and queue a build pointing at the branch created.
> 
> I triggered one here https://dev.azure.com/azure-sdk/public/_build/results?buildId=717283&view=results.

Oh, I see, makes sense, thanks. I still don't have permissions, but that is a separate issue.

**Comment by kushagraThapar** [comment]
Closing out this PR on behalf of automation.

**Pull request closed without merging**
