### PR TITLE
Updated versions for release to 4.13.1

### PR DESCRIPTION
**Pull request by kushagraThapar**
* Updated versions for release to 4.13.1

#### Key Bug Fixes
* Fixed issue preventing recovery from 410 status code and 0 sub status code due to stale Gateway caches when threads in parallel scheduler are starved.
* Fixed warning caused because of afterburner module usage in `CosmosDiagnostics`.

### CODE REVIEW

**Review by moderakh — APPROVED** [review]

**Review by FabianMeiswinkel — APPROVED** [review]
LGTM - Thanks

**Review by mbhaskar — APPROVED** [review]
Thanks for making the change Kushagra, it makes it easy to track.

**Pull request merged**
