### PR TITLE
fixAddressRefreshForWriteOperations

### PR DESCRIPTION
**Pull request by xinlian12**
Changes included:
1. Fixed https://github.com/Azure/azure-sdk-for-java/issues/37248. Added retry for write operations's addressRefresh on http timeout exceptions
2. Fixed an issue where address refresh response timeout is not being injected properly for write operations

### CODE REVIEW

**Review by FabianMeiswinkel — APPROVED** [review]
LGTM

**Review by jeet1995 — APPROVED** [review]
LGTM - thanks!

**Comment by xinlian12** [comment]
Failed tests:
faultInjectionServerErrorRuleTests_AddressRefresh_ResponseDelay - Tests pass locally with single-master & multi-master account, could be an issue only related to pipeline account configuration. will investigate separately

**Pull request merged**
