### PR TITLE
Update package name for sample and test moudle 

### PR DESCRIPTION
**Pull request by wujack778**
update package name for spring boot test and sample module

### CODE REVIEW

**Comment by zhoufenqin** [comment]
I find some readme files contain wrong links. like [azure-spring-integration-eventhub](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/spring/azure-spring-integration-eventhubs/README.md). It contains the wrong link like "https://github.com/Microsoft/spring-cloud-azure/blob/master/spring-integration-azure/spring-integration-eventhub/src/main/java/com/microsoft/azure/spring/integration/eventhub/EventHubOperation.java",  can you fix them?

**Comment by wujack778** [comment]
@zhoufenqin we dont need to update package name for spring cloud module this pr

**Comment by zhoufenqin** [comment]
> @zhoufenqin we dont need to update package name for spring cloud module this pr

fine

**Review by zhoufenqin — APPROVED** [review]

**Review by saragluna — APPROVED** [review]
LGTM.

**Pull request merged**
