### PR TITLE
App config merge versions

### PR DESCRIPTION
**Pull request by mrm9084**
Brings azure-spring-cloud-appconfiguration-config into master with spring-cloud-azure-appconfiguration-config

### CODE REVIEW

**Comment by saragluna** [comment]
No ci was triggered, I'm going to close and reopen the PR.

**Comment by weshaggard** [comment]
@mrm9084 it looks like something odd has happened with the changes which is blocking devops from correctly handling the ci triggering. In the past I've been able to workaround such issues by rebasing. Can you please rebase your changes on top of the latest master and perhaps squash them to eliminate any odd merge issues.

**Comment by mrm9084** [comment]
Created a new one that fixed everything. https://github.com/Azure/azure-sdk-for-java/pull/21021

**Pull request closed without merging**
