### PR TITLE
Update Spring Cloud Azure Support File

### PR DESCRIPTION
**Pull request by moarychan**
The Spring Cloud Azure 6.0.0-beta.4 will still use Spring Boot 3.0.0-RC2 + Spring  Cloud 2022.0.0-RC2 for release.

The new RC3 version for Spring Cloud has been released on Dec 1, which is a newer version based on Spring Boot RC2. After 6.0.0-beta.4 is released, this PR will be merged.

If you merged this PR, please update [Spring Cloud Azure Timeline](https://github.com/Azure/azure-sdk-for-java/wiki/Spring-Cloud-Azure-Timeline).

### CODE REVIEW

**Comment by moarychan** [comment]
The artifact `spring-cloud-stream-binder-test` was changed to `spring-cloud-stream-test-binder` since 4.0.0-RC3. @saragluna  please review, thanks~

**Comment by saragluna** [comment]
Could you please add some context in the PR's description?

**Comment by moarychan** [comment]
Update:
Bug fixed:
The script `sdk/spring/scripts/compatibility_get_spring_cloud_version.py` will override the latest Spring Cloud Version and use the previous one if there are multiple entries with the same Spring Boot versions and different Spring Cloud versions.

Not supported scenario for compatibility tests:
It's not supported to configure multiple supported entries to use the same Spring Boot version and different Spring Cloud version. Such as the below combination:
- Spring Boot RC2 + Spring Cloud RC2
- Spring Boot RC2 + Spring Cloud RC3

**Comment by moarychan** [comment]
Superseded by https://github.com/Azure/azure-sdk-for-java/pull/31730

**Pull request closed without merging**
