### PR TITLE
Regenerate Synapse Artifacts Composite V3 Jan 2022

### PR DESCRIPTION
**Pull request by g2vinay**
Added `MetaStoreClient` and `MetaStoreAsyncClient`
Added following models to support Metastore clients:
* MetastoreRegistrationResponse
* MetastoreRequestSuccessResponse
* MetastoreUpdateObject
* MetastoreUpdationResponse
* NotebookParameter
* NotebookParameterType
* RequestStatus
* ResourceStatus

### CODE REVIEW

**Review by srnagar — APPROVED** [review]
Newly generated code looks good but since the clients are fully autogenerated, do we want to switch Synapse over to LLC?

**Review by alzimmermsft — APPROVED** [review]

**Pull request merged**
