### PR TITLE
Remove authorization module from the sdk-all build

### PR DESCRIPTION
**Pull request by pallavit**
# Description

Please add an informative description that covers that changes made by the pull request and link all relevant issues.

Remove authorization module from the azure-sdk-all build. The SDK project was removed as part of https://github.com/Azure/azure-sdk-for-java/pull/25518 but this stale link was not removed causing a build break.

# All SDK Contribution checklist:
- [X] **The pull request does not introduce [breaking changes]**
- [ ] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [X] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#general-guidelines)
- [X] Title of the pull request is clear and informative.
- [X] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](../../CONTRIBUTING.md#building-and-unit-testing)
- [ ] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Review by lmolkova — APPROVED** [review]
LGTM, thanks!

**Review by JonathanGiles — APPROVED** [review]

**Review by srnagar — APPROVED** [review]
As a follow-up, we should clean up the Azure Pipelines too for authorization. [java - authorization - ci]

**Comment by pallavit** [comment]
> As a follow-up, we should clean up the Azure Pipelines too for authorization. [java - authorization - ci]

Yes, I am checking with engsys team before deleting it (in case there is a process to follow).

**Pull request merged**
