### PR TITLE
Fixed project.version conflict in  spring data cosmos

### PR DESCRIPTION
**Pull request by kushagraThapar**
# Description

* Because of multiple project.properties files in META-INF/project.properties, this tries to get the azure spring data cosmos specific version. 
* Closes https://github.com/Azure/azure-sdk-for-java/issues/27286

### CODE REVIEW

**Comment by kushagraThapar** [comment]
@backwind1233 / @saragluna  - please help review this PR - not sure if my method is correct to fix the above issue.

**Review by simplynaveen20 — APPROVED** [review]
LGTM

**Comment by backwind1233** [comment]
> @backwind1233 / @saragluna - please help review this PR - not sure if my method is correct to fix the above issue.

@kushagraThapar I have tested the code just now, but it seems doesn't resolve the issue, it will return null.
image

because the [code](https://github.com/kushagraThapar/azure-sdk-for-java/blob/d76ceda7c47871a7176a515a0307a20f7e19c329/sdk/cosmos/azure-spring-data-cosmos/src/main/java/com/azure/spring/data/cosmos/common/PropertyLoader.java#L36) here will load files from 
`spring-cloud-azure-autoconfigure-4.0.0-beta.3.jar!/META-INF/project.properties` or other folders 
not `azure-spring-data-cosmos-4.0.0-3.19.0-beta.1.jar!/META-INF/project.properties`

- I think we can specify the folder from `META-INF/project.properties` to `META-INF/cosmos***/project.properties` 
- or we can change the name from `project.properties` to `cosmos***-project.properties`;
but I am not sure whether it will cause any other issue?

**Review by backwind1233 — APPROVED** [review]
LGTM

**Comment by backwind1233** [comment]
@kushagraThapar Thank you so much, it looks great to me, I guess you will release this in March, right?

**Comment by kushagraThapar** [comment]
@backwind1233 - yes, this will be shipped next week, given the PR is merged, which is currently blocked on another PR here - https://github.com/Azure/azure-sdk-for-java/pull/27410 or this one - https://github.com/Azure/azure-sdk-for-java/pull/27416
Cosmos CI broke after we upgraded spring framework versions, so these above 2 PRs fix that issue.

**Pull request merged**
