### PR TITLE
[Communication] - Administration - Clean up Administration Package

### PR DESCRIPTION
**Pull request by minnieliu**
Remove Administration package and all references

### CODE REVIEW

**Comment by JianpingChen** [comment]
Remove reference from eng/jacoco-test-coverage/pom.xml

**Comment by JianpingChen** [comment]
Remove reference from eng/versioning/version_client.txt

**Comment by JianpingChen** [comment]
Remove reference from eng/.docsettings.yml if this file is managed by GitHub

**Review by alzimmermsft — APPROVED** [review]

**Review by JianpingChen — APPROVED** [review]

**Pull request merged**
