### PR TITLE
Add TestResourceDirectories parameter to store Arm template paths

### PR DESCRIPTION
**Pull request by yiliuTo**
This PR modifies the logic of deploying Arm template for Live tests and is migrated from #18773.

The original method is to scan all test-resources.json files under the directory of `$ServiceDirectory`, however, we want to provide a flexible way to split up Arm templates to be deployed.

This PR add a new sequence parameter of `$TestResourceDirectories` in archetype-sdk-tests.yml to specify directories of test-resources.json that is expected to be deployed.

### CODE REVIEW

**Review by weshaggard — COMMENTED** [review]
Looks reasonable to me but I will defer to @benbp

**Comment by benbp** [comment]
@weshaggard yep this is the direction we chatted about. It's nice because it doesn't require any underlying eng/common changes.

**Comment by yiliuTo** [comment]
Hi @weshaggard and @benbp , now that Ben and I have come to an agreement of this PR, can we get it approved?

**Comment by benbp** [comment]
@yiliuTo I still had one comment otherwise looks good

**Comment by yiliuTo** [comment]
> @yiliuTo I still had one comment otherwise looks good

Hi @benbp , is there anything I can improve for this PR? Or have I missed your comments?

**Review by benbp — APPROVED** [review]

**Pull request merged**
