### PR TITLE
Update partner release to use WIF

### PR DESCRIPTION
**Pull request by weshaggard**

### CODE REVIEW

**Review by benbp — APPROVED** [review]

**Comment by benbp** [comment]
I didn't know about LatestVersion. FYI @danieljurek we should use that as the az PowerShell version for the task in deploy test resources.

**Comment by weshaggard** [comment]
> I didn't know about LatestVersion. FYI @danieljurek we should use that as the az PowerShell version for the task in deploy test resources.

When I tested this originally it required me to include that but I'm not sure why.

**Comment by danieljurek** [comment]
> I didn't know about LatestVersion. FYI @danieljurek we should use that as the az PowerShell version for the task in deploy test resources.

It's already in the PR: https://github.com/Azure/azure-sdk-tools/pull/8249/files#diff-e4d8bce7ce67b80dcfd8a2c5b70b730b0b014a1e68bd3b881d16a2717808f450R51

**Pull request merged**
