### PR TITLE
Upgrade Netty and Reactor Netty Versions

### PR DESCRIPTION
**Pull request by alzimmermsft**
# Description

This PR upgrades the versions of Netty and Reactor Netty being used by the SDKs. This PR also prepares `azure-core-http-netty` for a release with the updated versions.

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](../../CONTRIBUTING.md#building-and-unit-testing)
- [x] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Review by g2vinay — APPROVED** [review]

**Review by lmolkova — APPROVED** [review]

**Review by mssfang — APPROVED** [review]

**Review by joshfree — APPROVED** [review]

**Comment by chenrujun** [comment]
This PR is included in #26380, how about closing this one and use #26380 instead?

**Comment by alzimmermsft** [comment]
> This PR is included in #26380, how about closing this one and use #26380 instead?

Yes, let's use that one instead, didn't see it. Is that going to be merged today?

**Comment by chenrujun** [comment]
@alzimmermsft 

Let's discuss here: https://github.com/Azure/azure-sdk-for-java/pull/26380#issuecomment-1009484264

**Comment by alzimmermsft** [comment]
Closing in favor of #26380

**Pull request closed without merging**
