### PR TITLE
Cosmos emulator start-up timeout

### PR DESCRIPTION
**Pull request by mitchdenny**
This PR sets a budget of 10 minutes for Cosmos emulator start-up which is already crazy long (I would anticipate a minute or so tops).

### CODE REVIEW

**Comment by mitchdenny** [comment]
@moderakh we are seeing Cosmos emulator start-up taking a long time. Generally when it starts successfully its under 10 minutes (in the 5-7 minute range). But often enough it just sits there in a StartPending state until the job times out.

This PR enforces a 10 minute timeout so that the job will fail so we aren't consuming an agent for nearly an hour waiting for the emulator to start - but we need to fix this for our builds to be reliable.

Do you have any ideas why the emulator wouldn't be starting reliably. Is there any logging we can get to figure out where it is getting stuck?

**Comment by moderakh** [comment]
@milismsft FYI as this is emulator FYI.

**Comment by milismsft** [comment]
The emulator startup time is heavily impacted by the quality of the agent's VM configuration and whatever the agent is doing at that particular time. We've been through these kind of issues a number of times with the DevOps guys. 

Having the agent configured with SSD's instead of regular HDD will drastically improve the startup time. Another option is to configure the emulator's startup to pass "/overrides=eseLogFileSize:1024;" as an argument.

**Comment by moderakh** [comment]
@mitchdenny could you try Millis suggestion on emulator? If that works that should be a better solution as it will reduce the emulator start up time.

**Comment by mitchdenny** [comment]
> @mitchdenny could you try Millis suggestion on emulator? If that works that should be a better solution as it will reduce the emulator start up time.

Done. Although I've got some more failing tests on my side :(

**Comment by milismsft** [comment]
@moderakh @mitchdenny I noticed that we are starting the emulator with 100 partitions; that's 4x the default and the emulator startup will be at least 2x slower. Do we actually have tests that require so many partitions or is this done to work around some of the tests not properly deleting/removing the databases/collections after they are done? Can we try with /PartitionCount=50 instead?

**Comment by mitchdenny** [comment]
> @moderakh @mitchdenny I noticed that we are starting the emulator with 100 partitions; that's 4x the default and the emulator startup will be at least 2x slower. Do we actually have tests that require so many partitions or is this done to work around some of the tests not properly deleting/removing the databases/collections after they are done? Can we try with /PartitionCount=50 instead?

Adding @danieljurek and @g2vinay for input on this question. I didn't set the original partition count so I'm not sure if there was a reason for this.

**Comment by mitchdenny** [comment]
The cosmos emulator is currently behaving itself, closing this down for now.

**Pull request closed without merging**
