### PR TITLE
Multiple fixes for issues reported by Sonar. Please see the issue list in description.

### PR DESCRIPTION
**Pull request by AlokRatnaparkhi**
This pull request contains refactoring/fixes for issues reported on Sonar. Please find issue numbers below.
1) [AYcBpAAOCwsdL7T9nljv ](https://sonarcloud.io/project/issues?resolved=false&id=stliu_azure-sdk-for-java&open=AYcBpAAOCwsdL7T9nljv) 
2) [AYcBpAAOCwsdL7T9nljw](https://sonarcloud.io/project/issues?resolved=false&id=stliu_azure-sdk-for-java&open=AYcBpAAOCwsdL7T9nljw)
3) [AYAHSbKNi07DX7oNprgx](https://sonarcloud.io/project/issues?resolved=false&id=stliu_azure-sdk-for-java&open=AYAHSbKNi07DX7oNprgx&tab=code)
4) [AYAHSbKzi07DX7oNprgz](https://sonarcloud.io/project/issues?resolved=false&id=stliu_azure-sdk-for-java&open=AYAHSbKzi07DX7oNprgz)
5) [AYZXoihnuI6TRXY4Otpd](https://sonarcloud.io/project/issues?resolved=false&id=stliu_azure-sdk-for-java&open=AYZXoihnuI6TRXY4Otpd&tab=code)
6) [AYZXoihOuI6TRXY4Otpc](https://sonarcloud.io/project/issues?resolved=false&id=stliu_azure-sdk-for-java&open=AYZXoihOuI6TRXY4Otpc)
7) [AYZXoioduI6TRXY4Otq3](https://sonarcloud.io/project/issues?resolved=false&id=stliu_azure-sdk-for-java&open=AYZXoioduI6TRXY4Otq3&tab=code)
8) [AYZXoioEuI6TRXY4Otq0](https://sonarcloud.io/project/issues?resolved=false&id=stliu_azure-sdk-for-java&open=AYZXoioEuI6TRXY4Otq0&tab=code)
9) [AYbirLvFYELHc-BHQkGt](https://sonarcloud.io/project/issues?resolved=false&id=stliu_azure-sdk-for-java&open=AYbirLvFYELHc-BHQkGt)
10) [AYbirLvFYELHc-BHQkGs](https://sonarcloud.io/project/issues?resolved=false&id=stliu_azure-sdk-for-java&open=AYbirLvFYELHc-BHQkGs)

Please see individual commits for detailed issue description and Sonar issue URL commit is targeted to.

### CODE REVIEW

**Comment by AlokRatnaparkhi** [comment]
@microsoft-github-policy-service agree

**Comment by AlokRatnaparkhi** [comment]
> @AlokRatnaparkhi please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

**Comment by saragluna** [comment]
@mrm9084 could you help take a look at this PR?

**Comment by Netyyyy** [comment]
Hi @AlokRatnaparkhi , could you help fix these pipeline errors, thanks
```
2023-05-22T03:35:06.9492793Z [INFO] There are 4 errors reported by Checkstyle 9.3 with /mnt/vss/_work/1/s/sdk/spring/spring-cloud-azure-appconfiguration-config/../../../eng/code-quality-reports/src/main/resources/checkstyle/checkstyle.xml ruleset.
2023-05-22T03:35:06.9723667Z ##[error] src/main/java/com/azure/spring/cloud/appconfiguration/config/implementation/AppConfigurationConstants.java(8,1): error :  src/main/java/com/azure/spring/cloud/appconfiguration/config/implementation/AppConfigurationConstants.java:[8,1] (design) FinalClass: Class AppConfigurationConstants should be declared as final.
2023-05-22T03:35:06.9731981Z [ERROR] src/main/java/com/azure/spring/cloud/appconfiguration/config/implementation/AppConfigurationConstants.java:[8,1] (design) FinalClass: Class AppConfigurationConstants should be declared as final.
2023-05-22T03:35:06.9736645Z ##[error] src/main/java/com/azure/spring/cloud/appconfiguration/config/implementation/AppConfigurationConstants.java(11,5): error :  src/main/java/com/azure/spring/cloud/appconfiguration/config/implementation/AppConfigurationConstants.java:[11,5] (whitespace) FileTabCharacter: File contains tab characters (this is the first instance).
2023-05-22T03:35:06.9737993Z [ERROR] src/main/java/com/azure/spring/cloud/appconfiguration/config/implementation/AppConfigurationConstants.java:[11,5] (whitespace) FileTabCharacter: File contains tab characters (this is the first instance).
2023-05-22T03:35:06.9742957Z ##[error] src/main/java/com/azure/spring/cloud/appconfiguration/config/implementation/AppConfigurationRefreshUtil.java(249,21): error :  src/main/java/com/azure/spring/cloud/appconfiguration/config/implementation/AppConfigurationRefreshUtil.java:[249,21] (whitespace) FileTabCharacter: File contains tab characters (this is the first instance).
2023-05-22T03:35:06.9744371Z [ERROR] src/main/java/com/azure/spring/cloud/appconfiguration/config/implementation/AppConfigurationRefreshUtil.java:[249,21] (whitespace) FileTabCharacter: File contains tab characters (this is the first instance).
2023-05-22T03:35:06.9748869Z ##[error] src/main/java/com/azure/spring/cloud/appconfiguration/config/implementation/AppConfigurationKeyVaultClientFactory.java(41,5): error :  src/main/java/com/azure/spring/cloud/appconfiguration/config/implementation/AppConfigurationKeyVaultClientFactory.java:[41,5] (whitespace) FileTabCharacter: File contains tab characters (this is the first instance).
2023-05-22T03:35:06.9750317Z [ERROR] src/main/java/com/azure/spring/cloud/appconfiguration/config/implementation/AppConfigurationKeyVaultClientFactory.java:[41,5] (whitespace) FileTabCharacter: File contains tab characters (this is the first instance).

2023-05-22T03:35:42.3859850Z [INFO] There is 1 error reported by Checkstyle 9.3 with /mnt/vss/_work/1/s/sdk/spring/spring-cloud-azure-appconfiguration-config-web/../../../eng/code-quality-reports/src/main/resources/checkstyle/checkstyle.xml ruleset.
2023-05-22T03:35:42.3870912Z ##[error] src/main/java/com/azure/spring/cloud/appconfiguration/config/web/implementation/AppConfigurationWebConstants.java(11,5): error :  src/main/java/com/azure/spring/cloud/appconfiguration/config/web/implementation/AppConfigurationWebConstants.java:[11,5] (whitespace) FileTabCharacter: File contains tab characters (this is the first instance).
2023-05-22T03:35:42.3872224Z [ERROR] src/main/java/com/azure/spring/cloud/appconfiguration/config/web/implementation/AppConfigurationWebConstants.java:[11,5] (whitespace) FileTabCharacter: File contains tab characters (this is the first instance).

2023-05-22T03:35:58.4827291Z [INFO] There are 6 errors reported by Checkstyle 9.3 with /mnt/vss/_work/1/s/sdk/spring/spring-cloud-azure-actuator/../../../eng/code-quality-reports/src/main/resources/checkstyle/checkstyle.xml ruleset.
2023-05-22T03:35:58.4843984Z ##[error] src/main/java/com/azure/spring/cloud/actuator/appconfiguration/AppConfigurationConfigHealthIndicator.java(33,13): error :  src/main/java/com/azure/spring/cloud/actuator/appconfiguration/AppConfigurationConfigHealthIndicator.java:[33,13] (whitespace) FileTabCharacter: File contains tab characters (this is the first instance).
2023-05-22T03:35:58.4846919Z [ERROR] src/main/java/com/azure/spring/cloud/actuator/appconfiguration/AppConfigurationConfigHealthIndicator.java:[33,13] (whitespace) FileTabCharacter: File contains tab characters (this is the first instance).
2023-05-22T03:35:58.4851177Z ##[error] src/main/java/com/azure/spring/cloud/actuator/appconfiguration/AppConfigurationHealthIndicator.java(40,9): error :  src/main/java/com/azure/spring/cloud/actuator/appconfiguration/AppConfigurationHealthIndicator.java:[40,9] (whitespace) FileTabCharacter: File contains tab characters (this is the first instance).
2023-05-22T03:35:58.4853043Z [ERROR] src/main/java/com/azure/spring/cloud/actuator/appconfiguration/AppConfigurationHealthIndicator.java:[40,9] (whitespace) FileTabCharacter: File contains tab characters (this is the first instance).
2023-05-22T03:35:58.4857129Z ##[error] src/main/java/com/azure/spring/cloud/actuator/appconfiguration/AppConfigurationHealthIndicator.java(40,17): error :  src/main/java/com/azure/spring/cloud/actuator/appconfiguration/AppConfigurationHealthIndicator.java:[40,17] (indentation) Indentation: 'catch' child has incorrect indentation level 16, expected level should be 12.
2023-05-22T03:35:58.4868406Z [ERROR] src/main/java/com/azure/spring/cloud/actuator/appconfiguration/AppConfigurationHealthIndicator.java:[40,17] (indentation) Indentation: 'catch' child has incorrect indentation level 16, expected level should be 12.
2023-05-22T03:35:58.4871678Z ##[error] src/main/java/com/azure/spring/cloud/actuator/keyvault/KeyVaultSecretHealthIndicator.java(38,9): error :  src/main/java/com/azure/spring/cloud/actuator/keyvault/KeyVaultSecretHealthIndicator.java:[38,9] (whitespace) FileTabCharacter: File contains tab characters (this is the first instance).
2023-05-22T03:35:58.4872715Z [ERROR] src/main/java/com/azure/spring/cloud/actuator/keyvault/KeyVaultSecretHealthIndicator.java:[38,9] (whitespace) FileTabCharacter: File contains tab characters (this is the first instance).
2023-05-22T03:35:58.4875886Z ##[error] src/main/java/com/azure/spring/cloud/actuator/keyvault/KeyVaultSecretHealthIndicator.java(38,17): error :  src/main/java/com/azure/spring/cloud/actuator/keyvault/KeyVaultSecretHealthIndicator.java:[38,17] (indentation) Indentation: 'catch' child has incorrect indentation level 16, expected level should be 12.
2023-05-22T03:35:58.4877141Z [ERROR] src/main/java/com/azure/spring/cloud/actuator/keyvault/KeyVaultSecretHealthIndicator.java:[38,17] (indentation) Indentation: 'catch' child has incorrect indentation level 16, expected level should be 12.
2023-05-22T03:35:58.4880235Z ##[error] src/main/java/com/azure/spring/cloud/actuator/keyvault/KeyVaultSecretHealthIndicator.java(40,17): error :  src/main/java/com/azure/spring/cloud/actuator/keyvault/KeyVaultSecretHealthIndicator.java:[40,17] (indentation) Indentation: 'catch' child has incorrect indentation level 16, expected level should be 12.
2023-05-22T03:35:58.4881771Z [ERROR] src/main/java/com/azure/spring/cloud/actuator/keyvault/KeyVaultSecretHealthIndicator.java:[40,17] (indentation) Indentation: 'catch' child has incorrect indentation level 16, expected level should be 12.
```

**Comment by AlokRatnaparkhi** [comment]
> Hi @AlokRatnaparkhi , could you help fix these pipeline errors, thanks
> 
> ```
> 2023-05-22T03:35:06.9492793Z [INFO] There are 4 errors reported by Checkstyle 9.3 with /mnt/vss/_work/1/s/sdk/spring/spring-cloud-azure-appconfiguration-config/../../../eng/code-quality-reports/src/main/resources/checkstyle/checkstyle.xml ruleset.
> 2023-05-22T03:35:06.9723667Z ##[error] src/main/java/com/azure/spring/cloud/appconfiguration/config/implementation/AppConfigurationConstants.java(8,1): error :  src/main/java/com/azure/spring/cloud/appconfiguration/config/implementation/AppConfigurationConstants.java:[8,1] (design) FinalClass: Class AppConfigurationConstants should be declared as final.
> 2023-05-22T03:35:06.9731981Z [ERROR] src/main/java/com/azure/spring/cloud/appconfiguration/config/implementation/AppConfigurationConstants.java:[8,1] (design) FinalClass: Class AppConfigurationConstants should be declared as final.
> 2023-05-22T03:35:06.9736645Z ##[error] src/main/java/com/azure/spring/cloud/appconfiguration/config/implementation/AppConfigurationConstants.java(11,5): error :  src/main/java/com/azure/spring/cloud/appconfiguration/config/implementation/AppConfigurationConstants.java:[11,5] (whitespace) FileTabCharacter: File contains tab characters (this is the first instance).
> 2023-05-22T03:35:06.9737993Z [ERROR] src/main/java/com/azure/spring/cloud/appconfiguration/config/implementation/AppConfigurationConstants.java:[11,5] (whitespace) FileTabCharacter: File contains tab characters (this is the first instance).
> 2023-05-22T03:35:06.9742957Z ##[error] src/main/java/com/azure/spring/cloud/appconfiguration/config/implementation/AppConfigurationRefreshUtil.java(249,21): error :  src/main/java/com/azure/spring/cloud/appconfiguration/config/implementation/AppConfigurationRefreshUtil.java:[249,21] (whitespace) FileTabCharacter: File contains tab characters (this is the first instance).
> 2023-05-22T03:35:06.9744371Z [ERROR] src/main/java/com/azure/spring/cloud/appconfiguration/config/implementation/AppConfigurationRefreshUtil.java:[249,21] (whitespace) FileTabCharacter: File contains tab characters (this is the first instance).
> 2023-05-22T03:35:06.9748869Z ##[error] src/main/java/com/azure/spring/cloud/appconfiguration/config/implementation/AppConfigurationKeyVaultClientFactory.java(41,5): error :  src/main/java/com/azure/spring/cloud/appconfiguration/config/implementation/AppConfigurationKeyVaultClientFactory.java:[41,5] (whitespace) FileTabCharacter: File contains tab characters (this is the first instance).
> 2023-05-22T03:35:06.9750317Z [ERROR] src/main/java/com/azure/spring/cloud/appconfiguration/config/implementation/AppConfigurationKeyVaultClientFactory.java:[41,5] (whitespace) FileTabCharacter: File contains tab characters (this is the first instance).
> 
> 2023-05-22T03:35:42.3859850Z [INFO] There is 1 error reported by Checkstyle 9.3 with /mnt/vss/_work/1/s/sdk/spring/spring-cloud-azure-appconfiguration-config-web/../../../eng/code-quality-reports/src/main/resources/checkstyle/checkstyle.xml ruleset.
> 2023-05-22T03:35:42.3870912Z ##[error] src/main/java/com/azure/spring/cloud/appconfiguration/config/web/implementation/AppConfigurationWebConstants.java(11,5): error :  src/main/java/com/azure/spring/cloud/appconfiguration/config/web/implementation/AppConfigurationWebConstants.java:[11,5] (whitespace) FileTabCharacter: File contains tab characters (this is the first instance).
> 2023-05-22T03:35:42.3872224Z [ERROR] src/main/java/com/azure/spring/cloud/appconfiguration/config/web/implementation/AppConfigurationWebConstants.java:[11,5] (whitespace) FileTabCharacter: File contains tab characters (this is the first instance).
> 
> 2023-05-22T03:35:58.4827291Z [INFO] There are 6 errors reported by Checkstyle 9.3 with /mnt/vss/_work/1/s/sdk/spring/spring-cloud-azure-actuator/../../../eng/code-quality-reports/src/main/resources/checkstyle/checkstyle.xml ruleset.
> 2023-05-22T03:35:58.4843984Z ##[error] src/main/java/com/azure/spring/cloud/actuator/appconfiguration/AppConfigurationConfigHealthIndicator.java(33,13): error :  src/main/java/com/azure/spring/cloud/actuator/appconfiguration/AppConfigurationConfigHealthIndicator.java:[33,13] (whitespace) FileTabCharacter: File contains tab characters (this is the first instance).
> 2023-05-22T03:35:58.4846919Z [ERROR] src/main/java/com/azure/spring/cloud/actuator/appconfiguration/AppConfigurationConfigHealthIndicator.java:[33,13] (whitespace) FileTabCharacter: File contains tab characters (this is the first instance).
> 2023-05-22T03:35:58.4851177Z ##[error] src/main/java/com/azure/spring/cloud/actuator/appconfiguration/AppConfigurationHealthIndicator.java(40,9): error :  src/main/java/com/azure/spring/cloud/actuator/appconfiguration/AppConfigurationHealthIndicator.java:[40,9] (whitespace) FileTabCharacter: File contains tab characters (this is the first instance).
> 2023-05-22T03:35:58.4853043Z [ERROR] src/main/java/com/azure/spring/cloud/actuator/appconfiguration/AppConfigurationHealthIndicator.java:[40,9] (whitespace) FileTabCharacter: File contains tab characters (this is the first instance).
> 2023-05-22T03:35:58.4857129Z ##[error] src/main/java/com/azure/spring/cloud/actuator/appconfiguration/AppConfigurationHealthIndicator.java(40,17): error :  src/main/java/com/azure/spring/cloud/actuator/appconfiguration/AppConfigurationHealthIndicator.java:[40,17] (indentation) Indentation: 'catch' child has incorrect indentation level 16, expected level should be 12.
> 2023-05-22T03:35:58.4868406Z [ERROR] src/main/java/com/azure/spring/cloud/actuator/appconfiguration/AppConfigurationHealthIndicator.java:[40,17] (indentation) Indentation: 'catch' child has incorrect indentation level 16, expected level should be 12.
> 2023-05-22T03:35:58.4871678Z ##[error] src/main/java/com/azure/spring/cloud/actuator/keyvault/KeyVaultSecretHealthIndicator.java(38,9): error :  src/main/java/com/azure/spring/cloud/actuator/keyvault/KeyVaultSecretHealthIndicator.java:[38,9] (whitespace) FileTabCharacter: File contains tab characters (this is the first instance).
> 2023-05-22T03:35:58.4872715Z [ERROR] src/main/java/com/azure/spring/cloud/actuator/keyvault/KeyVaultSecretHealthIndicator.java:[38,9] (whitespace) FileTabCharacter: File contains tab characters (this is the first instance).
> 2023-05-22T03:35:58.4875886Z ##[error] src/main/java/com/azure/spring/cloud/actuator/keyvault/KeyVaultSecretHealthIndicator.java(38,17): error :  src/main/java/com/azure/spring/cloud/actuator/keyvault/KeyVaultSecretHealthIndicator.java:[38,17] (indentation) Indentation: 'catch' child has incorrect indentation level 16, expected level should be 12.
> 2023-05-22T03:35:58.4877141Z [ERROR] src/main/java/com/azure/spring/cloud/actuator/keyvault/KeyVaultSecretHealthIndicator.java:[38,17] (indentation) Indentation: 'catch' child has incorrect indentation level 16, expected level should be 12.
> 2023-05-22T03:35:58.4880235Z ##[error] src/main/java/com/azure/spring/cloud/actuator/keyvault/KeyVaultSecretHealthIndicator.java(40,17): error :  src/main/java/com/azure/spring/cloud/actuator/keyvault/KeyVaultSecretHealthIndicator.java:[40,17] (indentation) Indentation: 'catch' child has incorrect indentation level 16, expected level should be 12.
> 2023-05-22T03:35:58.4881771Z [ERROR] src/main/java/com/azure/spring/cloud/actuator/keyvault/KeyVaultSecretHealthIndicator.java:[40,17] (indentation) Indentation: 'catch' child has incorrect indentation level 16, expected level should be 12.
> ```

Ok...working on it!!

**Comment by mrm9084** [comment]
@Netyyyy Is there a plan on how to move these changes to the Spring 3 branch?

**Comment by AlokRatnaparkhi** [comment]
I have fixed all the tab indentation issues reported on Azure pipeline checks. Please let me know if you have any review comments. Also, I have configured checkstyle on my eclipse, but it does not show me same errors as they are shown in azure pipeline checks. I am guessing you must have some customized configuration config file for checkstyle. Do you know how I can set it up locally so that I don't have to rely on remote pipeline checks to check the error?.

**Comment by Netyyyy** [comment]
> @Netyyyy Muyao Feng (CSI Interfusion Inc) Vendor Is there a plan on how to move these changes to the Spring 3 branch?

@AlokRatnaparkhi could you help sync those changes to `feature/spring-boot-3` branch by creating another PR, thanks.

**Comment by AlokRatnaparkhi** [comment]
> > @Netyyyy Muyao Feng (CSI Interfusion Inc) Vendor Is there a plan on how to move these changes to the Spring 3 branch?
> 
> @AlokRatnaparkhi could you help sync those changes to `feature/spring-boot-3` branch by creating another PR, thanks.

Sure, let me take a look :)

**Comment by AlokRatnaparkhi** [comment]
> > @Netyyyy Muyao Feng (CSI Interfusion Inc) Vendor Is there a plan on how to move these changes to the Spring 3 branch?
> 
> @AlokRatnaparkhi could you help sync those changes to `feature/spring-boot-3` branch by creating another PR, thanks.

Sure, let me take a look :)

> > > @Netyyyy Muyao Feng (CSI Interfusion Inc) Vendor Is there a plan on how to move these changes to the Spring 3 branch?
> > 
> > 
> > @AlokRatnaparkhi could you help sync those changes to `feature/spring-boot-3` branch by creating another PR, thanks.
> 
> Sure, let me take a look :)

@Netty - I am getting some conflicts after raising the PR against Spring-boot-3 branch. Will you be able to resolve conflict using my files or do I need to checkout the feature/spring-boot-3 branch, move my changes there and then raise a new PR?.

**Comment by Netyyyy** [comment]
> > > @Netyyyy
> > >             
> > >             Muyao Feng (CSI Interfusion Inc)
> > >             Vendor Muyao Feng (CSI Interfusion Inc) Vendor Is there a plan on how to move these changes to the Spring 3 branch?
> > 
> > 
> > @AlokRatnaparkhi could you help sync those changes to `feature/spring-boot-3` branch by creating another PR, thanks.
> 
> Sure, let me take a look :)
> 
> > > > @Netyyyy
> > > >             
> > > >             Muyao Feng (CSI Interfusion Inc)
> > > >             Vendor Muyao Feng (CSI Interfusion Inc) Vendor Is there a plan on how to move these changes to the Spring 3 branch?
> > > 
> > > 
> > > @AlokRatnaparkhi could you help sync those changes to `feature/spring-boot-3` branch by creating another PR, thanks.
> > 
> > 
> > Sure, let me take a look :)
> 
> @Netyyyy Muyao Feng (CSI Interfusion Inc) Vendor - I am getting some conflicts after raising the PR against Spring-boot-3 branch. Will you be able to resolve conflict using my files or do I need to checkout the feature/spring-boot-3 branch, move my changes there and then raise a new PR?.

I think the latter is better :)

**Pull request closed without merging**
