### PR TITLE
Prototype parallelizing unit test group

### PR DESCRIPTION
**Pull request by alzimmermsft**
# Description

Adds a second `BeforeSuite` method which enables `classes` level parallelization when running the `unit` test group. The parallelization is set to match the available processors to the JVM running tests.

Preliminary results show that this change reduced the runtime of unit tests from roughly 6 minutes to 2 minutes.

_By default TestNG does not enable test parallelization. This can be seen in the XML DTD which states the default for "parallel" is "none"._

> parallel (false | true | none | methods | tests | classes | instances) "none"

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [x] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Comment by alzimmermsft** [comment]
@kushagraThapar, mind finding someone to review this? I think it could add a nice shortening to the dev loop when iterating and testing :)

**Review by kushagraThapar — APPROVED** [review]
This looks great @alzimmermsft, thanks for the changes!

**Comment by kushagraThapar** [comment]
@alzimmermsft the only other thing is, we might have to put these changes in one of the other TestSuiteBase as well, that we should do. Do you want to tackle this in the same PR, or we can do it in a follow up?

**Review by kushagraThapar — APPROVED** [review]
Looks great now, thank you @alzimmermsft

**Pull request merged**
