### PR TITLE
External dependencies upgrade - Spring Boot 2.7.9 and Spring Cloud 2021.0.5

### PR DESCRIPTION
**Pull request by Netyyyy**
Updates external dependencies to align with Spring Boot version [2.7.9](https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-dependencies/2.7.9/spring-boot-dependencies-2.7.9.pom) from [2.7.8](https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-dependencies/2.7.8/spring-boot-dependencies-2.7.8.pom) and Spring Cloud version [2021.0.5](https://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-dependencies/2021.0.5/spring-cloud-dependencies-2021.0.5.pom) from [2021.0.5](https://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-dependencies/2021.0.5/spring-cloud-dependencies-2021.0.5.pom).
<details><summary>Release notes</summary><p><em>Sourced from <a href='https://github.com/spring-projects/spring-boot/releases/tag/v2.7.9'>spring-boot releases</a>.</em></p><h4> <g-emoji class="g-emoji" alias="lady_beetle" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f41e.png">  🐞 </g-emoji> Bug Fixes</h4><ul> <li>Maven Plugin's PropertiesMergingResourceTransformer closes InputStream when it should not do so <a href="https://github.com/spring-projects/spring-boot/pull/34063" data-hovercard-type="pull_request" data-hovercard-url="/spring-projects/spring-boot/pull/34063/hovercard">#34063</a></li> <li>Actuator Health web endpoint broken with Gson and Java 17 <a href="https://github.com/spring-projects/spring-boot/issues/34030" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/34030/hovercard">#34030</a></li> <li>Dependency management for Mongo's Java Driver is incomplete <a href="https://github.com/spring-projects/spring-boot/pull/33941" data-hovercard-type="pull_request" data-hovercard-url="/spring-projects/spring-boot/pull/33941/hovercard">#33941</a></li> <li>Using devtools with Reactive application results in slower restarts <a href="https://github.com/spring-projects/spring-boot/pull/33855" data-hovercard-type="pull_request" data-hovercard-url="/spring-projects/spring-boot/pull/33855/hovercard">#33855</a></li> <li>Spies are not reset after test execution when using <code>@SpyBean</code> <a href="https://github.com/spring-projects/spring-boot/issues/33830" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/33830/hovercard">#33830</a></li> <li>Properties Migrator does not detect properties of Map type that are marked as deprecated <a href="https://github.com/spring-projects/spring-boot/issues/27854" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/27854/hovercard">#27854</a></li></ul><h4> <g-emoji class="g-emoji" alias="notebook_with_decorative_cover" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f4d4.png">  📔 </g-emoji> Documentation</h4><ul> <li>Updated documentation for <code>@ConfigurationProperties</code> bean naming rules <a href="https://github.com/spring-projects/spring-boot/pull/34029" data-hovercard-type="pull_request" data-hovercard-url="/spring-projects/spring-boot/pull/34029/hovercard">#34029</a></li> <li>Restore "Use Jedis Instead of Lettuce" how-to documentation <a href="https://github.com/spring-projects/spring-boot/issues/33994" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/33994/hovercard">#33994</a></li> <li>Add Redis application properties example <a href="https://github.com/spring-projects/spring-boot/pull/33965" data-hovercard-type="pull_request" data-hovercard-url="/spring-projects/spring-boot/pull/33965/hovercard">#33965</a></li> <li>Use Maven Central for release downloads in CLI installation documentation <a href="https://github.com/spring-projects/spring-boot/issues/33962" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/33962/hovercard">#33962</a></li> <li>Actuator section is missing from documentation overview <a href="https://github.com/spring-projects/spring-boot/issues/33932" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/33932/hovercard">#33932</a></li> <li>Add Javadoc since to OperationParameter.getAnnotation() <a href="https://github.com/spring-projects/spring-boot/pull/33914" data-hovercard-type="pull_request" data-hovercard-url="/spring-projects/spring-boot/pull/33914/hovercard">#33914</a></li> <li>Document additional configuration that is required for spring.mvc.throw-exception-if-no-handler-found=true to be effective <a href="https://github.com/spring-projects/spring-boot/pull/31660" data-hovercard-type="pull_request" data-hovercard-url="/spring-projects/spring-boot/pull/31660/hovercard">#31660</a></li></ul><h4> <g-emoji class="g-emoji" alias="hammer" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f528.png">  🔨 </g-emoji> Dependency Upgrades</h4><ul> <li>Upgrade to ActiveMQ 5.16.6 <a href="https://github.com/spring-projects/spring-boot/issues/34238" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/34238/hovercard">#34238</a></li> <li>Upgrade to Byte Buddy 1.12.23 <a href="https://github.com/spring-projects/spring-boot/issues/34239" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/34239/hovercard">#34239</a></li> <li>Upgrade to Dropwizard Metrics 4.2.16 <a href="https://github.com/spring-projects/spring-boot/issues/34240" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/34240/hovercard">#34240</a></li> <li>Upgrade to Elasticsearch 7.17.9 <a href="https://github.com/spring-projects/spring-boot/issues/34241" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/34241/hovercard">#34241</a></li> <li>Upgrade to Glassfish JAXB 2.3.8 <a href="https://github.com/spring-projects/spring-boot/issues/34242" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/34242/hovercard">#34242</a></li> <li>Upgrade to Groovy 3.0.15 <a href="https://github.com/spring-projects/spring-boot/issues/34243" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/34243/hovercard">#34243</a></li> <li>Upgrade to Hibernate 5.6.15.Final <a href="https://github.com/spring-projects/spring-boot/issues/34244" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/34244/hovercard">#34244</a></li> <li>Upgrade to Jackson Bom 2.13.5 <a href="https://github.com/spring-projects/spring-boot/issues/34245" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/34245/hovercard">#34245</a></li> <li>Upgrade to Jaybird 4.0.9.java8 <a href="https://github.com/spring-projects/spring-boot/issues/34246" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/34246/hovercard">#34246</a></li> <li>Upgrade to Lombok 1.18.26 <a href="https://github.com/spring-projects/spring-boot/issues/34247" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/34247/hovercard">#34247</a></li> <li>Upgrade to Micrometer 1.9.8 <a href="https://github.com/spring-projects/spring-boot/issues/34141" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/34141/hovercard">#34141</a></li> <li>Upgrade to Netty 4.1.89.Final <a href="https://github.com/spring-projects/spring-boot/issues/34248" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/34248/hovercard">#34248</a></li> <li>Upgrade to Reactor Bom 2020.0.28 <a href="https://github.com/spring-projects/spring-boot/issues/34142" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/34142/hovercard">#34142</a></li> <li>Upgrade to Spring AMQP 2.4.10 <a href="https://github.com/spring-projects/spring-boot/issues/34321" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/34321/hovercard">#34321</a></li> <li>Upgrade to Spring Batch 4.3.8 <a href="https://github.com/spring-projects/spring-boot/issues/34143" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/34143/hovercard">#34143</a></li> <li>Upgrade to Spring Data Bom 2021.2.8 <a href="https://github.com/spring-projects/spring-boot/issues/34144" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/34144/hovercard">#34144</a></li> <li>Upgrade to Spring HATEOAS 1.5.3 <a href="https://github.com/spring-projects/spring-boot/issues/34249" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/34249/hovercard">#34249</a></li> <li>Upgrade to Spring Security 5.7.7 <a href="https://github.com/spring-projects/spring-boot/issues/34145" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/34145/hovercard">#34145</a></li> <li>Upgrade to Undertow 2.2.23.Final <a href="https://github.com/spring-projects/spring-boot/issues/34250" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/34250/hovercard">#34250</a></li></ul></details>

This PR is created by GitHub Actions: https://github.com/Azure/spring-cloud-azure-tools/actions/runs/4277661242

### CODE REVIEW

**Comment by Netyyyy** [comment]
@alzimmermsft please help take a look

**Review by vcolin7 — APPROVED** [review]
LGTM. By the way @Netyyyy, the Key Vault live tests have been failing for a good couple of months now and I'm working on fixing them this week. I don't think we should worry about these changes breaking the libraries at all.

**Pull request merged**
