### PR TITLE
update version of azure-servicebus

### PR DESCRIPTION
**Pull request by han-gao**

### CODE REVIEW

**Review by hemanttanwar — APPROVED** [review]

**Comment by chenrujun** [comment]
Hi, @hemanttanwar , @yvgopal 

For `com.microsoft.azure:azure-servicebus`, the `external_dependency`'s version is `3.6.1`, `current` version is `3.5.0`, `dependency` version is `3.4.0`.

Refs:
1. https://github.com/Azure/azure-sdk-for-java/blob/ab6d22820c965ef9f3a076d20b7e2130aa6d0e60/eng/versioning/external_dependencies.txt#L25
2. https://github.com/Azure/azure-sdk-for-java/blob/ab6d22820c965ef9f3a076d20b7e2130aa6d0e60/eng/versioning/version_data.txt#L37
3. https://mvnrepository.com/artifact/com.microsoft.azure/azure-servicebus

I have some questions: 
1. Why we already have `3.6.1` in Maven Central, but the `current` version is `3.5.0`, `dependency` version is `3.4.0`? In my understanding, `current` version should be `3.7.0`, `dependency` version is `3.6.1`.
2. Can I do like this:
 - Delete `com.microsoft.azure:azure-servicebus` in `external_dependencies.txt`'
 - Change `current` version to `3.7.0`, and `dependency` to `3.6.1` in `version_data.txt`.
 - Replace all `<!-- {x-version-update;com.microsoft.azure:azure-servicebus;external_dependency} -->` to `<!-- {x-version-update;com.microsoft.azure:azure-servicebus;dependency} -->`

**Comment by chenrujun** [comment]
We should not update `external_dependencies.txt` after in-band release and before out-of-band release. 
So I'll change this PR to draft.

**Comment by chenrujun** [comment]
Hi, @han-gao . Please resolve the conflicts.

**Comment by chenrujun** [comment]
The pipeline failure is not caused by this PR. 
So I'll merge this PR.

/check-enforcer override

**Pull request merged**
