### PR TITLE
revert preserve ordering in bulk

### PR DESCRIPTION
**Pull request by xinlian12**
Revert changes from "Preserve ordering in bulk" - https://github.com/Azure/azure-sdk-for-java/pull/35892

* Reverting this in order to build support for splits before pushing this as a public surface change.

### CODE REVIEW

**Review by kushagraThapar — CHANGES_REQUESTED** [review]
@xinlian12  - we should revert the changelog entry as well.

**Review by kushagraThapar — APPROVED** [review]

**Comment by xinlian12** [comment]
Failed two tests:
queryMetricsForReadAllItemsOfLogicalPartition - tested locally and passed
conflictCustomLWW - Known flaky tests

**Pull request merged**
