### PR TITLE
add a property to enable/disable the kafka cf auto-configuration

### PR DESCRIPTION
**Pull request by yiliuTo**
as subject, this pr resolves https://github.com/Azure/azure-sdk-for-java/issues/30574

### CODE REVIEW

**Review by stliu — APPROVED** [review]

**Comment by saragluna** [comment]
@yiliuTo, will the issue https://github.com/Azure/azure-sdk-for-java/issues/30397 still exist if users want to use Kafka with Storage? 

Users add storage and Kafka in their dependencies and enable the Kafka autoconfiguration. Will the same error persist?

**Comment by yiliuTo** [comment]
Yeah, the issue can still happen when our Kafka autoconfiguration getting enabled for a non-Event Hubs broker, so developers can choose to use this property to disable our autoconfiguration.

**Pull request merged**
