### PR TITLE
update readme for cosmos to include BOM information.

### PR DESCRIPTION
**Pull request by pallavit**

### CODE REVIEW

**Comment by kushagraThapar** [comment]
@pallavit - how do we plan to update these bom dependencies after every cosmos release ?
Through core releases ?

**Comment by pallavit** [comment]
> @pallavit - how do we plan to update these bom dependencies after every cosmos release ?
> Through core releases ?

I have updated the message to not have the version and have the readme link instead,

Here is the thought process behind it -
We can build tooling to keep this version current in the repo - however once a package is released we can't update its readme.

**Comment by kushagraThapar** [comment]
> > @pallavit - how do we plan to update these bom dependencies after every cosmos release ?
> > Through core releases ?
> 
> I have updated the message to not have the version and have the readme link instead,
> 
> Here is the thought process behind it -
> We can build tooling to keep this version current in the repo - however once a package is released we can't update its readme.

Sounds good, we can merge this PR.

**Review by kushagraThapar — APPROVED** [review]

**Comment by pallavit** [comment]
Thanks for the review.

**Pull request merged**
