### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by cybernethic**
Updating the RU information for containers: 
-  [Constants class](https://github.com/Azure/azure-sdk-for-java/blob/0d1a718c03f3ca780ba66785023410b1ae1c0ed3/sdk/cosmos/azure-spring-data-cosmos/src/main/java/com/azure/spring/data/cosmos/Constants.java) was updated removing the DEFAULT_REQUEST_UNIT 
-  DEFAULT_MINIMUM_RU is only for [TEST project](https://github.com/Azure/azure-sdk-for-java/blob/8b1ab17a2fd32453b5b315c81025f28d40ddf046/sdk/spring/azure-spring-data-cosmos/src/test/java/com/azure/spring/data/cosmos/common/TestConstants.java#L29) 

# Description

Please add an informative description that covers that changes made by the pull request and link all relevant issues.

If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [x] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Comment by kushagraThapar** [comment]
@cybernethic - what's the need for this PR? I see it just modifies the statement of mentioning of the default RUs.

**Comment by cybernethic** [comment]
> @cybernethic - what's the need for this PR? I see it just modifies the statement of mentioning of the default RUs.

Hello! I'm working with a customer using Spring SDK with Azure CosmosDb **Serverless** mode and they are having errors because the RUs are being sent to provision a **serverless @Container** but [serverless returns an error when provisioning RUs](https://learn.microsoft.com/en-us/azure/cosmos-db/serverless#use-serverless-resources). After reviewing the documentation, they saw that a minimum RU is defined. This PR is to clarify that RUs are optional and there's no minimum RU (according to the latest commits):
- DEFAULT_MINIMUM_RU = "400" only exists on the [TEST project](https://github.com/Azure/azure-sdk-for-java/blob/8b1ab17a2fd32453b5b315c81025f28d40ddf046/sdk/spring/azure-spring-data-cosmos/src/test/java/com/azure/spring/data/cosmos/common/TestConstants.java#L29). 
- DEFAULT_REQUEST_UNIT = "4000" was removed [Remove Container throughput default value from SDK (#13125) · Azure/azure-sdk-for-java@0d1a718 (github.com)](https://github.com/Azure/azure-sdk-for-java/commit/0d1a718c03f3ca780ba66785023410b1ae1c0ed3#diff-09f849d0b63825d51ce340082f8e7ab60e9851ce845b79163a8eb73534ba3cb4)

We are still investigating why this error is happening (probably because they don't have the latest SDK version), but updating the documentation is a good first step to clarify this behavior.

**Review by kushagraThapar — APPROVED** [review]

**Review by TheovanKraay — APPROVED** [review]
LGTM, thanks for this improvement!

**Comment by alzimmermsft** [comment]
@kushagraThapar @TheovanKraay can this be merged?

**Pull request merged**
