### PR TITLE
CosmosException when using azure-spring-data-cosmos query methods with repeated parameters

### PR DESCRIPTION
**Pull request by dsibilio**
Solves #17961 by guaranteeing unique aliases for repeated parameters within the same query.

### CODE REVIEW

**Comment by kushagraThapar** [comment]
@mbhaskar  - please take a look at this PR

**Comment by kushagraThapar** [comment]
Thanks @dsibilio for the contribution, we will look into it soon.

**Review by kushagraThapar — APPROVED** [review]
LGTM. 
However, I would love to have the same test coverage for ReactiveCosmosRepository as well.

**Comment by dsibilio** [comment]
@kushagraThapar added the JUnit tests for the reactive repository.

Also opened the same PR to backport the changes to the previous spring-data-cosmosdb library, on 2.3.x branch: https://github.com/microsoft/spring-data-cosmosdb/pull/555

**Pull request merged**
