### PR TITLE
Upgrade spring boot to 2.4.5

### PR DESCRIPTION
**Pull request by chenrujun**
Please check the commit message for more information.

### CODE REVIEW

**Comment by chenrujun** [comment]
Hi, @kushagraThapar , @mbhaskar .

Could you please help to fix the pipeline failure?

**Review by kushagraThapar — APPROVED** [review]
Version and cosmos changes look good to me.

**Comment by chenrujun** [comment]
@kushagraThapar 

Great! Thank you for your effort.
I'll merge this PR after @yiliuTo finished release.

**Comment by chenrujun** [comment]
Hi, @alzimmermsft , please help to review this PR. 🙏

**Review by alzimmermsft — APPROVED** [review]

**Pull request merged**
