### PR TITLE
Turn on aggregate reports for one agent, to receive code coverage

### PR DESCRIPTION
**Pull request by whisper6284**
# Description

Turn on aggregate reports for one agent, to receive code coverage

### CODE REVIEW

**Comment by whisper6284** [comment]
/azn run java - azure-communication-phonenumbers - tests

**Comment by whisper6284** [comment]
/azn run java - azure-communication-phonenumbers - tests

**Review by sofiar-msft — APPROVED** [review]

**Review by danielortega-msft — APPROVED** [review]

**Pull request merged**
