### PR TITLE
Fix query deserialization

### PR DESCRIPTION
**Pull request by Blackbaud-MikeLueders**
When the @Query annotation is used, the domain return type is passed to CosmosAsyncContainer#queryItems as the class type instead of JsonNode which all other methods use.  This results in MappingCosmosConverter not being used to deserialize the object, which fails on more complex types which would normally be deserialized without issue, such as OffsetDateTime.

### CODE REVIEW

**Comment by kushagraThapar** [comment]
@mbhaskar  - can you please take a look at this PR since it touches the Query Annotation path.

**Review by mbhaskar — APPROVED** [review]
LGTM. Thanks you for your contribution @Blackbaud-MikeLueders

**Comment by mbhaskar** [comment]
This also fixes https://github.com/Azure/azure-sdk-for-java/issues/18497

**Pull request merged**
