### PR TITLE
Adding Log Analytics data plane

### PR DESCRIPTION
**Pull request by alexeldeib**
Hi! This is a PR to include functionality for Log Analytics (aka microsoft.operationalinsights RP) data plane access. I came across a few things that I wanted to ask about while I was tweaking the generation:
- I noticed some large changes recently -- looks like there is no longer a rollup package for data plane services? Any guidance here is appreciated 😄 
- I modeled my pom file off of eventgrid, which was the most similar data plane service I could find. Let me know if this looks okay or if there are any glaring issues. 
- Is there anything particular about the testing setup? The wiki describes live tests, but for the other SDKs I've recorded the sessions for playback. How are these otherwise integrated e.g. into CI?

I've also updated the readme in the main spec repo: https://github.com/Azure/azure-rest-api-specs/pull/3269

Looking forward to your thoughts 😊

### CODE REVIEW

**Comment by jianghaolu** [comment]
Hi @alexeldeib Yes! There are ongoing efforts trying to make the Java repo similar to azure-rest-api-specs in the structure so that whoever familiar with that repo should find it easy to get hands on the Java repo.

In this process one goal is to individualize each service so that on-demand release job can be possible (otherwise we have to release everything every time). The hope is in the near future there will be a button to release one service at any time you'd like :)

Your changes look good overall - I'll take another close look. To record and playback your tests, add this dependency to your jar: https://github.com/Azure/azure-sdk-for-java/blob/master/storage/resource-manager/v2018_02_01/pom.xml#L69. You will have access to class `TestBase.java` and environment variable `AZURE_TEST_MODE` (Playback/Record).

**Comment by alexeldeib** [comment]
@jianghaolu Sorry for the slow follow up -- I see that authentication via the java runtime defaults to using ARM for the AAD token audience. We have a custom endpoint and use a different token audience for authentication. Would it be appropriate to do something in the runtime similar to [KeyVault/Graph/Data Lake ](https://github.com/Azure/autorest-clientruntime-for-java/blob/7bf38a942d25a1698a2c6f6bd6149cc078f852ec/azure-client-runtime/src/main/java/com/microsoft/azure/credentials/AzureTokenCredentials.java#L54-L63)and add our endpoint to the [AzureEnvironment ](https://github.com/Azure/autorest-clientruntime-for-java/blob/7bf38a942d25a1698a2c6f6bd6149cc078f852ec/azure-client-runtime/src/main/java/com/microsoft/azure/AzureEnvironment.java#L35)file? We did something similar already for [PowerShell](https://github.com/alexeldeib/azure-powershell/blob/cd15f9c9de82affe971e65c7b40235abbbf7d73f/src/Common/Commands.Common.Authentication.Abstractions/AzureEnvironment.cs#L54) (we only support commerical and USGov clouds currently). 

Or, sidestepping that entirely, is there a way I can authenticate using a custom token audience using adal4j or another existing feature? I mentioned we worked around this for PowerShell; for C# SDK we didn't need to because the runtime implementation of ApplicationTokenProvider has a [static method](https://github.com/Azure/azure-sdk-for-net/blob/f9e030cd82d6d8fa251e5c1b5240e44a11be37d3/src/SdkCommon/ClientRuntime.Azure.Authentication/ApplicationTokenProvider.cs#L217-L221) that fit our needs.

**Comment by alexeldeib** [comment]
@milismsft @anuchandy could one of you comment on the above about authentication with custom AAD resource in java sdk?

**Comment by jianghaolu** [comment]
@alexeldeib Sorry for the late response from my side :( Yes we can totally add your endpoint to it. Please file an issue here: https://github.com/azure/autorest-clientruntime-for-java/ with your endpoint and token audience info and we can prioritize it. You are welcome to send a pull request yourself if you need it within a week.

**Pull request merged**
