### PR TITLE
Move keyvault

### PR DESCRIPTION
**Pull request by mitchdenny**
This PR moves the KeyVault track 2 libraries to the sdk folder. These new modules sit alongside the track 1 libraries and so the pom.xml from track 2 has been renamed to pom.client.xml to disambiguate. Our optimizes PR pipelines build both track 1 and track 2 libraries currently but eventually we'll remove the track 1 libraries from the build once we decide we aren't maintaining them.

I also added reference to the core library to our pom.service.xml aggregator to overcome the fact that the updated version of core isn't published to maven central yet.

### CODE REVIEW

**Comment by g2vinay** [comment]
README of keys and secrets will need updates of samples location URL, after this move.

**Comment by mitchdenny** [comment]
@g2vinay done.

**Comment by conniey** [comment]
My PR may finish before yours: https://github.com/Azure/azure-sdk-for-java/pull/4344

**Pull request merged**
