### PR TITLE
WebFlux compatibility.for spring boot starter

### PR DESCRIPTION
**Pull request by thomas-worm-datev**
# Description

With this change the spring boot starter will support WebFlux security. The existing implementation for WebMVC is reused (wrapped) to work with WebFlux security. So the configuration is the same as for WebMVC.

## Usage

Here is an example Controller method of a controller implementing REST API interfaces generated by the openapi spring generator:

```java
Override()
    public Mono<ResponseEntity<User>> getCurrentUser(ServerWebExchange exchange) {
        return exchange
                .getSession()
                .map(session -> session.getAttribute("CURRENT_USER_PRINCIPAL"))
                .cast(UserPrincipal.class)
                .map(principal -> principal.getName())
                .map(name -> new User().displayName(name)).map(ResponseEntity::ok);
    }
```

## Related issues:

* https://github.com/microsoft/azure-spring-boot/issues/879

# All SDK Contribution checklist:
- [X] **The pull request does not introduce [breaking changes]**
- [x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [X] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [X] Title of the pull request is clear and informative.
- [X] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [X] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Comment by thomas-worm-datev** [comment]
It seems that the failed builds are not caused by the changes/pull request:


> *ubuntu2004_117_False_surefiretest*:  
> ```
> 07:18:51.584 [ForkJoinPool-1-worker-2] WARN com.azure.spring.cloud.actuator.appconfiguration.AppConfigurationHealthIndicator - Health check failed
> java.lang.IllegalStateException: The gremlins have cut the cable.
> 	at com.azure.spring.cloud.actuator.appconfiguration.AppConfigurationHealthIndicatorTests.appconfigurationIsDown(AppConfigurationHealthIndicatorTests.java:33)
> ```

Is this a special failure with the Ubuntu version on the agents?

**Comment by moarychan** [comment]
> Is this a special failure with the Ubuntu version on the agents?

it's a normal exception log, the actual exception is below:
```console
Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M3:test (default-cli) on project spring-cloud-azure-core: Execution default-cli of goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M3:test failed: Cannot invoke "java.io.File.getAbsolutePath()" because the return value of "org.apache.maven.artifact.Artifact.getFile()" is null
```
You can work on other failures first.

**Comment by JonathanGiles** [comment]
@saragluna What is the status on this PR?

**Comment by saragluna** [comment]
> @saragluna What is the status on this PR?

Hi @JonathanGiles, the web flux compatibility support is not in this semester's plan, so this PR is still in our backlog.

**Pull request closed without merging**
