### PR TITLE
 Added Widevine Base License Acquisition + FairPlay support

### PR DESCRIPTION
**Pull request by rnrneverdies**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@rnrneverdies__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by jianghaolu** [comment]
Looks like there are checkstyle errors. Make sure you run `mvn checkstyle:check` under `services/azure-media` and address the issues printed.

**Comment by rnrneverdies** [comment]
@jianghaolu ACK. Thanks

**Comment by jianghaolu** [comment]
LGTM. Merging.

**Pull request merged**
