### PR TITLE
Upgrade external dependencies managed by Spring Boot 3.0.2 and Spring Cloud 2022.0.1

### PR DESCRIPTION
**Pull request by moarychan**
# Description

Update the external dependencies on `feature/spring-boot-3` branch.

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [ ] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Comment by moarychan** [comment]
@saragluna all the Spring pipelines passed, please help review this PR, thanks!

**Comment by saragluna** [comment]
@moarychan why are the core, identity and eventhubs pipelines failing?

**Comment by weidongxu-microsoft** [comment]
not sure if you really want to merge now.

this week is for core package release.

**Comment by saragluna** [comment]
> not sure if you really want to merge now.
> 
> this week is for core package release.

@weidongxu-microsoft it should be okay, the target branch is a feature branch.

**Comment by weidongxu-microsoft** [comment]
I see. That's fine :-)

**Comment by saragluna** [comment]
@moarychan maybe we should modify the CODEOWNERS file on this feature branch https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#codeowners-file-location.

**Comment by moarychan** [comment]
> @moarychan why are the core, identity and eventhubs pipelines failing?

No new failures in this upgrade, we can still ignore these failures first, below are detail modules with failures:
- azure-spring-cloud-feature-management-web
- azure-spring-cloud-appconfiguration-config
- azure-spring-data-cosmos
- azure-monitor-opentelemetry-exporter

**Review by saragluna — APPROVED** [review]

**Pull request merged**
