### PR TITLE
AllowChangeFeedQueryToCompleteAfterFetchedChangesAvailableNow

### PR DESCRIPTION
**Pull request by xinlian12**
### Description
For query changeFeed, customer can define a feedRange filter which span multiple sub-ranges. Currently, the query will only complete when all sub-ranges included have received 304.  When there are still active write workloads happening on those sub-ranges, the changeFeed query may never reach to a complete status. 

In this PR, we exposed a new config in CosmosChangeFeedRequestOptions which allow the changeFeedQuery to complete once it has fetched all changes available when the query starts. 

### Public API
`changeFeedRequestOptions.setCompleteAfterAllCurrentChangesRetrieved(boolean)
`

### High level design
When the query starts, SDK will track the max LSN existing on each sub-range. When client has fetched all changes exceeds the maxLSN being tracked, the query can be completed.

### CODE REVIEW

**Review by FabianMeiswinkel — APPROVED** [review]
LGTM, Thanks

**Comment by xinlian12** [comment]
Following failed tests are not related to change in this PR:
queryAfterCreation
readAfterCreation

**Pull request merged**
