### PR TITLE
Prepare to release a patch version for azure-security-keyvault-jca and  azure-spring-boot-starter-keyvault-certificates.

### PR DESCRIPTION
**Pull request by chenrujun**
Prepare to release a patch version for azure-security-keyvault-jca and  azure-spring-boot-starter-keyvault-certificates.

### CODE REVIEW

**Review by yiliuTo — APPROVED** [review]
LGTM

**Comment by chenrujun** [comment]
The pipeline failure is not related to this PR. So merging this PR.

**Pull request merged**
