### PR TITLE
[TA] Merge feature branch, "Feature/shafang/azure ai textanalytics 5.1.0"

### PR DESCRIPTION
**Pull request by mssfang**
All changes get approved before merged to the feature branch.

API: https://apiview.dev/Assemblies/Review/f62ee261035a44189c597868c7a8a7ee?diffRevisionId=bd57798704a04412b224e5e4268a108b&doc=False&diffOnly=True

### CODE REVIEW

**Review by deyaaeldeen — APPROVED** [review]
🚀

**Review by deyaaeldeen — COMMENTED** [review]
In another PR, let's add a note about the addition of `categoriesFilter` to analyze in the changelog.

**Review by kristapratico — APPROVED** [review]
🎉

**Pull request merged**
