### PR TITLE
Fix sb IT failure

### PR DESCRIPTION
**Pull request by yiliuTo**
This pr fixes spring sb IT failure of https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1797971&view=logs&j=495e492e-98ba-5859-62ea-04a50efff90f&t=bde3d2a0-4918-548d-b90c-662a34185dec, which is cause by the auto-startup of service bus processor client. When setting as auto-startup by default, the processor client starts consuming messages before the receiver client, which is not the expected order of this test and causes a serires of problems: the test of receiver client becomes effectiveless since it cannot receive any messages, and the processor client doesn't have enough time to receive the second message since the the count has been zero.

### CODE REVIEW

**Review by Netyyyy — APPROVED** [review]
LGTM.

**Comment by saragluna** [comment]
@yiliuTo so this is why the IT test used to succeed but started to fail lately?

**Comment by yiliuTo** [comment]
> @yiliuTo so this is why the IT test used to succeed but started to fail lately?

yes, it started to fail since the lifecycle manager of processor client is enabled.

**Pull request merged**
