### PR TITLE
Update version after spring-cloud-azure:4.3.0 released

### PR DESCRIPTION
**Pull request by hui1110**
# Description

`spring-cloud-azure-4.3.0` branch is used to release `spring-cloud-azure:4.3.0`. Now release is finished. Merge it to the main branch,

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [x] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Review by chenrujun — APPROVED** [review]
LGTM.

**Comment by hui1110** [comment]
Hi @iaulakh, can you help fix this error? https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1679426&view=logs&j=ee661d54-f7aa-5141-9cce-4f03229036f5&t=1a7ff27e-3b91-5e17-825c-57647da46d62

**Comment by iaulakh** [comment]
@hui1110 would it be possible for you to contact repo owners to see pipeline issue? https://github.com/Azure/azure-sdk-for-java/blob/main/.github/CODEOWNERS

**Comment by hui1110** [comment]
> @hui1110 would it be possible for you to contact repo owners to see pipeline issue? https://github.com/Azure/azure-sdk-for-java/blob/main/.github/CODEOWNERS

> Hi @iaulakh, It's probably not a pipeline issue. Can you download the "linting-reports.zip" artifact to see what was found? https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1679426&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by hui1110** [comment]
`java-code-quality-reports-ci` failed because of this https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1679426&view=logs&j=ee661d54-f7aa-5141-9cce-4f03229036f5&t=1a7ff27e-3b91-5e17-825c-57647da46d62.

Get the following content in 'linting-reports.zip':

File   Name | Line Number | Column Number | Message | Type
-- | -- | -- | -- | --
/sdk/communication/azure-communication-common/src/test/java/com/azure/communication/common/CommunicationIdentifierTests.java|75|5|'{' at column 5 should be on the previous line.|com.puppycrawl.tools.checkstyle.checks.blocks.LeftCurlyCheck

**Comment by iaulakh** [comment]
@hui1110 Thanks, I sent PR https://github.com/Azure/azure-sdk-for-java/pull/29791

**Pull request merged**
