### PR TITLE
Policy Insights: generate 2019 10 01

### PR DESCRIPTION
**Pull request by ChenTanyi**

### CODE REVIEW

**Comment by weidongxu-microsoft** [comment]
@mitchdenny "check-enforcer" is not working in this PR. Could you find someway or just merge it?

**Comment by mitchdenny** [comment]
Shouldn't this be running some kind of build job? If you just trigger the management build check enforcer will get unblocked. But at the moment it it isn't meeting the minimum required number of checks to allow check enforcer to pass.

**Comment by weidongxu-microsoft** [comment]
@mitchdenny The CI supposed to be ci.mgmt.yml inside the service folders. But I think you have not batch added them yet.

https://github.com/Azure/azure-sdk-for-java/blob/policy_insight/sdk/policyinsights/ci.mgmt.yml

**Comment by mitchdenny** [comment]
OK ... just use the /azp command to trigger the management build then.

**Comment by weidongxu-microsoft** [comment]
@mitchdenny I cannot run it (likely because it exclude /sdk). Should we remove that exclude, before we get mgmt CIs on board?

**Comment by weidongxu-microsoft** [comment]
@mitchdenny Or as a workaround we just touch some file (with empty line e.g) in eng/mgmt to trigger it?

**Comment by mitchdenny** [comment]
I've disabled Check Enforcer as a required check. So you should be unblocked.

**Comment by ChenTanyi** [comment]
Thanks for your help!

**Pull request merged**
