### PR TITLE
alwaysUsePagedFluxMaxItemCount

### PR DESCRIPTION
**Pull request by xinlian12**
**Issue:**
`PageSize` from `byPage` is not always being honored
CosmosQueryRequestOption option = new CosmosQueryRequestOption()
Step 1: query(option).byPage(pageSize)
Step 2: query(option).byPage() -> we are expecting it to use the default pageSize in `CosmosPagedFluxOptions`, but for certain scenario, it is reusing the pageSize from step1

### CODE REVIEW

**Review by kushagraThapar — APPROVED** [review]
LGTM, thanks @xinlian12

**Review by FabianMeiswinkel — APPROVED** [review]
LGTM

**Comment by xinlian12** [comment]
Failed test: maxValueExceedingDefinedLimitStillWorksWithoutException

Tested locally succeeded and the changes in this PR does not touch metrics related logic. 
But this is a newly failing test which need attention, will fix it in another PR.

**Pull request merged**
