### PR TITLE
Collect cherry picked branches for 4.45.2 hotfix release.

### PR DESCRIPTION
**Pull request by jeet1995**
Changes summary:
- Following PRs have been cherry-picked:
   - #35586
   - #36067 
   - #36083 
   - #36225
   - #36397 
- Also adds back the omission of `multi-region` test group along with some refactorings of tests.

### CODE REVIEW

**Review by FabianMeiswinkel — APPROVED** [review]
LGTM

**Review by xinlian12 — APPROVED** [review]
LGTM, thanks

**Comment by jeet1995** [comment]
Pipeline result - https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3083559&view=ms.vss-test-web.build-test-results-tab

Failing tests:
- ProactiveOpenConnectionProcessorTests#recordNewAddressesAfterSplit - passes locally.
- CosmosBulkGatewayTest#createItem_withBulk_split - passes locally
- CosmosConflictsTest - all tests pass locally.
- ClientMetricsTest#readAllItemsWithDetailMetrics - looking for an RNTBD related metric (specific to Direct connectivity mode) for a client configured with the gateway connectivity mode.

Speculation related and client-telemetry related tests have been removed.

**Pull request merged**
