### PR TITLE
SchemaRegistry: Add missing schema descriptions in swagger

### PR DESCRIPTION
**Pull request by MiYanni**
Added descriptions for SchemaId.id, SchemaGroup.name, SchemaGroup.createdTimeUtc, SchemaGroup.updatedTimeUtc, and SchemaGroup.schemaType.

### CODE REVIEW

**Comment by ramya-rao-a** [comment]
@arerlend, @hmlam,

These changes to the swagger were needed to fix the errors found when trying to generate the .Net SDK.
See https://github.com/Azure/azure-sdk-for-net/issues/13471#issuecomment-662745525

**Comment by arerlend** [comment]
Yeah looks good, thanks for making the changes.

FYI - it is looking like we are going to have to switch to Swagger 2.0 for azure-rest-api-specs, but there will be no functional difference between the 3.0 and 2.0 specs, so I don't foresee issues with C# client dev.

**Comment by MiYanni** [comment]
> Yeah looks good, thanks for making the changes.
> 
> FYI - it is looking like we are going to have to switch to Swagger 2.0 for azure-rest-api-specs, but there will be no functional difference between the 3.0 and 2.0 specs, so I don't foresee issues with C# client dev.

AutoRest converts all OpenAPI 2.0 documents to 3.0 internally for new generators. So, it really doesn't make a difference either way. Whatever the specs repo needs, go for it.

**Comment by MiYanni** [comment]
This is no longer relevant.

**Pull request closed without merging**
