### PR TITLE
Implements cosmos.OLTP SPN support as requested  #29958

### PR DESCRIPTION
**Pull request by arykov**
# Description

Added cosmos.OLTP SPN support by changing azure-cosmos-spark. You can still use 
spark.cosmos.accountKey config key to specify accountKey. Alternatively combination of the following keys needs to be provided
spark.cosmos.tenantId
spark.cosmos.clientId
spark.cosmos.secret

If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.

# All SDK Contribution checklist:
- [ x] **The pull request does not introduce [breaking changes]**
- [ x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [ ] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Comment by arykov** [comment]
@microsoft-github-policy-service agree

**Comment by FabianMeiswinkel** [comment]
@arykov  - you change is missing an important design gap - AAD auth in the SDK would prevent using any metadata operations (like creating databases and containers) - which means the built-in Spark catalog functionality would be broken.

We have a PR already that will add AAD support and also addresses above gap - please take a look at https://github.com/Azure/azure-sdk-for-java/pull/32393

We are planning to release the AAD support like in the PR above in the January or February release of the SDK. Please let me know when you have any remaining questions. My assumption right now is that we can close this PR in favor of above?

**Review by FabianMeiswinkel — CHANGES_REQUESTED** [review]
Like mentioned in the comment - Spark catalog would be broken in this case with AAD. Annie has a PR already for adding SPN based AAD support and also addressing the Spark catalog changes

https://github.com/Azure/azure-sdk-for-java/pull/32393

**Comment by arykov** [comment]
Indeed. Too bad it was not linked from corresponding issues and I did not look at pull requests more thoroughly

**Comment by FabianMeiswinkel** [comment]
I added the missing link (and fixed the issue with didn't have porject association correctly - which is why the link was probably missed in the first place)

**Comment by FabianMeiswinkel** [comment]
https://github.com/Azure/azure-sdk-for-java/pull/32393 has been merged in the meantime.

**Pull request closed without merging**
