### PR TITLE
Fix NPE issue in MetadataRequestRetryPolicy.

### PR DESCRIPTION
**Pull request by jeet1995**
`MetadataRequestRetryPolicy` whose responsibility is to mark a region as unavailable cannot do so when `locationEndpointToRoute` is `null` (an example - reading the `DatabaseAccount`). In such cases, this retry policy should behave as a pass-through.

### CODE REVIEW

**Review by FabianMeiswinkel — APPROVED** [review]
LGTM

**Review by kushagraThapar — APPROVED** [review]

**Comment by kushagraThapar** [comment]
> **API change check**
> 
> APIView has identified API level changes in this PR and created following API reviews.
> 
> [com.azure:azure-cosmos](https://apiview.dev/Assemblies/Review/14eb3de7aeec4958abfc67c63f4543b3)

@praveenkuttappan - FYI, this PR doesn't touch any of the public surface, still an API review has been created, and when I click on it, it is loading some stale API review. Can you please take a look at this?

**Pull request merged**
