### PR TITLE
Update Testing Tools Versions

### PR DESCRIPTION
**Pull request by alzimmermsft**
# Description

Updates JUnit and Spock to their latest available versions. For Storage the usage of different Groovy compilers was unified under GMavenPlus.

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [x] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Review by joshfree — APPROVED** [review]
Thank you Alan

**Review by mssfang — APPROVED** [review]

**Comment by alzimmermsft** [comment]
Failing tests are due to a reason other than this change, they'll be followed up on in a separate PR

**Comment by weidongxu-microsoft** [comment]
@alzimmermsft 

Does there change on test file pattern matching in the new junit?

I've seen some failure in mgmt, e.g. https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1987672&view=results
Test at https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/datafactory/azure-resourcemanager-datafactory/src/test/java/com/azure/resourcemanager/datafactory

I assume test file ending with "Tests" should be picked up by surefire?

**Comment by weidongxu-microsoft** [comment]
Maybe it is caused by version conflict on junit via "azure-core-test 1.13.0" which still on junit 5.8.2?

If I move the 
```
    <dependency>
      <groupId>com.azure</groupId>
      <artifactId>azure-core-test</artifactId>
      <version>1.13.0</version> <!-- {x-version-update;com.azure:azure-core-test;dependency} -->
      <scope>test</scope>
    </dependency>
```
section after junit-engine, it works.

**Comment by alzimmermsft** [comment]
> Likely it is caused by version conflict on junit via "azure-core-test 1.13.0" which still on junit 5.8.2?
> 
> If I move the
> 
> ```
>     <dependency>
>       <groupId>com.azure</groupId>
>       <artifactId>azure-core-test</artifactId>
>       <version>1.13.0</version> 
>       <scope>test</scope>
>     </dependency>
> ```
> 
> section after junit-engine, it works.
> 
> Explicitly adding junit-api to pom should also work.

Yeah, the issue is in which version of `junit-jupiter-api` that gets resolved. Without a direct inclusion of the dependency at `5.9.1` it can result in it resolving to `5.8.2` in `azure-core-test` if it's listed as a dependency before `junit-jupiter-engine`. So, either reording the dependencies or directly including `junit-jupiter-api:5.9.1` will resolve this.

**Pull request merged**
