### PR TITLE
Event hubs: pass partition key when publishing with buffered client

### LINKED ISSUE #42700: Get partition key at event data on consumer when using EventHubBufferedProducerAsyncClient producer
Hi
I'm using EventHubBufferedProducerAsyncClient and do enqueueEvent(eventData, new SendOptions().setPartitionKey(partitionKey)).block(); but on the consumer side when i get this event by the consumer (EventHubConsumerClient) and try to get it's partition key by  eventData.getPartitionKey() it return null any idea what should i do in order to get the origin partition key ?

### PR DESCRIPTION
**Pull request by lmolkova**
Fixes #42700

### CODE REVIEW

**Review by anuchandy — APPROVED** [review]
looks good to me. Thanks for the very detailed changelog!

**Review by conniey — APPROVED** [review]

**Pull request merged**
