### PR TITLE
Fixed a bug resulting in high number of PartitionKeyRange ReadFeed requests when using bulk execution not using Spark connector.

### PR DESCRIPTION
**Pull request by FabianMeiswinkel**
# Description

BulkExecutor when outside of Spark was using ContainerAsync.getFeedRanges to get physical partition information - this call would always force the call to be sent to the service (instead of using the local cache). The fix will instead use the cached PKRanges in bulk.

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [x] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Review by xinlian12 — APPROVED** [review]
LGTM, thanks

**Review by kushagraThapar — APPROVED** [review]
LGTM, thanks @FabianMeiswinkel

**Pull request merged**
