### PR TITLE
[Communication] - TNM - Disable Search Number Test

### PR DESCRIPTION
**Pull request by minnieliu**

### CODE REVIEW

**Review by sacheu — APPROVED** [review]
Should we add a task/bug to re-enable this when we can? and add comment here about why we disable them? otherwise forgot about these tests.

**Comment by minnieliu** [comment]
> Should we add a task/bug to re-enable this when we can? and add comment here about why we disable them? otherwise forgot about these tests.

Good idea, let's add a task to re-enable the tests. I can add reason in the task

**Pull request merged**
