### PR TITLE
Added main branch in ci yaml files

### PR DESCRIPTION
**Pull request by sima-zhu**
This is the first step of switching master to main.

### CODE REVIEW

**Review by mitchdenny — APPROVED** [review]

**Review by alzimmermsft — APPROVED** [review]

**Comment by weshaggard** [comment]
@mitchdenny I assume this change caused a huge spike in CI jobs for little value. We should think about doing other large changes by directly pushing to the repo instead of going through the normal PR process.

**Comment by moderakh** [comment]
@weshaggard we are directly pushing changes to the feature branch. But we need to get CI validation, and that's what the purpose of this PR is.

**Comment by sima-zhu** [comment]
@weshaggard We have discussed the spike before open this PR. Mitch said we have provisioning for the agent pool, so it is safer than before. @mitchdenny Do we have any telemetry to check whether we cause a spike for the 4 PRs in each lang repo? Tried to understand the impact of the PR like this

**Comment by weshaggard** [comment]
Even if our pool can handle the spike it is a pretty big waste of work for a change like this so if we can avoid it we should try.

**Pull request merged**
