### PR TITLE
Data upload bigger than 4 MB - Chunked Upload

### PR DESCRIPTION
**Pull request by frascu**
I created a sample method in order to upload data bigger than 4 MB.

If the byte array has a length bigger than `ShareFileAsyncClient.FILE_DEFAULT_BLOCK_SIZE`(4 MB), for each chunk of 4MB a subarray of bytes is extracted and it is uploaded using the calculated offset.
In the end, the last chunk size has a length smaller than 4 MB and it is uploaded correctly.

I added a try-catch in the iteration because if the upload of one chunk fails the incompleted file is deleted on azure storage.

The feature request is explained in issue #18643

### CODE REVIEW

**Comment by alzimmermsft** [comment]
Thank you for submitting this sample @frascu!

@rickle-msft, @gapra-msft mind looking at this and how it aligns with our expectation on handling upload of data larger than 4MB

**Review by gapra-msft — APPROVED** [review]

**Comment by frascu** [comment]
@gapra-msft @alzimmermsft 
Should I fix anything related to failed pipelines?

**Comment by rickle-msft** [comment]
@frascu Yes, we'll ask you to fix the analyze step which should be some minor changes--it's typically a checkstyle or spotbugs error. For some reason the pipeline run seems to have been lost, so I'll run it again and let you know what the error is

**Comment by rickle-msft** [comment]
The pipeline is failing on verifying readme code snippets. You'll notice in the readme that each code sample is tagged with an embedme reference that specifies which lines in the ReadmeSamples file to verify against. This is to ensure that our readme samples actually build. Because your sample added an import, all the line numbers in those embedme references need to be incremented by 1

**Comment by frascu** [comment]
Ok I will add this fix about `embedme`.

Should I also add the new method `uploadDataToStorageBiggerThan4MB` as an example of the README.md?

**Comment by rickle-msft** [comment]
That would be great :)

**Comment by frascu** [comment]
I fixed the `embedme` lines and I added the new method as the example of README.md.

**Pull request merged**
