### PR TITLE
External dependencies upgrade - Spring Boot 2.7.2 and Spring Cloud 2021.0.3

### PR DESCRIPTION
**Pull request by Netyyyy**
Updates external dependencies to align with Spring Boot version [2.7.2](https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-dependencies/2.7.2/spring-boot-dependencies-2.7.2.pom) from [2.7.1](https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-dependencies/2.7.1/spring-boot-dependencies-2.7.1.pom) and Spring Cloud version [2021.0.3](https://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-dependencies/2021.0.3/spring-cloud-dependencies-2021.0.3.pom) from [2021.0.3](https://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-dependencies/2021.0.3/spring-cloud-dependencies-2021.0.3.pom).
<details><summary>Release notes</summary><p><em>Sourced from <a href='https://github.com/spring-projects/spring-boot/releases/tag/v2.7.2'>spring-boot releases</a>.</em></p><h4> <g-emoji class="g-emoji" alias="lady_beetle" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f41e.png">  🐞 </g-emoji> Bug Fixes</h4> <ul>  <li>Publishing a docker image to a private registry fails without authentication <a href="https://github.com/spring-projects/spring-boot/issues/31824" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/31824/hovercard">#31824</a></li>  <li>In a non-reactive application, health indicators in a parent context are not found <a href="https://github.com/spring-projects/spring-boot/issues/31818" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/31818/hovercard">#31818</a></li>  <li>Dependency management for Derby is incomplete <a href="https://github.com/spring-projects/spring-boot/issues/31814" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/31814/hovercard">#31814</a></li>  <li>ApplicationPid doesn't log a warning if it takes a long time to return <a href="https://github.com/spring-projects/spring-boot/issues/31810" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/31810/hovercard">#31810</a></li>  <li>A router function with attributes causes /actuator/mappings to return a 500 response due to an UnsupportedOperationException <a href="https://github.com/spring-projects/spring-boot/issues/31806" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/31806/hovercard">#31806</a></li>  <li>InstanceAlreadyExistsException when using Actuator with multiple context and JMX enabled <a href="https://github.com/spring-projects/spring-boot/issues/31804" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/31804/hovercard">#31804</a></li>  <li>Using 'ImportAutoConfigurationImportSelector' in the jar package loaded by a custom class loader throws ClassNotFoundException <a href="https://github.com/spring-projects/spring-boot/issues/31801" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/31801/hovercard">#31801</a></li>  <li>GraphQL auto-configuration does not configure the GrapQlSource with SubscriptionExceptionResolver beans <a href="https://github.com/spring-projects/spring-boot/issues/31794" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/31794/hovercard">#31794</a></li>  <li>Trailing whitespace in the value of a property is hard to identify in failure analysis descriptions <a href="https://github.com/spring-projects/spring-boot/issues/31780" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/31780/hovercard">#31780</a></li>  <li>Log4j2's shutdown hook is not disabled when using Log4j 2.18 or later <a href="https://github.com/spring-projects/spring-boot/issues/31732" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/31732/hovercard">#31732</a></li>  <li>HTTP Server and Data repositories metrics record null for the description <a href="https://github.com/spring-projects/spring-boot/issues/31706" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/31706/hovercard">#31706</a></li>  <li>Deprecation hint for spring.data.mongodb.grid-fs-database is located in the wrong section <a href="https://github.com/spring-projects/spring-boot/issues/31690" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/31690/hovercard">#31690</a></li>  <li>Image building fails with latest Paketo base builder and additional buildpacks configured <a href="https://github.com/spring-projects/spring-boot/issues/31558" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/31558/hovercard">#31558</a></li>  <li>Tomcat fails to start when PEM files are used and key-store-password is not specified <a href="https://github.com/spring-projects/spring-boot/issues/31253" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/31253/hovercard">#31253</a></li> </ul> <h4> <g-emoji class="g-emoji" alias="notebook_with_decorative_cover" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f4d4.png">  📔 </g-emoji> Documentation</h4> <ul>  <li>Clarify how docker image publishing registry is determined <a href="https://github.com/spring-projects/spring-boot/issues/31826" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/31826/hovercard">#31826</a></li>  <li>Fix typo in "HTTP and WebSocket" section of GraphQL documentation <a href="https://github.com/spring-projects/spring-boot/pull/31518" data-hovercard-type="pull_request" data-hovercard-url="/spring-projects/spring-boot/pull/31518/hovercard">#31518</a></li> </ul> <h4> <g-emoji class="g-emoji" alias="hammer" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f528.png">  🔨 </g-emoji> Dependency Upgrades</h4> <ul>  <li>Upgrade to AppEngine SDK 1.9.98 <a href="https://github.com/spring-projects/spring-boot/issues/31790" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/31790/hovercard">#31790</a></li>  <li>Upgrade to Byte Buddy 1.12.12 <a href="https://github.com/spring-projects/spring-boot/issues/31735" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/31735/hovercard">#31735</a></li>  <li>Upgrade to Couchbase Client 3.3.2 <a href="https://github.com/spring-projects/spring-boot/issues/31736" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/31736/hovercard">#31736</a></li>  <li>Upgrade to Dependency Management Plugin 1.0.12.RELEASE <a href="https://github.com/spring-projects/spring-boot/issues/31556" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/31556/hovercard">#31556</a></li>  <li>Upgrade to Embedded Mongo 3.4.7 <a href="https://github.com/spring-projects/spring-boot/issues/31830" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/31830/hovercard">#31830</a></li>  <li>Upgrade to GraphQL Java 18.2 <a href="https://github.com/spring-projects/spring-boot/issues/31812" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/31812/hovercard">#31812</a></li>  <li>Upgrade to Hibernate 5.6.10.Final <a href="https://github.com/spring-projects/spring-boot/issues/31738" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/31738/hovercard">#31738</a></li>  <li>Upgrade to HttpCore5 5.1.4 <a href="https://github.com/spring-projects/spring-boot/issues/31739" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/31739/hovercard">#31739</a></li>  <li>Upgrade to Jetty Reactive HTTPClient 1.1.12 <a href="https://github.com/spring-projects/spring-boot/issues/31740" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/31740/hovercard">#31740</a></li>  <li>Upgrade to JsonAssert 1.5.1 <a href="https://github.com/spring-projects/spring-boot/issues/31741" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/31741/hovercard">#31741</a></li>  <li>Upgrade to Kotlin Coroutines 1.6.4 <a href="https://github.com/spring-projects/spring-boot/issues/31742" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/31742/hovercard">#31742</a></li>  <li>Upgrade to Lettuce 6.1.9.RELEASE <a href="https://github.com/spring-projects/spring-boot/issues/31743" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/31743/hovercard">#31743</a></li>  <li>Upgrade to MariaDB 3.0.6 <a href="https://github.com/spring-projects/spring-boot/issues/31744" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/31744/hovercard">#31744</a></li>  <li>Upgrade to Micrometer 1.9.2 <a href="https://github.com/spring-projects/spring-boot/issues/31614" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/31614/hovercard">#31614</a></li>  <li>Upgrade to Neo4j Java Driver 4.4.9 <a href="https://github.com/spring-projects/spring-boot/issues/31745" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/31745/hovercard">#31745</a></li>  <li>Upgrade to Netty 4.1.79.Final <a href="https://github.com/spring-projects/spring-boot/issues/31746" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/31746/hovercard">#31746</a></li>  <li>Upgrade to Reactor 2020.0.21 <a href="https://github.com/spring-projects/spring-boot/issues/31608" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/31608/hovercard">#31608</a></li>  <li>Upgrade to SendGrid 4.9.3 <a href="https://github.com/spring-projects/spring-boot/issues/31747" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/31747/hovercard">#31747</a></li>  <li>Upgrade to Spring Data 2021.2.2 <a href="https://github.com/spring-projects/spring-boot/issues/31615" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/31615/hovercard">#31615</a></li>  <li>Upgrade to Spring Framework 5.3.22 <a href="https://github.com/spring-projects/spring-boot/issues/31613" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/31613/hovercard">#31613</a></li>  <li>Upgrade to Spring GraphQL 1.0.1 <a href="https://github.com/spring-projects/spring-boot/issues/31616" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/31616/hovercard">#31616</a></li>  <li>Upgrade to Spring Integration 5.5.14 <a href="https://github.com/spring-projects/spring-boot/issues/31800" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/31800/hovercard">#31800</a></li>  <li>Upgrade to Spring Kafka 2.8.8 <a href="https://github.com/spring-projects/spring-boot/issues/31786" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/31786/hovercard">#31786</a></li>  <li>Upgrade to Tomcat 9.0.65 <a href="https://github.com/spring-projects/spring-boot/issues/31831" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/31831/hovercard">#31831</a></li> </ul> </details>

This PR is created by GitHub Actions: https://github.com/Azure/spring-cloud-azure-tools/actions/runs/2743613902

### CODE REVIEW

**Review by alzimmermsft — APPROVED** [review]

**Review by saragluna — APPROVED** [review]

**Comment by Netyyyy** [comment]
Due to the keyvault tests always [failed](https://dev.azure.com/azure-sdk/internal/_build?definitionId=504&_a=summary), ignore it

**Pull request merged**
