### PR TITLE
Add GA tag to javadoc output and docindex

### PR DESCRIPTION
**Pull request by scbedd**
See title.

This is just the individual javadoc update. There will be another update coming [after this PR](https://github.com/Azure/azure-sdk-tools/pull/1848) is merged that will update the index @ azure.github.io/azure-sdk-for-java.

### CODE REVIEW

**Comment by scbedd** [comment]
The check didn't come back. [Available here](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1017364&view=results)

**Comment by weshaggard** [comment]
@scbedd won't this also end up embedding this into the docs.ms side?

**Comment by scbedd** [comment]
> @scbedd won't this also end up embedding this into the docs.ms side?

No.

**Review by danieljurek — APPROVED** [review]

**Pull request merged**
