### PR TITLE
Clean up specific resource for storage

### PR DESCRIPTION
**Pull request by sima-zhu**

### CODE REVIEW

**Comment by JonathanGiles** [comment]
@alzimmermsft Please review and decide if this should be merged or closed. Thanks.

**Comment by alzimmermsft** [comment]
@JonathanGiles The PRs aim was to remove some resource cleanup steps to help prevent test failures that were happening when the nightly live tests were using the same Storage resources, given @hemanttanwar's changes to deploy resources per test run this is no longer need. Additionally, this PR still has work to regenerate effected playback records.

Closing this PR, we may revisit this in the future but isn't a priority right now.

**Pull request closed without merging**
