### PR TITLE
[FaultInjection]FixConnectionCloseErrorNotAppliedWhenEndpointNotConfigured

### PR DESCRIPTION
**Pull request by xinlian12**
**Issue:**
when injecting connection close/reset errors, if the faultInjectionEndpoint is not being configured, then the rule does not inject properly.

### CODE REVIEW

**Review by FabianMeiswinkel — APPROVED** [review]
LGTM

**Comment by xinlian12** [comment]
Test following test locally and passed:
readAllItemsWithDetailMetricsWithExplicitPageSize

The other failed test is known flaky test: conflictCustomLWW

**Pull request merged**
