### PR TITLE
Unboxing of Boolean to boolean

### PR DESCRIPTION
**Pull request by DanielBenniah**
Unboxing Boolean to boolean 

Defaults to false if Boolean returned is null

https://github.com/Azure/azure-sdk-for-java/issues/9110

### CODE REVIEW

**Comment by kushagraThapar** [comment]
@DanielBenniah  there was some issue with the CI system, because of which the tests are failing. Can you please update your branch with latest master and push the latest changes ?
That way, CI should get fixed.

**Comment by kushagraThapar** [comment]
Didn't mean to close it, sorry. Reopened it.

**Comment by DanielBenniah** [comment]
@kushagraThapar All tests have passed, please let me know if I need to make any changes

**Comment by DanielBenniah** [comment]
Thank you!

**Pull request merged**
