### PR TITLE
Fixed the bug of syntax error

### PR DESCRIPTION
**Pull request by sima-zhu**
# Description

Please add an informative description that covers that changes made by the pull request and link all relevant issues.
The PR is to fix the issue we did not update the latest version in main branch. 
E.g. azure-core is supposed to be 1.30.0 but now it is still at 1.27.0

image

Testing pipeline: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1760460&view=results

If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.

# All SDK Contribution checklist:
- [ ] **The pull request does not introduce [breaking changes]**
- [ ] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [ ] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Review by JimSuplizio — APPROVED** [review]

**Review by benbp — APPROVED** [review]

**Comment by weshaggard** [comment]
@sima-zhu your test pipeline https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1745259&view=logs&j=dc056dfc-c0cf-5958-c8c4-8da4f91a3739 failed due to timeout is that expectec or are there still more issues to address.

**Comment by sima-zhu** [comment]
@weshaggard I triggered the pipeline again. It passed this time.

**Comment by sima-zhu** [comment]
> Did this syntax issue not result in a pipeline failure before? Do we need to handle potential errors from this area more explicitly?

I think use strict mode will help. Language-Setting includes too many other changes. I can't fix all errors in this PR.

**Pull request merged**
