### PR TITLE
[SparkFix]itemBulkUpdateForPkNotEqualId

### PR DESCRIPTION
**Pull request by xinlian12**
**Issue:**
When using the new spark write strategy `ItemBulkUpdate`, when the container's pk != id,  the spark job failed with the following exceptions:

image

**Root Cause:**
For `ItemBulkUpdate` strategy, internally it is using readMany to first read the items, then based on whether the item already exists or not, constructing create or update bulk operation. 

For readMany, it takes in a list of CosmosItemIdentity(PartitionKey, id), and then using the PartitionKey.keyObject in each itemIdentity to construct the query which will be used to fetch the items. However, currently in spark SDK, when parsing the partitionKey, its keyObject is always null, which causing no items will be able to be fetched back, which causing the repeated 409 exceptions. 

**Fix**:
populate the keyObject with proper value

**Test**:
Added integration test

### CODE REVIEW

**Review by FabianMeiswinkel — APPROVED** [review]
LGTM - Thanks!

**Comment by xinlian12** [comment]
Failed tests:
tryGetAddress_repeatedlySetUnhealthyStatus_forceRefresh -> broken in main branch as well, will have a following PR to fix it
ClientMetricsTest::readAllItems, conflictCustomLWW -> known existing flaky tests

**Pull request merged**
