### PR TITLE
Prepare merge spring boot 3 to main

### PR DESCRIPTION
**Pull request by moarychan**
# Description
We plan to stop releasing Spring Cloud Azure 4.x and only release Spring Cloud Azure 5.x in the future, so we will only maintain the main branch for Spring Boot 3 in the future.

Changelogs:
- Merge branch `feature/spring-boot-3` to `main` branch, only keep the source code from `sdk/spring` directory same with `feature/spring-boot-3`; also keep the monitor modules.
- Spring models will pick up the external dependency versions of Spring Boot 3 managed, and tagged with a fixed prefix `springboot3_` in `eng/versioning/external_dependencies.txt`; except for monitor 2 modules;
- Non Spring models will still pick up the external dependency of Spring Boot 2 managed, their dependency versions will be decoupled from the Spring module dependencies.
- Remove cosmos test emulator with java 8.
- Add java 17 and more test agents for Spring combability test.

Ref test PRs:
- https://github.com/Azure/azure-sdk-for-java/pull/41026
- https://github.com/Azure/azure-sdk-for-java/pull/40700

# All SDK Contribution checklist:
- [ ] **The pull request does not introduce [breaking changes]**
- [x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [x] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [ ] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Review by saragluna — APPROVED** [review]

**Review by saragluna — APPROVED** [review]

**Review by Netyyyy — APPROVED** [review]

**Review by Netyyyy — APPROVED** [review]

**Review by kushagraThapar — APPROVED** [review]
LGTM, thanks @moarychan

**Review by JonathanGiles — APPROVED** [review]

**Comment by moarychan** [comment]
Hi @JimSuplizio, @benbp, @hallipr, @weshaggard, can any of you please approve this PR? Thanks in advance!

**Review by JimSuplizio — APPROVED** [review]

**Pull request merged**
