### PR TITLE
Move mediaservices data-plane to sdk/mediaservices

### PR DESCRIPTION
**Pull request by mitchdenny**
This change relocates the mediaservices data plane library to the sdk folder.

### CODE REVIEW

**Comment by mitchdenny** [comment]
@weshaggard do you know who owns the media services data plane library - looks like this was a code dump with no active development going on right now on these libraries.

**Comment by weshaggard** [comment]
>@weshaggard Wes Haggard FTE do you know who owns the media services data plane library - looks like this was a code dump with no active development going on right now on these libraries.

Sorry I'm not sure.

**Pull request merged**
