### PR TITLE
FlowChart

### PR DESCRIPTION
**Pull request by xinlian12**
### Current behavior
Any failure response from the transport that matches the conditions for cross-region communication are handled in ClientRetryPolicy. You can think of ClientRetryPolicy decides which region the request is going to happen. The cross region retry happens sequentially. A new request is being created for each region.

```mermaid
graph TD;
    subgraph ClientRetryPolicy
        subgraph RegionA
        end
        subgraph RegionB
        end
        subgraph RegionC
        end
    end 
    RegionA --> Request1
    Request1 --> B[StoreClient]
    B --> C[GoneAndRetryPolicy]
    C --> D[ConsistencyReader]
    D --> E[SessionTokenMismatchRetryPolicy]
    E --> F[StoreReader]
    F --> G[RntbdTransportClient]
    RegionB --> Request2
    Request2 --> H[StoreClient]
    H --> I[GoneAndRetryPolicy]
    I --> J[ConsistencyReader]
    J --> K[SessionTokenMismatchRetryPolicy]
    K --> L[StoreReader]
    L --> M[RntbdTransportClient]
    RegionC --> Request3
    Request3 --> N[StoreClient]
    N --> O[GoneAndRetryPolicy]
    O --> P[ConsistencyReader]
    P --> Q[SessionTokenMismatchRetryPolicy]
    Q --> R[StoreReader]
    R --> S[RntbdTransportClient]
    
```

```mermaid
timeline
    RegionA : Request1 : StoreClient : GoneAndRetryPolicy : ConsistencyReader 
    RegionB : Request2 : StoreClient : GoneAndRetryPolicy : ConsistencyReader
    RegionC : Request3 : StoreClient : GoneAndRetryPolicy : ConsistencyReader
```

### Future
With the new E2E time out retry policy, speculative processing in another region may happen at the same time. 

```mermaid
timeline
    section 1 
        RegionA : Request1 : StoreClient : GoneAndRetryPolicy : ConsistencyReader 
        RegionB : Request2 : StoreClient : GoneAndRetryPolicy : ConsistencyReader
    section 2
        RegionC : Request3 : StoreClient : GoneAndRetryPolicy : ConsistencyReader
```

### Current region failover flow
```mermaid
graph TD;
    subgraph ClientRetryPolicy
        subgraph RegionA
        end
        subgraph RegionB
        end
    end 
    RegionA --> A[Request1]
    A --> B[StoreReader]
    B --> D{Address from cache}
    D -- Yes --> C[Send request to replica]
    C --> E{Success response}   
    E -- Yes --> F[End]
    E -- No --> G{Exhausted all replicas}
    G -- Yes --> H[GoneAndRetryPolicy]
    G -- No --> C
    H --> B
    D -- No --> J{AddressRefresh succeeded}
   J -- Yes --> C
   J -- No --> RegionB
```

### CODE REVIEW

**Review by FabianMeiswinkel — APPROVED** [review]
LGTM

**Comment by kushagraThapar** [comment]
@xinlian12   we should merge this, it looks good!

**Review by kushagraThapar — APPROVED** [review]

**Comment by xinlian12** [comment]
do not close

**Comment by kushagraThapar** [comment]
@xinlian12 - why close this? It looked good. Shouldn't we merge it in the docs.

**Comment by xinlian12** [comment]
@kushagraThapar - planning to have one PR for the region flow PR + the replica validation flow PR, will move them in a .md file. Do not worry, it will not be lost :)

**Pull request closed without merging**
