### PR TITLE
Auth tutorial

### PR DESCRIPTION
**Pull request by martinsawicki**
enjoy

### CODE REVIEW

**Comment by selvasingh** [comment]
One other terminology items. s/U.S. public cloud/Azure worldwide public cloud/g

**Comment by selvasingh** [comment]
>This approach enables permanent, unattended authentication for your application 

Not permanent :) Instead, this is all about registering an app, securing a client id and key, and authorizing access to Azure resources.

**Comment by martinsawicki** [comment]
ok.. Removing "permanent". 
Note that trying to comprehend the remaining details flies even over my head after waking up 30 min ago :-)  I don't think users at this stage of reading the article are ready for (or care) what happens under the hood, all they want is - "get me out of this article, I want my code to start running!"

**Comment by martinsawicki** [comment]
fixed the U.S. naming issue as suggested.

**Pull request merged**
