### PR TITLE
Validation: Update README.md

### PR DESCRIPTION
**Pull request by v-emilypr**
Updated absolute links per @kushagraThapar

### CODE REVIEW

**Comment by kushagraThapar** [comment]
@v-emilypr - thanks a lot for creating this PR. 

I looked at the builds and found that exactly what issues we are trying to fix in the docs, are not allowed to be fixed because of the CI - see this failure - https://dev.azure.com/azure-sdk/public/_build/results?buildId=1524389&view=logs&jobId=b70e5e73-bbb6-5567-0939-8415943fadb9&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=d155e9a2-7cbb-5b0e-f3c1-03b63fe55961

It is not allowing us to put relative links. 
Also my concern is that these links will not work from the README.md page in the repo. For example, if you go to your branch here - https://github.com/v-emilypr/azure-sdk-for-java/tree/patch-1/sdk/cosmos/azure-cosmos-encryption
And open any links that you have changed, they will not work. 

At this point, I am not sure what would be the way to fix these links just for the docs pages, and not for the repo and anywhere else this README.md file is used. Thoughts?

**Comment by v-emilypr** [comment]
@kushagraThapar 

Thank you for the follow up, let me chat with Andrea about how best to move forward with this.

**Comment by v-andreaco** [comment]
@kushagraThapar 

Thanks for sharing this! This seems like a situation where relative links just won't work. This is a new one for our team, so I'm sorry for all of the runaround, and I really appreciate you taking the time to figure this out. This PR can be closed and we will make a note that the absolute links shouldn't be changed.

**Comment by kushagraThapar** [comment]
@v-andreaco no worries at all, I understand :)
Thanks for the effort and your understanding, appreciate it.

**Pull request closed without merging**
