### PR TITLE
Move storage to sdk/storage

### PR DESCRIPTION
**Pull request by mitchdenny**
This PR moves ```storage``` to ```sdk/storage```. This is the final client/data-plane library we are moving before moving onto the management plane libraries.

### CODE REVIEW

**Comment by danieljurek** [comment]
changes to `tests.yml` look good 👍

**Comment by joshfree** [comment]
@mitchdenny please don't merge this without coordinating with @alzimmermsft @rickle-msft @jaschrep-msft as there are a few PRs still in flight this week for Preview 2

**Comment by mitchdenny** [comment]
> Could you also include an edit to the .github/CODEOWNERS file with this storage => sdk/storage PR?

Done! @alzimmermsft I discussed this restructuring work with you late last week - are you still good for me to land this change?

**Comment by mitchdenny** [comment]
Just rebased after some changes that came in.

**Comment by mitchdenny** [comment]
Rebasing off master again due to conflicting changes. If this builds I'll merge it in.

**Comment by mitchdenny** [comment]
Rebased again :)

https://media.giphy.com/media/44EvH2sc7O06I/giphy.gif

**Pull request merged**
