### PR TITLE
Azure Media Services, bug fixing and missing update methods

### PR DESCRIPTION
**Pull request by rnrneverdies**
Hi folks! In July we sent you some updates to support Content Protection features, Encoding Units Scale feature, and Streaming Endpoints Scale feature.

This time we send you two bug fixes and two missing features for mentioned contribution.

Please let me know if you have any questions or feedback!
Thanks!

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@rnrneverdies__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@rnrneverdies__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by rnrneverdies** [comment]
Any feedback?

**Comment by rnrneverdies** [comment]
@jianghaolu Any feedback?

**Comment by jianghaolu** [comment]
@azuresdkci add to whitelist

**Pull request merged**
