### PR TITLE
adding EnqueuedTimeUtc to BrokerProperties and BrokeredMessage

### PR DESCRIPTION
**Pull request by collinsauve**

### CODE REVIEW

**Comment by jianghaolu** [comment]
Closing as obsolete & merge conflicts. Please reopen with conflicts resolved if this is still the desire behavior.

**Comment by collinsauve** [comment]
How is this obsolete? Was this fixed in another patch?

If I fix the merge conflicts will actually be merged?  This sat for 10 months with no action, it is not exactly inspiring me to submit pull requests to you.

**Comment by jianghaolu** [comment]
@collinsauve 

We are moving onto the AutoRest generated clients and I'm cleaning up the pull requests to the old libraries. (so we can move the new modules to master)

SDK team only hosts the libraries but we don't really own them. I added the service bus team on your issue but apparently they haven't taken a look at. I just think it helps if I can present them with a more up-to-date pull request. Sorry for the frustration, please understand as the repository owner but not the feature owner we experience the same if not more.

**Comment by collinsauve** [comment]
Understood and thanks you.  I'll wait for the new "AutoRest" generated clients.

**Comment by jianghaolu** [comment]
Thanks for your understanding. JFYI, When I said AutoRest I meant https://github.com/azure/autorest.

**Pull request closed without merging**
