### PR TITLE
feature: make non azure implement support different endpoint

### PR DESCRIPTION
**Pull request by xmkevin**
# Description

Sometimes, we want to use non azure implement for other OpenAI compatible endpoint, check azure.com for azure implement seems more nature.

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [x] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Comment by xmkevin** [comment]
@microsoft-github-policy-service agree [company="Sky AI"]

**Comment by Benzhaomin** [comment]
We have the exact same need. I was just about to push the same kind of PR but checked open PRs to see if anything happened since yesterday and there it is! I tested your PR, it fits our usecase as well and just works. 🚀 

For reference, here is my code https://github.com/Azure/azure-sdk-for-java/commit/466ace904e888660ddd2a64febe67c90d3779596

**Comment by xmkevin** [comment]
@ agree company="Sky AI"

**Comment by mssfang** [comment]
@xmkevin @Benzhaomin 
Thank you for your interest and contributions to OpenAI SDK.

May I know what the possible other endpoints could be exist other than the Azure and [Public OpenAI endpoint](https://platform.openai.com/docs/api-reference/authentication) which always started with `https://api.openai.com/v1`?

Appreciate it If more details on the scenarios is provided.

**Comment by xmkevin** [comment]
> @xmkevin @Benzhaomin Thank you for your interest and contributions to OpenAI SDK.
> 
> May I know what the possible other endpoints could be exist other than the Azure and [Public OpenAI endpoint](https://platform.openai.com/docs/api-reference/authentication) which always started with `https://api.openai.com/v1`?
> 
> Appreciate it If more details on the scenarios is provided.

In some case, I need to put an nginx before openai api to use my own domain name. I try to use proxy configuration, but it seems doesn't work.

**Comment by Benzhaomin** [comment]
> @xmkevin @Benzhaomin Thank you for your interest and contributions to OpenAI SDK.
> 
> May I know what the possible other endpoints could be exist other than the Azure and [Public OpenAI endpoint](https://platform.openai.com/docs/api-reference/authentication) which always started with `https://api.openai.com/v1`?
> 
> Appreciate it If more details on the scenarios is provided.

We want to support a new hosted LLM provider that exposes an OpenAI-compatible API. We already have integration with both OpenAI and Azure OpenAI so just being able to customize the endpoint for this other service would be great.

The service in question is https://endpoints.ai.cloud.ovh.net and an example of their API is https://mistral-7b-instruct-v02.endpoints.kepler.ai.cloud.ovh.net/doc#post-/api/openai_compat/v1/chat/completions

**Comment by mssfang** [comment]
Thank you for the reply. Let me bring this topic up to team to see if we should do it. Will keep you updated.

**Comment by viswanathk** [comment]
@mssfang another point in support of this - few companies have some gateway in front of the public facing endpoint through which they control the configuration (org id, auth etc)

this sdk doesn't support those cases.

**Comment by mssfang** [comment]
Hi, @xmkevin @Benzhaomin @viswanathk 

Unfortunately, we will not support non-OpenAI models in this SDK, `azure-ai-openai` as per our partnership with OpenAI. 
The most major models are available as first-class Azure Host Endpoints, such as Llama2, Cohere and Mistra, via Azure MaaS ([Azure AI Studio Model Catalog](https://learn.microsoft.com/en-us/azure/ai-studio/how-to/model-catalog)). They can also host most Hugging Face models or your own models in the future via Azure MaaP(AML) in the future. We will provide an ("OpenAI like") Model Inference API spec for completions to MaaS in the near future.

Note that this SDK support [proxy feature](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/openai/azure-ai-openai/src/samples/java/com/azure/ai/openai/OpenAIProxySample.java). I know it does solve your problem but worth to mention it.

**Comment by xmkevin** [comment]
> Hi, @xmkevin @Benzhaomin @viswanathk
> 
> Unfortunately, we will not support non-OpenAI models in this SDK, `azure-ai-openai` as per our partnership with OpenAI. The most major models are available as first-class Azure Host Endpoints, such as Llama2, Cohere and Mistra, via Azure MaaS ([Azure AI Studio Model Catalog](https://learn.microsoft.com/en-us/azure/ai-studio/how-to/model-catalog)). They can also host most Hugging Face models or your own models in the future via Azure MaaP(AML) in the future. We will provide an ("OpenAI like") Model Inference API spec for completions to MaaS in the near future.
> 
> Worth to mention here that this SDK supports [proxy feature](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/openai/azure-ai-openai/src/samples/java/com/azure/ai/openai/OpenAIProxySample.java) in case someone not aware of it.

ok, waiting for the new feature.

**Pull request closed without merging**
