### PR TITLE
Remove unused Option serialization classes

### PR DESCRIPTION
**Pull request by lmolkova**
`OptionsModule` and a few other package-private classes for `Option` serialization are never used. 

`JsonPatchDocumentSerializer` is also never used, `JsonPatchDocument` takes care  of it own serialization.

I couldn't find any magic that may leverage them. Can they be removed or  I missed something?

### CODE REVIEW

**Comment by srnagar** [comment]
I think this was added to support `PATCH` operations. The `Option` type was added to represent a PATCH operation that serializes the following cases appropriately:
- a property value is not set, so, the service should not update that field when performing the patch operation
- a property value is set to `null`, so, the service should update the field to set its value to `null`.

@anuchandy is this pending autorest support?

**Comment by lmolkova** [comment]
> I think this was added to support `PATCH` operations. The `Option` type was added to represent a PATCH operation that serializes the following cases appropriately:
> 
> * a property value is not set, so, the service should not update that field when performing the patch operation
> * a property value is set to `null`, so, the service should update the field to set its value to `null`.
> 
> @anuchandy is this pending autorest support?

my understanding is that `json-patch` is supported with [JsonPatchDocument](https://github.com/Azure/azure-sdk-for-java/blob/7c9e466e9450fb9c8d0aa204c41758804be6f44b/sdk/core/azure-core/src/main/java/com/azure/core/models/JsonPatchDocument.java#L23), and it's [expected](https://github.com/Azure/azure-sdk-for-java/blob/211865ab80f362da0ab918f7d98013dbc1ae3b78/sdk/core/azure-core/src/test/java/com/azure/core/models/JsonPatchDocumentTests.java#L28-L27) to work with default `JacksonAdapter` serializer, that doesn't need any of the above.

But happy to learn otherwise.

**Comment by alzimmermsft** [comment]
This is actually for `json-merge-patch` which has slightly different semantics.

https://datatracker.ietf.org/doc/html/rfc6902/
https://datatracker.ietf.org/doc/html/rfc7396

**Comment by lmolkova** [comment]
Based on offline discussion with @anuchandy this is a part of the future patrial-update feature. Closing this. Thanks!

**Comment by anuchandy** [comment]
>  srnagar commented 12 hours ago
@anuchandy is this pending autorest support?

@srnagar, the plan to generate the PATCH model (that supports JSON-merge-patch semantics) is not yet there. While we have a good idea of how the model should look like, there needs to have a clear set of rules that CodeGen can follow to determine a swagger definition can be modeled so. Additionally, REST-API review has to ensure the patch definitions follow specific rules to be able to transform those definitions correctly in generated code.

**Pull request closed without merging**
