### PR TITLE
External dependencies upgrade - Spring Boot 2.7.11 and Spring Cloud 2021.0.7

### PR DESCRIPTION
**Pull request by Netyyyy**
Updates external dependencies to align with Spring Boot version [2.7.11](https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-dependencies/2.7.11/spring-boot-dependencies-2.7.11.pom) from [2.7.9](https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-dependencies/2.7.9/spring-boot-dependencies-2.7.9.pom) and Spring Cloud version [2021.0.7](https://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-dependencies/2021.0.7/spring-cloud-dependencies-2021.0.7.pom) from [2021.0.5](https://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-dependencies/2021.0.5/spring-cloud-dependencies-2021.0.5.pom).
<details><summary>Release notes</summary><p><em>Sourced from <a href='https://github.com/spring-projects/spring-boot/releases/tag/v2.7.11'>spring-boot releases</a>.</em></p><h4> <g-emoji class="g-emoji" alias="lady_beetle" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f41e.png">  🐞 </g-emoji> Bug Fixes</h4><ul> <li>CloudFoundry integration does not use endpoint path mappings <a href="https://github.com/spring-projects/spring-boot/issues/35085" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/35085/hovercard">#35085</a></li> <li>Gradle Spring Boot plugin with Kotlin DSL does not support includeProjectDependencies in bootJar &gt; layered &gt; dependencies configuration <a href="https://github.com/spring-projects/spring-boot/issues/35033" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/35033/hovercard">#35033</a></li> <li>Banner placeholders use default values too soon <a href="https://github.com/spring-projects/spring-boot/pull/34764" data-hovercard-type="pull_request" data-hovercard-url="/spring-projects/spring-boot/pull/34764/hovercard">#34764</a></li> <li>Cassandra default configuration substitutions don't resolve against configuration derived from spring.data.cassandra properties <a href="https://github.com/spring-projects/spring-boot/issues/34643" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/34643/hovercard">#34643</a></li> <li>ApplicationAvailability bean is auto-configured even if a custom one is already present <a href="https://github.com/spring-projects/spring-boot/pull/34347" data-hovercard-type="pull_request" data-hovercard-url="/spring-projects/spring-boot/pull/34347/hovercard">#34347</a></li> <li>Nested test classes don't inherit properties from slice test annotations on enclosing class <a href="https://github.com/spring-projects/spring-boot/issues/33317" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/33317/hovercard">#33317</a></li></ul><h4> <g-emoji class="g-emoji" alias="notebook_with_decorative_cover" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f4d4.png">  📔 </g-emoji> Documentation</h4><ul> <li>Use current Neo4j version in Testcontainers-based examples <a href="https://github.com/spring-projects/spring-boot/pull/34775" data-hovercard-type="pull_request" data-hovercard-url="/spring-projects/spring-boot/pull/34775/hovercard">#34775</a></li> <li>Clarify servlet container compatibility <a href="https://github.com/spring-projects/spring-boot/pull/34697" data-hovercard-type="pull_request" data-hovercard-url="/spring-projects/spring-boot/pull/34697/hovercard">#34697</a></li> <li>Document that optional dependencies are included by default in fat jars built with Maven <a href="https://github.com/spring-projects/spring-boot/issues/34636" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/34636/hovercard">#34636</a></li></ul><h4> <g-emoji class="g-emoji" alias="hammer" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f528.png">  🔨 </g-emoji> Dependency Upgrades</h4><ul> <li>Upgrade to DB2 JDBC 11.5.8.0 <a href="https://github.com/spring-projects/spring-boot/issues/34906" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/34906/hovercard">#34906</a></li> <li>Upgrade to GraphQL Java 18.5 <a href="https://github.com/spring-projects/spring-boot/issues/34995" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/34995/hovercard">#34995</a></li> <li>Upgrade to Groovy 3.0.17 <a href="https://github.com/spring-projects/spring-boot/issues/34907" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/34907/hovercard">#34907</a></li> <li>Upgrade to Logback 1.2.12 <a href="https://github.com/spring-projects/spring-boot/issues/34908" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/34908/hovercard">#34908</a></li> <li>Upgrade to Micrometer 1.9.10 <a href="https://github.com/spring-projects/spring-boot/issues/34855" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/34855/hovercard">#34855</a></li> <li>Upgrade to MySQL 8.0.33 <a href="https://github.com/spring-projects/spring-boot/issues/35057" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/35057/hovercard">#35057</a></li> <li>Upgrade to Netty 4.1.91.Final <a href="https://github.com/spring-projects/spring-boot/issues/34909" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/34909/hovercard">#34909</a></li> <li>Upgrade to Reactor Bom 2020.0.31 <a href="https://github.com/spring-projects/spring-boot/issues/34856" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/34856/hovercard">#34856</a></li> <li>Upgrade to Spring AMQP 2.4.12 <a href="https://github.com/spring-projects/spring-boot/issues/34947" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/34947/hovercard">#34947</a></li> <li>Upgrade to Spring Data Bom 2021.2.11 <a href="https://github.com/spring-projects/spring-boot/issues/34902" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/34902/hovercard">#34902</a></li> <li>Upgrade to Spring Framework 5.3.27 <a href="https://github.com/spring-projects/spring-boot/issues/34857" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/34857/hovercard">#34857</a></li> <li>Upgrade to Spring Security 5.7.8 <a href="https://github.com/spring-projects/spring-boot/issues/34948" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/34948/hovercard">#34948</a></li> <li>Upgrade to Spring WS 3.1.6 <a href="https://github.com/spring-projects/spring-boot/issues/34949" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/34949/hovercard">#34949</a></li> <li>Upgrade to Tomcat 9.0.74 <a href="https://github.com/spring-projects/spring-boot/issues/35058" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/35058/hovercard">#35058</a></li> <li>Upgrade to Undertow 2.2.24.Final <a href="https://github.com/spring-projects/spring-boot/issues/34910" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/34910/hovercard">#34910</a></li></ul></details>

This PR is created by GitHub Actions: https://github.com/Azure/spring-cloud-azure-tools/actions/runs/4934000528

### CODE REVIEW

**Comment by Netyyyy** [comment]
Hi @alzimmermsft , 
does it ok to add `netty-common` in `azure-core-http-netty` to fix [error1](https://dev.azure.com/azure-sdk/public/_build/results?buildId=2764263&view=logs&j=8213c06b-ec82-5e45-560c-352e1c4b1152&s=6884a131-87da-5381-61f3-d7acc3b91d76&t=47e1c3c4-d009-54a6-9d70-f959854bb17b&l=58) and [error2](https://dev.azure.com/azure-sdk/public/_build/results?buildId=2764266&view=logs&j=8213c06b-ec82-5e45-560c-352e1c4b1152&t=47e1c3c4-d009-54a6-9d70-f959854bb17b&s=6884a131-87da-5381-61f3-d7acc3b91d76)
Here is the [commit](https://github.com/Azure/azure-sdk-for-java/pull/34875/commits/91f6cb635c3cb659192b7244290575e6e0956102)

**Comment by alzimmermsft** [comment]
> Hi @alzimmermsft , does it ok to add `netty-common` in `azure-core-http-netty` to fix [error1](https://dev.azure.com/azure-sdk/public/_build/results?buildId=2764263&view=logs&j=8213c06b-ec82-5e45-560c-352e1c4b1152&s=6884a131-87da-5381-61f3-d7acc3b91d76&t=47e1c3c4-d009-54a6-9d70-f959854bb17b&l=58) and [error2](https://dev.azure.com/azure-sdk/public/_build/results?buildId=2764266&view=logs&j=8213c06b-ec82-5e45-560c-352e1c4b1152&t=47e1c3c4-d009-54a6-9d70-f959854bb17b&s=6884a131-87da-5381-61f3-d7acc3b91d76) Here is the [commit](https://github.com/Azure/azure-sdk-for-java/pull/34875/commits/91f6cb635c3cb659192b7244290575e6e0956102)

I have no issue with adding a direct dependency on `netty-common` into `azure-core-http-netty` as that ends up being a transitive dependency anyways and making it a direct dependency will help prevent version mismatch scenarios.

**Review by alzimmermsft — APPROVED** [review]

**Pull request merged**
