### PR TITLE
Add ENV AuthorityHost Test

### PR DESCRIPTION
**Pull request by Luyunmt**
Add ENV AuthorityHost Test

### CODE REVIEW

**Comment by Luyunmt** [comment]
@g2vinay  This is PR [Add EnvVar AZURE_AUTHORITY_HOST](https://github.com/Azure/azure-sdk-for-java/pull/9392)'s Test, please merge it.

**Comment by jongio** [comment]
@g2vinay - We good on this one?

**Comment by g2vinay** [comment]
This change was merged via #20782

**Pull request closed without merging**
