### PR TITLE
Fix integration test not executed in AAD modules.

### PR DESCRIPTION
**Pull request by chenrujun**
Fix integration test not executed in:

1. azure-spring-boot-test-aad-resource-server
2. azure-spring-boot-test-aad-resource-server-by-filter
3. azure-spring-boot-test-aad-obo

### CODE REVIEW

**Comment by chenrujun** [comment]
Hi, @backwind1233 , please help to review this PR. 🙏

**Comment by chenrujun** [comment]
Related PR: https://github.com/Azure/azure-sdk-for-java/pull/20700

**Review by backwind1233 — APPROVED** [review]
LGTM

**Pull request merged**
