### PR TITLE
Support two major spring boot version in azure spring boot modules

### PR DESCRIPTION
**Pull request by moarychan**
According to the two versions 2.2.x and 2.3.x of spring boot, all the azure-spring-boot-test-xxx modules need to pass the live test respectively.

### CODE REVIEW

**Comment by chenrujun** [comment]
Test failed, and, I re-run `java - spring - tests` just now.

**Review by chenrujun — APPROVED** [review]
LGTM.

**Review by saragluna — APPROVED** [review]
LGTM.

**Pull request merged**
