### PR TITLE
mgmt redis, update to 2022-06

### PR DESCRIPTION
**Pull request by XiaofeiCao**
# Description

Manual code on tests in https://github.com/Azure/azure-sdk-for-java/commit/eb91c93656fe2743b68d2ca4f4259fb45a5e7d36
1. `aof-backup-enabled` moved from `additionalProperties` to root of `RedisConfiguration`.
2. Added linked server removal after test.

live tests pass. 

Please add an informative description that covers that changes made by the pull request and link all relevant issues.

If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.

# All SDK Contribution checklist:
- [ ] **The pull request does not introduce [breaking changes]**
- [ ] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [ ] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Review by weidongxu-microsoft — COMMENTED** [review]
Did you run "RedisConfigurationTests.generateConfigurationUtils" and update the code in ConfigurationUtils?

**Review by weidongxu-microsoft — APPROVED** [review]

**Comment by XiaofeiCao** [comment]
> Did you run "RedisConfigurationTests.generateConfigurationUtils" and update the code in ConfigurationUtils?

Yeah, it passed. 

I checked again and find out that `aof-backup-enabled` is a newly added property of `RedisConfiguraion`. I'll add a test case of `aof-backup-enabled` and add it to `toMap` in `ConfigurationUtils`.

**Comment by weidongxu-microsoft** [comment]
> Yeah, it passed.
> 
> I checked again and find out that `aof-backup-enabled` is a newly added property of `RedisConfiguraion`. I'll add a test case of `aof-backup-enabled` and add it to `toMap` in `ConfigurationUtils`.

I mean this is not actually a test. It outputs the code of ConfigurationUtils.java. You should be able to just paste and replace the output to ConfigurationUtils.java

**Comment by XiaofeiCao** [comment]
> I mean this is not actually a test. It outputs the code of ConfigurationUtils.java. You should be able to just paste the output and replace part of ConfigurationUtils.java <-- this replacement is still manual

OK, got it... Thanks!

**Pull request merged**
