### PR TITLE
Marked all share and share snapshot tests as playback

### PR DESCRIPTION
**Pull request by gapra-msft**
This feature has been disabled on the service

### CODE REVIEW

**Comment by gapra-msft** [comment]
Check enforcer is stuck

**Review by xiafu-msft — APPROVED** [review]

**Comment by seanmcc-msft** [comment]
What about ShareClient tests involving Shares with existing leases?  Like GetProperties_Lease() (Assuming you have tests like this)

**Review by kasobol-msft — APPROVED** [review]

**Comment by gapra-msft** [comment]
Check enforcer is stuck

**Pull request merged**
