### PR TITLE
Add integration test for keyvault certificate

### PR DESCRIPTION
**Pull request by zhichengliu12581**
add integration test for keyvault certificate.
related task: https://dev.azure.com/azure-spring-integration/spring-integration-private/_sprints/backlog/spring-integration-private%20Team/spring-integration-private/188?workitem=1239

- add integration test module and create certificates
- add test for mTLS

### CODE REVIEW

**Comment by chenrujun** [comment]
@lzc-1997-abel , maybe wrong operation of `merge`?

**Comment by lzc-1997-abel** [comment]
@chenrujun Fixed, Thanks

**Comment by chenrujun** [comment]
Hi, @lzc-1997-abel , please fix the pipeline failure.

**Review by chenrujun — CHANGES_REQUESTED** [review]

**Comment by chenrujun** [comment]
Hi, @lzc-1997-abel , please fix the pipeline failure.

**Pull request merged**
