### PR TITLE
Fix the issue where the token acquisition timeout is not set via the property `azure.accessTokenTimeoutInSeconds`

### PR DESCRIPTION
**Pull request by moarychan**
Changelogs:
- Fixes https://github.com/Azure/azure-sdk-for-java/issues/43512
- Add the released version in CHANGELOG.md
- Assume the next version is 1.2.0

# Description

Please add an informative description that covers that changes made by the pull request and link all relevant issues.

If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [ ] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Comment by moarychan** [comment]
Hi @mssfang, I note the minor version of previous release package is still 1.1 and increase the patch version, shall we increase the minor version to 1.2 for the next version release?

**Review by rujche — APPROVED** [review]
LGTM.

**Review by saragluna — APPROVED** [review]

**Comment by vcolin7** [comment]
> Hi @mssfang, I note the minor version of previous release package is still 1.1 and increase the patch version, shall we increase the minor version to 1.2 for the next version release?

Our libraries adhere to the [Semantic Versioning guidelines](https://semver.org/). In general, if we have not added new functionality, we should not increase the minor version number.

**Comment by moarychan** [comment]
> Our libraries adhere to the [Semantic Versioning guidelines](https://semver.org/). In general, if we have not added new functionality, we should not increase the minor version number.

@vcolin7 thanks for update, it just so happens that there is a feature ready to be merged, see more from https://github.com/Azure/azure-sdk-for-java/pull/43659

**Pull request merged**
