### PR TITLE
Autogen sdk Javadoc 

### PR DESCRIPTION
**Pull request by hovsepm**

### CODE REVIEW

**Comment by Petermarcu** [comment]
@kurtzeborn can you follow up on this and see if its still a needed change?

**Comment by mitchdenny** [comment]
Removing Scott from this PR so we don't starve any dogs. @hovsepm can you provide a bit more detail about this PR. If we don't need it can we please close it. If I don't hear back in a week or so I'll just close it and we can re-open it if we need to.

**Comment by hovsepm** [comment]
@mitchdenny this was an effort to automate JavaDocs publishing directly from the repo to gh-pages. I believe you can close the PR as bunch of things have been changed since and I do not remember much context of why the PR was not merged.

**Comment by kurtzeborn** [comment]
@hovsepm, Looks like this is okay to close based on your last comment.

**Pull request closed without merging**
