### PR TITLE
Migrate Tables tests 

### PR DESCRIPTION
**Pull request by jairmyree**
This PR migrates all tests except the following to use MI instead of connections strings and SAS tokens:

### Untransitioned Tests
These tests require the use of connection string / SAS token authentication and cannot be migrated.
- TableServiceClientTest
  - generateAccountSasTokenWithMinimumParameters
  - generateAccountSasTokenWithAllParameters
  - canUseSasTokenToCreateValidTableClient
- TableServiceAsyncClientTest
  - generateAccountSasTokenWithMinimumParameters
  - generateAccountSasTokenWithAllParameters
  - canUseSasTokenToCreateValidTableClient
- TableClientTest
  - generateSasTokenWithMinimumParameters
  - generateSasTokenWithAllParameters
  - canUseSasTokenToCreateValidTableClient
  - setAndListAccessPolicies
  - setAndListMultipleAccessPolicies
- TableAsyncClientTest
  - generateSasTokenWithMinimumParameters
  - generateSasTokenWithAllParameters
  - canUseSasTokenToCreateValidTableClient
  - setAndListAccessPolicies
  - setAndListMultipleAccessPolicies

### CODE REVIEW

**Review by vcolin7 — COMMENTED** [review]
Changes look good other than us disabling the Cosmos tests. I'm going to re-enable them soon and check if the pipelines are green with the current changes :)

**Review by g2vinay — APPROVED** [review]

**Review by vcolin7 — APPROVED** [review]

**Pull request merged**
