### PR TITLE
Fix readme issues for the azure service bus

### PR DESCRIPTION
**Pull request by frascu**
This fixes issue #18807.
If @hemanttanwar has not already fixed, this pull request could be merged.

### CODE REVIEW

**Comment by v-xuto** [comment]
@hemanttanwar @conniey - Can you help review this PR?

**Comment by joshfree** [comment]
@ki1729 can you please review this PR as part of resolving https://github.com/Azure/azure-sdk-for-java/issues/18807

**Review by ki1729 — APPROVED** [review]
Looks good!

**Comment by mikeharder** [comment]
Closing and re-opening to trigger pipelines

**Comment by mikeharder** [comment]
Validation build: https://dev.azure.com/azure-sdk/public/_build/results?buildId=982171&view=results

**Pull request merged**
