### PR TITLE
enableHandleLatestChanges API

### PR DESCRIPTION
**Pull request by xinlian12**
Part of the feature work https://github.com/Azure/azure-sdk-for-java/issues/32131

**Changes included:**
Enable `handleLatestVersionChanges` in ChangeFeedProcessor. Related design can be found in PR https://github.com/Azure/azure-sdk-for-java/pull/32496

**Tests included:**

- Unit Tests
- Changed CI pipeline to create database account with `enablePartitionMerge` 
- Manual testing with query (with/without continuationToken) after merge happens
- Manual testing with query with continuationToken with split, merge then split flow
- Manual testing with changeFeedProcessor before & after merge happens
- Manual testing with changeFeedProcessor with split, merge then split flow
- Running CtlWorkload with merge being triggered

### CODE REVIEW

**Review by FabianMeiswinkel — APPROVED** [review]
TLGTM - Thanks

**Comment by xinlian12** [comment]
Tested the following two failed tests locally:
createItem_withBulk_split
readFeedDocumentsAfterSplit

**Pull request merged**
