### PR TITLE
Add Monitor service

### PR DESCRIPTION
**Pull request by RikkiGibson**
Note particularly b782cff and ac6266e. @hovsepm does this seem like a reasonable way to expose both resource and data plane clients?

### CODE REVIEW

**Comment by hovsepm** [comment]
Looks good. Please also uncomment azure-mgmt-monitor entry in azure\pom.xml at line 150 and include that file to your PR

**Comment by RikkiGibson** [comment]
Done. Just checking-- for most of these generated Beta-annotated managers, we aren't including them in azure/pom.xml but are requiring people pull them down individually, right?

**Comment by martinsawicki** [comment]
@RikkiGibson right, since they have no interesting fluent layers yet, there is no point of rolling them up into the Azure package, which is intended as a convenience. These are for advanced devs only.

**Comment by RikkiGibson** [comment]
@hovsepm In this case I'll refrain from issuing another PR to add the newly generated services to azure/pom.xml

**Comment by hovsepm** [comment]
LGTM.

**Pull request merged**
