### PR TITLE
Migrate Mixed Reality Authentication tests to `TokenCredential` auth

### PR DESCRIPTION
**Pull request by vcolin7**
Migrates Mixed Reality Authentication to use `TokenCredential` auth in tests. For more information, see [here](https://github.com/Azure/azure-sdk-for-java-pr/issues/1418).

### CODE REVIEW

**Comment by anuchandy** [comment]
Hi @vcolin7, it looks like the SDK requires a resource instance of type [spatial-anchors](https://github.com/Azure/azure-sdk-for-java/blob/d00b78804e7eec0d2fba897ef6c1018cacd80eb1/sdk/mixedreality/test-resources.json#L33). This resource type is being retired (complete phaseout in Nov-2024). It is [not allowed to create](https://learn.microsoft.com/en-us/answers/questions/1662533/microsoft-spatialanchorsaccount-deployment-fails-d) new instances anymore - [azure-spatial-anchors-retirement](https://azure.microsoft.com/en-us/updates/azure-spatial-anchors-retirement/#:%7E:text=Please%20note%20that%20Azure%20Spatial,spatial%20computing%20technologies%20and%20platforms). So maybe we just leave this SDK as it is or set pipeline for federated auth and force merge it

**Review by anuchandy — APPROVED** [review]

**Comment by vcolin7** [comment]
Closing in favor of #41037.

**Pull request closed without merging**
