### PR TITLE
Upgrade Jackson and Netty Patch Versions

### PR DESCRIPTION
**Pull request by alzimmermsft**

### CODE REVIEW

**Review by srnagar — APPROVED** [review]

**Review by kushagraThapar — APPROVED** [review]
LGTM, thanks @alzimmermsft - please run the full cosmos tests for sanity check.

**Review by moderakh — CHANGES_REQUESTED** [review]
@alzimmermsft could you please pause merging this PR for a few hours?

we are merging a feature branch to master which should complete in the next few hours. our ETA for our completing our merge is EOD.

**Review by moderakh — APPROVED** [review]
our cosmos db spark connector branch merged to master. 

from Cosmos spark prespective, please make sure "windows2019_18_SparkIntegrationTeststargetingCosmosEmulator" CI pass.

**Pull request merged**
