### PR TITLE
Resolve From Source Compilation Failure Caused by Spark Modules

### PR DESCRIPTION
**Pull request by alzimmermsft**
# Description

This PR attempts to resolve the From Source compilation failures being seen in the Cosmos Spark modules.

The following changes were made:

- The Cosmos Spark parent POM was added back to the repository. Without it the sparse checkout step wouldn't include the directory that contained it which contains shared source code for the Spark 3.1 and 3.2 implementations.
- The `generate_from_source_pom.py` script added the Cosmos Spark parent POM as a valid parent POM. This ensures that the two children Cosmos Spark implementations will be included in the From Source runs.
- The Cosmos Spark implementation POMs now include `azure-cosmos` directly. This ensures they are included in the From Source runs.
- The build configurations in the Cosmos Spark parent POM were moved into a profile that only the implementation POMs will activate. This prevent the Cosmos Spark parent POM from attempting to run build that it will fail on, the reason why it was previously removed.
- The shading plugin in the Cosmos Spark parent POM was moved into a separate profile as there is a known bug where `maven-shade-plugin` can deadlock an application when used in a parallel build.
- A bug was fixed in the `generate_overview_from_readme.py` if the output directory doesn't exist. If the output directory doesn't exist the directory path(s) are now created.

Follow-ups to this PR are the following:

- The `generate_from_source_pom.py` script needs to be updated to handle a few new scenarios.
  - The parent POM hierarchy needs to be traversed when determining to include or exclude a project POM. The lack of this functionality is one of the reasons why the Cosmos Spark implementations weren't included in the From Source POM as they use an intermediate parent.
  - The parent POM dependencies need to be inspected when determining to include or exclude a project POM. The lack of this functionality is one of the reason why the Cosmos Spark implementations weren't included in the From Source POM as the `azure-cosmos` dependency (the only `com.azure` dependency being used) is defined in the parent POM.
- The Cosmos pipelines need to pass the profile flag to trigger shading for the Cosmos Spark implementations to validate the shaded JARs were generated as expected. This may also require reducing the parallelization of the Cosmos CI pipelines to reduce the chances the threading bug is hit.

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](../../CONTRIBUTING.md#building-and-unit-testing)
- [x] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Review by FabianMeiswinkel — APPROVED** [review]
Thanks - LGTM. The Spark CI failure I can address separately - so feel free to override that one.

**Comment by alzimmermsft** [comment]
Tracking issue for `generate_from_source_pom.py`: https://github.com/Azure/azure-sdk-for-java/issues/26640

**Comment by alzimmermsft** [comment]
Spark integration tests are known to have a failure case, once Core CI passes I will override check-enforcer and merge the PR.

**Pull request merged**
