### PR TITLE
Update last unhealthy timestamp only when replica transitions to Unhealthy state

### PR DESCRIPTION
**Pull request by jeet1995**
**Issue:**

The `lastUnhealthyTimestamp` in `Uri` is updated to `Instant.now()` each time the Uri is set as `Unhealthy`. This can delay address refreshes which happen when a `Uri` has been `Unhealthy` for more than a minute since the SDK thinks the `Uri` only recently became `Unhealthy` and not a minute ago.

**Fix:**

Use a `lastTransitionToUnhealthyTimestamp` which tracks the timestamp when the `Uri` transitioned to `Unhealthy` state from a different state.

### CODE REVIEW

**Review by FabianMeiswinkel — APPROVED** [review]
LGTM - Thanks

**Review by xinlian12 — APPROVED** [review]
LGTM, thanks

**Pull request merged**
