### PR TITLE
Renamed setXXX() to withXXX() for non top-level methods

### LINKED ISSUE #734: Rename setXXX() to withXXX() for non top-level models for consistency

### PR DESCRIPTION
**Pull request by dsesclei**
Closes #734

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@dsesclei__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (t-dasesc). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by jianghaolu** [comment]
`azure-batch` is the folder that has a bunch of customization code.
`azure-mgmt-resource/storage/compute/network` has fluent interface.
It will be nice if you can run a quick regex replacement on their setters. 😺 

BTW once that's done I'm sure there will be a bunch of merge conflicts. If you'd like to leave them to me just close this and send

**Comment by azurecla** [comment]
Hi __@dsesclei__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (t-dasesc). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by jianghaolu** [comment]
Whoops unintentional closing and reopening.

**Comment by jianghaolu** [comment]
Continued in #771. Closing.

**Pull request closed without merging**
