### PR TITLE
mgmt, loadtesting, change namespace to com.azure.resourcemanager.loadtesting

### PR DESCRIPTION
**Pull request by weidongxu-microsoft**
SDK arch board review https://github.com/Azure/azure-sdk/issues/4987

Move to loadtesting folder. Data-plane SDK is not modified. Currently there is no sample browse link to either the data-plane SDK nor the mgmt SDK. Anyway both is preview.

No need for code review as it is generated. Mgmt is regened. https://github.com/Azure/azure-sdk-for-java/pull/32096/commits/33f7c3ac333eb7509c560a39021c1e47e26a043e

I will delete or archive the old CI pipeline from loadtestservice folder.

After SDK with new namespace released, I will update the csv and mark the previous preview SDK as deprecated.

May need to update doc as well https://github.com/Azure/azure-docs-sdk-java/blob/main/preview/docs-ref-mapping/reference-preview.yml#L1271

@Harshan01 @abranj1219

# Description

Please add an informative description that covers that changes made by the pull request and link all relevant issues.

If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.

# All SDK Contribution checklist:
- [ ] **The pull request does not introduce [breaking changes]**
- [ ] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [x] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [ ] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Comment by weidongxu-microsoft** [comment]
cspell flaged "vuser" from Javadoc on API

```java
    /**
     * Get test run details by name.
     *
     * <p><strong>Response Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     testRunId: String (Optional)
     *     displayName: String (Optional)
     *     testId: String (Optional)
     *     resourceId: String (Optional)
     *     description: String (Optional)
     *     status: String (Optional)
     *     startDateTime: OffsetDateTime (Optional)
     *     endDateTime: OffsetDateTime (Optional)
     *     loadTestConfig (Optional): {
     *         engineInstances: Integer (Optional)
     *         splitAllCSVs: Boolean (Optional)
     *     }
     *     testResult: String (Optional)
     *     passFailCriteria (Optional): {
     *         passFailMetrics (Optional): {
     *             String (Optional): {
     *                 clientmetric: String (Optional)
     *                 aggregate: String (Optional)
     *                 condition: String (Optional)
     *                 requestName: String (Optional)
     *                 value: Double (Optional)
     *                 action: String (Optional)
     *                 actualValue: Double (Optional)
     *                 result: String (Optional)
     *             }
     *         }
     *     }
     *     testArtifacts (Optional): {
     *         inputArtifacts (Required): {
     *             configUrl (Optional): {
     *                 url: String (Optional)
     *                 fileId: String (Optional)
     *                 filename: String (Optional)
     *                 fileType: String(0/1/2) (Optional)
     *                 expireTime: OffsetDateTime (Optional)
     *                 validationStatus: String (Optional)
     *             }
     *             testScriptUrl (Optional): (recursive schema, see testScriptUrl above)
     *             userPropUrl (Optional): (recursive schema, see userPropUrl above)
     *             inputArtifactsZipFileurl (Optional): (recursive schema, see inputArtifactsZipFileurl above)
     *             additionalUrls (Optional): [
     *                 (recursive schema, see above)
     *             ]
     *         }
     *         outputArtifacts (Optional): {
     *             resultUrl (Optional): (recursive schema, see resultUrl above)
     *             logsUrl (Optional): (recursive schema, see logsUrl above)
     *         }
     *     }
     *     executedDateTime: OffsetDateTime (Optional)
     *     vusers: Integer (Optional)
     *     testRunStatistics (Optional): {
     *         String (Optional): {
     *             transaction: String (Optional)
     *             sampleCount: Double (Optional)
     *             errorCount: Double (Optional)
     *             errorPct: Double (Optional)
     *             meanResTime: Double (Optional)
     *             medianResTime: Double (Optional)
     *             maxResTime: Double (Optional)
     *             minResTime: Double (Optional)
     *             pct1ResTime: Double (Optional)
     *             pct2ResTime: Double (Optional)
     *             pct3ResTime: Double (Optional)
     *             throughput: Double (Optional)
     *             receivedKBytesPerSec: Double (Optional)
     *             sentKBytesPerSec: Double (Optional)
     *         }
     *     }
     *     createdDateTime: OffsetDateTime (Optional)
     *     createdBy: String (Optional)
     *     lastModifiedDateTime: OffsetDateTime (Optional)
     *     lastModifiedBy: String (Optional)
     *     portalUrl: String (Optional)
     *     secrets (Optional): {
     *         String (Optional): {
     *             value: String (Optional)
     *             type: String (Optional)
     *         }
     *     }
     *     environmentVariables (Optional): {
     *         String: String (Optional)
     *     }
     *     duration: Long (Optional)
     *     subnetId: String (Optional)
     * }
     * }</pre>
     *
     * @param testRunId Unique name of load test run, must be a valid URL character ^[a-z0-9_-]*$.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return test run details by name along with {@link Response} on successful completion of {@link Mono}.
     */
```

**Comment by Harshan01** [comment]
@weidongxu-microsoft Is it possible to change the management package namespace to `loadtesting` while retaining the service directory as `loadtestservice`? We use `loadtestservice` in `azure-rest-api-specs` and all other SDK repos.

**Comment by weidongxu-microsoft** [comment]
@Harshan01

We will see opinions from SDK reviewers.

If your namespace is `loadtesting` in Java SDK, it should take the service folder as `loadtesting`, regardless of your swagger or other SDK repo.

The only problem is that it wrongly used `loadtestservice` before, so some might not wish to do the switch now.

**Comment by weidongxu-microsoft** [comment]
@alzimmermsft @samvaity

Any guide on the service/group folder name? Checking whether we should rename the folder to "loadtesting".

Artifact is "azure-developer-loadtesting" and "azure-resourcemanager-loadtesting".

Their swagger location is "loadtestservice" https://github.com/Azure/azure-rest-api-specs/tree/main/specification/loadtestservice

---

We've released a few preview in SDK "loadtestservice" folder, but there is no sample.md hence should be no link back from doc.

**Comment by samvaity** [comment]
> @alzimmermsft @samvaity
> 
> Any guide on the service/group folder name? Checking whether we should rename the folder to "loadtesting".
> 
> Artifact is "azure-developer-loadtesting" and "azure-resourcemanager-loadtesting".
> 
> Their swagger location is "loadtestservice" https://github.com/Azure/azure-rest-api-specs/tree/main/specification/loadtestservice
> 
> We've released a few preview in SDK "loadtestservice" folder, but there is no sample.md hence should be no link back from doc.

I think we should rename it to `loadtesting` and be consistent throughout everywhere including rest-api specification folder.

**Comment by weidongxu-microsoft** [comment]
> I think we should rename it to `loadtesting` and be consistent throughout everywhere including rest-api specification folder.

Thanks Sameeksha. They rest spec folder likely not going to change, as their registered service namespace is [Microsoft.LoadTestService](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/loadtestservice/resource-manager/Microsoft.LoadTestService).

It is for SDK that everyone is called LoadTesting for all languages.

**Review by haolingdong-msft — APPROVED** [review]

**Pull request merged**
