### PR TITLE
External dependencies upgrade - Spring Boot 2.7.5 and Spring Cloud 2021.0.4

### PR DESCRIPTION
**Pull request by Netyyyy**
Updates external dependencies to align with Spring Boot version [2.7.5](https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-dependencies/2.7.5/spring-boot-dependencies-2.7.5.pom) from [2.7.4](https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-dependencies/2.7.4/spring-boot-dependencies-2.7.4.pom) and Spring Cloud version [2021.0.4](https://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-dependencies/2021.0.4/spring-cloud-dependencies-2021.0.4.pom) from [2021.0.4](https://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-dependencies/2021.0.4/spring-cloud-dependencies-2021.0.4.pom).
<details><summary>Release notes</summary><p><em>Sourced from <a href='https://github.com/spring-projects/spring-boot/releases/tag/v2.7.5'>spring-boot releases</a>.</em></p><h4> <g-emoji class="g-emoji" alias="lady_beetle" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f41e.png">  🐞 </g-emoji> Bug Fixes</h4> <ul>  <li>Multi-Document-Separators "#---" comment checks do not account for '!' prefixed comments <a href="https://github.com/spring-projects/spring-boot/issues/32777" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/32777/hovercard">#32777</a></li>  <li>Actuator configprops endpoint does not display DataSize properties correctly <a href="https://github.com/spring-projects/spring-boot/issues/32775" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/32775/hovercard">#32775</a></li>  <li><code>@Bean</code> methods in KafkaAutoConfiguration provide less type information than they could <a href="https://github.com/spring-projects/spring-boot/issues/32773" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/32773/hovercard">#32773</a></li>  <li>PEM formatted elliptic-curve TLS keys are an unrecognized private key format <a href="https://github.com/spring-projects/spring-boot/issues/32681" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/32681/hovercard">#32681</a></li>  <li>Assertion calls on CapturedOutput with Kotlin are very slow <a href="https://github.com/spring-projects/spring-boot/issues/32575" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/32575/hovercard">#32575</a></li>  <li>Empty <code>@DefaultValue</code> cannot be used on collections, maps, arrays or optional values <a href="https://github.com/spring-projects/spring-boot/issues/32563" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/32563/hovercard">#32563</a></li>  <li>CouchbaseReactiveHealthIndicator uses blocking API to retrieve the cluster diagnostics <a href="https://github.com/spring-projects/spring-boot/issues/32513" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/32513/hovercard">#32513</a></li>  <li>BootBuildImage's archiveFile property is annotated as an <code>@Input</code> but should be annotated as an <code>@InputFile</code> <a href="https://github.com/spring-projects/spring-boot/issues/32499" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/32499/hovercard">#32499</a></li> </ul> <h4> <g-emoji class="g-emoji" alias="notebook_with_decorative_cover" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f4d4.png">  📔 </g-emoji> Documentation</h4> <ul>  <li>Remove redundant <code>@ExtendWith</code>(SpringExtension.class) from MyJmxTests example <a href="https://github.com/spring-projects/spring-boot/issues/32515" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/32515/hovercard">#32515</a></li> </ul> <h4> <g-emoji class="g-emoji" alias="hammer" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f528.png">  🔨 </g-emoji> Dependency Upgrades</h4> <ul>  <li>Upgrade to Byte Buddy 1.12.18 <a href="https://github.com/spring-projects/spring-boot/issues/32697" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/32697/hovercard">#32697</a></li>  <li>Upgrade to Dependency Management Plugin 1.0.15.RELEASE <a href="https://github.com/spring-projects/spring-boot/issues/32786" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/32786/hovercard">#32786</a></li>  <li>Upgrade to Ehcache3 3.10.2 <a href="https://github.com/spring-projects/spring-boot/issues/32663" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/32663/hovercard">#32663</a></li>  <li>Upgrade to Embedded Mongo 3.4.11 <a href="https://github.com/spring-projects/spring-boot/issues/32664" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/32664/hovercard">#32664</a></li>  <li>Upgrade to Glassfish JAXB 2.3.7 <a href="https://github.com/spring-projects/spring-boot/issues/32787" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/32787/hovercard">#32787</a></li>  <li>Upgrade to Hazelcast 5.1.4 <a href="https://github.com/spring-projects/spring-boot/issues/32698" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/32698/hovercard">#32698</a></li>  <li>Upgrade to Hibernate 5.6.12.Final <a href="https://github.com/spring-projects/spring-boot/issues/32665" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/32665/hovercard">#32665</a></li>  <li>Upgrade to Infinispan 13.0.12.Final <a href="https://github.com/spring-projects/spring-boot/issues/32788" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/32788/hovercard">#32788</a></li>  <li>Upgrade to Jackson Bom 2.13.4.20221013 <a href="https://github.com/spring-projects/spring-boot/issues/32724" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/32724/hovercard">#32724</a></li>  <li>Upgrade to Jetty Reactive HTTPClient 1.1.13 <a href="https://github.com/spring-projects/spring-boot/issues/32699" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/32699/hovercard">#32699</a></li>  <li>Upgrade to Lettuce 6.1.10.RELEASE <a href="https://github.com/spring-projects/spring-boot/issues/32666" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/32666/hovercard">#32666</a></li>  <li>Upgrade to Micrometer 1.9.5 <a href="https://github.com/spring-projects/spring-boot/issues/32591" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/32591/hovercard">#32591</a></li>  <li>Upgrade to MySQL 8.0.31 and extend dependency management to new Maven identifiers <a href="https://github.com/spring-projects/spring-boot/issues/32781" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/32781/hovercard">#32781</a></li>  <li>Upgrade to Netty 4.1.84.Final <a href="https://github.com/spring-projects/spring-boot/issues/32700" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/32700/hovercard">#32700</a></li>  <li>Upgrade to Reactor 2020.0.24 <a href="https://github.com/spring-projects/spring-boot/issues/32592" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/32592/hovercard">#32592</a></li>  <li>Upgrade to Spring Data 2021.2.5 <a href="https://github.com/spring-projects/spring-boot/issues/32595" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/32595/hovercard">#32595</a></li>  <li>Upgrade to Spring Kafka 2.8.10 <a href="https://github.com/spring-projects/spring-boot/issues/32596" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/32596/hovercard">#32596</a></li>  <li>Upgrade to Spring Retry 1.3.4 <a href="https://github.com/spring-projects/spring-boot/issues/32594" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/32594/hovercard">#32594</a></li>  <li>Upgrade to Spring Security 5.7.4 <a href="https://github.com/spring-projects/spring-boot/issues/32597" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/32597/hovercard">#32597</a></li>  <li>Upgrade to Tomcat 9.0.68 <a href="https://github.com/spring-projects/spring-boot/issues/32667" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/32667/hovercard">#32667</a></li>  <li>Upgrade to Undertow 2.2.20.Final <a href="https://github.com/spring-projects/spring-boot/issues/32668" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/32668/hovercard">#32668</a></li> </ul> </details>

This PR is created by GitHub Actions: https://github.com/Azure/spring-cloud-azure-tools/actions/runs/3325294270

### CODE REVIEW

**Comment by Netyyyy** [comment]
Hi @alzimmermsft please help take a look and fix the java - core - ci [failed error](https://dev.azure.com/azure-sdk/public/_build/results?buildId=1951222&view=logs&j=c51d6cb2-95cd-5b4d-48e3-5062b75e6984&t=b62ccbdd-d117-5716-c02f-c3937fbd094d)

**Comment by alzimmermsft** [comment]
@conniey, @anuchandy, @srnagar - this is happening in AMQP Core, could you take a look what's happening? The only upgrades that would affect this are Reactor and Reactor Test

**Review by AikoBB — APPROVED** [review]

**Comment by Netyyyy** [comment]
> @conniey, @anuchandy, @srnagar - this is happening in AMQP Core, could you take a look what's happening? The only upgrades that would affect this are Reactor and Reactor Test

Hi @conniey , @anuchandy , @srnagar ,please help take a look, thanks!

**Comment by Netyyyy** [comment]
Close it for updating SpringBoot 2.7.6

**Pull request closed without merging**
