### PR TITLE
Correct getAsyncClient in Sample code

### PR DESCRIPTION
**Pull request by ragilr**
Added credential to the ConfigurationClientBuilder()

### CODE REVIEW

**Comment by conniey** [comment]
@ragilr The build appears to be failing because you may need to add the import for ConfigurationClientCredentials.

```java
[ERROR] /home/vsts/work/1/s/sdk/appconfiguration/azure-data-appconfiguration/src/samples/java/com/azure/data/appconfiguration/ConfigurationAsyncClientJavaDocCodeSnippets.java:[258,64] cannot find symbol
[ERROR]   symbol:   class ConfigurationClientCredentials
```

**Comment by ragilr** [comment]
Added the import still build failing

**Comment by ragilr** [comment]
@conniey can you let me what is failing in the build I'm unable to see the logs

**Comment by ragilr** [comment]
@conniey Could you please merge this?

**Comment by conniey** [comment]
@ragilr Thanks!

**Pull request merged**
