### PR TITLE
make Timer task run as a daemon thread

### PR DESCRIPTION
**Pull request by yiliuTo**
This pr is to fix a [bug](https://github.com/Azure/azure-sdk-for-java/issues/19978) of KeyVault Secret starter that refresh Timer task blocks application termination. Solution is to make Timer task run in a daemon thread.

### CODE REVIEW

**Comment by yiliuTo** [comment]
Change log will be updated after the release of 3.3.0 is done.

**Review by backwind1233 — APPROVED** [review]
LGTM

**Review by chenrujun — APPROVED** [review]

**Comment by stliu** [comment]
Actually I don't like this idea, is there a way to get rid of this Timer and replace it with `ScheduledThreadPoolExecutor` ? 
And make this more spring way? 

I can see this `KeyVaultOperation` is only used by `KeyVaultEnvironmentPostProcessor`, can this `KeyVaultEnvironmentPostProcessor` implements `DisposableBean` work?

**Pull request merged**
