### PR TITLE
noMarkingRegionUnavailableOnHttpTimeout

### PR DESCRIPTION
**Pull request by xinlian12**
**Issue:**
SDK currently will mark region unavailable on HttpTimeout for dataplane read, metadata read requests(expect address refresh)

**Changes:**
No marking region unavailable on httpTimeout exceptions

### CODE REVIEW

**Review by jeet1995 — APPROVED** [review]
LGTM - thanks!

**Review by FabianMeiswinkel — APPROVED** [review]
LGTM - Thanks!

**Pull request merged**
