### PR TITLE
mgmt update keyvault to 2021-10-01

### PR DESCRIPTION
**Pull request by XiaofeiCao**
# Description
link https://github.com/Azure/azure-sdk-for-java/issues/27617

Manual code on adding `purge` before `restore` to `KeyTests.canBackupAndRestore`. https://github.com/Azure/azure-sdk-for-java/pull/30337/commits/b47ce86275e7c2f1ac7bdc35623d07359e7e0fb3
Without the purge step, trying to restore key in the same keyvault will result in "conflict key name error" from server side. 
This happens for `old` api-version as well. Not sure if this test worked in the past.

live tests pass

Please add an informative description that covers that changes made by the pull request and link all relevant issues.

If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.

# All SDK Contribution checklist:
- [ ] **The pull request does not introduce [breaking changes]**
- [ ] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [ ] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Comment by weidongxu-microsoft** [comment]
We might need to locally remove `keys` and `secrets.json` from tag, as they are actually data-plane operation (that being duplicated in mgmt?).

The change on sample might be caused by behavior change, keyvault having different default behavior on soft-delete and purge in recent years.

**Comment by XiaofeiCao** [comment]
We don't have `KeysClient` and `SecretsClient` from old api-version. They are basic CRUD operations on these two resources and are duplicates of data-plane operations.

I'm quite confused, why do we have convenience methods in mgmt plane for data-plane operations?

**Comment by weidongxu-microsoft** [comment]
@XiaofeiCao So we probably continue to avoid `KeysClient` and `SecretClient`.

1. Reason is similar to MSGraph, it was supported in track1 years ago, and we migrate to track2 with backward compatibility.
2. The 2 json was not there at track2 migration (if they were they, we might actually use them instead of the data-plane client).

**Review by weidongxu-microsoft — APPROVED** [review]
You might need check playback after network upgrade.

**Comment by XiaofeiCao** [comment]
Seems ok by ci, will merge.

**Pull request merged**
