### PR TITLE
Upgrade spring boot to 2.5.2

### PR DESCRIPTION
**Pull request by chenrujun**
Upgrade spring boot to 2.5.2

### CODE REVIEW

**Comment by chenrujun** [comment]
Hi, @alzimmermsft, could you please help to fix the pipeline failure?
https://dev.azure.com/azure-sdk/public/_build/results?buildId=980920&view=logs&j=3facec84-71ec-57ab-8937-e7da3fbb0ee2&t=37d9083c-54a5-5aa6-1534-0a9b04411157&l=1305

**Comment by chenrujun** [comment]
Hi, @vcolin7 , FYI. 
I'll ignore the test failure of [java - keyvault - tests](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=980947&view=logs&j=dfd73531-a258-5256-cbbe-7a59f8d7ad3f&s=22f14647-22b2-5859-ead3-8d3994ffe155).

**Comment by yiliuTo** [comment]
Need we make sure cosmos tests passed as well?

**Review by yiliuTo — APPROVED** [review]
LGTM

**Pull request merged**
