### PR TITLE
Update Track 2 GH docs to reflect GA for Mgmt SDK

### PR DESCRIPTION
**Pull request by nickzhums**

### CODE REVIEW

**Review by weidongxu-microsoft — APPROVED** [review]

**Comment by sima-zhu** [comment]
Hi @nickzhums @weidongxu-microsoft We recently updated the github IO documentation [page](https://azure.github.io/azure-sdk-for-java/). We read and categorize the artifacts and its service name based on the central [csv file](https://github.com/Azure/azure-sdk/blob/master/_data/releases/latest/java-packages.csv). 

Especially, the resource manager packages are now distributed into different service page. E.g. azure-resourcemanager-storage is now under Storage [page](https://azure.github.io/azure-sdk-for-java/storage.html#azure-resourcemanager-storage). Also, the resource manager page renames to https://azure.github.io/azure-sdk-for-java/resources.html.

If you feel this is not the right listing as you expect, could you please file us an issue, or submit a change to [csv file](https://github.com/Azure/azure-sdk/blob/master/_data/releases/latest/java-packages.csv)?

FYI, I have a PR to fix the broken link introduced by this change. https://github.com/Azure/azure-sdk-for-java/pull/17067

@weshaggard Please suggest if you have any better approaches.

**Comment by nickzhums** [comment]
@sima-zhu Hi Sima, we took a look at the current structure, and found some packages are under each service while some end up in "Others". This is kinda inconsistent and since management SDK customers usually use a couple different services together, we would like to create a "Resource Management" category and put all packages there, we will submit an issue or PR , thanks

**Pull request merged**
