### PR TITLE
Add AADDatabindModule

### PR DESCRIPTION
**Pull request by chenrujun**
Add AADDatabindModule

### CODE REVIEW

**Comment by chenrujun** [comment]
Hi, @yiliuTo , please help to review this PR. 🙏

**Comment by chenrujun** [comment]
Hi, @yiliuTo , FYI;:

The pipeline failure is not caused by my commit. And after merge to master branch, the failure will not exist any more.
So I decide to ignore the failure.

**Review by yiliuTo — APPROVED** [review]
LGTM

**Pull request merged**
