### PR TITLE
Fix bug: not get certificates from key vault when refreshInterval is not set.

### PR DESCRIPTION
**Pull request by chenrujun**
1. Fix bug: not get certificates from key vault when refreshInterval is not set.
2. Prepare for a out-of-band release.

### CODE REVIEW

**Comment by chenrujun** [comment]
Hi, @yiliuTo ,  @lzc-199708 , please help to review this PR.

**Comment by chenrujun** [comment]
the `java - spring - tests` failure is caused by [azure-spring-cloud-sample-eventhubs-binder](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=973569&view=logs&j=6ddc3820-470e-5638-11a6-c1adaee6c311&t=bc3ee25f-f9c3-51f8-9377-b7a5795518e8&l=4000)

**Comment by chenrujun** [comment]
Now I merged latest main branch to my branch. And won't run `java - spring - tests` again. Because there is no problem in last execution.

**Review by yiliuTo — APPROVED** [review]
LGTM

**Pull request merged**
