### PR TITLE
Move core/ under sdk/

### PR DESCRIPTION
**Pull request by mitchdenny**
This change is the first of a set of restructuring changes. This one is a bit of a canary to feel out any issues that crop up with the relocation of the folder. I've updated the ```pom.xml``` file in the ```sdk/core/``` folder as well as the module reference in the root.

### CODE REVIEW

**Comment by mitchdenny** [comment]
@JonathanGiles and @weshaggard this is the first move of a library under the sdk folder. It appears to be building fine and is ready to merge pending your feedback. I was planning to move a bunch of libraries at a time based on where folks are working in the code base right now to try and reduce any merge/rebase pain but wanted to start with core first.

**Comment by JonathanGiles** [comment]
Should this wait until https://github.com/Azure/azure-sdk-for-java/pull/3829 and https://github.com/Azure/azure-sdk-for-java/pull/3824 are merged?

**Comment by weshaggard** [comment]
Yes @mitchdenny please be sure to include the owners of the libraries you are moving to ensure we correctly coordinate the efforts as well.

**Comment by mitchdenny** [comment]
How far out are those PRs from merging? I'm happy to pick another library and get going with that and then when those PRs merge I can rebase. Or we could do it the other way around - rebase is supposed to be able to handle renames if you give it a few extra hints.

But it could all go horribly wrong too :)

https://tenor.com/xSVX.gif

**Comment by JonathanGiles** [comment]
I don't expect the PRs will be far out - next week some time.

**Comment by mitchdenny** [comment]
OK - I might just pick another part of the code base, is there a set of data-plane libraries that are relatively quiet right now?

**Comment by JonathanGiles** [comment]
Pretty much all of track 1 data-plane directories are not being worked on by anyone.

**Pull request closed without merging**
