### PR TITLE
move client.yml to /eng/pipelines

### PR DESCRIPTION
**Pull request by danieljurek**
client.yml belongs under /eng/pipelines, like the other repositories. 

After this merges we'll need to: 
* Update internal client build location 

A search through the files in the repo turned up no mentions of `client.yml` so that should be the only dependency-related change we'll need to make. 

@Azure/azure-sdk-eng 

cc: @bsiegel -- FYI You last touched this file... I'm moving it in the event you need to edit it again.

### CODE REVIEW

**Comment by mikeharder** [comment]
@danieljurek: I believe this YAML is deprecated and can just be deleted now.

**Comment by mitchdenny** [comment]
Assuming you'll repoint the pipeline definitions :)

**Comment by danieljurek** [comment]
@mitchdenny indeed, I see that `azure-sdk-for-java - client` also depends on this file location 👍

**Pull request merged**
