### PR TITLE
Enable test coverage for OpenAI

### PR DESCRIPTION
**Pull request by srnagar**

### CODE REVIEW

**Review by brandom-msft — APPROVED** [review]

**Review by mssfang — APPROVED** [review]

**Comment by srnagar** [comment]
CI pipeline now shows the [coverage report](https://dev.azure.com/azure-sdk/public/_build/results?buildId=3051307&view=codecoverage-tab)

**Comment by srnagar** [comment]
Ran the [OpenAI pipeline manually](https://dev.azure.com/azure-sdk/public/_build/results?buildId=3051307&view=results) for this PR as this is a pom.xml only change.

**Pull request merged**
