### PR TITLE
Cosmos: Adding databricks CI integration

### PR DESCRIPTION
**Pull request by ealsur**
This PR adds the required files to trigger a Databricks run that will:

* Build the current Spark Connector
* Authenticate to a Databricks cluster
* Uninstall any libraries previously installed and restart the cluster. Wait until the cluster is ready.
* Install the last built library and restart the cluster. Wait until the cluster is ready.
* Clean any Notebooks installed in the workspace previously.
* Install any Notebook that exists in the `sdk/cosmos/azure-cosmos-spark_3-1_2-12/databricks/notebooks/` folder.
* For each Notebook, trigger the execution and capture the job results. If the execution succeeded, the job is deleted to avoid pollution. If the execution failed, the job is maintained so the logs can be checked.

### CODE REVIEW

**Review by moderakh — COMMENTED** [review]
couple of questions

1) I don't see any change in the build CI yaml file.  Are we using a different approach for the CIs? why aren't we using the build CI yaml files?
2) what is the execution flow? who/what triggers the CI? 
3) does this run on every PR? or manually triggered?

**Comment by ealsur** [comment]
1. Initial files are leveraging a private pipeline, not yaml. I could add the yaml to the PR, but we need help from the Azure SDK team to set it up.
2. Currently it is completely manual, Databricks requires cluster restarts and other orchestration that cannot run in parallel in multiple PRs, so we would need to trigger it
3. Manual on any branch (including PRs)

**Review by moderakh — APPROVED** [review]
LGTM. Thanks Matias.

**Comment by moderakh** [comment]
@ealsur can we change the CI name? "azure-cosmos-java-databricks". There is nothing really related to java here.
perhpaps "oltp-spark-databricks" would be better name.

**Pull request merged**
