### PR TITLE
Adding storage test keys to credscan suppression

### PR DESCRIPTION
**Pull request by JonathanGiles**
Proposed PR that will add all storage test keys to credscan suppression list. Pending review and approval by storage and engsys teams (@kasobol-msft and @rickle-msft are on point to review these keys).

### CODE REVIEW

**Review by srnagar — APPROVED** [review]

**Review by kasobol-msft — APPROVED** [review]

**Review by weshaggard — CHANGES_REQUESTED** [review]
We generally do not want to add entire recording files to the suppression list as that adds the risk of leaking secrets in these recording files, which is our highest risk. Instead we should be trying to eliminating these things that look like secrets from the recordings by using placeholders redacted values.

**Comment by YijunXieMS** [comment]
> We generally do not want to add entire recording files to the suppression list as that adds the risk of leaking secrets in these recording files, which is our highest risk. Instead we should be trying to eliminating these things that look like secrets from the recordings by using placeholders redacted values.

To pass the build without warnings/errors, we can tentatively baseline these CredScan errors. From the long run, we better do what Wes said above instead of suppressing them. We may keep adding new file names into the suppression list if Storage SDK or other SDKs have new playback files from time to time. This is what we don't want to happen.

**Comment by JonathanGiles** [comment]
I'm unclear if this PR should be merged temporarily or not?

**Comment by weshaggard** [comment]
>I'm unclear if this PR should be merged temporarily or not?

No we should avoid merging this in its current state. We should try to tackle it using the strategies @alzimmermsft outlined in email.

**Pull request closed without merging**
