### PR TITLE
Storage code migration

### PR DESCRIPTION
**Pull request by g2vinay**
Includes source code as it is from Storage Java SDK master branch with history preserved.
Code location is in storage/data-plane/   
In this PR, Storage SDK source code is migrated without any changes.
SDK component is not configured in the build.
No code changes on our end are included in this PR.

Follow up PR will include:
Storage SDK build integration to the central java repo.
Live tests Integration to our Azure Dev Ops pipeline.
Code + Pom cleanup

### CODE REVIEW

**Comment by amishra-dev** [comment]
@rickle-msft please look at this PR when you are back, we want to make sure that everything we have in our repo moved over here successfully.

@g2vinay please wait for Rick to approve before merging

**Comment by scbedd** [comment]
@g2vinay Hey mate make sure to hit me up when this merges. I'll need to get the ball rolling on documentation once that happens.

Do you also plan to migrate the preview branches? (if any?)

**Comment by weshaggard** [comment]
>

**Comment by weshaggard** [comment]
>SDK component is not configured in the build.
No code changes on our end are included in this PR.

Is there any reason we don't go ahead and make those changes as part of this PR as well? There seems like there is a lot of unnecessary files and stuff coming in that we could eliminate completely if we just cleaned them up at the same time. Also as I mentioned in another similar PR we have analysis tools like component governance that will start flagging stuff even if this isn't part of the build.

**Pull request merged**
