### PR TITLE
Address Cosmos issues after POM restructure

### PR DESCRIPTION
**Pull request by mitchdenny**
Because Cosmos is quite different in the way it builds the POM restructure didn't work out so well so there will be more changes required to make it behave correctly. This PR is being used to try out a few things to see if we can make it work.

### CODE REVIEW

**Comment by mitchdenny** [comment]
@kushagraThapar and @alzimmermsft this should fix up the Cosmos issues after POM restructuring

**Comment by kushagraThapar** [comment]
Thanks @mitchdenny  - I have started the live test CI to test at least one of them.

**Comment by kushagraThapar** [comment]
@mitchdenny  - Looks good from Cosmos live test point.

**Pull request merged**
