### PR TITLE
Add aad obo integration test case

### PR DESCRIPTION
**Pull request by moarychan**
Add aad obo integration testcase `azure-spring-boot-test-aad-obo` module, public `azure-spring-boot-test-aad` resource.
`

### CODE REVIEW

**Review by saragluna — APPROVED** [review]
LGTM.

**Comment by saragluna** [comment]
I'm going to merge this PR because the error seems unrelated to the obo integration test.  

@chenrujun please take a look at this test error: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=665037&view=logs&j=364de821-210b-596e-0928-4e0d2b619091&t=4057129a-b461-5555-fc9f-95b5eaf73fb2&l=257.

**Comment by chenrujun** [comment]
@saragluna . 
Got it. I already let JackLu to fix it.

**Pull request merged**
