### PR TITLE
Update configuration-reference.md

### PR DESCRIPTION
**Pull request by SnehaGunda**
This configuration file is referenced in public docs: https://docs.microsoft.com/en-us/azure/cosmos-db/create-sql-api-spark#generic-configuration

* Adding "preserve-view=true" tag in the URL to resolve docs build issue.
* Submitted a fix for the table row that has an extra entry at the end. It also resulted in a docs build error.

### CODE REVIEW

**Review by kushagraThapar — APPROVED** [review]
LGTM. 

@moderakh  - can you please take a look at this PR ?

**Review by moderakh — CHANGES_REQUESTED** [review]
@SnehaGunda this file has changed on master. could you merge master to your branch and resolve the conflicts.

**Comment by SnehaGunda** [comment]
@moderakh Thank you, I resolved the conflicts.

**Review by moderakh — APPROVED** [review]
LGTM. thanks @SnehaGunda

**Pull request merged**
