### PR TITLE
Respect org.springframework.data.domain.Persistable

### PR DESCRIPTION
**Pull request by Blackbaud-MikeLueders**
If an entity implements Persistable, the entity's isNew should be invoked to determine newness rather than using org.springframework.data.repository.core.support.AbstractEntityInformation#isNew.  Otherwise, the update function will be used and instead of getting a 409 on duplicate document, cosmos will respond with a 412.

### CODE REVIEW

**Comment by Blackbaud-MikeLueders** [comment]
It looks like the build failed due to a maven central read timeout but didn't see an option for re-triggering the build, guessing i don't have exceptions.

**Review by kushagraThapar — APPROVED** [review]
LGTM

**Comment by kushagraThapar** [comment]
Thanks for the contribution @Blackbaud-MikeLueders , I will figure out the CI issues. 
Also, do you think this github issue is related to `PersistableEntity` - https://github.com/Azure/azure-sdk-for-java/issues/19181 ?

**Comment by Blackbaud-MikeLueders** [comment]
hmm, i don't think so, PersistableEntity is a class defined by the poster; org.springframework.data.mapping.PersistentEntity is a thing in spring-data but is distinct from org.springframework.data.domain.Persistable.  i did notice one thing off about their configuration, i'll post in the other pr

**Pull request merged**
