### PR TITLE
Merge master into feature/tokenrefreshoptions

### PR DESCRIPTION
**Pull request by jianghaolu**

### CODE REVIEW

**Comment by weshaggard** [comment]
@jianghaolu did you happen to do a squash merge on this change? If so that might make for an interesting merge into master once this feature branch gets merged back. For merges like this I recommend merging from the command line once the PR validation is done, see https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/16/FAQ?anchor=i-have-a-special-case-where-i-do-not-want-to-squash-and-merge-a-pr.--what-should-i-do%3F.

**Comment by jianghaolu** [comment]
Good point @weshaggard. Unfortunately neither merge commit nor rebase merge is enabled on the repo. So yeah, we will have to merge from master outside pull requests. But that may not work sometimes especially when a pull request has merge conflicts.

**Comment by weshaggard** [comment]
You should still do the merge and handle the conflicts and submit a PR for validation but then do the PR merging from the command line.

**Pull request merged**
