### PR TITLE
Add checkstyle rule to check usage of String literals is on the left side of an equals() comparison

### PR DESCRIPTION
**Pull request by samvaity**
Calling the equals() method on String literals will avoid a potential NullPointerException. Also, it is pretty common to see null checks right before equals comparisons but following this rule, such checks are not required.

### CODE REVIEW

**Comment by samvaity** [comment]
@alzimmermsft, @srnagar Thoughts on adding these checkstyle rules?

**Review by alzimmermsft — APPROVED** [review]
Looks good to me! I didn't check if any of these classes were code generated, it'll be good to check if there are any if we need to update codegen.

**Review by JonathanGiles — APPROVED** [review]

**Review by weidongxu-microsoft — APPROVED** [review]

**Comment by weidongxu-microsoft** [comment]
In my memory codegen does not output code of this pattern. And agree `Objects.equals` is likely the easier pattern when dev does not know whether some variable will be `null`.

PS: codegen also has a checkstyle (though it only targets mgmt output) but need to be updated from time to time to track the one from main SDK repo.
https://github.com/Azure/autorest.java/blob/main/fluent-tests/checkstyle.xml

**Pull request merged**
