### PR TITLE
Update Spring security to 5.6.0 to fix WS-2016-7107

### PR DESCRIPTION
**Pull request by backwind1233**
[WS-2016-7107](https://www.whitesourcesoftware.com/vulnerability-database/WS-2016-7107)
> CSRF tokens in Spring Security are vulnerable to a breach attack. Spring Security always returns the same CSRF token to the browser.

Location:
image

### CODE REVIEW

**Review by chenrujun — APPROVED** [review]
LGTM.

**Comment by stliu** [comment]
I think this should be port to our 4.0 branch as well?

**Comment by backwind1233** [comment]
> I think this should be port to our 4.0 branch as well?

@stliu The main branch will be merged into 4.0 branch in one day or two, it will cover this I think.

**Pull request merged**
