### PR TITLE
Update AADAppRoleStatelessAuthenticationFilter and AADAuthenticationFilter Javadoc

### PR DESCRIPTION
**Pull request by ZhuXiaoBing-cn**
Update AADAppRoleStatelessAuthenticationFilter and AADAuthenticationFilter Javadoc.

### CODE REVIEW

**Review by saragluna — APPROVED** [review]
LGTM.

**Comment by chenrujun** [comment]
Hi, @ZhuXiaoBing-cn , it's better to left a comment to explain why you closed the PR.

**Comment by ZhuXiaoBing-cn** [comment]
@chenrujun I'm sorry, It was closed because I deleted the branch by mistake. It has been reopened, please help review and merge it.

**Review by chenrujun — APPROVED** [review]
LGTM.

**Pull request merged**
