### PR TITLE
Release/azure communication common/1.0.8

### PR DESCRIPTION
**Pull request by AikoBB**
# Description

Patch release for the azure-communication-common package

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [x] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Review by petrsvihlik — COMMENTED** [review]
Should this PR touch these files from other SDKs?

- sdk/securityinsights/pom.xml
- sdk/resourcemanager/pom.xml
- sdk/oep/pom.xml

**Review by weidongxu-microsoft — APPROVED** [review]
OK for me on
```
•	sdk/securityinsights/pom.xml
•	sdk/oep/pom.xml
•	sdk/resourcemanager/pom.xml
```

Likely cause for first 2 is the time difference of PR/CI pass, and the change to jacoco-maven-plugin version.

Not sure about the 3rd, as we didn't change that pom. But OK for me.

**Comment by AikoBB** [comment]
> 

@petrsvihlik I guess the script checks and updates the version of plugins/libraries defined in eng/versioning/external_dependencies.txt, so that is how they got updated. I do not think it will break anything, but I can revert it if you think we should do

**Comment by petrsvihlik** [comment]
if it's done by the script, I'd keep it then

**Review by petrsvihlik — APPROVED** [review]

**Pull request merged**
