### PR TITLE
Delete readme and changelog in azure-spring-boot-starters

### LINKED ISSUE #23926: Delete README and CHANGELOG in azure-spring-boot-starter-xxx
Parent issue: https://github.com/Azure/azure-sdk-for-java/issues/23925

Related doc: https://github.com/Azure/azure-sdk-for-java/wiki/Spring-Cloud-Azure-design#33-developing-guide-of-spring-cloud-azure-starter-xxx

### PR DESCRIPTION
**Pull request by chenrujun**
Resolve #23926

### CODE REVIEW

**Comment by saragluna** [comment]
Why are we deleting them?

**Comment by chenrujun** [comment]
@saragluna 

> Why are we deleting them?

Discussed with @stliu , starter module should only contain a pom, not just like spring-cloud-aws and spring-cloud-gcp did.

**Comment by stliu** [comment]
what there content from readme will be hosted after this removal?

**Comment by chenrujun** [comment]
@stliu 

> where these content from readme will be hosted after this removal?

I created an issue: https://github.com/Azure/azure-sdk-for-java/issues/23938

**Review by stliu — APPROVED** [review]

**Pull request merged**
