### PR TITLE
fixed noncompliant test code on IncrementalChangeFeedProcessorTest.java

### PR DESCRIPTION
**Pull request by abbytec**
# Description

fixed noncompliant test code
https://rules.sonarsource.com/java/tag/assertj/RSPEC-5833

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [ ] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [x] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Comment by kushagraThapar** [comment]
@abbytec not sure if this is a compliant issue on our end, since our spot bugs and check style analysis haven't caught it. I am curious to know why is this an issue for you?

**Comment by abbytec** [comment]
> @abbytec not sure if this is a compliant issue on our end, since our spot bugs and check style analysis haven't caught it. I am curious to know why is this an issue for you?

Following the [assertj documentation](https://assertj.github.io/doc/#calling-as-after-the-assertion)
Describing an assertion must be done before calling the assertion otherwise it is ignored as a failing assertion breaks will prevent the call to as().

**Review by FabianMeiswinkel — APPROVED** [review]
LGTM

**Review by kushagraThapar — APPROVED** [review]
Thanks for the fix @abbytec , appreciate your contribution!

**Pull request merged**
