### PR TITLE
Support for streaming created resources

### PR DESCRIPTION
**Pull request by anuchandy**
Today the Observable from  `createAsync` emits only the root resource not any of the dependent resources that gets created.

An overload for the `createAsync` with following signature has been added to address this

```java
    /**
     * Puts the request into the queue and allow the HTTP client to execute
     * it when system resources are available.
     *
     * @param enableStreaming true if the resources needs to be emitted in the order
     *                        they gets created, false if only the root resource needs
     *                        be streamed
     * @return an observable where the resource and all it's dependencies gets emitted
     */
    Observable<Indexable> createAsync(boolean enableStreaming);
```

if enableStreaming is true then caller will receive the resources as they gets created otherwise only the root resource will be emitted. The an example usage is:

```java
        VirtualMachine virtualMachine = (VirtualMachine) virtualMachines.define(vmName)
                .withRegion(Region.US_EAST)
                .withNewResourceGroup(rgCreatable)
                .withNewPrimaryNetwork("10.0.0.0/28")
                .withPrimaryPrivateIpAddressDynamic()
                .withNewPrimaryPublicIpAddress(ResourceNamer.randomResourceName("pip", 20))
                .withPopularWindowsImage(KnownWindowsVirtualMachineImage.WINDOWS_SERVER_2012_R2_DATACENTER)
                .withAdminUsername("testuser")
                .withAdminPassword("12NewPA$$w0rd!")
                .withSize(VirtualMachineSizeTypes.STANDARD_D1_V2)
                .withNewStorageAccount(storageCreatable)
                .withNewAvailabilitySet(ResourceNamer.randomResourceName("avset", 10))
                .createAsync(true)
                .map(new Func1<Indexable, Resource>() {
                    @Override
                    public Resource call(Indexable resource) {
                        Resource createdResource = (Resource) resource;
                        System.out.println("Created :" + createdResource.id());
                        return createdResource;
                    }
                }).toBlocking().last();
```

Why not streaming as `Resource`: There are couple of types those are creatable but not Resource, the same applicable with `HasId` as well

some resources that belongs to this category are:

azure-mgmt-graph-rbac/src/main/java/com/microsoft/azure/management/graphrbac/User.java
azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/Deployment.java

### CODE REVIEW

**Comment by martinsawicki** [comment]
considering that this approach really exposes the power and value of observables, why not use this as the the default way i.e. `createAsync()`,  and only have the overload exposed to expose the previous behavior  -- using `createAsync(false)`?

**Comment by jianghaolu** [comment]
@martinsawicki 
Sounds like making entry users' life harder - as an entry user, after calling `Creatable<VM>.createAsync()` I expect to get one item of type `VM` back.

**Comment by martinsawicki** [comment]
entry user uses create() not createAsync() ;-)

**Comment by anuchandy** [comment]
If `Creatable<VirtualMachine>.createAsync(false)` returns the root resource (VirtualMachine) then what should be the behavior of `Creatable<VirtualMachine>.createAsync(true)`? Do we honor the boolean flag? If we want to honor it then how do we stream all resources?

We cannot return `Observable<Indexable>` when the declared return type is `Observable<VirtualMachine>`, right?

**Comment by martinsawicki** [comment]
starting to feel like a different method, not overload with a  param.
createAsyncStreaming?

**Comment by anuchandy** [comment]
`createAsyncStreaming` seems better

**Comment by anuchandy** [comment]
Closing this in favor of https://github.com/Azure/azure-sdk-for-java/pull/1300

**Pull request closed without merging**
