### PR TITLE
Update aggregate reports to publish bom report even when the build fails - v2

### PR DESCRIPTION
**Pull request by pallavit**

### CODE REVIEW

**Comment by JonathanGiles** [comment]
Paging @srnagar who is doing some work on improving aggregate reports.

**Comment by pallavit** [comment]
/cc: @srnagar,  what improvements are you considering for aggregate-reports. Does this change any of those plans?

**Comment by srnagar** [comment]
@pallavit I am looking into generating aggregate javadocs and aggregate test coverage reports.

**Comment by pallavit** [comment]
@srnagar Do you see any concern with this change?

**Pull request merged**
