### PR TITLE
Add reactor-bom and netty-bom in cosmos test.

### PR DESCRIPTION
**Pull request by chenrujun**
Add reactor-bom and netty-bom in cosmos test.

### CODE REVIEW

**Comment by mitchdenny** [comment]
Why are you referencing a BOM? We should be specifying our dependency versions explicitly for our libraries, at which point the BOM doesn't add much value?

**Comment by chenrujun** [comment]
@mitchdenny 

Sorry for make you confused.
It's just a demo PR, used to discuss this issue: https://github.com/Azure/azure-sdk-for-java/issues/17986

I changed the PR to `Draft` just now.

**Pull request closed without merging**
