### PR TITLE
[Communication] - All - Bugfix: Changed env variable names from json

### PR DESCRIPTION
**Pull request by jbeauregardb**

### CODE REVIEW

**Comment by sacheu** [comment]
so these varaible ADMINISTRATION_SERVICE_ACCESS_TOKEN,  ADMINISTRATION_SERVICE_ENDPOINT will no longer being used?

**Review by sacheu — APPROVED** [review]
LGTM

**Comment by jbeauregardb** [comment]
@sacheu Yes, all SDKs were using different names for the endpoint and access key. This was kind of cumbersome for anyone who wanted to get the tests up and running for the first time so I just made it easier for them :)

**Comment by sacheu** [comment]
> , all SDKs were using different names for the endpoint and access key. This was kind of cumbersome for anyone who wanted to get the tests up and running for the first time so I just made it easier for them :)

Are we going to  this change 'same name for all sdks for the endpoint and access key' in other languages SDK as well?

**Comment by jbeauregardb** [comment]
@sacheu This was an issue that was probably just something in the Java SDK. Will check on Python SDK as well to see if this is also an issue there

**Pull request merged**
