### PR TITLE
Fixing a bunch of RawType usages and minor improvments in simplying callback

### PR DESCRIPTION
**Pull request by anuchandy**

### CODE REVIEW

**Comment by anuchandy** [comment]
In this PR I tried to simplify the callback logic across the fluent models. We should be able to use observable/Rx and further simplify this in general but that's a big change [involves change in generated SDK as well].

**Comment by martinsawicki** [comment]
So am I inferring correctly that a new requirement for our model impls based on this is that `.apply()` implementations must return the interface not the impl?

**Comment by anuchandy** [comment]
@martinsawicki that's right. do you see any issue in returning interface instead of Impl?

**Comment by martinsawicki** [comment]
not off the top of my head. Just something to keep in mind as a pattern now.

**Comment by anuchandy** [comment]
@martinsawicki Ok, i am seeing some issue here.

Lets take StorageAccount as an example 

If we want to follow the pattern then the `createAsync` method should return `ServiceCall<StorageAccountImpl>` instead of `ServiceCall<StorageAccount>`. If we want to achieve this then the `Creatable` interface needs to be updated from:

```java
public interface Creatable<T> {
    ServiceCall<T> createAync();
}
```
to

```java
public interface Creatable<T> {
    ServiceCall<? extends T> createAync();
}
```

StorageAccount interface will looks like:

```java
public interface StorageAccount extends Creatable<StorageAccount> {
}
```
with this we should be able to write `StorageAccountImpl` as the way we want:

```java

public class StorageAccountImpl implements StorageAccount {
    public ServiceCall<StorageAccountImpl> createAync() {
        return null;
    }
}

```

We want user experience to be like below:

```java
    public static void main(String[] args) {
        StorageAccount storageAccount = ...
        ServiceCall<StorageAccount> serviceCall = storageAccount.createAync();
    }
```

This will not compile, we will get below error:

```
incompatible types: ServiceCall<capture#1 of ? extends StorageAccount> cannot be converted to ServiceCall<StorageAccount>
```

Then the user needs to do like:

```java
    public static void main(String[] args) {
        ....
        ServiceCall<? extends StorageAccount> serviceCall = storageAccount.createAync();
    }
```

This looks bad, right?

Here I used Creatable interface as an example but applicable for Applicable as well.

@martinsawicki @jianghaolu thoughts?

**Comment by jianghaolu** [comment]
I think the pattern in the impl file should just be
```java
FluentModelImplT create();
ServiceCall<FluentModelT> createAsync(ServiceCallback<FluentModelT> callback);
```
since
the implementation for `ServiceCall<FluentModelT>` isn't really `ServiceCall<FluentModelImplT>`.

**Comment by jianghaolu** [comment]
Merging this is blocking other PRs. We can discuss and address anything related in a separate PR.

**Pull request merged**
