### PR TITLE
Updating external dependencies

### PR DESCRIPTION
**Pull request by jairmyree**
### External Dependency Updates

- org.apache.avro:avro: 1.11.3 -> 1.11.4
- commons-io:commons-io: 2.11.0 -> 2.17.0

### CODE REVIEW

**Review by weidongxu-microsoft — APPROVED** [review]
LGTM for mgmt libs, as long as CI good.

**Comment by jairmyree** [comment]
**Batch SDK Owners**: @skapur12 @wiboris @dpwatrous @NickKouds 

Please review these dependency updates and reply with any issues you may have with these changes.

**Comment by jairmyree** [comment]
**Cosmos SDK Owners**: @kirankumarkolli @Azure/azure-cosmos-java-sdk-connectors 

Please review these dependency updates and reply with any issues you may have with these changes.

**Comment by jairmyree** [comment]
**Schema Registry SDK Owners**: @srnagar @conniey 

Please review these dependency updates and reply with any issues you may have with these changes.

**Review by srnagar — APPROVED** [review]

**Review by jeet1995 — APPROVED** [review]

**Pull request merged**
