### PR TITLE
quickstart script for LLC codegen

### PR DESCRIPTION
**Pull request by weidongxu-microsoft**
sample
> `python eng/mgmt/automation/generate_data.py --input-file=https://github.com/Azure/azure-rest-api-specs/blob/main/specification/purview/data-plane/Azure.Analytics.Purview.Account/preview/2019-11-01-preview/account.json --group=purview --module=azure-analytics-purview-account --credential-types=tokencredential --credential-scopes=https://purview.azure.net/.default`

Similar to [`generate.py`](https://github.com/Azure/azure-sdk-for-java/blob/1fc22962a75e8a5de443449c107acb0002393a61/eng/mgmt/automation/generate.py) for mgmt.
It might not be a good practice to put in `mgmt` folder, but let us just leave it for a while, to see how many code we are able to share (in future iterations).

### CODE REVIEW

**Comment by weidongxu-microsoft** [comment]
Documented here on how to use https://github.com/Azure/azure-sdk-for-java/wiki/Protocol-Methods-Quickstart-with-AutoRest

It needs next release of azure-core and autorest/java to fully work.

**Comment by weidongxu-microsoft** [comment]
Sample generated module from the script https://github.com/Azure/azure-sdk-for-java/pull/25233

**Comment by weshaggard** [comment]
>Similar to generate.py for mgmt.
It might not be a good practice to put in mgmt folder, but let us just leave it for a while, so see how many code we are able to share.

@weidongxu-microsoft is there a way to actually combine these into one configuration? We should share as much as possible between mgmt and data and if there is unique work we can split it but if possible in the end I'd like us to only have one swagger_to_sdk config and handle the split in the generate script as necessary.

**Comment by weidongxu-microsoft** [comment]
@weshaggard 

Agree that we should have single entry point from swagger_to_sdk config. That will be the `generate.py`. I will try find time later to let it handle data-plane as well (hence it might just all method in generate_data.py if it find it is data-plane swagger).

So far there is very little duplicate code in `generate_data.py`, and as a script for dev (instead of one invoked from swagger pipeline), it has different parameters to set. Therefore for this particular usage, we still wish to have a different script.

**Comment by weshaggard** [comment]
Thanks for the context and I'm fine with having wrapper scripts to make consumption easier for local devs. I just want to make sure we aren't duplicating more than we need to across the different scenarios.

**Review by haolingdong-msft — APPROVED** [review]

**Pull request merged**
