### PR TITLE
[Ready for review] Regenerated the Batch management apis as swagger is updated.

### PR DESCRIPTION
**Pull request by anudeepsharma**
This change is just generation with new swagger, plus resolved errors accordingly.

### CODE REVIEW

**Comment by anudeepsharma** [comment]
This is just generation with new swagger, plus resolved errors accordingly.

**Comment by anuchandy** [comment]
lgtm, can be merged once CI passes.

**Comment by martinsawicki** [comment]
CI fails with this: 

4161[ERROR] /home/travis/build/Azure/azure-sdk-for-java/azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/implementation/BatchAccountImpl.java:73:64: Name 'BatchAccountInner' must match pattern '^[a-z][a-zA-Z0-9]*$'. [ParameterName]

Huh?

**Comment by martinsawicki** [comment]
sounds like a *parameter* name starts with a capitalized letter instead of small?

**Pull request merged**
