### PR TITLE
Internal exceptions cause havoc for App Insights

### PR DESCRIPTION
**Pull request by DaveGodwin**
The problem is with the Azure **BlobServiceClient.createBlobContainerIfNotExists(String containerName)** library method.
•	This method returns an access object for the named container.  If the container does not exist then it will be created.
o	This is implemented using an internal call to the BlobContainerClient.createBlobContainer(String containerName) method.
o	This call then uses a lower-level web service call that attempts to create the container.  This call is implemented to accept only status code 201 (container created) as a valid response.  Any other status code causes an exception to be thrown.  
o	If the exception was thrown because of receiving code 409 (container exists) then the exception is squashed and the createBlobContainerIfNotExists() method returns normally.
o	Internally the exception is reported to App Insights as a hard error.  **This causes havoc for anyone using App Insights.**

My solution is to modify the existing Azure BlobServiceClient.createBlobContainerIfNotExists(String containerName) library method.
•	This method returns an access object for the named container.  If the container does not exist then it will be created.
o	This is implemented using a **new** lower-level web service call that attempts to create the container.  This call is implemented to accept status codes 201 and 409 as valid responses.  Any other status code causes an exception to be thrown.  
o	If either 201 or 409 was received then the createBlobContainerIfNotExists() method returns normally.

A similar problem exists for the **BlobServiceClient.deleteBlobContainerIfExists (String containerName)** library method.
A similar solution is provided.

Existing test cases cover these modifications.

### CODE REVIEW

**Comment by alzimmermsft** [comment]
Thanks for creating this PR @DaveGodwin! I think it's a really good idea to prevent these methods from throwing an exception when we know we're going to ignore it in some cases as we're making a specialized API call that doesn't match service REST behaviors. Unfortunately, this will need some additional work as the files that you've modified are generated code (denoted by a header comment like `// Code generated by Microsoft (R) AutoRest Code Generator.`) that will be wiped away when there is an update to the generated code.

@srnagar, @JonathanGiles, have we ever had design considerations for scenarios like this where we should skip logging the thrown exception within `RestProxyBase` as we're making a service client call that may handle the error response differently than the service REST API design?

**Comment by DaveGodwin** [comment]
Hello Alan,

Thank you for your reply.  Please let me know if you’d like me to do any upgrade work on your code generator.

I know that my company is not the only one to have had to do extra work in App Insights in order to ignore the bogus errors being thrown and quashed inside the Azure library.  Anyone using both the Azure Java library and App Insights will see the problem.  We’ve seen questions about this on various web sites with the complaints going back for years.

Regards,

Dave Godwin
Software Architect

INEIGHT
9977 N. 90th St., Ste. 250 | Scottsdale, AZ 85258

[A black and white logo  Description automatically generated]<ineight.com>

**Comment by DaveGodwin** [comment]
@microsoft-github-policy-service agree [company="InEight"]


Dave Godwin
Software Architect

INEIGHT
9977 N. 90th St., Ste. 250 | Scottsdale, AZ 85258

[A black and white logo  Description automatically generated]<ineight.com>

**Comment by DaveGodwin** [comment]
@microsoft-github-policy-service agree company="InEight"


Dave Godwin
Software Architect

INEIGHT
9977 N. 90th St., Ste. 250 | Scottsdale, AZ 85258

[A black and white logo  Description automatically generated]<ineight.com>

**Pull request closed without merging**
