### PR TITLE
fix flaky test caused by timing issue

### PR DESCRIPTION
**Pull request by ZejiaJiang**
# Description

The eventhub test triggered by core-ci is failed. It's a flaky test.

According to the other tests https://github.com/Azure/azure-sdk-for-java/blob/cf84f4b8930cfb87b1362df258c0095583718e19/sdk/servicebus/azure-messaging-servicebus/src/test/java/com/azure/messaging/servicebus/ServiceBusProcessorTest.java#L412-L414
I found that `processEvent` and `endSpan` have the timing issue in https://github.com/Azure/azure-sdk-for-java/blob/cf84f4b8930cfb87b1362df258c0095583718e19/sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/PartitionPumpManager.java#L275-L284

I take the same approach just like the other tests.

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [x] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Comment by ZejiaJiang** [comment]
https://github.com/Azure/azure-sdk-for-java/issues/26759

**Comment by ZejiaJiang** [comment]
@lmolkova

**Comment by haolingdong-msft** [comment]
LGTM.

**Review by weidongxu-microsoft — APPROVED** [review]

**Review by haolingdong-msft — APPROVED** [review]

**Comment by lmolkova** [comment]
@ZejiaJiang thanks you!

**Pull request merged**
