### PR TITLE
Communication Identity : Removing exclusion of Autorest code from coverage report

### PR DESCRIPTION
**Pull request by mjafferi-msft**
# Description
Removing exclusion of Autorest code from coverage report and adjusting minimum coverage criteria check as per [discussion](https://teams.microsoft.com/l/message/19:5e673e41085f4a7eaaf20823b85b2b53@thread.skype/1675076820954?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1675076820954&teamName=Azure%20SDK&channelName=Language%20-%20Java&createdTime=1675076820954)

Since, we don't have CTE enable in INT & PPE , I have lowered the coverage threshold to what it needs for build to pass.

Coverage :[ 66.42 % ](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2203262&view=results)

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [ ] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [ ] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Review by AikoBB — APPROVED** [review]
Can we note somewhere(maybe the best place could be [User Story 3005784](https://skype.visualstudio.com/SPOOL/_workitems/edit/3005784)) to increase the coverage numbers once we have cte tests included

**Comment by mjafferi-msft** [comment]
> Can we note somewhere(maybe the best place could be [User Story 3005784](https://skype.visualstudio.com/SPOOL/_workitems/edit/3005784)) to increase the coverage numbers once we have cte tests included
Done.

**Pull request merged**
