### PR TITLE
revert spring scope property and provide default client-registration

### PR DESCRIPTION
**Pull request by yiliuTo**
Remove scope property of `azure.activedirectory.scope` and support `spring.security.oauth2.client.registration.azure.scope` instead.

### CODE REVIEW

**Review by chenrujun — APPROVED** [review]
LGTM.

**Comment by saragluna** [comment]
Why are we adding back these properties?

**Comment by chenrujun** [comment]
@saragluna , 

Originally, we plan to use `azure.activedirectory.scopes` to replace `spring.security.oauth2.client.registration.azure.scope`.

New aad implementation will have configuration like :
```
azure:
  activedirectory:
    tenant-id: <tenant-id>
    client-id: <client-id>
    client-secret: <client-secret>
    authorization:
      graph:
        scopes:
          - "https://graph.microsoft.com/Calendars.Read"
      arm:
        on-demand: true
        scopes:
          - "https://management.core.windows.net/user_impersonation"
    user-group:
      value: "#microsoft.graph.group"
      allowed-groups: group1, group2
```

So `azure.activedirectory.scopes` will not be used any more.

To avoid introduce `azure.activedirectory.scopes` to users, we decide to use original `spring.security.oauth2.client.registration.azure.scope`.

**Pull request merged**
