### PR TITLE
Update the version of azure-identity-providers-* libraries to 1.0.0 

### PR DESCRIPTION
**Pull request by backwind1233**
The PR https://github.com/Azure/azure-sdk-for-java/pull/32100 has been merged to main branch,
and these changes should also be merged into feature/spring-boot-3 branch.

Checklist
- [ ] Remove all code changes which are not in folder sdk/spring.
- [ ] This PR is ready for review only when azure-identity-providers-* libraries are GA released.

### CODE REVIEW

**Comment by backwind1233** [comment]
@moarychan please help review this PR

**Comment by backwind1233** [comment]
It's better not to merge this PR until the 1.0.0 GA is released.

**Comment by saragluna** [comment]
Closing in favor of https://github.com/Azure/azure-sdk-for-java/pull/32433.

**Pull request closed without merging**
