### PR TITLE
Opened azure.cosmos.implementation package to afterburner module for usage of Client Side Request Statistics

### PR DESCRIPTION
**Pull request by kushagraThapar**
* Opened azure.cosmos.implementation package to afterburner module for usage of Client Side Request Statistics
* Closes https://github.com/Azure/azure-sdk-for-java/issues/19847

### CODE REVIEW

**Review by xinlian12 — APPROVED** [review]
LGTM, thanks

**Review by FabianMeiswinkel — APPROVED** [review]
Thanks

**Review by moderakh — APPROVED** [review]
awesome. Thanks a lot :-)

**Pull request merged**
