### PR TITLE
External dependencies upgrade - Spring Boot 2.7.13 and Spring Cloud 2021.0.7

### PR DESCRIPTION
**Pull request by Netyyyy**
Updates external dependencies to align with Spring Boot version [2.7.13](https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-dependencies/2.7.13/spring-boot-dependencies-2.7.13.pom) from [2.7.11](https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-dependencies/2.7.11/spring-boot-dependencies-2.7.11.pom) and Spring Cloud version [2021.0.7](https://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-dependencies/2021.0.7/spring-cloud-dependencies-2021.0.7.pom) from [2021.0.7](https://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-dependencies/2021.0.7/spring-cloud-dependencies-2021.0.7.pom).
<details><summary>Release notes</summary><p><em>Sourced from <a href='https://github.com/spring-projects/spring-boot/releases/tag/v2.7.13'>spring-boot releases</a>.</em></p><h4> <g-emoji class="g-emoji" alias="lady_beetle" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f41e.png">  🐞 </g-emoji> Bug Fixes</h4><ul> <li>Spring Boot properties migrator can create circular references <a href="https://github.com/spring-projects/spring-boot/issues/35919" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/35919/hovercard">#35919</a></li> <li>Devtools does not support package-private main classes <a href="https://github.com/spring-projects/spring-boot/issues/35858" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/35858/hovercard">#35858</a></li> <li>Java 20 is supported but there's no value for it in the JavaVersion enum <a href="https://github.com/spring-projects/spring-boot/issues/35758" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/35758/hovercard">#35758</a></li> <li>Processing of <code>@EndpointCloudFoundryExtension</code> logs a warnings as it does not use <code>@AliasFor</code> on its override of the endpoint attribute <a href="https://github.com/spring-projects/spring-boot/pull/35716" data-hovercard-type="pull_request" data-hovercard-url="/spring-projects/spring-boot/pull/35716/hovercard">#35716</a></li> <li>Actuator loggers list endpoint throws exception on Log4J2 loggers with custom log levels <a href="https://github.com/spring-projects/spring-boot/issues/35227" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/35227/hovercard">#35227</a></li> <li>Validation is not applied for ConfigurationProperties that implement Validator and use <code>@ConstructorBinding</code> <a href="https://github.com/spring-projects/spring-boot/issues/33669" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/33669/hovercard">#33669</a></li></ul><h4>📔 Documentation</h4><ul> <li>Description of spring.data.mongodb.uri property incorrectly states that it overrides spring.data.mongodb.database <a href="https://github.com/spring-projects/spring-boot/issues/35686" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/35686/hovercard">#35686</a></li> <li>Update description of spring-boot-starter-data-rest to clarify that it uses Spring MVC <a href="https://github.com/spring-projects/spring-boot/issues/35678" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/35678/hovercard">#35678</a></li> <li>Move property notes up to external configuration section <a href="https://github.com/spring-projects/spring-boot/pull/35662" data-hovercard-type="pull_request" data-hovercard-url="/spring-projects/spring-boot/pull/35662/hovercard">#35662</a></li> <li>Document audience support in OAuth2 resource server <a href="https://github.com/spring-projects/spring-boot/pull/35286" data-hovercard-type="pull_request" data-hovercard-url="/spring-projects/spring-boot/pull/35286/hovercard">#35286</a></li> <li>Add <code>@DynamicPropertySource</code> to documented list of property source ordering <a href="https://github.com/spring-projects/spring-boot/issues/32901" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/32901/hovercard">#32901</a></li></ul><h4> <g-emoji class="g-emoji" alias="hammer" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f528.png">  🔨 </g-emoji> Dependency Upgrades</h4><ul> <li>Upgrade to Dropwizard Metrics 4.2.19 <a href="https://github.com/spring-projects/spring-boot/issues/35794" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/35794/hovercard">#35794</a></li> <li>Upgrade to Hazelcast 5.1.7 <a href="https://github.com/spring-projects/spring-boot/issues/35987" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/35987/hovercard">#35987</a></li> <li>Upgrade to Infinispan 13.0.18.Final <a href="https://github.com/spring-projects/spring-boot/issues/35795" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/35795/hovercard">#35795</a></li> <li>Upgrade to Lombok 1.18.28 <a href="https://github.com/spring-projects/spring-boot/issues/35796" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/35796/hovercard">#35796</a></li> <li>Upgrade to Micrometer 1.9.12 <a href="https://github.com/spring-projects/spring-boot/issues/35725" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/35725/hovercard">#35725</a></li> <li>Upgrade to Netty 4.1.94.Final <a href="https://github.com/spring-projects/spring-boot/issues/35988" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/35988/hovercard">#35988</a></li> <li>Upgrade to Reactor Bom 2020.0.33 <a href="https://github.com/spring-projects/spring-boot/issues/35726" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/35726/hovercard">#35726</a></li> <li>Upgrade to Spring AMQP 2.4.13 <a href="https://github.com/spring-projects/spring-boot/issues/35727" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/35727/hovercard">#35727</a></li> <li>Upgrade to Spring Data Bom 2021.2.13 <a href="https://github.com/spring-projects/spring-boot/issues/35728" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/35728/hovercard">#35728</a></li> <li>Upgrade to Spring Framework 5.3.28 <a href="https://github.com/spring-projects/spring-boot/issues/35729" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/35729/hovercard">#35729</a></li> <li>Upgrade to Spring Security 5.7.9 <a href="https://github.com/spring-projects/spring-boot/issues/35730" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/35730/hovercard">#35730</a></li> <li>Upgrade to Spring Session Bom 2021.2.2 <a href="https://github.com/spring-projects/spring-boot/issues/35731" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/35731/hovercard">#35731</a></li> <li>Upgrade to Tomcat 9.0.76 <a href="https://github.com/spring-projects/spring-boot/issues/35799" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/35799/hovercard">#35799</a></li> <li>Upgrade to UnboundID LDAPSDK 6.0.9 <a href="https://github.com/spring-projects/spring-boot/issues/35800" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/35800/hovercard">#35800</a></li> <li>Upgrade to Undertow 2.2.25.Final <a href="https://github.com/spring-projects/spring-boot/issues/35801" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/35801/hovercard">#35801</a></li></ul><h4>❤️ Contributors</h4><p>Thank you to all the contributors who worked on this release:</p><p><a class="user-mention notranslate" data-hovercard-type="user" data-hovercard-url="/users/bbulgarelli/hovercard" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="https://github.com/bbulgarelli">@bbulgarelli</a>, <a class="user-mention notranslate" data-hovercard-type="user" data-hovercard-url="/users/bikash30851/hovercard" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="https://github.com/bikash30851">@bikash30851</a>, and <a class="user-mention notranslate" data-hovercard-type="user" data-hovercard-url="/users/twobiers/hovercard" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="https://github.com/twobiers">@twobiers</a></p></details>

This PR is created by GitHub Actions: https://github.com/Azure/spring-cloud-azure-tools/actions/runs/5439312045

### CODE REVIEW

**Comment by Netyyyy** [comment]
@alzimmermsft please help take a look, thanks!

**Comment by weidongxu-microsoft** [comment]
Please run `/azp run java - resourcemanager` after resolve conflict.

If it pass, I can approve for mgmt-plane.

**Review by weidongxu-microsoft — APPROVED** [review]
LGTM for mgmt.

Please still wait for confirmation on core and data-plane.

**Review by alzimmermsft — APPROVED** [review]

**Pull request merged**
