### PR TITLE
Updated versions for hotfix release

### PR DESCRIPTION
**Pull request by gapra-msft**

### CODE REVIEW

**Review by alzimmermsft — APPROVED** [review]

**Review by kasobol-msft — APPROVED** [review]

**Comment by gapra-msft** [comment]
Weekly test here https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1012103&view=results

**Comment by gapra-msft** [comment]
Both pipelines are passing but it seems like the UI here isnt updating
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1012142&view=results
https://dev.azure.com/azure-sdk/public/_build/results?buildId=1012156&view=logs&jobId=6b6453ff-b717-53e4-9b68-8cedd66e23e4

Going to override check enforcer

**Pull request merged**
