### PR TITLE
Move track2 Fluent mgmt SDK

### PR DESCRIPTION
**Pull request by weidongxu-microsoft**
For https://github.com/Azure/azure-sdk-for-java/issues/9451

New folders:

sdk/appservice/mgmt
sdk/authorization/mgmt
sdk/compute/mgmt
sdk/containerregistry/mgmt
sdk/containerservice/mgmt
sdk/cosmos/mgmt
sdk/dns/mgmt
sdk/keyvault/mgmt
sdk/managedserviceidentity/mgmt
sdk/monitor/mgmt
sdk/network/mgmt
sdk/resources/mgmt
sdk/sql/mgmt
sdk/storage/mgmt
sdk/management

### CODE REVIEW

**Comment by weidongxu-microsoft** [comment]
@yungezz @ChenTanyi @xccc-msft

**Comment by weidongxu-microsoft** [comment]
`managedserviceidentity` is a new folder for [msi](https://github.com/Azure/azure-rest-api-specs/tree/master/specification/msi/resource-manager). I used the folder name from [azure-sdk-for-net](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/managedserviceidentity/Microsoft.Azure.Management.ManagedServiceIdentity).

**Comment by yungezz** [comment]
> `managedserviceidentity` is a new folder for [msi](https://github.com/Azure/azure-rest-api-specs/tree/master/specification/msi/resource-manager). I adopt the folder name from [azure-sdk-for-net](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/managedserviceidentity/Microsoft.Azure.Management.ManagedServiceIdentity).

just confirmed, MSI should be supported inside each service right?

**Comment by yungezz** [comment]
this one has to be forced merged right?  we'll need rerun CI against mgmt CI pipeline when ready. @ChenTanyi

**Comment by weidongxu-microsoft** [comment]
@yungezz 

The support for identity is in services, this `msi` is for create/list/delete identity. @xccc-msft for detail.

**Comment by xccc-msft** [comment]
> > `managedserviceidentity` is a new folder for [msi](https://github.com/Azure/azure-rest-api-specs/tree/master/specification/msi/resource-manager). I adopt the folder name from [azure-sdk-for-net](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/managedserviceidentity/Microsoft.Azure.Management.ManagedServiceIdentity).
> 
> just confirmed, MSI should be supported inside each service right?

@yungezz Not all services use MSI. For current track 2 services, we can find MSI gets used by some of them like AppService, Network, Compute by method `withIdenetity(identity)` to specify an identity to be associated with certain resource from the providers.

**Comment by weidongxu-microsoft** [comment]
@mitchdenny @anuchandy 
Let me know if you have comment on this. If OK I will merge it tomorrow.

**Comment by mitchdenny** [comment]
I'm fine for this to merge in as is given that all the code is in the mgmt sub-folder under each service directory. Provided it is building locally for developers that will mean that they can start working on of the repo. After that I think that there is going to be a non-trivial amount of work conforming this to the the engineering system (which is also a moving target).

For example I can see that there are a few new parent POMs being introduced. I'm doing work at the moment to move our parent POMs (```azure-client-sdk-parent```, ```azure-data-sdk-parent```, and ```azure-sdk-parent```) into the ```sdk/parents``` folder. At the moment you've got a new parent going into ```sdk/management``` which I'm not sure is where we want it in the future.

My experience tells me that its best to get you landed in master and stable for developers to work against and tackle these tidy up activities one step at a time.

**Comment by weidongxu-microsoft** [comment]
@mitchdenny 

Yes, sdk/management/pom.xml is both a parent and a aggregate. We will try to separate the functions, though it might mixed a bit on our previous release job (which I think only upload "pom.xml" but not any "pom.xxx.xml" to storage blob).

Besides pom, checkstyle could also be a big challenge (maybe a much bigger one).

Also there might be security warning on dependency involved and json recorded. We ensured that it was clean in our previous repo. But thing may be configured differently in this repo. Let us know if there is warning popping-up and we would fix on high priority.

**Pull request merged**
