### PR TITLE
Generate stub services

### PR DESCRIPTION
**Pull request by RikkiGibson**
This PR contains generated code for many services that were observed to be in the .NET SDK but not in the Java Fluent SDK. The status of each service is noted in the following table.

| Service                       | Status                                   | Swagger last modified |
|-------------------------------|------------------------------------------|-----------------------|
| AnalysisServices              | Gen code doesn't compile                 | 22 Jun 2017           |
| Automation                    | AutoRest Duplicate File Generation error | 6 Apr 2017            |
| Billing                       | Generated                                | 26 Apr 2017           |
| CognitiveServices             | Generated                                | 16 May 2017           |
| Consumption                   | Generated                                | 5 May 2017            |
| CustomerInsights              | Generated                                | 5 Jul 2017            |
| DevTestLab                    | Generated                                | 25 Apr 2017           |
| Insights                      | Generated                                | 16 Feb 2017           |
| Intune                        | Gen code doesn't compile                 | 14 Sept 2016          |
| IoTHub                        | Generated (named devices)                | 5 Jun 2017            |
| Logic                         | Generated                                | 13 Apr 2017           |
| MachineLearning               | Generated                                | 31 Mar 2017           |
| Media                         | Generated                                | 30 Nov 2016           |
| OperationalInsights           | Gen code doesn't compile                 | 26 Jan 2017           |
| PowerBI                       | Generated                                | 1 Feb 2017            |
| RecoveryServices              | Generated                                | 14 Jun 2017           |
| RecoveryServices.Backup       | Naming conflict with RecoveryServices    | 16 Jun 2017           |
| RecoveryServices.SiteRecovery | Naming conflict with RecoveryServices    | 12 Jul 2017           |
| Relay                         | Generated                                | 30 Jun 2017           |
| ServerManagement              | Generated                                | 15 Nov 2016           |
| StorSimple                    | Gen code doesn't compile                 | 10 Jul 2017           |
| StreamAnalytics               | Generated                                | 30 May 2017           |

### CODE REVIEW

**Comment by jianghaolu** [comment]
@azuresdkci add to whitelist

**Comment by martinsawicki** [comment]
let's pull out Media and ServerManagement for now, as their swaggers haven't seen any work done in a while (since 2016)

**Comment by RikkiGibson** [comment]
Rebased and removed Media and ServerManagement. I also just realized that I need to reference the child modules in the parent pom, so I've added all those references.

**Comment by RikkiGibson** [comment]
Pending: Monitor service needs a stub Manager and possibly gen code for data plane. @hovsepm

**Comment by martinsawicki** [comment]
we'll process Monitor via a separate PR, as that requires some extra work

**Pull request merged**
