### PR TITLE
Cosmos Spark: Fixes conversion for MapType schema

### PR DESCRIPTION
**Pull request by ealsur**
When converting from JSON (ObjectNode) to Row (Spark) a document that had a nested object, for example:

```json
{
    "nested" : {
        "property": "value"
    }
}
```

If the pre-defined schema was using `MapType`, for example `MapType(keyType = StringType, valueType = StringType, valueContainsNull = false)`, it was throwing the following error:

```
Error while encoding: java.lang.RuntimeException: scala.collection.Iterator$$anon$10 is not a valid external type for schema of map<string,string>
```

### CODE REVIEW

**Review by FabianMeiswinkel — APPROVED** [review]
Thanks for the quick help!

**Review by moderakh — APPROVED** [review]
LGTM. thanks

**Pull request merged**
