### PR TITLE
Adds RNTBD Service Endpoint Statistics to request diagnostics

### PR DESCRIPTION
**Pull request by moderakh**
Adds RNTBD Service Endpoint Statistics to request diagnostics, the following section added to the request diagnostics:
```json
"channelTaskQueueSize": 1,
"pendingRequestsCount": 0,
"serviceEndpointStatistics": {
	"availableChannels": 1,
	"acquiredChannels": 0,
	"executorTaskQueueSize": 0,
	"inflightRequests": 1,
	"lastSuccessfulRequestTime": "2020-09-25T17:13:28.216Z",
	"lastRequestTime": "2020-09-25T17:13:28.215Z",
	"createdTime": "2020-09-25T17:13:26.312417Z",
	"isClosed": false
}
```

complete request diagnostics:
```json
{
	"userAgent": "azsdk-java-cosmos/4.6.0-beta.1 MacOSX/10.15.6 JRE/11.0.6",
	"requestLatencyInMs": 1,
	"requestStartTimeUTC": "2020-09-25T17:13:28.217060Z",
	"requestEndTimeUTC": "2020-09-25T17:13:28.218749Z",
	"connectionMode": "DIRECT",
	"responseStatisticsList": [{
		"storeResult": {
			"storePhysicalAddress": "rntbd://10.37.129.3:10253/apps/DocDbApp/services/DocDbServer2/partitions/a4cb494e-38c8-11e6-8106-8cdcd42c33be/replicas/1p/",
			"lsn": 1712,
			"globalCommittedLsn": -1,
			"partitionKeyRangeId": "1",
			"isValid": true,
			"statusCode": 200,
			"subStatusCode": 0,
			"isGone": false,
			"isNotFound": false,
			"isInvalidPartition": false,
			"requestCharge": 1.0,
			"itemLSN": 1712,
			"sessionToken": "-1#1712",
			"exception": null,
			"transportRequestTimeline": [{
				"eventName": "created",
				"durationInMicroSec": "12",
				"startTime": "2020-09-25T17:13:28.217489Z"
			}, {
				"eventName": "queued",
				"durationInMicroSec": "150",
				"startTime": "2020-09-25T17:13:28.217501Z"
			}, {
				"eventName": "pipelined",
				"durationInMicroSec": "202",
				"startTime": "2020-09-25T17:13:28.217651Z"
			}, {
				"eventName": "transitTime",
				"durationInMicroSec": "799",
				"startTime": "2020-09-25T17:13:28.217853Z"
			}, {
				"eventName": "received",
				"durationInMicroSec": "60",
				"startTime": "2020-09-25T17:13:28.218652Z"
			}, {
				"eventName": "completed",
				"durationInMicroSec": "1",
				"startTime": "2020-09-25T17:13:28.218712Z"
			}],
			"rntbdRequestLengthInBytes": 419,
			"rntbdResponseLengthInBytes": 769,
			"requestPayloadLengthInBytes": 0,
			"responsePayloadLengthInBytes": 303,
			"channelTaskQueueSize": 1,
			"pendingRequestsCount": 0,
			"serviceEndpointStatistics": {
				"availableChannels": 1,
				"acquiredChannels": 0,
				"executorTaskQueueSize": 0,
				"inflightRequests": 1,
				"lastSuccessfulRequestTime": "2020-09-25T17:13:28.216Z",
				"lastRequestTime": "2020-09-25T17:13:28.215Z",
				"createdTime": "2020-09-25T17:13:26.312417Z",
				"isClosed": false
			}
		},
		"requestResponseTimeUTC": "2020-09-25T17:13:28.218749Z",
		"requestResourceType": "Document",
		"requestOperationType": "Read"
	}],
	"supplementalResponseStatisticsList": [],
	"addressResolutionStatistics": {},
	"regionsContacted": ["https://10.37.129.3:8081/"],
	"retryContext": {
		"retryCount": 0,
		"statusAndSubStatusCodes": null,
		"retryLatency": 0
	},
	"metadataDiagnosticsContext": {
		"metadataDiagnosticList": null
	},
	"serializationDiagnosticsContext": {
		"serializationDiagnosticsList": [{
			"serializationType": "ITEM_DESERIALIZATION",
			"startTimeUTC": "2020-09-25T17:13:28.218997Z",
			"endTimeUTC": "2020-09-25T17:13:28.219078Z",
			"durationInMicroSec": 81
		}]
	},
	"gatewayStatistics": null,
	"systemInformation": {
		"usedMemory": "77483 KB",
		"availableMemory": "16699733 KB",
		"systemCpuLoad": "empty"
	}
}
```

### CODE REVIEW

**Comment by kirankumarkolli** [comment]
Nice! 

There are two taskQueues (channelPool, channel), would capturing both of them be useful?

**Review by FabianMeiswinkel — APPROVED** [review]
LGTM - thanks!

**Review by FabianMeiswinkel — APPROVED** [review]

**Review by kirankumarkolli — APPROVED** [review]

**Comment by kirankumarkolli** [comment]
Thanks for covering both the task queue length.

**Comment by kushagraThapar** [comment]
Merging on @moderakh 's request.

**Pull request merged**
