### PR TITLE
Update CreationSource.java

### PR DESCRIPTION
**Pull request by RaRe2604**
Null check on resourceType

### CODE REVIEW

**Comment by weidongxu-microsoft** [comment]
Hi @RaRe2604 
Thanks for the help.

If the resource type is null, does it mean that the source resource ID/URI is not correctly provided?

Note that checkstyle requires 4 space indention.
```
[ERROR] /home/vsts/work/1/s/sdk/resourcemanager/azure-resourcemanager-compute/src/main/java/com/azure/resourcemanager/compute/models/CreationSource.java:37: 'if' child has incorrect indentation level 15, expected level should be 16. [Indentation]
[ERROR] /home/vsts/work/1/s/sdk/resourcemanager/azure-resourcemanager-compute/src/main/java/com/azure/resourcemanager/compute/models/CreationSource.java:40: 'if' child has incorrect indentation level 15, expected level should be 16. [Indentation]
[ERROR] /home/vsts/work/1/s/sdk/resourcemanager/azure-resourcemanager-compute/src/main/java/com/azure/resourcemanager/compute/models/CreationSource.java:41: 'if' has incorrect indentation level 15, expected level should be 16. [Indentation]
[ERROR] /home/vsts/work/1/s/sdk/resourcemanager/azure-resourcemanager-compute/src/main/java/com/azure/resourcemanager/compute/models/CreationSource.java:42: 'if' child has incorrect indentation level 18, expected level should be 20. [Indentation]
[ERROR] /home/vsts/work/1/s/sdk/resourcemanager/azure-resourcemanager-compute/src/main/java/com/azure/resourcemanager/compute/models/CreationSource.java:43: 'if rcurly' has incorrect indentation level 15, expected level should be 16. [Indentation]
[ERROR] /home/vsts/work/1/s/sdk/resourcemanager/azure-resourcemanager-compute/src/main/java/com/azure/resourcemanager/compute/models/CreationSource.java:44: 'if' has incorrect indentation level 15, expected level should be 16. [Indentation]
[ERROR] /home/vsts/work/1/s/sdk/resourcemanager/azure-resourcemanager-compute/src/main/java/com/azure/resourcemanager/compute/models/CreationSource.java:45: 'if' child has incorrect indentation level 18, expected level should be 20. [Indentation]
[ERROR] /home/vsts/work/1/s/sdk/resourcemanager/azure-resourcemanager-compute/src/main/java/com/azure/resourcemanager/compute/models/CreationSource.java:46: 'if rcurly' has incorrect indentation level 15, expected level should be 16. [Indentation]
```

**Comment by RaRe2604** [comment]
Hi @weidongxu-microsoft Thanks I'll take care of the style.

Yes, resourceType is not checked for null and can throw NullPointerException.
We must use String literals first avoid NPE.

Example: 
In the below code if we pass null to heyInfo, it will throw NPE
```
String heyInfo = "Hey";
heyInfo.equalsIgnoreCase("Hello World");
```

A simple tweak to avoid NPE
```
String heyInfo = "Hey";
"Hello World".equalsIgnoreCase(heyInfo);
```

**Comment by weidongxu-microsoft** [comment]
@RaRe2604
Sure. I asked to check that if you encountered the NPE, whether it helps more to continue the flow, or to throw an `IllegalArgumentException`. If you didn't encountered the NPE, it is fine.

As long as the checkstyle passes, we can merge the fix.

**Comment by RaRe2604** [comment]
@weidongxu-microsoft  It will continue the flow.

**Review by weidongxu-microsoft — APPROVED** [review]

**Pull request merged**
