### PR TITLE
Adds HttpRequestMetadata

### PR DESCRIPTION
**Pull request by alzimmermsft**
# Description

Adds `HttpRequestMetadata` to contain all potential metadata that could be associated with an `HttpRequest`. Request metadata is the following, at this time:

| Metadata | Description |
| ---------- | ------------- |
| Caller method | The SwaggerMethodParser method that is making the HTTP request |
| Logger | The `ClientLogger` associated with the SwaggerMethodParser method used to associate any HTTP request and response logging to the SwaggerMethodParser method |
| Eagerly read response | Whether the network response for the request should be eagerly read into memory |
| Ignore response body | Whether the network response for the request should be ignored and eagerly discarded |
| Eagerly convert headers | Whether the response headers should be eagerly converted in the `azure-core` `HttpHeaders` |
| Try count | The current attempt of making the HTTP request |

This PR reduces the over usage of `Context` to pass metadata through the `HttpPipeline` and `HttpClient` when making requests and provides explicit APIs for getting data that may be required during the request call.

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [x] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Review by lmolkova — APPROVED** [review]
LGTM!

**Comment by lmolkova** [comment]
It seems we're also passing headers in context

BTW, found this thing that gets headers from context https://github.com/Azure/azure-sdk-for-java/blob/7c71625811cda371e27b7bf2f32dd71689df000b/sdk/core/azure-core/src/main/java/com/azure/core/http/policy/AddHeadersFromContextPolicy.java#L49

It's used in a bunch of places, maybe worth adding to metadata now or later

**Comment by alzimmermsft** [comment]
> BTW, found this thing that gets headers from context
> 
> https://github.com/Azure/azure-sdk-for-java/blob/7c71625811cda371e27b7bf2f32dd71689df000b/sdk/core/azure-core/src/main/java/com/azure/core/http/policy/AddHeadersFromContextPolicy.java#L49
> 
> It's used in a bunch of places, maybe worth adding to metadata now or later

I think `HttpRequestMetadata` should be reserved for values passed in `Context` used internally to the SDKs, like what was changed in the PR, and not for user passed values.

**Comment by lmolkova** [comment]
> > BTW, found this thing that gets headers from context
> > https://github.com/Azure/azure-sdk-for-java/blob/7c71625811cda371e27b7bf2f32dd71689df000b/sdk/core/azure-core/src/main/java/com/azure/core/http/policy/AddHeadersFromContextPolicy.java#L49
> > 
> > It's used in a bunch of places, maybe worth adding to metadata now or later
> 
> I think `HttpRequestMetadata` should be reserved for values passed in `Context` used internally to the SDKs, like what was changed in the PR, and not for user passed values.

I see, I was not aware we let users pass it, thanks for the explanation!

**Pull request closed without merging**
