### PR TITLE
[Communication]: Add package specific tests.yml

### PR DESCRIPTION
**Pull request by JianpingChen**

### CODE REVIEW

**Comment by sacheu** [comment]
Please add 'Int' Cloud Config to each of your tests.yml 
see https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/communication/tests.yml

image

**Comment by JianpingChen** [comment]
> Please add 'Int' Cloud Config to each of your tests.yml
> see https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/communication/tests.yml
> 
> image

Will do

**Review by sacheu — APPROVED** [review]
Looks Good. All 4 pipelines have 2 stages:  Prod and INT. And they all passed.

**Pull request merged**
