### PR TITLE
make context load config only for the first time

### PR DESCRIPTION
**Pull request by backwind1233**
1. update version to 2.0.0-beta.1
2. make context load config only for the first time
https://github.com/Azure/azure-sdk-for-java/issues/18646

### CODE REVIEW

**Review by saragluna — APPROVED** [review]
LGTM.

**Comment by saragluna** [comment]
@mrm9084 this is the PR to fix the loading configuration multiple times issue. Please help review it too 🙏 .

**Comment by mrm9084** [comment]
@backwind1233 this isn't what I was thinking about and I think it will break the refresh feature.

**Comment by backwind1233** [comment]
@mrm9084  can you tell me what's your idea? 
If we don't reload configs only for the binder context,  is it helpful for you?

**Review by mrm9084 — APPROVED** [review]

**Pull request merged**
