### PR TITLE
mgmt sdk restructure

### PR DESCRIPTION
**Pull request by weidongxu-microsoft**

### CODE REVIEW

**Comment by weidongxu-microsoft** [comment]
https://github.com/Azure/azure-sdk-for-java/issues/5682

**Comment by weidongxu-microsoft** [comment]
Batch done via script https://github.com/weidongxu-microsoft/misc-automation/blob/master/update_spec_java_sdk.py

**Comment by mitchdenny** [comment]
I noticed that your ci.mgmt.yml files are all duplicates, this might make maintenance a bit challenging for you in the future, so you might like to consider refactoring into a template, but in terms of the substance of the changes I don't think that this will negatively impact the client SDK builds.

**Comment by weshaggard** [comment]
@weidongxu-microsoft after trying to pull these changes locally I'm hitting file long path issues on windows. My root repo path is `D:\adp\azure-sdk-for-java` which is about as small a root we can get. I think we are going to have to figure out a way to shorten these file paths.

**Comment by weshaggard** [comment]
@weidongxu-microsoft can you please work with @mitchdenny and @JimSuplizio to come up with a strategy to reduce the file length. As it stands after your change if you have a root path greater then 9 chars in length you will hit long path. The longest path I found was 251 chars in length without the root. @chidozieononiwu  correct me if I'm wrong but for other repo's we have been trying to keep about 50 chars available for root paths and I think we should strive for that here as well.

**Comment by weidongxu-microsoft** [comment]
@weshaggard 
I think it mostly due to new folder structure. Previously it is something like
`/recoveryservices.siterecovery/resource-manager/`
and now it is
`/sdk/recoveryservices.siterecovery/azure-mgmt-recoveryservices.siterecovery/`

The service name get repeated twice.

`azure-mgmt-recoveryservices.siterecovery` part of the folder is probably not of significance since that already under the folder of this service name. So one option for those service with long name, we could just use say `mgmt` instead. E.g.
`/sdk/recoveryservices.siterecovery/mgmt/`

Another option is try to get with a shorter service name, but that might not be easy.

**Pull request merged**
