### PR TITLE
Migrate azure-storage-file-share to azure-json and azure-xml

### PR DESCRIPTION
**Pull request by alzimmermsft**
# Description

Migrates `azure-storage-file-share` to `azure-json` and `azure-xml` and removes all usages of Jackson. Shares has both JSON and XML which is why it is migrating to both libraries.

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [x] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Review by ibrahimrabab — APPROVED** [review]

**Comment by alzimmermsft** [comment]
Overriding check enforcer as live tests validated no regressions, failing due to flaky tests that were happening before the PR. code-quality-reports was also failing before this PR.

**Comment by HerrDerb** [comment]
@alzimmermsft maybe you can help me here. Since this change I am having trouble when compiling native with quarkus.

With the update to `com.azure:azure-storage-file-share:12.22.0` (which includes this change) the directory client keeps returning an empty list when calling `listFilesAndDirectories` even if there is data. It does work as expected when executing the application as jar. I kind of would have expected an exception when running it nativley or anything like that. But there is none, which makes this problem quite hard to debug. SO currently I am still puzzled. That is where I hope that you might be able to give me a hint 🙏

With the change to azure-xml/json, are there any classes (services) which need to be registered for reflection which are not obvious? Anything special to watch out when compiling native?

**Comment by srnagar** [comment]
@HerrDerb could you please share a quarkus sample to repro this issue? With migration to azure-xml/json, the use of reflection to serialize/deserialize has significantly reduced. So, I am not sure if that is causing an issue. It would be helpful to see sample code.

**Pull request merged**
