### PR TITLE
Enable connection state listener by default

### PR DESCRIPTION
**Pull request by xinlian12**
Task: https://github.com/Azure/azure-sdk-for-java/issues/28268

**Description:**
Enable endpointRediscovery(aka. ConnectionStateListener) by default.

BenchmarkTest:

**P95 Latency:**
image

**P99 Latency:**
image

**P999 Latency:**
image

**Max Latency:**
image

**Throughput:**
image

### CODE REVIEW

**Review by FabianMeiswinkel — COMMENTED** [review]
Changelog is missing

**Comment by xinlian12** [comment]
Azure cosmos pipeline: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1576752&view=results

Run the following tests locally:
getSessionTokensInRequests
splitQueryContinuationToken
orderByQueryForLargeCollection
before_MultiOrderByQueryTests

**Comment by xinlian12** [comment]
check-enforcer override

**Comment by xinlian12** [comment]
The pipeline has completed based on here: https://dev.azure.com/azure-sdk/public/_build/results?buildId=1577257&view=results

**Pull request merged**
