### PR TITLE
Updated ManageVirtualMachineExtension.java

### PR DESCRIPTION
**Pull request by Amankantkashyap**
# Description
This code snippet only updates the existing user's password instead of creating a new user.

i tried multiple ways and finally found the solution seems like it is case sensitive instead of withProtectedSetting use withPublicSetting for username and the change the key to UserName and Password and change the version to 2.4

### CODE REVIEW

**Comment by weidongxu-microsoft** [comment]
@XiaofeiCao 

Could you double check, and merge if correct?

I think we had a refresh of samples planned.

**Comment by weidongxu-microsoft** [comment]
@XiaofeiCao

Could you double check, and approve / merge if sample in PR is correct?

**Comment by XiaofeiCao** [comment]
ok

**Review by XiaofeiCao — APPROVED** [review]

**Comment by XiaofeiCao** [comment]
@Amankantkashyap 

LGTM. Thanks for your contribution!

PS(Irrelavant): I saw that in official doc, this feature is supported as early as 2.0:
https://github.com/uglide/azure-content/blob/master/articles/virtual-machines/virtual-machines-windows-extensions-configuration-samples.md#vmaccess-extension
But I can't get it to work in version 2.3. Once I install the extension, RDP seems not working any more.. 2.4 works like magic though.. Wonder if you encounter the same issue for 2.3...

**Pull request merged**
