### PR TITLE
Fixed existsById API in ReactiveCosmosTemplate

### PR DESCRIPTION
**Pull request by kushagraThapar**
* Fixed existsById API in ReactiveCosmosTemplate
* Fixes: https://github.com/Azure/azure-sdk-for-java/issues/40019

### CODE REVIEW

**Review by trande4884 — APPROVED** [review]
Do we need to check CosmosTemplate also? Otherwise LGTM!

**Comment by kushagraThapar** [comment]
@trande4884  - `CosmosTemplate` doens't have `existsById` API, so we are good.

**Review by FabianMeiswinkel — APPROVED** [review]
LGTM - Thanks

**Pull request merged**
