### PR TITLE
updating netty, reactor-core, reactor-netty versions in arm-parent  pom.

### PR DESCRIPTION
**Pull request by anuchandy**

### CODE REVIEW

**Comment by JonathanGiles** [comment]
What is the motivation for doing this upgrade? Are there particular improvements that we want to benefit from, etc? One thing we need to temper our enthusiasm for upgrading to the latest with is the need to ensure that we are not moving faster than our audience and forcing classpath conflicts between versions of these libraries.

**Comment by anuchandy** [comment]
@JonathanGiles, thanks for the review!

1. The track1 mgmt libraries in our repro are not using the packages this PR is touching.
2. We haven't started publishing track2 mgmt libraries; those will eventually use these packages.

[@weidongxu-microsoft, please chime in if my above statements are wrong!]

Hence I think, as of today, mgmt libs do not directly benefit from any improvements in the latest versions of these packages. 

But of course, customers might be using these packages transitively. 

The main reason for `io.netty` update is to pull a netty fix related to unbounded-memory-allocation when running netty in "server mode." The reason for updating the reactor-core is also to align the same transitive netty dependency. [It also algins with track2 data-plane dependencies]

Again only mgmt customers using this pom to pick netty transitively will benefit from these.

I'll loop you into a running email thread regarding this.

Let me know your thoughts on this PR.

**Comment by weidongxu-microsoft** [comment]
1. Yes, track1 mgmt does not use these packages.
2. When we release track2 mgmt libraries, I think we would use `azure-client-sdk-parent` as parent. (I am not 100% sure here. But I think `azure-client-sdk-parent` would be the 1st choice).

**Comment by joshfree** [comment]
@anuchandy what's happening with this old PR?

**Comment by alzimmermsft** [comment]
Closing as this was resolved by #16611

**Pull request closed without merging**
