### PR TITLE
Added support for providing a custom login URI to get access tokens from via the system property `azure.login.uri`

### PR DESCRIPTION
**Pull request by vcolin7**

### CODE REVIEW

**Review by saragluna — APPROVED** [review]
LGTM

**Comment by vcolin7** [comment]
Overriding Check Enforcer because it's failing due to an unrelated issue with package `azure-cosmos-spark_3-5_2-12`:
```
Failed to execute goal net.alchim31.maven:scala-maven-plugin:4.8.1:compile (default) on project azure-cosmos-spark_3-5_2-12: Execution default of goal net.alchim31.maven:scala-maven-plugin:4.8.1:compile failed. CompileFailed -> [Help 1]
```

**Pull request merged**
