### PR TITLE
Merge the Spring Cloud Azure 4.0 back to main branch

### PR DESCRIPTION
**Pull request by saragluna**
We have GAed the Spring Cloud Azure 4.0 from the 4.0 branch, this PR is used to merge it back to the main branch.

### CODE REVIEW

**Comment by saragluna** [comment]
@hallipr, please take a look at the changes made in eng/scripts and eng/pipelines. If no concerns, we're planning to merge the pr back to main by the end of this week.

**Review by stliu — APPROVED** [review]
LGTM

**Comment by saragluna** [comment]
> @hallipr, please take a look at the changes made in eng/scripts and eng/pipelines. If no concerns, we're planning to merge the pr back to main by the end of this week.

Hi @hallipr, since no comments were left on this PR, I will go ahead to merge it to main now. If you have concerns we can change them in the main.

**Comment by saragluna** [comment]
The linting failed because the graalvm sample, so I will override the check enforcer. https://dev.azure.com/azure-sdk/public/_build/results?buildId=1478454&view=results

**Pull request merged**
