### PR TITLE
Make external depencencies' version align to spring-boot 2.6.2

### PR DESCRIPTION
**Pull request by Netyyyy**
1. spring-boot:2.6.2 released: https://github.com/spring-projects/spring-boot/releases/tag/v2.6.2
2. spring-boot-dependencies: https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-dependencies/2.6.2/spring-boot-dependencies-2.6.2.pom

### CODE REVIEW

**Comment by chenrujun** [comment]
Hi, @alzimmermsft , originally, we plan to merge it after all pipeline passed.

**Review by alzimmermsft — APPROVED** [review]

**Review by chenrujun — APPROVED** [review]
LGTM.

**Comment by chenrujun** [comment]
Hi, @Netyyyy .
FYI:

Comments from @alzimmermsft :
> if the branch isn't up-to-date with upstream main the failing EventGrid test isn't caused by changes but was a real bug that has been fixed

**Pull request merged**
