### PR TITLE
Convert pipeline to run under 1ES template

### PR DESCRIPTION
**Pull request by weshaggard**
Convert to 1ES

### CODE REVIEW

**Review by JimSuplizio — APPROVED** [review]

**Comment by weshaggard** [comment]
This pipeline needs more work before it is ready.

**Comment by benbp** [comment]
@weshaggard I have some examples of container build/publishing with 1es here: https://github.com/Azure/azure-sdk-tools/blob/main/eng/pipelines/publish-docker-image-isolated.yml

Additionally you have to add a service connection to the registry via the 1es template: https://github.com/Azure/azure-sdk-tools/blob/main/eng/pipelines/templates/stages/1es-redirect.yml#L26-L28

**Comment by weshaggard** [comment]
test run https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3723036&view=results

@benbp this PR is ready for review now.

**Pull request merged**
