### PR TITLE
Decouple the auto-configuration of resource manager with data plane sdks in Spring Cloud Azure 4.0

### PR DESCRIPTION
**Pull request by saragluna**
This PR will:
- Move resource provisioner API to the resource manager module
- Decouple resource manager auto-configuration with data plane SDK
- Unmark tenant-id as required property for a resource manager's auto-configuration

### CODE REVIEW

**Review by stliu — APPROVED** [review]

**Comment by saragluna** [comment]
The integration tests failed for a temporary networking issue. Merging this PR now.

**Pull request merged**
