### PR TITLE
Delete jacoco setting in spring modules

### LINKED ISSUE #26175: Use default jacoco setting for all spring-cloud-azure modules @moary
## jacoco-maven-plugin

We should delete the following contents:
```
<jacoco.min.linecoverage>xxx</jacoco.min.linecoverage>
<jacoco.min.branchcoverage>xxx</jacoco.min.branchcoverage>
```

in these modules:

 - [x] spring-cloud-azure-actuator
 - [x] spring-cloud-azure-actuator-autoconfigure
 - [ ] spring-cloud-azure-autoconfigure
 - [x] spring-cloud-azure-core
 - [x] spring-cloud-azure-resourcemanager
 - [x] spring-cloud-azure-service
 - [x] spring-cloud-azure-stream-binder-eventhubs
 - [x] spring-cloud-azure-stream-binder-eventhubs-core
 - [x] spring-cloud-azure-stream-binder-servicebus
 - [x] spring-cloud-azure-stream-binder-servicebus-core
 - [x] spring-cloud-azure-stream-binder-test
 - [x] spring-cloud-azure-trace-sleuth
 - [x] spring-integration-azure-core
 - [x] spring-integration-azure-eventhubs
 - [x] spring-integration-azure-servicebus
 - [x] spring-integration-azure-storage-queue
 - [x] spring-messaging-azure
 - [x] spring-messaging-azure-eventhubs
 - [x] spring-messaging-azure-servicebus
 - [x] spring-messaging-azure-storage-queue

Add more tests if pipeline failed after delete these contents.

### PR DESCRIPTION
**Pull request by chenrujun**
As title.
Resolve #26175

### CODE REVIEW

**Review by saragluna — APPROVED** [review]
LGTM.

**Comment by chenrujun** [comment]
Hi, @yiliuTo .
https://dev.azure.com/azure-sdk/public/_build/results?buildId=1268419&view=logs&j=b7e05d34-ff84-5d4f-6be8-71e0852fbae4&t=14ed7cc3-77e0-5c56-7dbf-9a450ffc4d86&l=486

Could you please add more tests for `spring-integration-azure-eventhubs` and `pring-integration-azure-servicebus`?

**Comment by chenrujun** [comment]
Hi, @moarychan , could you please help to fix the pipeline failure?

**Pull request merged**
