### PR TITLE
Update change log for next release

### PR DESCRIPTION
**Pull request by trask**

### CODE REVIEW

**Comment by heyams** [comment]
Need to increment version in the README too.

**Comment by trask** [comment]
> Need to increment version in the README too.

is that automatic via this line?

https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/monitor/azure-monitor-opentelemetry-exporter/README.md?plain=1#L21

**Comment by heyams** [comment]
> > Need to increment version in the README too.
> 
> is that automatic via this line?
> 
> https://github.com/Azure/azure-sdk-for-java/blob/54c16300121a65c80ee3440a7df346dbaf7757f5/sdk/monitor/azure-monitor-opentelemetry-exporter/README.md?plain=1#L21

no, it's not auto updated.

**Comment by trask** [comment]
what's the purpose of this line then?

https://github.com/Azure/azure-sdk-for-java/blob/54c16300121a65c80ee3440a7df346dbaf7757f5/sdk/monitor/azure-monitor-opentelemetry-exporter/README.md?plain=1#L21

**Comment by trask** [comment]
(btw it seems wrong to me to update the version on the README.md before we make the release, since then someone using that README.md will be broken until the release actually makes it to maven central)

**Comment by heyams** [comment]
> (btw it seems wrong to me to update the version on the README.md before we make the release, since then someone using that README.md will be broken until the release actually makes it to maven central)

it's a question for azure sdk team. you can reach out to them directly. you don't need to have it in this PR to test out the new release. then push another PR to update after the release when auto-update fails.

**Comment by trask** [comment]
> you don't need to have it in this PR to test out the new release. then push another PR to update after the release when auto-update fails.

sounds good, can you approve this PR then?

**Review by heyams — APPROVED** [review]

**Pull request merged**
