### PR TITLE
Fix bugs caused by supporting azure ad proxy

### PR DESCRIPTION
**Pull request by chenrujun**
Fix these bugs:
 - #31190
 - #31191
 - #31482 
 - #31593
 - #31593

### CODE REVIEW

**Comment by chenrujun** [comment]
Hi, @saragluna , @moarychan , please help review this PR when you have time.

**Comment by chenrujun** [comment]
Hi, @saragluna , @moarychan , please help to review this PR.

**Comment by chenrujun** [comment]
The failure of **java - code-quality-reports-ci** can be ignored. Here is the detail information:

The [java - code-quality-reports-ci#1938677](https://dev.azure.com/azure-sdk/public/_build/results?buildId=1938677&view=results) failed because the [Revapi Maven Plugin](https://revapi.org/revapi-maven-plugin/0.14.7/index.html) checks the currently built project against the its latest released version (as reported by Maven). Current PR targeting to a patch release (4.4.1). The artifacts released new versions after 4.4.0, so comparing to latest released version will have error.

**Review by moarychan — APPROVED** [review]
LGTM.

**Pull request merged**
