### PR TITLE
End-to-End TLS/SSL - Changes for Checkstyle

### PR DESCRIPTION
**Pull request by mnriem**

### CODE REVIEW

**Comment by mnriem** [comment]
@chenrujun I will need your help to put in exclusions for the remainder of the failing Checkstyle issues as they are false-positives.

**Comment by vcolin7** [comment]
> 
> 
> @chenrujun I will need your help to put in exclusions for the remainder of the failing Checkstyle issues as they are false-positives.

We can suppress the logger errors the Checkstyle plugin is flagging since we don't make use of Azure Core. We can also suppress [this](https://dev.azure.com/azure-sdk/public/_build/results?buildId=590674&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=ba3cf43a-b2bf-50f9-f95f-93049ca44ad1&l=709) and [this](https://dev.azure.com/azure-sdk/public/_build/results?buildId=590674&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=ba3cf43a-b2bf-50f9-f95f-93049ca44ad1&l=710) error because these variables might be assigned a value more than once.

We should, however, make `tenantId`, `clientId` and `clientSecret` final in `KeyVaultClient` like Checkstyle suggests, they are only assigned a value in the client's constructor.

**Comment by mnriem** [comment]
The `tenantId`, `clientId` and `clientSecret` can't be final as they are also false positives. If you change them to final compilation fails.

**Comment by vcolin7** [comment]
Oh you are right, I missed that there's a constructor that does not set these values.

**Comment by vcolin7** [comment]
Added the required Checkstyle suppressions.

**Review by chenrujun — APPROVED** [review]
LGTM.

**Pull request merged**
