### PR TITLE
Moved Generic Core classes

### PR DESCRIPTION
**Pull request by vcolin7**
Changes in this PR:

- Moved `Response` to `com.generic.core.http.models`
- Moved `BinaryData` classes to `com.generic.core.util.binarydata`
- Moved `Context` to `com.generic.core.util`
- Moved `Header`, `HeaderName`, and `Headers` to `com.generic.core.http.models`

### CODE REVIEW

**Comment by alzimmermsft** [comment]
I'm not sure how I feel about moving `Header`, `Headers`, `HeaderName`, and `Response` into `http.models`, we dropped `Http` from the class names to enable them to be shared across wire formats (AMQP, HTTP) but by moving them into the `http.models` package we're effectively bringing that back but leaving the classes with less unique names possible leading to needing to fully qualify classes in code more often.

**Comment by alzimmermsft** [comment]
Per offline discussion the models will move into `models.http` but their names will also change to suffix with `Http` to help reduce class name conflicts.

**Comment by vcolin7** [comment]
> Per offline discussion the models will move into `models.http` but their names will also change to suffix with `Http` to help reduce class name conflicts.

Correct, all mudels but `Response` will get an `Http` prefix.

**Review by srnagar — APPROVED** [review]

**Pull request merged**
