### PR TITLE
fix issues about Synapse service

### PR DESCRIPTION
**Pull request by Melanie-Ma**
Fix issues #18364 , #18365 , #18366 , #18367 , #18368  about Synapse service 

@scottaddie , @joshfree , @jameszliao-msft , @lmazuel and @jongio for notification

### CODE REVIEW

**Comment by v-xuto** [comment]
@jongio - Can you help ping the corresponding person to review this PR?

**Comment by jongio** [comment]
@joshfree - Who should review this?

**Comment by v-xuto** [comment]
@joshfree - Could you help us review this PR?

**Comment by v-xuto** [comment]
@scottaddie , @joshfree , @jameszliao-msft , @lmazuel  Could you please review this PR?

**Comment by v-xuto** [comment]
@scottaddie , @joshfree , @jameszliao-msft , @lmazuel Could you please review this PR?

**Comment by v-xuto** [comment]
@scottaddie , @joshfree , @jameszliao-msft , @lmazuel Could you please review this PR?

**Pull request merged**
