### PR TITLE
Implemented TimeSpan type, which is the type used to represents durat…

### PR DESCRIPTION
**Pull request by anuchandy**
…ion of various service bus specific properties

### CODE REVIEW

**Comment by jianghaolu** [comment]
Is this similar to http://joda-time.sourceforge.net/apidocs/org/joda/time/Period.html?

**Comment by anuchandy** [comment]
The Period in Java and TimeSpan in C# represents duration. One issue I'm facing with Period is using it to parse RP returned duration represented in TimeSpan format. 

Period's built-in formatter `ISOPeriodFormat` can be used only if the duration is represented in ISO8601 format, which is the swagger recommended format but service bus will switch to this format only in the future api version.

I tried `PeriodFormatBuilder`, but unable to parse all the possible combination that TimeSpan string format.

```bash
    [-]d\0
    [-]d.hh:mm\0
    [-]hh:mm\0
    [-]d.hh:mm:ss\0
    [-]hh:mm:ss\0
    [-]d.hh:mm:ss:ffffffff\0
    [-]hh:mm:ss:ffffffff\0
```

For example following builder requires string to be exactly in `hh:mm:ss:ffffffff` format

```java
        PeriodFormatter formatter = new PeriodFormatterBuilder()
                .appendDays().appendSeparatorIfFieldsAfter(".")
                .appendHours().appendSeparatorIfFieldsAfter(":")
                .appendMinutes().appendSeparatorIfFieldsAfter(":")
                .appendSeconds().appendSeparatorIfFieldsAfter(".")
                .appendMillis()
                .toFormatter();
```

But I'm thinking that in fluent user can specify duration using `Period` type and internally we use `TimeSpan` type. Once the PR started supporting ISOPeriodFormat (which is planned for next api version) we can just remove the TimeSpan.

**Comment by jianghaolu** [comment]
https://github.com/Azure/autorest/pull/369

**Comment by anuchandy** [comment]
@jianghaolu - thanks for the autorest discussion link about duration. 

Once the service bus starts supporting ISO8601 duration then Java codegen will emit `joda.time.Period`. 
In the fluent layer, we accept `joda.time.Period` and `TimeSpan` type (in implementation namespace) can convert this to C# TimeSpan format to send over the wire. This means once service bus update rolled out fix https://github.com/Azure/azure-rest-api-specs/issues/962#issuecomment-282851197 without breaking customer we can just remove period-to-timespan conversion.

**Pull request merged**
