### PR TITLE
mgmt, deploymentstacks

### PR DESCRIPTION
**Pull request by weidongxu-microsoft**
It also upgrades "resources" to 2024-03-01 (in same folder).

LIVE pass. I didn't update the whole recording (it is in another branch https://github.com/weidongxu-microsoft/azure-sdk-for-java/tree/mgmt_deploymentstacks_record), as the sanitization of "name" property in chat.

Manual fix https://github.com/Azure/azure-sdk-for-java/pull/40410/commits/90504c1e910b10e5b646e398410e79a616f312f1
(it likely can be solved by reverting the order of generation, run "deploymentstacks" after "resources" -- but they do have model of same name, at present of same schema)

Test https://github.com/Azure/azure-sdk-for-java/pull/40410/commits/443760e08a8ebaf1be8d6259181b74fd63a88c9c

# Description

Please add an informative description that covers that changes made by the pull request and link all relevant issues.

If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [x] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Comment by haolingdong-msft** [comment]
For the manual fix, do we need to do the same when generating deploymentstacks next time?

**Comment by XiaofeiCao** [comment]
We could do something like, combine resources' tags together as a full inputfiles list to generate. Though haven't tried and not sure of the consequences.

**Review by XiaofeiCao — APPROVED** [review]

**Comment by weidongxu-microsoft** [comment]
Xiaofei's idea may work -- if it works, we should not need to do manual change.

**Comment by weidongxu-microsoft** [comment]
There is one more difference of "type" property in `DeploymentParameter`.
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/resources/resource-manager/Microsoft.Resources/stable/2024-03-01/resources.json#L4666-L4678
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/resources/resource-manager/Microsoft.Resources/stable/2024-03-01/deploymentStacks.json#L1420-L1436

I guess I would first use the one in resources.json

**Pull request merged**
