### PR TITLE
Fix live test pipeline Form Recognizer

### PR DESCRIPTION
**Pull request by samvaity**
Problem
-  `checkRecognizeFormTypeComposedModelWithModelName` test case is failing for a resource deployed in `westUS2` region.

Cause
- Inspite the test-resources.json file specifying the location as `canadacentral` resource is [being deployed in `westUS2` region](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1027505&view=logs&j=dfd73531-a258-5256-cbbe-7a59f8d7ad3f&t=aa93b7a4-17c5-5081-cdc6-0ad44a0daac3&l=23).

Fix
- the test-resources.json should use a variable location.
- [TODO] reach out to the service team for this observation in the `westUs2` region

### CODE REVIEW

**Comment by samvaity** [comment]
/ azp run java - formrecognizer - tests

**Review by JonathanGiles — APPROVED** [review]

**Comment by samvaity** [comment]
Ref Live pipeline build - https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1029117&view=results

**Pull request merged**
