### PR TITLE
[Spring]FixIllegalStateExceptionForDelete

### PR DESCRIPTION
**Pull request by xinlian12**
Fix issue https://github.com/Azure/azure-sdk-for-java/issues/38917

Fix: avoid using .block/.blockLast in our reactive pipeline  - As documented here https://github.com/reactor/reactor-core/releases/tag/v3.2.0.M2.

### CODE REVIEW

**Review by FabianMeiswinkel — APPROVED** [review]
LGTM

**Comment by edavedian** [comment]
@xinlian12 thank you very much for addressing this issue.  I have a follow up question.  The statement 

`new PartitionKey(entityInfo.getPartitionKeyFieldValue(object)),`

in the area that the fix was, is obtaining the partition key value from the instance of the domainType that was created a few lines above with this statement

`CosmosEntityInformation<T, Object> entityInfo = (CosmosEntityInformation<T, Object>) CosmosEntityInformation.getInstance(domainType);`

This instance though since it was just instantiated won't have any value for partition key unless I am misunderstanding the approach.  The same issue exists in `findItems` method.  Would it be possible for me to create an enhancement request to support something like 

`deleteByNaId(String naId, PartitionKey partitionKey);`

and use this partition key during `findItems `and `delete` methods.

**Comment by xinlian12** [comment]
Hi @edavedian 

`  final Flux<JsonNode> results = findItems(query, finalContainerName, domainType);
`
this is the first step happened to retrieve all the items need to be deleted. The partitionKey is retrieved from the cosmosQuery based on the partitionKeyField in the domainType.

so in your scenario `Mono<Void> deleteByNaId(String naId); `, the cosmosQuery here will contain criteria naId = naId(the value passed in), and then we tried to parsing the partition key value based on the criteria. However, since in your case naId is not the partition Key, so essentially this will be translated into a query "select * from naId = {naId}" and this will be a cross partition query. 

After we get all the items from the above step, then we will go ahead to delete them, here when we calculate the partitionKeyValue, we use the value from the items. 

If I understand correctly, the issue you pointed out is that in step one, it will be a cross partition query as no partitionKey value is being defined, whether we can support to accept a partitionKey value as well. I think it is a valid ask, please feel free to create a GitHub feature request and our team will evaluate it :)

**Comment by edavedian** [comment]
@xinlian12 Thank you very much.  I will created a feature request.

**Comment by edavedian** [comment]
@xinlian12 I have submitted the feature request https://github.com/Azure/azure-sdk-for-java/issues/39331 based on our conversation.

**Pull request merged**
