### PR TITLE
Decouple OpenAI Models from the Client Library

### PR DESCRIPTION
**Pull request by brunoborges**
# Description

This change decouples the OpenAI Models to a separate artifact. With this change, 3rd-party developers and other Microsoft libraries may reuse the OpenAI Models without depending on the OpenAI Client Library.

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [ ] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Comment by mssfang** [comment]
@brunoborges Thanks for bringing this idea up. It should be bring up to other Azure OpenAI SDKs as well. It is a fundamental change in the packaging structure in a DPG library.

**Comment by karianna** [comment]
@brunoborges Not sure if you have agency to fix the GH Action build errors.  On a side note I noticed that Maven 3.8.8 is being used, could probably go to 3.9.2

**Comment by brunoborges** [comment]
Not sure this PR is the best place to fix those things.

But regarding the build action, I would appreciate the review from the SDK team.

**Comment by brunoborges** [comment]
Hey @mssfang ... Not sure if you merged this or not?

**Comment by mssfang** [comment]
@brunoborges  The feature branch was merged to the `main` so this PR is automatically closed by git. A new PR should be open to `main` now.  Sorry for the confusion.

**Pull request closed without merging**
