### PR TITLE
Make external depencencies' version align to spring-boot 2.6.3

### PR DESCRIPTION
**Pull request by Netyyyy**
1. spring-boot:2.6.3 released: https://github.com/spring-projects/spring-boot/releases/tag/v2.6.3
2. spring-boot-dependencies: https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-dependencies/2.6.3/spring-boot-dependencies-2.6.3.pom

### CODE REVIEW

**Review by chenrujun — APPROVED** [review]
LGTM.

**Comment by chenrujun** [comment]
@Netyyyy Please merge it after SpringCloudAzure:3.14.0 released.
To make sure SpringCloudAzure and SDK share the same external dependencies'version.

Related PR: https://github.com/Azure/azure-sdk-for-java/pull/27141

**Review by weidongxu-microsoft — COMMENTED** [review]
OK for mgmt

**Comment by Netyyyy** [comment]
Due to Spring cloud having new version:2021.0.1, need to update

**Comment by Netyyyy** [comment]
Hi @vcolin7 , @g2vinay while spring-cloud updating to *2021.0.1*, `KeyVaultBackupClientTest` [failed](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1390472&view=logs&j=65b31511-849f-511e-db8e-625328b18c53&t=b80d7120-0e6c-5e0c-c7d0-a94b3ea98288&l=1733)
image
, please help to fix it asap, thanks so much.

**Comment by chenrujun** [comment]
Hi, @Netyyyy 

Since this PR is not merged yet, how about upgrading to 2.6.4 directly?
Here is related issue: https://github.com/Azure/azure-sdk-for-java/issues/27304

**Comment by kushagraThapar** [comment]
@Netyyyy / @chenrujun - this broke Rev API in spring data Cosmos, because of some changes in `ParameterAccessor` interface in spring framework new version - https://dev.azure.com/azure-sdk/public/_build/results?buildId=1404014&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=ba3cf43a-b2bf-50f9-f95f-93049ca44ad1
This is the pipeline that is failing for Cosmos - which will also block our releases, and any PR merges. 

Please help!
cc @alzimmermsft  / @srnagar  - does Rev API makes sense on spring cosmos SDK ?
It is also being done on other spring SDKs / connectors in our repo? If yes, why was this not caught in their CIs ?

**Comment by srnagar** [comment]
@kushagraThapar It would be better to have RevApi enabled for the Spring Data Cosmos library as a safety net to not accidentally ship a backward breaking change. When it complains (which doesn't happen very frequently), it's good to review it manually and suppress those specific false positives. 

Regarding the failure above, [this PR](https://github.com/Azure/azure-sdk-for-java/pull/27393) may have caused this and looking at the CI pipelines that ran, it doesn't seem like the Cosmos CI was included. This could be because the only change was to the pom file which skips CI builds. Ideally, when external dependencies are updated, the PR should trigger CIs for all services using that dependency. While I discuss this issue with the EngSys team, you can go ahead and suppress this RevApi error and continue with the PR/release process for Cosmos.

**Comment by Netyyyy** [comment]
> @Netyyyy / @chenrujun - this broke Rev API in spring data Cosmos, because of some changes in `ParameterAccessor` interface in spring framework new version - https://dev.azure.com/azure-sdk/public/_build/results?buildId=1404014&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=ba3cf43a-b2bf-50f9-f95f-93049ca44ad1 This is the pipeline that is failing for Cosmos - which will also block our releases, and any PR merges.
> 
> Please help! cc @alzimmermsft / @srnagar - does Rev API makes sense on spring cosmos SDK ? It is also being done on other spring SDKs / connectors in our repo? If yes, why was this not caught in their CIs ?

@kushagraThapar This PR, https://github.com/Azure/azure-sdk-for-java/pull/27416 may help fix the pipeline, please review and merge, thanks.

**Pull request merged**
