### PR TITLE
[TA] Disable regression tests to keep live test green

### PR DESCRIPTION
**Pull request by mssfang**
Created an issue to track the regression test service bugs: https://github.com/Azure/azure-sdk-for-java/issues/28625

### CODE REVIEW

**Review by samvaity — APPROVED** [review]
looks good. It would be good to take a tentative To be fixed by date.

**Comment by mssfang** [comment]
> looks good. It would be good to take a tentative To be fixed by date.
Yeah. The service team is working on the 2022-05-01 version. It is still uncertianty.

**Pull request merged**
