### PR TITLE
External dependencies upgrade - Spring Boot 2.7.17 and Spring Cloud 2021.0.8

### PR DESCRIPTION
**Pull request by Netyyyy**
Updates external dependencies to align with Spring Boot version [2.7.17](https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-dependencies/2.7.17/spring-boot-dependencies-2.7.17.pom) from [2.7.16](https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-dependencies/2.7.16/spring-boot-dependencies-2.7.16.pom) and Spring Cloud version [2021.0.8](https://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-dependencies/2021.0.8/spring-cloud-dependencies-2021.0.8.pom) from [2021.0.8](https://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-dependencies/2021.0.8/spring-cloud-dependencies-2021.0.8.pom).
<details><summary>Release notes</summary><p><em>Sourced from <a href='https://github.com/spring-projects/spring-boot/releases/tag/v2.7.17'>spring-boot releases</a>.</em></p><h4> <g-emoji class="g-emoji" alias="warning">  ⚠️ </g-emoji> Noteworthy Changes</h4><ul> <li>The behavior of <code>spring.jms.listener.concurrency</code> has been corrected to match the documentation (<a href="https://github.com/spring-projects/spring-boot/pull/37180" data-hovercard-type="pull_request" data-hovercard-url="/spring-projects/spring-boot/pull/37180/hovercard">#37180</a>). If you were setting <code>spring.jms.listener.concurrency</code> without also setting <code>spring.jms.listener.max-concurrency</code>, please review your configuration when upgrading.</li></ul><h4>🐞 Bug Fixes</h4><ul> <li><code>@Order</code> does not work on (CommandLine|Application)Runner <code>@Bean</code> methods <a href="https://github.com/spring-projects/spring-boot/pull/37905" data-hovercard-type="pull_request" data-hovercard-url="/spring-projects/spring-boot/pull/37905/hovercard">#37905</a></li> <li>Gradle plugin uses to-be-deprecated API for getting and setting file permissions <a href="https://github.com/spring-projects/spring-boot/issues/37878" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/37878/hovercard">#37878</a></li> <li>Task executor metrics are not registered when using lazy initialization <a href="https://github.com/spring-projects/spring-boot/issues/37832" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/37832/hovercard">#37832</a></li> <li>Constructor binding with a custom collection type does not work <a href="https://github.com/spring-projects/spring-boot/issues/37734" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/37734/hovercard">#37734</a></li> <li>Dependency management for kafka-server-common with a test classifier is missing <a href="https://github.com/spring-projects/spring-boot/issues/37499" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/37499/hovercard">#37499</a></li> <li>fileMode and dirMode are not applied to all entries in an archive produced by BootJar <a href="https://github.com/spring-projects/spring-boot/issues/37496" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/37496/hovercard">#37496</a></li> <li>Gradle plugin's build info support produces a deprecation warning when using Gradle 8.4-rc-1 <a href="https://github.com/spring-projects/spring-boot/issues/37493" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/37493/hovercard">#37493</a></li> <li>RepackageMojo doesn't support 1 digit numerical values for project.build.outputTimestamp <a href="https://github.com/spring-projects/spring-boot/pull/37438" data-hovercard-type="pull_request" data-hovercard-url="/spring-projects/spring-boot/pull/37438/hovercard">#37438</a></li> <li>Restarter creates memory leak in tests <a href="https://github.com/spring-projects/spring-boot/issues/37373" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/37373/hovercard">#37373</a></li> <li>Contrary to the documentation, setting spring.jms.listener.concurrency alone configures the maximum concurrency <a href="https://github.com/spring-projects/spring-boot/pull/37180" data-hovercard-type="pull_request" data-hovercard-url="/spring-projects/spring-boot/pull/37180/hovercard">#37180</a></li> <li>Application fails to start when an optional config import cannot be resolved <a href="https://github.com/spring-projects/spring-boot/issues/35683" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/35683/hovercard">#35683</a></li> <li><code>@ComponentScan</code> on a test class is processed when creating a test context but is not included in the context's cache key <a href="https://github.com/spring-projects/spring-boot/issues/31577" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/31577/hovercard">#31577</a></li> <li>AspectJ transaction management with compile-time weaving does not work with spring.main.lazy-initialization=true <a href="https://github.com/spring-projects/spring-boot/issues/37506" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/37506/hovercard">#37506</a></li></ul><h4>📔 Documentation</h4><ul> <li>Remove link to LiveReload website due to timeout <a href="https://github.com/spring-projects/spring-boot/pull/37643" data-hovercard-type="pull_request" data-hovercard-url="/spring-projects/spring-boot/pull/37643/hovercard">#37643</a></li> <li>Refer to ActiveMQ as ActiveMQ "Classic" <a href="https://github.com/spring-projects/spring-boot/pull/37606" data-hovercard-type="pull_request" data-hovercard-url="/spring-projects/spring-boot/pull/37606/hovercard">#37606</a></li> <li>Use more idiomatic Kotlin in example for "Map Health Indicators to Micrometer Metrics" <a href="https://github.com/spring-projects/spring-boot/pull/37491" data-hovercard-type="pull_request" data-hovercard-url="/spring-projects/spring-boot/pull/37491/hovercard">#37491</a></li> <li>Document support for Java 21 <a href="https://github.com/spring-projects/spring-boot/issues/37371" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/37371/hovercard">#37371</a></li></ul><h4>🔨 Dependency Upgrades</h4><ul> <li>Upgrade to Dropwizard Metrics 4.2.21 <a href="https://github.com/spring-projects/spring-boot/issues/37893" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/37893/hovercard">#37893</a></li> <li>Upgrade to Elasticsearch 7.17.14 <a href="https://github.com/spring-projects/spring-boot/issues/37840" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/37840/hovercard">#37840</a></li> <li>Upgrade to Infinispan 13.0.20.Final <a href="https://github.com/spring-projects/spring-boot/issues/37841" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/37841/hovercard">#37841</a></li> <li>Upgrade to Jetty 9.4.53.v20231009 <a href="https://github.com/spring-projects/spring-boot/issues/37842" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/37842/hovercard">#37842</a></li> <li>Upgrade to Jetty Reactive HTTPClient 1.1.15 <a href="https://github.com/spring-projects/spring-boot/issues/37927" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/37927/hovercard">#37927</a></li> <li>Upgrade to Micrometer 1.9.16 <a href="https://github.com/spring-projects/spring-boot/issues/37674" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/37674/hovercard">#37674</a></li> <li>Upgrade to Netty 4.1.100.Final <a href="https://github.com/spring-projects/spring-boot/issues/37843" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/37843/hovercard">#37843</a></li> <li>Upgrade to Pooled JMS 1.2.5 <a href="https://github.com/spring-projects/spring-boot/issues/37894" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/37894/hovercard">#37894</a></li> <li>Upgrade to Reactor Bom 2020.0.37 <a href="https://github.com/spring-projects/spring-boot/issues/37675" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/37675/hovercard">#37675</a></li> <li>Upgrade to Spring AMQP 2.4.17 <a href="https://github.com/spring-projects/spring-boot/issues/37676" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/37676/hovercard">#37676</a></li> <li>Upgrade to Spring Data Bom 2021.2.17 <a href="https://github.com/spring-projects/spring-boot/issues/37677" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/37677/hovercard">#37677</a></li> <li>Upgrade to Spring Session Bom 2021.2.3 <a href="https://github.com/spring-projects/spring-boot/issues/37928" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/37928/hovercard">#37928</a></li> <li>Upgrade to Tomcat 9.0.82 <a href="https://github.com/spring-projects/spring-boot/issues/37895" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/37895/hovercard">#37895</a></li> <li>Upgrade to UnboundID LDAPSDK 6.0.10 <a href="https://github.com/spring-projects/spring-boot/issues/37753" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/37753/hovercard">#37753</a></li> <li>Upgrade to Undertow 2.2.28.Final <a href="https://github.com/spring-projects/spring-boot/issues/37929" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/37929/hovercard">#37929</a></li></ul><h4>❤️ Contributors</h4><p>Thank you to all the contributors who worked on this release:</p><p><a class="user-mention notranslate" data-hovercard-type="user" data-hovercard-url="/users/bottlerocketjonny/hovercard" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="https://github.com/bottlerocketjonny">@bottlerocketjonny</a>, <a class="user-mention notranslate" data-hovercard-type="organization" data-hovercard-url="/orgs/dependabot/hovercard" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="https://github.com/dependabot">@dependabot</a>[bot], <a class="user-mention notranslate" data-hovercard-type="user" data-hovercard-url="/users/erichaagdev/hovercard" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="https://github.com/erichaagdev">@erichaagdev</a>, <a class="user-mention notranslate" data-hovercard-type="user" data-hovercard-url="/users/esperar/hovercard" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="https://github.com/esperar">@esperar</a>, <a class="user-mention notranslate" data-hovercard-type="user" data-hovercard-url="/users/izeye/hovercard" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="https://github.com/izeye">@izeye</a>, <a class="user-mention notranslate" data-hovercard-type="user" data-hovercard-url="/users/jbertram/hovercard" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="https://github.com/jbertram">@jbertram</a>, <a class="user-mention notranslate" data-hovercard-type="user" data-hovercard-url="/users/nielsbasjes/hovercard" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="https://github.com/nielsbasjes">@nielsbasjes</a>, <a class="user-mention notranslate" data-hovercard-type="user" data-hovercard-url="/users/onobc/hovercard" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="https://github.com/onobc">@onobc</a>, <a class="user-mention notranslate" data-hovercard-type="user" data-hovercard-url="/users/ttddyy/hovercard" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="https://github.com/ttddyy">@ttddyy</a>, and <a class="user-mention notranslate" data-hovercard-type="user" data-hovercard-url="/users/vpavic/hovercard" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="https://github.com/vpavic">@vpavic</a></p></details>

This PR is created by GitHub Actions: https://github.com/Azure/spring-cloud-azure-tools/actions/runs/6661194920

### CODE REVIEW

**Comment by Netyyyy** [comment]
@alzimmermsft , please help take a look, thanks

**Review by alzimmermsft — APPROVED** [review]

**Pull request merged**
