### PR TITLE
Renames com.azure.azconfig -> com.azure.applicationconfig

### PR DESCRIPTION
**Pull request by conniey**
* Renames the package to com.azure.applicationconfig
* Moves files into correct directory structure.

Related to work for #3011

### CODE REVIEW

**Comment by conniey** [comment]
> Looks fine. You'll move out of the azconfig main directory at some point too?

Move to applicationconfig directory? I'll do it in this PR. File renames are often annoying to merge.

**Comment by JonathanGiles** [comment]
What are your thoughts about hyphenation? In packages we would definitely have no hyphenation, etc - but I wonder what we should do about the 'home' directory - should we be consistent with package name, or should we improve readability with 'application-config'?

**Comment by conniey** [comment]
> should we improve readability with 'application-config'?

application-config looks great to me. :)

**Comment by JonathanGiles** [comment]
Lets discuss offline sometime - I'm sitting firmly on the fence :-)

**Pull request merged**
