### PR TITLE
Adding reactor netty timeline to query plan calls

### PR DESCRIPTION
**Pull request by simplynaveen20**
This PR contains two items
1. Adding reactor netty timeline to query plan calls
2. Adding reactor netty timeline to existing gateway call diagnostics for  network failed request (to diff between connection error vs timeouts)

Below is the first call (no warm up) Reactor is taking most of the time initially 
image

Once sdk is warmed up  
image

### CODE REVIEW

**Review by moderakh — COMMENTED** [review]
Couple of notes we discussed on the teams chat:

1) Hey Naveen in the graph attached the PR, the QueryPlan seems to take 498ms but looking the the timeline and summing up the stages I see total of 13ms. Do we know where the rest of 498-13ms is spent?
https://user-images.githubusercontent.com/43345335/124816047-0a5c9600-df36-11eb-99e6-bc716b678cfe.png

2) in the request-timeline for GW: for `connectionCreated` stage I suspect we are not capturing the e2e connection establishment time. establishing a new connections requires SSL handshaking which normally takes 100ms or more, but the time captured here is 2ms. (maybe the connection already exists and we are acquiring it from a connection pool?)
it seems in some scenarios we may capture the time for acquiring an existing connection from connection pool. maybe `connectionAcquired` would be a better name.

**Comment by simplynaveen20** [comment]
> Couple of notes we discussed on the teams chat:
> 
> 1. Hey Naveen in the graph attached the PR, the QueryPlan seems to take 498ms but looking the the timeline and summing up the stages I see total of 13ms. Do we know where the rest of 498-13ms is spent?
>    https://user-images.githubusercontent.com/43345335/124816047-0a5c9600-df36-11eb-99e6-bc716b678cfe.png

Reactor is taking time in chaining during warm up initial calls

> 2. in the request-timeline for GW: for `connectionCreated` stage I suspect we are not capturing the e2e connection establishment time. establishing a new connections requires SSL handshaking which normally takes 100ms or more, but the time captured here is 2ms. (maybe the connection already exists and we are acquiring it from a connection pool?)
>    it seems in some scenarios we may capture the time for acquiring an existing connection from connection pool. maybe `connectionAcquired` would be a better name.

Decouple the connection created and connection acquired in new iteration

**Comment by simplynaveen20** [comment]
Discussed with in the team , we will go with timeline , and when if any ICM comes around this , we will see how many requests have high reactor chaining time

**Review by kushagraThapar — APPROVED** [review]

**Review by moderakh — APPROVED** [review]
PR looks good high level.

We need to understand why in some scenarios the end to end query plan time doesn't match with the sum of the time from the timeline.

> Reactor is taking time in chaining during warm up initial calls

reactor chaining when io is not involved should be very fast. are you referring to io operation chaining in reactor-netty?

we should try to understand why this the case, feel free to do the further investigation after this PR.

I am signing off but please get sign off from others as well.

**Comment by simplynaveen20** [comment]
> PR looks good high level.
> 
> We need to understand why in some scenarios the end to end query plan time doesn't match with the sum of the time from the timeline.
> 
> > Reactor is taking time in chaining during warm up initial calls
> 
> reactor chaining when io is not involved should be very fast. are you referring to io operation chaining in reactor-netty?
> 
> we should try to understand why this the case, feel free to do the further investigation after this PR.
> 
> I am signing off but please get sign off from others as well.

Query plan call use two classes QueryPlanRetriever, PartitionedQueryExecutionInfo, which reactor have to load for the first time to do the chaining. If we do eager loading of these classes before the query call, we no longer see the issue on the first request.

**Pull request merged**
