### PR TITLE
[Storage] Use BinaryData.toBuffer in blobs SDK to avoid array copy

### PR DESCRIPTION
**Pull request by kasobol-msft**
resolves https://github.com/Azure/azure-sdk-for-java/issues/19799

### CODE REVIEW

**Review by alzimmermsft — APPROVED** [review]
Where these all the locations where `BinaryData` is being used? I thought Queues was using it as well?

**Comment by kasobol-msft** [comment]
> Were these all the locations where `BinaryData` is being used? I thought Queues was using it as well?

I did search sdk/storage directory. The usage in Queues is slightly different as target type there is string.

**Pull request merged**
