### PR TITLE
Merge Spring December release branch to main

### PR DESCRIPTION
**Pull request by yiliuTo**
As subject.

### CODE REVIEW

**Review by saragluna — APPROVED** [review]
LGTM.

**Comment by yiliuTo** [comment]
cc @alzimmermsft and @srnagar , due to pr #26331 ,  the compilation of source code is now skipped in the stage of **Run SpotBugs, Checkstyle, RevApi, and Javadoc**, and it causes that the maven shade plugin uses the source jar built in the last job to shade external libraries' code into, which has already get shaded, thus we will get the error of https://dev.azure.com/azure-sdk/public/_build/results?buildId=1283989&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=ba3cf43a-b2bf-50f9-f95f-93049ca44ad1.

 To fix it, we want to modify the pipeline parameter of **Run SpotBugs, Checkstyle, RevApi, and Javadoc** by adding a parameter to disable the maven-shade-plugin for keyvault ci, and for other pipelines, that value is blank by default.

**Comment by alzimmermsft** [comment]
> 

Thank you for submitting the fix! I'm wondering if longer term the step should be updated to be similar to the testing step where it targets specific plugins instead of the lifecycle phase (`surefire:test` vs `test` and `checkstyle:check spotbugs:check ...` vs `verify`). It'll mean more maintenance for the pipeline jobs when we add new functionality (fairly rare) but will ensure consistence in jobs when new functionality is added (adding a new plugin won't result in additional work running).

@srnagar - what are your thoughts?

**Pull request merged**
