### PR TITLE
Use client property to determine track 1 or track 2 CI pipeline to run

### PR DESCRIPTION
**Pull request by srnagar**
Previously, in Event Hubs `pom.service.xml`, `data` property was used to determine if track 1 or track 2 pipeline to run. But `data` was not the right value to check and this cause both tracks to build when there were changes in sdk/eventhubs.

### CODE REVIEW

**Comment by alzimmermsft** [comment]
@mitchdenny does the pipelines set environment or JDK properties based on the commit type?

**Comment by danieljurek** [comment]
Pipelines have the following variables defined in them by default: 
java - keyvault - ci -- `SDKTYPE=client` 
java - keyvault - ci.data -- `SDKTYPE=client`
java - eventhubs - ci -- `SDKTYPE=client` 
java - eventhubs - ci.data -- `SDKTYPE=data`

**Comment by srnagar** [comment]
@danieljurek interesting!
I was expecting the following:
java - keyvault - ci -- SDKTYPE=client
java - keyvault - ci.data -- SDKTYPE=data
java - eventhubs - ci -- SDKTYPE=client
java - eventhubs - ci.data -- SDKTYPE=data

**Comment by danieljurek** [comment]
> @danieljurek interesting!
> I was expecting the following:
> java - keyvault - ci -- SDKTYPE=client
> java - keyvault - ci.data -- SDKTYPE=data
> java - eventhubs - ci -- SDKTYPE=client
> java - eventhubs - ci.data -- SDKTYPE=data

@srnagar  -- oops yours is correct. I had the tabs in the wrong order for KV ci.data

**Comment by danieljurek** [comment]
@mitchdenny -- Would you let us know if this is a correct read of the reasoning behind this change. 

@srnagar upon deeper review of some documentation the `!` means "not" in the value position which, I think effectively defines client as the default when running a build command without any environment variable set. It may be better to keep the default so the build will produce something if no environment variable is given. https://maven.apache.org/guides/introduction/introduction-to-profiles.html (see the 6th and 7th examples in the "Details on profile activation" section)

**Comment by srnagar** [comment]
No longer relevant as the service pom uses a different mechanism now to determine track 1 vs track 2.. Closing this PR.

**Pull request closed without merging**
