### PR TITLE
Remove prohibited java package in java.com.azure.cosmos.test

### PR DESCRIPTION
**Pull request by lmolkova**

### CODE REVIEW

**Comment by lmolkova** [comment]
pipeline (green) https://dev.azure.com/azure-sdk/public/_build/results?buildId=2627384&view=logs&j=8213c06b-ec82-5e45-560c-352e1c4b1152&t=ff704854-d1a8-5227-9cf3-6dc8b172d111

**Review by xinlian12 — APPROVED** [review]
LGTM, thanks

**Pull request merged**
