### PR TITLE
Eventhubs java

### PR DESCRIPTION
**Pull request by mssfang**
This is pure source code from Eventhubs repo

### CODE REVIEW

**Comment by JonathanGiles** [comment]
@weshaggard Would appreciate you giving this a second +1 before merging, once you are back in the office. I'm assured that this is nothing more than a copy / paste of revision history with no changes or integration into our systems and processes. That will come in a follow-up PR.

**Comment by weshaggard** [comment]
Is there any particular reason we feel like we should merge the commit history first and then do the integration into the repo? While I'm not necessarily opposed to it I don't see much value in doing this way as we should be able to clean a lot of this up and get it working in our build in another commit but in the same PR. 

Also keep in mind that while it might not be included in our builds yet there are analysis tools like component governance that run on the raw sources and might start flagging that in our internal builds.

**Comment by JonathanGiles** [comment]
I like the ability to review a pull request with the integration changes applied. Merging them into this pull request makes it harder to do that, and has in the past made people uneasy about what other changes might have been applied. I know it is possible to review commit by commit, but in my experience so far the transition into our repo had been performed over many commits, making reviewing more difficult than ideal.

I don't strongly prefer doing it this way, but it does seem to make things easier.

**Comment by mssfang** [comment]
As I know, there will be three seperate PR;
1) clean source code without any changes [this PR].
2) source code with the neccessary code and pom changes by following "Adding Track One Components" doc
3) there is a ongoing PR in another repo, but has a small change in this repo to corresponding the changes. 

With 1) clean code PR,  the 2) will be easier to show the diff made.

**Comment by weshaggard** [comment]
I agree you would have to review commit-by-commit which can make it kind of difficult to see the exact changes but still doable. I'm OK with this approach as long as we have clear work items slated to clean-up the stuff we are bringing in. I don't want all these merges to cause us to have a lot of dead files (i.e. all the various github templates, other CI yml files, other .gitattribute files, etc) and ideally we wouldn't have any git source history for them either but as long as they get cleaned out in a follow-up I live with that.

**Comment by mayurid** [comment]
I agree @weshaggard. We will create the items. We also have a step 1.5 or 2.5 where we make this code checkstyles and spot bugs clean to meet the overall repo guidelines.

**Comment by JonathanGiles** [comment]
Thanks. I'll assume we can now get your approval here and for storage?

**Comment by mssfang** [comment]
Following issue filed;

Eventhubs: Integrate event hubs into azure-sdk-for-java repo #3065

**Pull request merged**
