### PR TITLE
Change folder structure to better separate generated code.

### PR DESCRIPTION
**Pull request by azabbasi**
image

### CODE REVIEW

**Comment by azabbasi** [comment]
> I see models twice in your snapshot?

yes, the one you see at the root will be the folder we use for overriding models.

**Comment by azabbasi** [comment]
> > I see models twice in your snapshot?
> 
> yes, the one you see at the root will be the folder we use for overriding models.

https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/formrecognizer/azure-ai-formrecognizer/src/main/java/com/azure/ai/formrecognizer
as an example.

**Comment by azabbasi** [comment]
> We seem to have lost some Query specific files, are they a part of some other files now?

Are you talking about the QueriesImpl file?

**Comment by azabbasi** [comment]
image

**Comment by abhipsaMisra** [comment]
> > We seem to have lost some Query specific files, are they a part of some other files now?
> 
> Are you talking about the QueriesImpl file?

Yeah, the refactoring is probably not showing up properly on GitHub.  It listed a couple of query files as deleted (instead of moved), so that threw me off. The files look good.

**Pull request merged**
