### PR TITLE
Cleanup Swagger Transforms and Customizations in Azure Storage

### PR DESCRIPTION
**Pull request by alzimmermsft**
# Description

~~This PR takes advantage of a new change in AutoRest which uses `JacksonXmlElementWrapper` instead of a private inner class when dealing with XML element list wrapper nodes. The change better leverages capabilities of Jackson while also giving Jackson more insight into how to properly handle deserialization and serialization of the wrapped property list.~~

_The above was found to have too many edge cases and was rolled back._

Additionally, this PR also cleans up a bad Swagger transform pattern of using `.xml = {"name": "value"}` when renaming model types. This was being done to fix the `JacksonXmlRootElement` name for renamed models as the value for it changed from what was defined in Swagger to the renamed model (for example renaming `Metrics` to `BlobMetrics` changed the annotation value from `Metrics` to `BlobMetrics`). But this fundamentally changes how modelerfour and AutoRest consume the model as the XML takes precedence over the property name defined in the Swagger model and forced other transforms to be used to resolve it (for example when setting `BlobMetrics` XML name to `Metrics` all references of `BlobMetrics` would use `Metrics` as the serialization name). All locations where XML name could be removed have been, there is a follow-up needed for `SignedIdentifier` in both Files and Queues as Blobs `SignedIdentifier` has an XML name while Files and Queues do not in their Swagger, this resulted in a runtime exception in AutoRest (to be determined if it is a Swagger change or AutoRest change).

Lastly, this PR also makes a convenience change to how the Storage libraries use AutoRest code customizations. Previously, they were using a compiled JAR file to perform customizations but I learned that if the JAR isn't present customizations aren't performed and yet worse regenerated code isn't written to disk. So, this PR has additional changes to the customizations being used and to the implementation interfaces as [this PR](https://github.com/Azure/azure-sdk-for-java/pull/25741) never wrote its changes to disk. Now instead the Storage libraries reference a Java source code file containing the code customizations which AutoRest loads and compiles before running the customizations in it, this more eagerly throws exceptions preventing cases where it appeared regeneration occurred when it didn't.

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](../../CONTRIBUTING.md#building-and-unit-testing)
- [x] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Review by rickle-msft — APPROVED** [review]

**Comment by alzimmermsft** [comment]
Live tests were failing with existing, known errors

**Pull request merged**
