### PR TITLE
Added VM extension tests

### PR DESCRIPTION
**Pull request by khoatle**
Added VM Extension Test with a couple of fixes:
- **Line 27 of NetworkHelper**

``` java
PublicIpAddress publicIpParams = new PublicIpAddress(context.getLocation(), IpAllocationMethod.DYNAMIC);
```

The order of the params should be

``` java
 PublicIpAddress publicIpParams = new PublicIpAddress(IpAllocationMethod.DYNAMIC, context.getLocation());
```
- **Adding tests for VMExtensions**
- **Modified VirtualMachineExtensionOperationsImpl settings.getTextValue -> settings.toString()**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@khoale-azure__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by ljhljh235** [comment]
@matt-gibbs Khoa works in Microsoft, I don't think CLA is required?

**Comment by ljhljh235** [comment]
Cortana add to whitelist

**Comment by ljhljh235** [comment]
Hi Khoa,

We will ignore the CLA prompt for now. 

Other than that, a test failure is failing. The test report is here: http://azuresdkci.cloudapp.net/job/sdk-for-java/4/testReport/. Please address.

Thanks!

**Pull request closed without merging**
