### PR TITLE
enhance idle-timeout property

### PR DESCRIPTION
**Pull request by yiliuTo**
# Description

Resolves https://github.com/Azure/azure-sdk-for-java/issues/32036
Change the default value of `spring.jms.servicebus.idle-timeout` from 30min to 2min accourding to [the doc](https://learn.microsoft.com/azure/service-bus-messaging/service-bus-amqp-troubleshoot#link-is-not-created). And the value should be 2 min instead of 1 min because [Proton J will half it](https://github.com/apache/qpid-proton-j/blob/754d40e2a2e58aab7a252d933daef6d572f9f508/proton-j/src/main/java/org/apache/qpid/proton/engine/impl/TransportImpl.java#L925) to follow [AMQP specs](http://docs.oasis-open.org/amqp/core/v1.0/os/amqp-core-transport-v1.0-os.html#doc-doc-idle-time-out). And service bus will send the heartbeats within 1 minute.

# All SDK Contribution checklist:
- [ ] **The pull request does not introduce [breaking changes]**
- [x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [ ] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Review by backwind1233 — APPROVED** [review]
LGTM

**Comment by backwind1233** [comment]
Do you think we should also change the value in the reference [doc](https://microsoft.github.io/spring-cloud-azure/current/reference/html/appendix.html##configuration-properties)?

**Comment by yiliuTo** [comment]
Will the property part of our ref doc be generated/updated automically according to the code? I know that it's true for our MS [DOC](https://learn.microsoft.com/azure/developer/java/spring-framework/configuration-properties-azure-service-bus-jms).

**Comment by saragluna** [comment]
Any linked issue?

**Comment by yiliuTo** [comment]
resolves https://github.com/Azure/azure-sdk-for-java/issues/32036

**Review by saragluna — APPROVED** [review]

**Pull request merged**
