### PR TITLE
Build and test with Java 17

### PR DESCRIPTION
**Pull request by mikeharder**
Draft PR to start building and testing with Java 17

### Latest builds
* `java - core - ci`: https://dev.azure.com/azure-sdk/public/_build/results?buildId=1322669&view=results
  * Test failure: `[ERROR] Test mechanism :: Unable to make protected native java.lang.Object java.lang.Object.clone() throws java.lang.CloneNotSupportedException accessible: module java.base does not "opens java.lang" to unnamed module`
* `java - storage - ci`: https://dev.azure.com/azure-sdk/public/_build/results?buildId=1322694&view=results

### Issues - Open
* JavaDoc fails
  * Workaround: Disable JavaDoc for now

### Issues - Closed
* JDK 17 missing from Azure Pipelines Ubuntu images
  * Issues
    * https://github.com/actions/virtual-environments/issues/4085
    * https://github.com/adoptium/installer/issues/330
  * Workaround: Manually install JDK 17
  * Pipeline to detect when JDK 17 is available: https://dev.azure.com/azure-sdk/playground/_build?definitionId=3068
* Storage tests fail to compile
  * Issue: https://github.com/Azure/azure-sdk-for-java/issues/6551
* SpotBugs error "java.lang.IllegalArgumentException: Unsupported class file major version 61"
  * Issue: https://github.com/Azure/azure-sdk-for-java/pull/24398
* Mockito cannot mock this class: interface com.azure.core.amqp.ClaimsBasedSecurityNode
  * Issue: https://github.com/Azure/azure-sdk-for-java/pull/24398

### CODE REVIEW

**Comment by JonathanGiles** [comment]
To fix the SpotBugs issue, we need to update the following lines in /eng/versioning/external_dependencies.txt:

```
com.github.spotbugs:spotbugs;4.4.1
com.github.spotbugs:spotbugs-annotations;4.4.1
com.github.spotbugs:spotbugs-maven-plugin;4.4.1
```

**Comment by JonathanGiles** [comment]
To fix the Mockito issue, we need to update the following lines in /eng/versioning/external_dependencies.txt:

```
org.powermock:powermock-api-mockito2;2.0.9
org.powermock:powermock-module-junit4;2.0.9

org.mockito:mockito-core;3.12.4
org.mockito:mockito-inline;3.12.4
```

**Comment by JonathanGiles** [comment]
I am investigating the JavaDoc issue currently. It relates to our codesnippet doclet so my work is taking place in a [separate repository](https://github.com/jtulach/codesnippet4javadoc/pull/26).

**Comment by mikeharder** [comment]
> /azp run java - storage - ci

@kasobol-msft: Manual run: https://dev.azure.com/azure-sdk/public/_build/results?buildId=1124806&view=results

**Comment by mikeharder** [comment]
Closing in favor of https://github.com/Azure/azure-sdk-for-java/pull/26482

**Pull request closed without merging**
