### PR TITLE
openai assistants, hide the uploadFile overload of filename argument

### PR DESCRIPTION
**Pull request by weidongxu-microsoft**
# Description

I don't think `filename` argument should be exposed to user.

See https://github.com/Azure/azure-rest-api-specs/blob/main/specification/ai/OpenAI.Assistants/files/routes.tsp#L48-L55

`filename` of the file is set via `FileDetails` class.

Service throws if one calls it `client.uploadFile(fileDetails, FilePurpose.ASSISTANTS, "retrieval_sample_java_sdk.txt");`
```
Exception in thread "main" com.azure.core.exception.HttpResponseException: Status code 400, "{
  "error": {
    "message": "Additional properties are not allowed ('filename' was unexpected)",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}
"
```

If one really want to take the `filename` from method argument, it should be set to the 3rd param on this line
https://github.com/Azure/azure-sdk-for-java/blob/ebe037f13c6b203659fdc0c672f1e984a7c05b58/sdk/openai/azure-ai-openai-assistants/src/main/java/com/azure/ai/openai/assistants/AssistantsClient.java#L2955-L2956

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [ ] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [ ] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Comment by weidongxu-microsoft** [comment]
Seems I failed to catch beta.1 release

The preferred solution is actually remove the `filename` in typespec source.

We can close this PR if decide to fix typespec source.

**Comment by mssfang** [comment]
Thank you Weidong for catching this.

For current cross language API consistency, it is better to stay with same API which explored the fileName.

**Comment by weidongxu-microsoft** [comment]
Then we may better to modify the impl of this API as following:

```diff
    @ServiceMethod(returns = ReturnType.SINGLE)
    public OpenAIFile uploadFile(FileDetails file, FilePurpose purpose, String filename) {
        // Generated convenience method for uploadFileWithResponse
        RequestOptions requestOptions = new RequestOptions();
        UploadFileRequest requestObj = new UploadFileRequest(file, purpose).setFilename(filename);
        BinaryData request = new MultipartFormDataHelper(requestOptions)
            .serializeFileField("file", requestObj.getFile().getContent(), requestObj.getFile().getContentType(),
-                requestObj.getFile().getFilename())
+                filename != null ? filename : requestObj.getFile().getFilename())
            .serializeTextField("purpose", Objects.toString(requestObj.getPurpose()))
-            .serializeTextField("filename", requestObj.getFilename()).end().getRequestBody();
+            .end().getRequestBody();
        return uploadFileWithResponse(request, requestOptions).getValue().toObject(OpenAIFile.class);
    }
```

So that
1. we set this `filename` in method argument to the `file` field
2. we don't add the `filename` field, which is invalid and cause the error in PR description

**Review by mssfang — APPROVED** [review]

**Review by jpalvarezl — APPROVED** [review]
I've re-opened and approved the PR so we can address the scenario where we don't have a `filename` set in a way that's according to other languages.

**Pull request merged**
