### PR TITLE
Add support for Widevine (DRM) dynamic encryption to Azure Media Services SDK

### PR DESCRIPTION
**Pull request by mconverti**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@mconverti__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@mconverti__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by mconverti** [comment]
Hi guys, do you have any feedback about this pull request? If not, could you please merge it?

Thanks!
Mariano

**Comment by devigned** [comment]
@mconverti The build failed with the following:
>[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.11:check (validate) on project azure-media: Failed during checkstyle execution: There are 64 checkstyle errors. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :azure-media

**Comment by mconverti** [comment]
Thanks @devigned 

I just pushed the fixes for the checkstyle issues.

**Comment by jianghaolu** [comment]
Build passed.

@mingfeiy Could you have one of you devs review this? Thanks!

**Pull request merged**
