### PR TITLE
Update AsyncServiceClientCredentials to take HttpRequest

### PR DESCRIPTION
**Pull request by conniey**
* There are auth schemes that require more information than just the service url. Example is the HMAC-SHA256 that the Azure Application Configuration team requires for their service. This requires us to construct a string from HttpHeaders in addition to the service url.
* Makes a fix in .editorconfig where we were only checking for new-lines and trimming in *.md files rather than all files.

Pulling changes from: https://github.com/Azure/autorest-clientruntime-for-java/pull/593/

### CODE REVIEW

**Comment by anuchandy** [comment]
LGTM

**Comment by anuchandy** [comment]
Just one question, the changes in `.editorconfig`, is it expected?

**Comment by conniey** [comment]
@anuchandy Yes. I realised that because they were at the bottom, they were only applying to `[*.md]` files. I can create another PR for this if you want.

**Comment by anuchandy** [comment]
@conniey thanks for clarifying, that is a separate commit, so fine with having it in this PR. Between, it will be good to add small description about it in the PR description, just the way you did for Credential + HttpRequest. Just for future ref.

**Pull request merged**
