### PR TITLE
Fix tests not executed in pipeline

### PR DESCRIPTION
**Pull request by chenrujun**
1. Fix tests not executed in azure-spring-boot-test-aad
2. Fix tests not executed in azure-spring-boot-test-aad-b2c

### CODE REVIEW

**Comment by saragluna** [comment]
Why is junit5 required here?

**Comment by chenrujun** [comment]
@saragluna 

After upgrade to spring-boot:2.4.0, the default junit is junit-5.
If we want to use junit-4, we need to add extra dependencies: `junit-vintage-engine`. 
To make things simple and fit newest spring-boot, I prefer junit-5.

**Review by backwind1233 — APPROVED** [review]
LGTM

**Pull request merged**
