### PR TITLE
FixConcurrentModificationException

### PR DESCRIPTION
**Pull request by xinlian12**
**Exception:**
java.util.ConcurrentModificationException
at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1493)
at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1526)
at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1524)
at java.base/java.util.AbstractMap.toString(AbstractMap.java:551)
at com.azure.cosmos.CosmosException.toString(CosmosException.java:332)
at java.base/java.lang.Throwable.<init>(Throwable.java:316)
at java.base/java.lang.Exception.<init>(Exception.java:102)
at java.base/java.lang.RuntimeException.<init>(RuntimeException.java:96)
at java.base/java.util.concurrent.CompletionException.<init>(CompletionException.java:88)
at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:870)

**Possible root cause:**
CompletableFuture.uniWhenComplete --> CompletableFuture.encodeThrowable --> CosmosException.toString() --> responseHeaders.toString() 

the responseHeaders in cosmosException is HashMap which is not thread safe.
When customer using session consistency, and get 404, SDK currently will change the statusCode to 1002 so to retry several times, which will touch the responseHeaders. 

**Solution:**
Using ConcurrentHashMap instead

### CODE REVIEW

**Review by mbhaskar — APPROVED** [review]
LGTM. Thanks a lot for quick changes.
There might be a slight perf impact due to introduction of ConcurrentHashMap though but since it is called only during the Exception path, the impact should be very minimal?

**Comment by xinlian12** [comment]
> LGTM. Thanks a lot for quick changes.
> There might be a slight perf impact due to introduction of ConcurrentHashMap though but since it is called only during the Exception path, the impact should be very minimal?

yea, it will only impact when exception path, we can discuss more offline

**Review by FabianMeiswinkel — APPROVED** [review]
LGTM - Thanks for taking care of this reported bug so quickly!

**Review by kushagraThapar — APPROVED** [review]

**Comment by xinlian12** [comment]
The failed tests is clientTelemetryWithStageJunoEndpoint

Tested locally facing the same issue, merge this PR since it does not change anything relates to client telemetry.

**Pull request merged**
