### PR TITLE
Added spec location verification to batch release

### PR DESCRIPTION
**Pull request by raych1**
Java repo has two types of release pipeline, one is normal release pipeline, and the other is batch release pipeline.

The same verification had been added to the normal release pipeline, and this PR is to add it to the batch release pipeline.

See this PR for details of what does this verification do.
https://github.com/Azure/azure-sdk-for-java/pull/38332

### CODE REVIEW

**Comment by weidongxu-microsoft** [comment]
If release is under https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/storage

And only some package is to be released, e.g. `azure-storage-blob`.

Does validation only check `azure-storage-blob`?

**Comment by raych1** [comment]
> If release is under https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/storage
> 
> And only some package is to be released, e.g. `azure-storage-blob`.
> 
> Does validation only check `azure-storage-blob`?

@weidongxu-microsoft , the packages to be released are selected by the user when pipeline is triggered then they will be filtered in the pipeline definition [here](https://github.com/Azure/azure-sdk-for-java/blob/af1935918e196798eba415b168085c05600dd98a/eng/pipelines/templates/stages/archetype-sdk-client.yml#L150).

**Review by weidongxu-microsoft — APPROVED** [review]

**Comment by raych1** [comment]
@weshaggard , can you please review?

**Comment by weshaggard** [comment]
@raych1 do you have any test runs? I couldn't see one that ran this.

@JimSuplizio should this new validation check also be added to the non-batch template?

**Comment by raych1** [comment]
> @raych1 do you have any test runs? I couldn't see one that ran this.
> 
> @JimSuplizio should this new validation check also be added to the non-batch template?

@weshaggard , this is the [test run](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3446847&view=logs&j=da35a07f-f2a0-5802-21eb-2343f475d719&t=c1080606-1aa4-52f8-52f5-e1d077503625) of azure template package for Java. 
I added the step to download artifact, otherwise it would fail.

This validation check has already added to the non-batch release pipeline by below PR.
https://github.com/Azure/azure-sdk-for-java/pull/38332

**Comment by weshaggard** [comment]
@raych1 do you have any test runs of the non-batch check?

**Review by weshaggard — APPROVED** [review]
Looks reasonable once your testing is complete.

**Comment by raych1** [comment]
> Looks reasonable once your testing is complete.

Thanks @weshaggard , this is the [testing run](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3450054&view=logs&j=da35a07f-f2a0-5802-21eb-2343f475d719&t=6e22014a-2fb4-5726-310f-2720edf917e6) for non-batch release.

**Comment by raych1** [comment]
[Template package release pipeline run](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3450148&view=logs&j=da35a07f-f2a0-5802-21eb-2343f475d719&t=200eaffb-fa8a-548e-2017-e0460c4dd2a5) works fine after the merge.

**Pull request merged**
