### PR TITLE
External dependencies upgrade - Spring Boot 3.3.4 and Spring Cloud 2023.0.3

### PR DESCRIPTION
**Pull request by Netyyyy**
Updates external dependencies to align with Spring Boot version [3.3.4](https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-dependencies/3.3.4/spring-boot-dependencies-3.3.4.pom) from [3.3.3](https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-dependencies/3.3.3/spring-boot-dependencies-3.3.3.pom) and Spring Cloud version [2023.0.3](https://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-dependencies/2023.0.3/spring-cloud-dependencies-2023.0.3.pom) from [2023.0.3](https://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-dependencies/2023.0.3/spring-cloud-dependencies-2023.0.3.pom).
<details><summary>Release notes</summary><p><em>Sourced from <a href='https://github.com/spring-projects/spring-boot/releases/tag/v3.3.4'>spring-boot releases</a>.</em></p><h4>🐞 Bug Fixes</h4><ul> <li>management.health.db.ignore-routing-datasources=true has no effect when an AbstractRoutingDataSource has been wrapped <a href="https://github.com/spring-projects/spring-boot/issues/42322" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/42322/hovercard">#42322</a></li> <li>Missing details in OAuth2ClientProperties validation error message <a href="https://github.com/spring-projects/spring-boot/issues/42279" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/42279/hovercard">#42279</a></li> <li>FileNotFoundException from unused mis-configured SSL bundles <a href="https://github.com/spring-projects/spring-boot/issues/42169" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/42169/hovercard">#42169</a></li> <li>ZipkinHttpClientSender fails with "Failed to introspect Class" when spring-web is not on the classpath <a href="https://github.com/spring-projects/spring-boot/issues/42161" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/42161/hovercard">#42161</a></li> <li><code>@RestartScope</code> can cause 'Recursive update' exceptions when used with container beans <a href="https://github.com/spring-projects/spring-boot/issues/42107" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/42107/hovercard">#42107</a></li> <li>JarLauncher fails to load large jar files <a href="https://github.com/spring-projects/spring-boot/issues/42079" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/42079/hovercard">#42079</a></li> <li>PropertiesMigrationListener wrongly reports property as deprecated when has group <a href="https://github.com/spring-projects/spring-boot/issues/42071" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/42071/hovercard">#42071</a></li> <li>Using an empty string MongoDB 'replica-set-name' property will result in ClusterType=REPLICA_SET <a href="https://github.com/spring-projects/spring-boot/issues/42059" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/42059/hovercard">#42059</a></li> <li>Default Logback config uses deprecated "converterClass" attribute <a href="https://github.com/spring-projects/spring-boot/issues/42006" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/42006/hovercard">#42006</a></li></ul><h4>📔 Documentation</h4><ul> <li>Document that spring.jmx.enabled is not intended for third-party libraries <a href="https://github.com/spring-projects/spring-boot/issues/42285" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/42285/hovercard">#42285</a></li> <li>Update link to Log4j2 system properties <a href="https://github.com/spring-projects/spring-boot/issues/42263" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/42263/hovercard">#42263</a></li> <li>Links to GraphQL in the reference guide redirect to the root instead of specific sections <a href="https://github.com/spring-projects/spring-boot/issues/42208" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/42208/hovercard">#42208</a></li> <li>Syntax error in "Receive a message reactively section" of the reference guide <a href="https://github.com/spring-projects/spring-boot/issues/42200" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/42200/hovercard">#42200</a></li> <li>Deprecation reason for the autotime enabled, percentiles, and percentiles-historgram properties is confusing <a href="https://github.com/spring-projects/spring-boot/issues/42193" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/42193/hovercard">#42193</a></li> <li>Replace RFC 7807 by RFC 9457 in property documentation <a href="https://github.com/spring-projects/spring-boot/issues/42190" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/42190/hovercard">#42190</a></li> <li>Document that configuration property binding to a Kotlin value class with a default is not supported <a href="https://github.com/spring-projects/spring-boot/issues/42176" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/42176/hovercard">#42176</a></li> <li>Update documentation to reflect new no handler found exception behavior <a href="https://github.com/spring-projects/spring-boot/issues/42167" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/42167/hovercard">#42167</a></li> <li>Polish configuration property reference <a href="https://github.com/spring-projects/spring-boot/issues/42165" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/42165/hovercard">#42165</a></li> <li>Remove link to “Converting a Spring Boot JAR Application to a WAR” as the guide is no longer available <a href="https://github.com/spring-projects/spring-boot/issues/42111" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/42111/hovercard">#42111</a></li> <li>Fix StatsD link typo on Metrics documentation page <a href="https://github.com/spring-projects/spring-boot/pull/42109" data-hovercard-type="pull_request" data-hovercard-url="/spring-projects/spring-boot/pull/42109/hovercard">#42109</a></li> <li>Improve docker without buildpacks documentation <a href="https://github.com/spring-projects/spring-boot/issues/42106" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/42106/hovercard">#42106</a></li> <li>Improve documentation in "Command-line Completion" <a href="https://github.com/spring-projects/spring-boot/issues/42103" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/42103/hovercard">#42103</a></li> <li>Kotlin code examples are missing from the Testing section <a href="https://github.com/spring-projects/spring-boot/issues/42094" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/42094/hovercard">#42094</a></li> <li>Fix incorrect command in Docker configuration for Colima <a href="https://github.com/spring-projects/spring-boot/pull/42078" data-hovercard-type="pull_request" data-hovercard-url="/spring-projects/spring-boot/pull/42078/hovercard">#42078</a></li> <li>Gradle Plugin AOT documentation has sample error <a href="https://github.com/spring-projects/spring-boot/issues/42046" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/42046/hovercard">#42046</a></li></ul><h4>🔨 Dependency Upgrades</h4><ul> <li>Upgrade to Groovy 4.0.23 <a href="https://github.com/spring-projects/spring-boot/issues/42292" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/42292/hovercard">#42292</a></li> <li>Upgrade to Hibernate 6.5.3.Final <a href="https://github.com/spring-projects/spring-boot/issues/42365" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/42365/hovercard">#42365</a></li> <li>Upgrade to Infinispan 15.0.8.Final <a href="https://github.com/spring-projects/spring-boot/issues/42253" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/42253/hovercard">#42253</a></li> <li>Upgrade to Jakarta Servlet JSP JSTL 3.0.2 <a href="https://github.com/spring-projects/spring-boot/issues/42254" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/42254/hovercard">#42254</a></li> <li>Upgrade to Jetty 12.0.13 <a href="https://github.com/spring-projects/spring-boot/issues/42256" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/42256/hovercard">#42256</a></li> <li>Upgrade to Jetty Reactive HTTPClient 4.0.7 <a href="https://github.com/spring-projects/spring-boot/issues/42255" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/42255/hovercard">#42255</a></li> <li>Upgrade to Logback 1.5.8 <a href="https://github.com/spring-projects/spring-boot/issues/42257" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/42257/hovercard">#42257</a></li> <li>Upgrade to Micrometer 1.13.4 <a href="https://github.com/spring-projects/spring-boot/issues/42129" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/42129/hovercard">#42129</a></li> <li>Upgrade to Micrometer Tracing 1.3.4 <a href="https://github.com/spring-projects/spring-boot/issues/42130" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/42130/hovercard">#42130</a></li> <li>Upgrade to MSSQL JDBC 12.6.4.jre11 <a href="https://github.com/spring-projects/spring-boot/issues/42258" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/42258/hovercard">#42258</a></li> <li>Upgrade to Native Build Tools Plugin 0.10.3 <a href="https://github.com/spring-projects/spring-boot/issues/42205" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/42205/hovercard">#42205</a></li> <li>Upgrade to Netty 4.1.113.Final <a href="https://github.com/spring-projects/spring-boot/issues/42259" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/42259/hovercard">#42259</a></li> <li>Upgrade to Postgresql 42.7.4 <a href="https://github.com/spring-projects/spring-boot/issues/42260" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/42260/hovercard">#42260</a></li> <li>Upgrade to R2DBC MariaDB 1.2.2 <a href="https://github.com/spring-projects/spring-boot/issues/42326" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/42326/hovercard">#42326</a></li> <li>Upgrade to Reactor Bom 2023.0.10 <a href="https://github.com/spring-projects/spring-boot/issues/42131" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/42131/hovercard">#42131</a></li> <li>Upgrade to SendGrid 4.10.3 <a href="https://github.com/spring-projects/spring-boot/issues/42366" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/42366/hovercard">#42366</a></li> <li>Upgrade to Spring Data Bom 2024.0.4 <a href="https://github.com/spring-projects/spring-boot/issues/42132" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/42132/hovercard">#42132</a></li> <li>Upgrade to Spring Framework 6.1.13 <a href="https://github.com/spring-projects/spring-boot/issues/42133" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/42133/hovercard">#42133</a></li> <li>Upgrade to Spring HATEOAS 2.3.3 <a href="https://github.com/spring-projects/spring-boot/issues/42282" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/42282/hovercard">#42282</a></li> <li>Upgrade to Spring Integration 6.3.4 <a href="https://github.com/spring-projects/spring-boot/issues/42134" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/42134/hovercard">#42134</a></li> <li>Upgrade to Spring Kafka 3.2.4 <a href="https://github.com/spring-projects/spring-boot/issues/42135" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/42135/hovercard">#42135</a></li> <li>Upgrade to Spring Pulsar 1.1.4 <a href="https://github.com/spring-projects/spring-boot/issues/42136" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/42136/hovercard">#42136</a></li> <li>Upgrade to Spring Retry 2.0.9 <a href="https://github.com/spring-projects/spring-boot/issues/42327" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/42327/hovercard">#42327</a></li> <li>Upgrade to Tomcat 10.1.30 <a href="https://github.com/spring-projects/spring-boot/issues/42346" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/42346/hovercard">#42346</a></li> <li>Upgrade to Undertow 2.3.17.Final <a href="https://github.com/spring-projects/spring-boot/issues/42303" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/42303/hovercard">#42303</a></li> <li>Upgrade to Zipkin Reporter 3.4.2 <a href="https://github.com/spring-projects/spring-boot/issues/42364" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/42364/hovercard">#42364</a></li></ul><h4>❤️ Contributors</h4><p>Thank you to all the contributors who worked on this release:</p><p><a class="user-mention notranslate" data-hovercard-type="user" data-hovercard-url="/users/Alchemik/hovercard" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="https://github.com/Alchemik">@Alchemik</a>, <a class="user-mention notranslate" data-hovercard-type="user" data-hovercard-url="/users/arefbehboudi/hovercard" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="https://github.com/arefbehboudi">@arefbehboudi</a>, <a class="user-mention notranslate" data-hovercard-type="user" data-hovercard-url="/users/einarpehrson/hovercard" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="https://github.com/einarpehrson">@einarpehrson</a>, <a class="user-mention notranslate" data-hovercard-type="user" data-hovercard-url="/users/izeye/hovercard" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="https://github.com/izeye">@izeye</a>, <a class="user-mention notranslate" data-hovercard-type="user" data-hovercard-url="/users/martinfrancois/hovercard" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="https://github.com/martinfrancois">@martinfrancois</a>, <a class="user-mention notranslate" data-hovercard-type="user" data-hovercard-url="/users/mushroom528/hovercard" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="https://github.com/mushroom528">@mushroom528</a>, <a class="user-mention notranslate" data-hovercard-type="user" data-hovercard-url="/users/nosan/hovercard" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="https://github.com/nosan">@nosan</a>, and <a class="user-mention notranslate" data-hovercard-type="user" data-hovercard-url="/users/quaff/hovercard" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="https://github.com/quaff">@quaff</a></p></details>

This PR is created by GitHub Actions: https://github.com/Azure/spring-cloud-azure-tools/actions/runs/10950878260

### CODE REVIEW

**Review by alzimmermsft — APPROVED** [review]

**Review by saragluna — APPROVED** [review]

**Comment by Netyyyy** [comment]
Hi @jeanbisutti , please help approve, thanks

**Review by jeanbisutti — APPROVED** [review]

**Comment by jeanbisutti** [comment]
> Hi @jeanbisutti , please help approve, thanks

@Netyyyy Done

**Pull request merged**
