### PR TITLE
Azure Media Services, support for Azure AD authentication

### PR DESCRIPTION
**Pull request by rnrneverdies**
# ChangeLog

- Update to Blob storage API version that supports 256MB PUT requests
- Add Azure Active Directory (Azure AD) Authentication
  - Service principal with symmetric key scenario
  - Service principal with certificate scenario
  - User credentials with username and password scenario
- Remove ACS Authentication
- Fix Streaming Endpoints error handling

### CODE REVIEW

**Comment by jianghaolu** [comment]
@azuresdkci test this please

**Comment by jianghaolu** [comment]
@azuresdkci retest this please

**Comment by jianghaolu** [comment]
@azuresdkci test this please

**Comment by jianghaolu** [comment]
Hi @rnrneverdies 
Apologize for getting back to you late! The PR looks great and almost passes CI except for a couple style errors. - Style errors like missing javadoc tags can prevent you from publishing to Maven. If you can run `mvn checkstyle:check` locally on media services and fix those issues, we can get this PR merged right away.

**Comment by rnrneverdies** [comment]
Hi @jianghaolu,
I didn't found any missing Javadoc but unwanted tab characters which were causing checkstyle to fail. I've replaced them with spaces so the build works well now. 
Let me know if you have additional feedback. 
Regards.

**Comment by jianghaolu** [comment]
Thanks @rnrneverdies - merging

**Pull request merged**
