### PR TITLE
Fix spring tests failed

### PR DESCRIPTION
**Pull request by Netyyyy**
Fixes spring tests [error](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2202204&view=results)

### CODE REVIEW

**Comment by Netyyyy** [comment]
Hi @mrm9084, app configuration tests [failed ](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2202204&view=logs&j=bb195619-05f5-5325-3d4d-9a84027ef4d6&t=b2026478-675c-5899-3d56-a4a9ca004e60&l=1821)in UsGov cloud, does it support for UsGov? please help take a look, thanks.

**Review by mrm9084 — APPROVED** [review]

**Comment by Netyyyy** [comment]
> Hi @mrm9084, app configuration tests [failed ](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2202204&view=logs&j=bb195619-05f5-5325-3d4d-9a84027ef4d6&t=b2026478-675c-5899-3d56-a4a9ca004e60&l=1821)in UsGov and China cloud, does it support for them? please help take a look, thanks.

Matt is working on the errors, so merge this PR to fix other errors

**Pull request merged**
