### PR TITLE
Fix spring builds with CHANGELOG

### PR DESCRIPTION
**Pull request by mitchdenny**
Due to a recent change in the ```azure-client-sdk-parent``` POM file we now need both a ```README.md``` and ```CHANGELOG.md``` file in each module directory. In the case of test modules that are not going to be released they'll just be static. Doing this is easier that complex properties to control the ```skipAttach``` property in the parent POM (and having both a ```README.md``` and ```CHANGELOG.md``` is not such a bad idea on a per-module basis).

### CODE REVIEW

**Comment by mitchdenny** [comment]
@Azure/azure-sdk-write-spring just a heads up that I am merging this in because it was the cause of some failed builds overnight.

**Comment by saragluna** [comment]
Thanks for adding these files. I also added these files in another PR yesterday since the build couldn't pass otherwise. Since that PR is approved now so I suggest we close this PR. https://github.com/Azure/azure-sdk-for-java/pull/12581.

**Comment by mitchdenny** [comment]
Thanks @saragluna  .... closing this one.

**Comment by saragluna** [comment]
Sorry for the late notice, I'll trigger the Spring live test pipeline against the master branch to see if it could pass now.

**Pull request closed without merging**
