### PR TITLE
Don't send ip range in tests.

### PR DESCRIPTION
**Pull request by kasobol-msft**
Some tests started to fail after we started to run tests in same region as storage account is. Looks like this is a case.

https://docs.microsoft.com/en-us/rest/api/storageservices/create-service-sas

image

The setSasIpRange is also covered in other tests that don't send requests.

### CODE REVIEW

**Review by alzimmermsft — APPROVED** [review]
Should the setters and getters for configuring the allowed IP ranges in SAS creation link to this documentation?

**Review by gapra-msft — APPROVED** [review]

**Pull request merged**
