### PR TITLE
Downgrade to nimbus-jose-jwt 8.20.2

### PR DESCRIPTION
**Pull request by chenrujun**
To keep external dependency's version same to [spring-boot-dependencies](https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-dependencies/2.4.4/spring-boot-dependencies-2.4.4.pom), downgrade to nimbus-jose-jwt 8.20.2

Related PR: https://github.com/spring-projects/spring-security/pull/9453

### CODE REVIEW

**Comment by alzimmermsft** [comment]
Do we know why Spring Boot downgraded this dependency? In [spring-boot-starter-parent 2.4.0](https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-parent/2.4.0) it was `9.1.2` but then later in [spring-boot-starter-parent 2.4.4](https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-parent/2.4.4) it was downgraded to `8.20.2`.

**Comment by chenrujun** [comment]
@alzimmermsft 

Refs:
1. https://github.com/spring-projects/spring-security/pull/9453
2. https://github.com/spring-projects/spring-security/issues/9399

**Comment by chenrujun** [comment]
Hi, @alzimmermsft , please approve this PR if you think it's OK to merge.

**Review by alzimmermsft — APPROVED** [review]

**Pull request merged**
