### PR TITLE
Add BOM information to the libraries readme files.

### PR DESCRIPTION
**Pull request by pallavit**

### CODE REVIEW

**Comment by pallavit** [comment]
@vcolin7 please review :)

**Review by vcolin7 — COMMENTED** [review]
Changes look good to me. I added suggestions to update the text under `#### Include the Package` so it looks uniform across READMEs. One thing to note though is that I don't think these are all the documents that need updating in the repository. For example, the following:

- appconfiguration/azure-spring-cloud-starter-appconfiguration-config
- communication/azure-communication-networktraversal
- cosmos/azure-spring-data-cosmos
- spring/azure-spring-cloud-context
- tables/azure-data-tables

are all in one of the BOMs and yet their READMEs make no mention of how to include them as dependencies via a BOM.

**Comment by pallavit** [comment]
> Changes look good to me. I added suggestions to update the text under `#### Include the Package` so it looks uniform across READMEs. One thing to note though is that I don't think these are all the documents that need updating in the repository. For example, the following:
> 
> * appconfiguration/azure-spring-cloud-starter-appconfiguration-config
> * communication/azure-communication-networktraversal
> * cosmos/azure-spring-data-cosmos
> * spring/azure-spring-cloud-context
> * tables/azure-data-tables
> 
> are all in one of the BOMs and yet their READMEs make no mention of how to include them as dependencies via a BOM.

I have included tables and networktraversal. However the rest are spring libraries that should be consuming spring BOM azure-sdk-bom.

**Review by vcolin7 — APPROVED** [review]
LGTM! :shipit:

**Comment by pallavit** [comment]
Thank you for the review.

**Pull request merged**
