### PR TITLE
fixChangeFeedPartitionImplCheckpointFor304

### PR DESCRIPTION
**Pull request by xinlian12**
**Issue:**
Currently if for partition, only 304 has been observed since changeFeedProcessor startup, the continuationToken in the lease document will not be updated. 

**Fix:**
Always do lease checkpoint update

### CODE REVIEW

**Review by FabianMeiswinkel — APPROVED** [review]
LGTM - Thanks

**Review by kushagraThapar — APPROVED** [review]
LGTM, however, we should mention this fix in the changelog.

**Comment by xinlian12** [comment]
Failed tests are not related to this PR

**Pull request merged**
