### PR TITLE
Make Internal Methods Synchronous

### PR DESCRIPTION
**Pull request by alzimmermsft**
# Description

Changes implementation code to be synchronous instead of using Reactor's `Mono` types. Additionally, determined that in many cases the passed `byte[] body`/`String body` was the body from the `HttpResponse` we would attempt to read later, so the use of `HttpResponse.getBody*` could be removed.

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [x] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Review by kasobol-msft — APPROVED** [review]
lgtm

**Comment by alzimmermsft** [comment]
Overriding check-enforcer as known live tests are failing and aren't caused by this change.

**Comment by alzimmermsft** [comment]
Overriding check-enforcer as known live tests are failing and aren't caused by this change.

**Pull request merged**
