### PR TITLE
Set skipPublishDocMs to true for packages which do not build docs

### PR DESCRIPTION
**Pull request by danieljurek**
You are on this PR review because you are a CODEOWNER reviewer. Please have a look at your service and package and let me know if you have concerns about skipping building docs.ms documentation for the following excluded packages. 

The following packages do not build docs. This encodes the fact that those packages are not intended to be documented (as opposed to filtering by our validation heuristics). 

Impacted packages: 

* sdk/aot
    * azure-aot-graalvm-support
    * azure-aot-graalvm-support-netty
* sdk/core
    * azure-core-exprimental
    * azure-core-test
* ~sdk/cosmos~
    * ~azure-cosmos-test~ (removed after speaking with @kushagraThapar) 
* sdk/personalizer
    * azure-ai-personalizer @sharathmalladi -- there are no java docs in this package. Is this intended?
* sdk/storagemover
    * azure-resourcemanager-storagemover 
* sdk/template -- straightforward: we shouldn't be publishing docs.ms docs for templates
    * azure-sdk-template
    * azure-sdk-template-two
    * azure-sdk-template-three
* sdk/voiceservices
    * azure-resourcemanager-voiceservices

### CODE REVIEW

**Review by weshaggard — APPROVED** [review]

**Review by joshfree — APPROVED** [review]

**Comment by joshfree** [comment]
`/aot`, `/core`, and `/template` are fine. 

Just need an ack from cosmos (@kushagraThapar), mgmt (@weidongxu-microsoft), and personalizer (@sharathmalladi)

**Comment by weidongxu-microsoft** [comment]
Thanks Josh.

Does voiceservices and storagemover there because the service was deprecated?

**Comment by danieljurek** [comment]
@weidongxu-microsoft -- From notes in our [`Language-Settings.ps1` file](https://github.com/Azure/azure-sdk-for-java/blob/main/eng/scripts/Language-Settings.ps1#L295-L296): 

```
  "azure-resourcemanager-voiceservices" = "Doc build attempts to download a package that does not have published sources.";
  "azure-resourcemanager-storagemover" = "Attempts to azure-sdk-build-tool and fails";
```

Generally speaking, to make these work in the docs build a new version would need to be released which addresses these issues.

**Comment by weidongxu-microsoft** [comment]
Thanks @danieljurek. I am OK for the "resourcemanager" packages, if they currently fails.

Is there any way we can test if a new release of them would pass the doc build? (local run of doc build? some pipeline?)

Reason is that there seems nothing special from storagemover or voiceservices. And both lib is fully generated by tool, which is used for other 100+ libs as well. (Maybe the problem is from Javadoc in the code)
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storagemover/azure-resourcemanager-storagemover/pom.xml
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/voiceservices/azure-resourcemanager-voiceservices/pom.xml
Therefore SDK dev may still need to figure out why doc build fails for these 2 libs.

**Comment by danieljurek** [comment]
@weidongxu-microsoft -- Sent email with instructions.

**Review by weidongxu-microsoft — APPROVED** [review]

**Comment by danieljurek** [comment]
I spoke with @kushagraThapar -- this package is intended to be documented so no changes to the `ci.yml` in this PR.

**Comment by danieljurek** [comment]
Spoke with @alzimmermsft, the test failures in the `java - core - ci` pipeline are the result of flaky tests (different ones fail on different runs). This PR is OK to merge.

**Pull request merged**
