### PR TITLE
Using child-modules versions for Cosmos Spark 3.1 and 3.2 to fix build issue

### PR DESCRIPTION
**Pull request by FabianMeiswinkel**
# Description
Build failed - https://dev.azure.com/azure-sdk/public/_build/results?buildId=1313532&view=logs&j=f3f0555b-6d71-5563-11ad-63837111d4fb&t=81744b76-0479-52fc-f696-a65c3dc23f48 - due to the fact that a pom file was used that is generated via eng/scripts/generate_from_source_pom.py - which generates the pom based on entries in client_version file.

So we can't use the artifactId "azure-cosmos-spark_3_2-12" (the parent module for the modules of spark-specific versions) but instead have to define the child artifacts ("azure-cosmos-spark_3-1_2-12" and "azure-cosmos-spark_3-2_2-12") and manually ensure that the version will always be identical for all children.

### CODE REVIEW

**Review by milismsft — APPROVED** [review]

**Review by kushagraThapar — APPROVED** [review]
LGTM

**Comment by weidongxu-microsoft** [comment]
Please fix that pom. It causes almost all Java CI get failure, and protentional blocking release pipeline for almost all Java SDKs.

**Comment by FabianMeiswinkel** [comment]
> Please fix that pom. It causes almost all Java CI get failure, and protentional blocking release pipeline for almost all Java SDKs.

@weidongxu-microsoft are you saying you are still blocked even after I merged this PR? If so, can you please point me to one of the failed pipelines to allow me investigate it?

**Comment by weidongxu-microsoft** [comment]
@FabianMeiswinkel 
You probably already addressing this in https://github.com/Azure/azure-sdk-for-java/pull/26605

Right now we are not blocked, we just delaying any release job until this get fixed.

**Pull request merged**
