### PR TITLE
Communication Services - Chat: Fix incorrect tests

### PR DESCRIPTION
**Pull request by danielgerlag**
Fixing tests with wrong assumptions.

### CODE REVIEW

**Comment by minnieliu** [comment]
Thanks for these changes @danielgerlag. 

Is it necessary to update all the recorded files when only 2 tests have been updated? For better readability, I suggest only update the related recordings.

**Comment by danielgerlag** [comment]
\azp run java - communication - tests

**Review by minnieliu — APPROVED** [review]

**Pull request merged**
