### PR TITLE
fix the issue of readme in cosmos service

### PR DESCRIPTION
**Pull request by Melanie-Ma**
Fix the issue #19471 of readme in cosmos service.

### CODE REVIEW

**Review by kushagraThapar — APPROVED** [review]
@Melanie-Ma - thanks for the contribution, looks good to me, however Build Analyze step is failing, can you please look into it.

**Comment by Melanie-Ma** [comment]
@kushagraThapar  - This link http://www.slf4j.org/ caused this error, because the link is not a secure link. However I found this link in other service. 
image
Can we delete this link or change it to a secure link( however I can not fiind other secure link.)

**Comment by kushagraThapar** [comment]
@Melanie-Ma - there is no other secure link for SLF4j, I would rather not have any link for SLF4j, and just keep it as it was originally. Other Java and maven links are good, so let's keep them, but revert the slf4j link.

**Review by moderakh — APPROVED** [review]

**Comment by Melanie-Ma** [comment]
@kushagraThapar - Done

**Comment by kushagraThapar** [comment]
> @kushagraThapar - Done

Thanks @Melanie-Ma - I will merge the PR now.

**Pull request merged**
