### PR TITLE
Kv live test config update

### PR DESCRIPTION
**Pull request by g2vinay**
1. Update KV tests setup logic.
2. Fixes MQ ARM template for KV permissions.

### CODE REVIEW

**Comment by hemanttanwar** [comment]
@g2vinay  Please ensure that `java-keyvault-tests` pipeline is green.

**Comment by g2vinay** [comment]
> @g2vinay Please ensure that `java-keyvault-tests` pipeline is green.

@hemanttanwar , the pipeline is green.
I will merge this in the morning.

**Comment by hemanttanwar** [comment]
@g2vinay  LGTM

**Pull request merged**
