### PR TITLE
Fault injection fix connection error hit count

### PR DESCRIPTION
**Pull request by xinlian12**
**Changes included:**

> Increased the hit count for connection error rule correctly 

each time the rule got triggered, the hit count will increase. So the most reliable way to figure out how many times the rule has applied is by using `rule.getHitCount()`

> Based on the feedback, add log when connection close/reset is being triggered

`WARN  com.azure.cosmos.implementation.directconnectivity.rntbd.RntbdRequestManager - Inject Connection close with ruleId {}`

`WARN  com.azure.cosmos.implementation.directconnectivity.rntbd.RntbdRequestManager - Inject Connection reset with ruleId {}`

> Try to capture the faultInjectionId in the diagnostics when applicable

When the connection got closed/reset, if there is no in-flight requests pending on the connection, then no requests will be impacted. But if the requests failed and retry due to connection close/reset, then the faultInjectionId will be properly populated in the diagnostics. 

image

image

### CODE REVIEW

**Review by FabianMeiswinkel — APPROVED** [review]
LGTM - thanks

**Comment by xinlian12** [comment]
local test the following tests:
readAllItemsWithDetailMetricsWithExplicitPageSize
readAllItemsWithDetailMetrics
readFeedDocumentsAfterSplit
queryOrderWithTop

**Pull request merged**
