### PR TITLE
Core-Mgmt: update azure environment for graph api

### PR DESCRIPTION
**Pull request by ChenTanyi**
Split from https://github.com/Azure/azure-sdk-for-java/pull/18420/commits/8de3c2de658a7d82ca3045adf0373c62939d672e

### CODE REVIEW

**Review by alzimmermsft — APPROVED** [review]

**Comment by ChenTanyi** [comment]
Host is from https://docs.microsoft.com/en-us/graph/deployments#microsoft-graph-and-graph-explorer-service-root-endpoints

**Review by weidongxu-microsoft — APPROVED** [review]

**Comment by weidongxu-microsoft** [comment]
What if we add a `microsoftGraphResourceId` instead?

**Comment by ChenTanyi** [comment]
OK, I'll change it.

**Review by xccc-msft — APPROVED** [review]

**Comment by ChenTanyi** [comment]
The Build from source fail is not caused by core-management.

**Pull request merged**
