### PR TITLE
[Service Bus] Change getter of boolean values to isXyz()

### LINKED ISSUE #14139: Change names of booleans to use "is"
Update names of booleans to use a question like name, "isRequiresSession" to make them more Java-esque?

API View https://apiview.dev/Assemblies/Review/64f40be9988242c9a8facc8a20c5e9e7

### PR DESCRIPTION
**Pull request by YijunXieMS**
It's customary to use isXyz() for a boolean value getter than getXyz(), as suggested in issue #14139 . So This PR suggests the following and other similar changes to the public APIs.

enableBatchedOperations() -> isBatchedOperationsEnabled()
enablePartitioning() -> isPartitioningEnabled()
deadLetteringOnMessageExpiration -> isDeadLetteringOnMessageExpiration()
requiresDuplicateDetection() -> isDuplicateDetectionRequired()
supportsOrdering() -> isOrderingSupported()

`ServiceBusAdministrationClient` has `getQueueExists(String queueName)` and other similar methods. This get method name kept because it implies an HTTP get operation. .Net calls it `QueueExists`.

Closes #14139

### CODE REVIEW

**Review by conniey — APPROVED** [review]
LGTM

**Comment by ramya-rao-a** [comment]
The changes in this PR are not necessarily applicable only to Java. The other languages we are working on for Service Bus should be considered as well.

**Review by JonathanGiles — APPROVED** [review]

**Review by ramya-rao-a — CHANGES_REQUESTED** [review]
My conclusions after multiple discussions on this subject:

We are not too keen on being consistent between the "Enable" and "Requires" prefixes as matching with what goes over the wire trumps the small win of being consistent with the prefixes. This would not hold true for cases where the name is way too bad in the first place, but we do not find any such instances for Service Bus at the moment. 

Unlike other languages, Java has getters and setters with get/set prefixes. For boolean return types, is is preferred instead of get. Since most of the properties do not read well if we just added is prefix, we will be taking the liberty to reword the names of these properties to help with readability. These will not match exactly with what goes over the wire, but will have similar words, so that should not be a problem. The win to readability trumps for Java due to the necessity to have separate prefixes for the getters and setters.

My mistake was to assume that the efforts in this PR also included in improving names in general and so would affect other languages.

Having said this, @JonathanGiles and I noticed that we are not updating the setters in this PR. One would expect the setter and getter names to differ only in the prefix i.e. is vs set. Can we have the setters updated here as well?

**Comment by YijunXieMS** [comment]
boolean getters and setters suggestion.
@ramya-rao-a @JonathanGiles Does this look good to you?


attribute name | getter (is) | setter
-- | -- | --
enableBatchedOperations | isBatchedOperationsEnabled | setBatchedOperationsEnabled
enablePartitioning | isPartitioningEnabled | setPartitioningEnabled
requiresDuplicateDetection | isDuplicateDetectionRequired | setDuplicateDetectionRequired
requiresSession | isSessionRequired | setSessionRequired
deadLetteringOnMessageExpiration | isDeadLetteringOnMessageExpiration | setDeadLetteringOnMessageExpiration
deadLetteringOnFilterEvaluationExceptions | isDeadLetteringOnFilterEvaluationExceptions | setDeadLetteringOnFilterEvaluationExceptions
supportOrdering | isOrderingSupported | setOrderingSupported
requiresProprocessing | isProprocessingRequired | setProprocessingRequired

**Review by hemanttanwar — APPROVED** [review]

**Review by ramya-rao-a — APPROVED** [review]

**Pull request merged**
