### PR TITLE
Update Dependency Versions

### PR DESCRIPTION
**Pull request by alzimmermsft**
This PR updates dependency versions to newer versions.

### CODE REVIEW

**Review by joshfree — APPROVED** [review]

**Comment by jamesc** [comment]
@joshfree Could you help investigate why the tests are still failing ?

**Comment by jamesc** [comment]
RSA PKC SV1.5 encryption

**Comment by alzimmermsft** [comment]
Hi @jamesc, what test failures are you seeing? I'm seeing that CI is passing, are there specific tests within the CI pipelines that are failing?

**Comment by alzimmermsft** [comment]
@moderakh, @kushagraThapar, does the bouncycastle dependency upgrade for `azure-cosmos-encryption` look appropriate?

**Comment by moderakh** [comment]
> @moderakh, @kushagraThapar, does the bouncycastle dependency upgrade for `azure-cosmos-encryption` look appropriate?

It looks good. thank you.

**Comment by jamesc** [comment]
> Hi @jamesc James Casey FTE, what test failures are you seeing? I'm seeing that CI is passing, are there specific tests within the CI pipelines that are failing?

I was seeing a lot of failures with connection errors.  Looks like they've cleared up or it was a sync issue.

**Comment by ONFU** [comment]
tank your body shelther

**Comment by ONFU** [comment]
> @joshfree Could you help investigate why the tests are still failing ?

the wolfheath haved changing galth of olson mary kate my dauther holme lonely destroye all subsistyance of districk apocalypsme NoX-PacT

**Comment by ONFU** [comment]
conviable votre

**Pull request merged**
