### PR TITLE
[Storage] Tests - Make test account configuration read DRY

### PR DESCRIPTION
**Pull request by kasobol-msft**
In this PR:
- centralize logic that reads storage accounts.

Out of scope:
- figure out if we can reduce amount of account we need for tests. https://github.com/Azure/azure-sdk-for-java/issues/21221

### CODE REVIEW

**Comment by kasobol-msft** [comment]
Green live test run https://dev.azure.com/azure-sdk/internal/_build/results?buildId=879895&view=results

**Review by alzimmermsft — APPROVED** [review]

**Pull request merged**
