### PR TITLE
Update Perf Libraries to Add Multi-Release to the JAR With Dependencies Manifest

### PR DESCRIPTION
**Pull request by alzimmermsft**
# Description

This PR updates the `maven-assembly-plugin` configuration to include `Multi-Release: true` in the JAR with dependencies manifest that is generated in the build process for perf framework JARs. `Multi-Release: true` is being added as `azure-core` contains multi-release JAR functionality and the JAR with dependencies includes all source code of the dependencies in the project but doesn't include any manifest entries that enable specific functionality. Adding this enables the perf framework JARs to hook into the multi-release functionality that `azure-core`, and any other dependency libraries, provides.

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](../../CONTRIBUTING.md#building-and-unit-testing)
- [x] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Comment by alzimmermsft** [comment]
Running Storage live tests as it includes running perf tests, so it is the best option to validate this PR.

**Review by srnagar — APPROVED** [review]

**Pull request merged**
