### PR TITLE
JavaCheckStyleRule: Package Naming

### PR DESCRIPTION
**Pull request by mssfang**
Add a CheckStyle Rule for PackageName.

Issue: CheckStyle: Pacakage Naming (Start and Patterns) #3268

### CODE REVIEW

**Comment by JonathanGiles** [comment]
Did this test turn up any new failures in our codebase?

**Comment by mssfang** [comment]
no failures.

**Comment by JonathanGiles** [comment]
Did you test against other illegal package names? e.g. no characters other than lower-case 'a' through 'z', no spaces, no underscores, etc.

**Comment by mssfang** [comment]
"no characters other than lower case a - z" is different than the notes required. Current regular expression is only check not A-Z, underscore, hyphen,  I will edited the regular expression. 
Note:
The regular expression:"^(?=.{9,80}$)((com.microsoft.azure|com.azure)(\.[^A-Z_-]{1,20})*)+$"

(?=.{9,80}) means the total length packages name is between 9 to 80 characters.
^(com.microsoft.azure|com.azure) means the package name have to start with either com.microsoft.azure or com.azure.

**Comment by mssfang** [comment]
modify the current partial of regular expression from (.[^A-Z_-]{1,20})* to  (\.[a-z]{1,20})*) will meet the requirement that "no character other than lower case 'a' through 'z' "

**Comment by JonathanGiles** [comment]
Looks good. Please improve the comment to clarify all the rules being enforced, and then this can be merged.

**Comment by mssfang** [comment]
the new comment is updated. Does it looks good?

**Pull request merged**
