### PR TITLE
End to End TLS/SSL - step #6 - enable revapi plugin

### PR DESCRIPTION
**Pull request by mnriem**

### CODE REVIEW

**Comment by mnriem** [comment]
@chenrujun or @saragluna I enabled the revapi plugin. Not sure how to put the necessary exclusions in (I think that is what is needed). Can you take it the rest of the way? Thanks!

**Comment by mnriem** [comment]
@chenrujun or @saragluna Can you take this PR all the way? Thanks!

**Comment by chenrujun** [comment]
@han-gao , please help to handle this PR.

**Comment by han-gao** [comment]
@chenrujun ok,I'm doing.

**Comment by chenrujun** [comment]
Will merge in https://github.com/Azure/azure-sdk-for-java/pull/17112, so close this PR.

**Pull request closed without merging**
