### PR TITLE
Fix Service Bus live test breaks

### PR DESCRIPTION
**Pull request by liukun-msft**
# Description

To fix failed tests in `ServiceBusAdministrationClientIntegrationTest`.  Most failures are due to naming issues, such as conflicting queue names or not found.

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [ ] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [ ] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Comment by lmolkova** [comment]
I'm sorry I broke them - let me send another PR to update ServiceBus to new tracing changes that would fix tests and implement some other features.

**Comment by liukun-msft** [comment]
> I'm sorry I broke them - let me send another PR to update ServiceBus to new tracing changes that would fix tests and implement some other features.

Awesome! Thank you @lmolkova! Please link to that PR when you are done, I would also like to gain some knowledge about the tracing tests.

**Comment by anuchandy** [comment]
Liudmila cleanup the integration test and is in a good state now, so we can close this pr.

**Pull request closed without merging**
