### PR TITLE
fixing loading correct class bug that Naveen found

### PR DESCRIPTION
**Pull request by moderakh**
fixing loading correct class bug that Naveen found

### CODE REVIEW

**Review by simplynaveen20 — APPROVED** [review]
LGTM

**Review by kushagraThapar — APPROVED** [review]
LGTM

**Review by simplynaveen20 — CHANGES_REQUESTED** [review]
Can we also change the exception message as well, we are using CosmosQueryRequestOptionsHelper  in all there helper

**Comment by moderakh** [comment]
> Can we also please change the exception message as well, we are using CosmosQueryRequestOptionsHelper in all these helper

could you refer to the actual code, it is not clear to me what you are referring to and what the scenario you are pointing at.

**Comment by moderakh** [comment]
> Can we also please change the exception message as well, we are using CosmosQueryRequestOptionsHelper in all these helper

discussed offline to understand the comment. Thanks for the comment. I addressed in the last commit.

**Review by simplynaveen20 — APPROVED** [review]

**Pull request merged**
