### PR TITLE
Move jdbc/azure-identity-extensions to identity/azure-identity-extensions

### PR DESCRIPTION
**Pull request by saragluna**
# Description

To address review comment https://github.com/Azure/azure-sdk-for-java/pull/32370#discussion_r1037493473. 

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [x] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Review by billwert — APPROVED** [review]
Looks fine to me. Will you continue to manage the release for this library or is it going to roll into releasing `azure-identity`? I expect the former but wanted to check.

**Comment by saragluna** [comment]
Thanks @billwert. Yes, we will manage the release.

**Comment by stliu** [comment]
> Thanks @billwert. Yes, we will manage the release. @stliu am I understanding this correctly?

yeah, let's do it for now

**Review by stliu — APPROVED** [review]

**Comment by saragluna** [comment]
The `jdbc-ci` can be ignored now for the folder doesn't have any content.

**Pull request merged**
