### PR TITLE
Add ink module to cogserv pom

### PR DESCRIPTION
**Pull request by minaltolpadi**
Add artifact for the new Ink Recognizer SDK. Associated PRs:

[https://github.com/Azure/azure-sdk-for-java/pull/5354](url)
[https://github.com/Azure/azure-sdk-for-java/pull/5708](url)
[https://github.com/Azure/azure-sdk-for-java/pull/5727](url)
[https://github.com/Azure/azure-sdk-for-java/pull/5728](url)
[https://github.com/Azure/azure-sdk-for-java/pull/5765](url)

### CODE REVIEW

**Comment by minaltolpadi** [comment]
I want to mention here that the tests are failing because they require a valid subscription key to succeed.

**Comment by weshaggard** [comment]
Tests that require secrets to subscriptions should not be run by default in our PR validation jobs. We have a live test job that will run those when they are correctly configured with the secrets. For the PR validation these tests should be skipped or use recordings to validation the functionality.

**Comment by JonathanGiles** [comment]
@minaltolpadi Can this PR be closed now?

**Comment by weshaggard** [comment]
I believe this work is postponed so closing the PR.

**Pull request closed without merging**
