### PR TITLE
Cosmos - Fix @EnableAuditing can't work with Java Modules

### PR DESCRIPTION
**Pull request by saragluna**
Fix https://github.com/Azure/azure-sdk-for-java/issues/18892. When `@EnableAuditing` is used with Java Modules, the below exception will be thrown. This PR is to open `com.azure.spring.data.cosmos.core.mapping` to `spring.core`.

```
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make com.azure.spring.data.cosmos.core.mapping.CosmosAuditingRegistrar() accessible: module com.azure.spring.data.cosmos does not "opens com.azure.spring.data.cosmos.core.mapping" to module spring.core
```

Already tested with the Java 11 sample here - https://github.com/Azure-Samples/azure-spring-data-cosmos-java-sql-api-getting-started

### CODE REVIEW

**Review by kushagraThapar — APPROVED** [review]
LGTM, thanks a lot @saragluna for the quick fix, appreciate it.

**Comment by saragluna** [comment]
@kushagraThapar any idea why the emulator ci failed?

**Comment by kushagraThapar** [comment]
> @kushagraThapar any idea why the emulator ci failed?

@saragluna - there are some issues with emulator right now, we are fixing them. So this PR is good to go in.

**Pull request merged**
