### PR TITLE
mgmt regen resources module for checkstyle fix

### PR DESCRIPTION
**Pull request by weidongxu-microsoft**

### CODE REVIEW

**Comment by weidongxu-microsoft** [comment]
autorest.java PR https://github.com/Azure/autorest.java/pull/566

**Comment by ChenTanyi** [comment]
What happen for the manual fix? Could it be done by generator?

**Comment by weidongxu-microsoft** [comment]
@ChenTanyi 

Currently major thing is `build()` -> `buildClient()`, which I am still checking with Redmond whether they are OK with the change. Since it is only 1 per service, I figure it is not urgent.

The rest is either on conflict class always in resources (since it got 4 clients, instead of 1 for usual services), or on Features (which is strange). I will check Features later.

Generator is on `v4_fix_checkstyle1` branch. Not merged.

**Comment by xccc-msft** [comment]
> @ChenTanyi
> 
> Currently major thing is `build()` -> `buildClient()`, which I am still checking with Redmond whether they are OK with the change. Since it is only 1 per service, I figure it is not urgent.
> 
> The rest is either on conflict class always in resources (since it got 4 clients, instead of 1 for usual services), or on Features (which is strange). I will check Features later.
> 
> Generator is on `v4_fix_checkstyle1` branch. Not merged.

Is this for consistency? Normally it should be `build()` for Builder class.

**Comment by weidongxu-microsoft** [comment]
@xccc-msft 

checkstyle requires it be `buildClient` for class annotated with `@ServiceClientBuilder`.

**Comment by xccc-msft** [comment]
> @xccc-msft
> 
> checkstyle requires it be `buildClient` for class annotated with `@ServiceClientBuilder`.
Got it. Yes, resources has more clients as it contains different RPs.

**Pull request merged**
