### PR TITLE
Fixing UserAgent Version Population Issue

### PR DESCRIPTION
**Pull request by trande4884**
# Description

See here: https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto.properties-and-configuration

We have a file azure-spring-data-cosmos.properties in our resources that references @project.version@. At some point this stopped getting populated and in our logs the majority of our UserAgent's simply say @project.version@ instead of having the proper version number injected. The link above specifies that if you don't use "spring-boot-starter-parent" than this filtering resource is needed for the @..@ tags to be replaced.

If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [ ] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Review by kushagraThapar — COMMENTED** [review]
LGTM, however, I would like to have someone with more experience in spring to sign off on this PR, just to verify our approach :)

**Comment by saragluna** [comment]
@trande4884 what's the issue right now, and why are we adding the resources section in the pom file?

**Comment by trande4884** [comment]
> @trande4884 what's the issue right now, and why are we adding the resources section in the pom file?

See here: https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto.properties-and-configuration

We have a file azure-spring-data-cosmos.properties in our resources that references @project.version@. At some point this stopped getting populated and in our logs the majority of our UserAgent's simply say @project.version@ instead of having the proper version number injected. The link above specifies that if you don't use "spring-boot-starter-parent" than this filtering resource is needed. I looked back and I don't see anytime we ever had this in our pom, so not sure if something changed at some point that causes this block to be needed in the POM but if fixes our issue.

**Review by FabianMeiswinkel — APPROVED** [review]
LGTM - Thanks

**Review by saragluna — APPROVED** [review]

**Review by kushagraThapar — APPROVED** [review]
LGTM, thanks @trande4884  and @saragluna

**Pull request merged**
