### PR TITLE
Use JDK 1.7 as build version

### PR DESCRIPTION
**Pull request by jianghaolu**

### CODE REVIEW

**Comment by martinsawicki** [comment]
this fails the build. What is this for?  Aren't we already compiling with v7??

**Comment by jianghaolu** [comment]
This will pass after api-annotations shows up here: http://search.maven.org/#search%7Cga%7C1%7Capi-annotations

**Comment by martinsawicki** [comment]
it says "In Progress" -- is it not ok to merge yet?

**Comment by jianghaolu** [comment]
Oh if it's passing sure.

**Pull request merged**
