### PR TITLE
make cosmos sdk extensible

### PR DESCRIPTION
**Pull request by Gueorgi**
# Description

There is a need to be able to extend the Cosmos Client SDK so one can create a wrapper for various purposes like hot swap of the client if credentials are changed, custom compression and encryption, enforcing org policies, adding tiered access, caching etc.

The current SDK does not allow that since a lot of classes have "final" declarations and also package private access.

This PR addresses the issue by removing "final" from all class declarations as well as changing the package private access to protected. The rest of the already existing access modifiers like public, private and protected are not changed. This allows sub-classes to extend existing SDK classes with full freedom to extend, overwrite and access all but private members, while non sub-classes see the same API surface as before. At the same time the SDK internal package access is preserved.

# All SDK Contribution checklist:
- [X ] **The pull request does not introduce [breaking changes]**
- [ ] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [ X] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [ X] Title of the pull request is clear and informative.
- [ X] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [ N/A] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Comment by Gueorgi** [comment]
I could add test for checking the "final" removal from classes by extending these with new sub-classes. But for the the change for package-private to protected the options seems to be either unit tests with reflection to check the access modifier on the changed methods or just call these from sub-classes (with any failures that may happen at compile time - not really needing to be running the tests)

**Comment by FabianMeiswinkel** [comment]
Hi @Gueorgi - this PR is opening the public surface area way too much. Instead of removing final everywhere we should add an extension point that allows transformations of the payload. Opening all public API to override makes it impossible to service the SDK except if we clearly stop supporting all inherited APIs - which is probably also not acceptable for you?

**Review by FabianMeiswinkel — CHANGES_REQUESTED** [review]
Hi @Gueorgi - this PR is opening the public surface area way too much. Instead of removing final everywhere we should add an extension point that allows transformations of the payload. Opening all public API to override makes it impossible to service the SDK except if we clearly stop supporting all inherited APIs - which is probably also not acceptable for you?

**Comment by Gueorgi** [comment]
> Hi @Gueorgi - this PR is opening the public surface area way too much. Instead of removing final everywhere we should add an extension point that allows transformations of the payload. Opening all public API to override makes it impossible to service the SDK except if we clearly stop supporting all inherited APIs - which is probably also not acceptable for you?

So payload access extension can work for some of the cases may be (compression, encryption, org policy to add/remove/change specific fields etc.) but how one can do a hot swap of the client if you can't wrap the whole SDK? There are cases for that (different storage tiers to go to on some conditions, credentials rotations). Perhaps if it was just the client stored in the (Sync/Async) Container and Database it could have worked, but unfortunately the (Sync/Async) Client is something already being given out to users directly to use and then the only way to do hot swap or tiers on it is to have a wrapper given out and that just delegates most of the calls to the real clients. May be only these 3 classes Client/Container/Database need to be changed to not be final + the payload extension? ... Feels like there will be other cases where a full wrapper only could help - I am open to suggestions.

**Comment by FabianMeiswinkel** [comment]
> > Hi @Gueorgi - this PR is opening the public surface area way too much. Instead of removing final everywhere we should add an extension point that allows transformations of the payload. Opening all public API to override makes it impossible to service the SDK except if we clearly stop supporting all inherited APIs - which is probably also not acceptable for you?
> 
> So payload access extension can work for some of the cases may be (compression, encryption, org policy to add/remove/change specific fields etc.) but how one can do a hot swap of the client if you can't wrap the whole SDK? There are cases for that (different storage tiers to go to on some conditions, credentials rotations). Perhaps if it was just the client stored in the (Sync/Async) Container and Database it could have worked, but unfortunately the (Sync/Async) Client is something already being given out to users directly to use and then the only way to do hot swap or tiers on it is to have a wrapper given out and that just delegates most of the calls to the real clients. May be only these 3 classes Client/Container/Database need to be changed to not be final + the payload extension? ... Feels like there will be other cases where a full wrapper only could help - I am open to suggestions.

Yes, it is correct that only opening the public surface area would allow everything - but that makes it impossible to support. So, our strategy is to allow extensions for common asks - while intentionally requiring custom wrappers (where it is obvious and clear that support can't be provided by Microsoft Comsos DB team) for certain edge cases.

**Comment by Gueorgi** [comment]
> > > Hi @Gueorgi - this PR is opening the public surface area way too much. Instead of removing final everywhere we should add an extension point that allows transformations of the payload. Opening all public API to override makes it impossible to service the SDK except if we clearly stop supporting all inherited APIs - which is probably also not acceptable for you?
> > 
> > 
> > So payload access extension can work for some of the cases may be (compression, encryption, org policy to add/remove/change specific fields etc.) but how one can do a hot swap of the client if you can't wrap the whole SDK? There are cases for that (different storage tiers to go to on some conditions, credentials rotations). Perhaps if it was just the client stored in the (Sync/Async) Container and Database it could have worked, but unfortunately the (Sync/Async) Client is something already being given out to users directly to use and then the only way to do hot swap or tiers on it is to have a wrapper given out and that just delegates most of the calls to the real clients. May be only these 3 classes Client/Container/Database need to be changed to not be final + the payload extension? ... Feels like there will be other cases where a full wrapper only could help - I am open to suggestions.
> 
> Yes, it is correct that only opening the public surface area would allow everything - but that makes it impossible to support. So, our strategy is to allow extensions for common asks - while intentionally requiring custom wrappers (where it is obvious and clear that support can't be provided by Microsoft Comsos DB team) for certain edge cases.

Well, there are JDBC drivers from Azure, Oracle etc. and these are supported - despite very frequently being wrapped (in connection pool managers etc.). That works since all is based in interfaces. May be the way to go is to change the Client, Container, Database etc. classes to interfaces instead and leave the implementations closed as now. With interfaces one can create wrappers while still not make it difficult to you to support the implementations below. This is how a lot of other SDKs are done. Adding an extension APIs here and there feels like a band-aid and just increases the SDK complexity.

**Comment by Gueorgi** [comment]
Closing this PR in leu of a dedicated payload hook/extension (TBD) and adding credentials swap capability in another PR (had a look in the CosmosAsyncClient and hot swap appears to be not too difficult to do actually).

The tier storage I agree is better to be left outside of the SDK.

**Pull request closed without merging**
