### PR TITLE
fixChangingFeedModeCheckingForPkRangeVersion

### PR DESCRIPTION
**Pull request by xinlian12**
**Issue:**
When customer uses handleChanges (PkRange based lease), if lease store has been initialized, then starting the change feed processor will fail with the following exception: 

`java.lang.IllegalArgumentException: Illegal base64 character 22`

**Root cause:**
There has been a recent change to validate the change feed mode in the lease during changeFeed startup. When trying to validate the changeFeedMode in the lease, we are using ChangeFeedState.fromString() to parse the continuationToken, this method excepts the continuationToken to be in base64 format. However, for pkRange based lease, the continuationToken is only a long, that is when the above exception will be thrown.

**Fix:**
Remove the change feed mode checking if customer is on pkRange based lease, as only Incremental change feed mode is supported in the pkRange based lease.

### CODE REVIEW

**Review by kushagraThapar — APPROVED** [review]
LGTM, thanks @xinlian12

**Review by jeet1995 — APPROVED** [review]
LGTM - thanks!

**Review by FabianMeiswinkel — APPROVED** [review]
LGTM

**Comment by xinlian12** [comment]
Tested readAllItemsWithDetailMetricsWithExplicitPageSize locally

**Pull request merged**
