### PR TITLE
Try out new Maven proxy.

### PR DESCRIPTION
**Pull request by mitchdenny**
This PR uses a different Maven proxy which is redirected to Azure Artifacts. It makes use of Azure Front Door which has a rules engine rule to insert an auth header to a private Azure Artifacts feed, which then takes care of the upstreaming.

### CODE REVIEW

**Comment by weshaggard** [comment]
Does this correctly pull packages from upstream?

**Comment by mitchdenny** [comment]
Yep

**Comment by mitchdenny** [comment]
Merging onto feature/broken-pipe-fix to continue validation of this change.

**Pull request merged**
