### PR TITLE
Updated versions in feature branch

### PR DESCRIPTION
**Pull request by gapra-msft**

### CODE REVIEW

**Comment by gapra-msft** [comment]
> This is meant to match what is in master right?

Yep, that's the goal

**Comment by weshaggard** [comment]
You will need to also add the placeholder version entries in the CHANGELOG files to get CI passing. fyi @chidozieononiwu @JimSuplizio

**Comment by rickle-msft** [comment]
I think Dozie told us that that ci check was going to be updated to only run after certain versions

**Comment by weshaggard** [comment]
It only checks one version but the version it checks is the version in the project.

**Comment by chidozieononiwu** [comment]
> I think Dozie told us that that ci check was going to be updated to only run after certain versions

Yes am working on a fix so it doesn't block old branches.

**Comment by rickle-msft** [comment]
@chidozieononiwu Can you help us understand why we're still seeing the same readme failures here? Does it have to do with the fact that we are upgrading the version in this PR?

**Comment by chidozieononiwu** [comment]
> @chidozieononiwu Can you help us understand why we're still seeing the same readme failures here? Does it have to do with the fact that we are upgrading the version in this PR?
Is this a recent run? It is still using version 0.4.0 of DocWarden. We publishe 0.4.1 yesterday. If you trigger a completely new build it should use the more recent one and you should have no issues.

**Comment by chidozieononiwu** [comment]
No you have just one readme to fix 
`/sdk/storage/azure-storage-queue-cryptography` which seems to be a legitimate case.
Just add a single entry for it in `docsettings.yml` and you should be good to go.

**Pull request merged**
