### PR TITLE
Switch eventgrid ci to client instead of data

### PR DESCRIPTION
**Pull request by weshaggard**

### CODE REVIEW

**Comment by weshaggard** [comment]
@srnagar @yijunxiems according to code owners you guys are the owners of eventgrid so pinging you to have a look. I only noticed this because the readme has broken links in aggregate reports pipeline at https://dev.azure.com/azure-sdk/internal/_build/results?buildId=531095&view=results and I was trying to figure out why this wasn't caught by CI and it is because we only have the link checks in the track 2 client build templates and not the data templates. 

cc @sima-zhu

**Comment by sima-zhu** [comment]
I learned from Java team channel. Here is the pipeline setup PR for eventgrid: https://github.com/Azure/azure-sdk-for-java/pull/15039/files

**Comment by weshaggard** [comment]
I believe the broken links were introduced by @Soreloser2 PR https://github.com/Azure/azure-sdk-for-java/pull/14442

**Comment by joshfree** [comment]
@Soreloser2 is following up on this

**Comment by weshaggard** [comment]
@Soreloser2  I updated the ci.yml and fixed the readme broken links but now I'm hitting a missing changelog error. At this point I'll let you take over these changes. Feel free to steal my changes, just be sure to also pull in the change in the ci.yml file.

**Comment by weshaggard** [comment]
Ok after a closer look the change log issue was complaining about the track 1 azure-eventgrid and we cannot mix track 1 and track 2 libraries in the same ci.yml file. I'll add the ci.data.yml file to add back the track 1 library but for now lets try to get your new track 2 library working.

**Comment by weshaggard** [comment]
OK I'm closing this PR as it is already be addressed in https://github.com/Azure/azure-sdk-for-java/pull/15039.

**Pull request closed without merging**
