### PR TITLE
[Communication]: Trigger communication ci when core is changed

### PR DESCRIPTION
**Pull request by JianpingChen**
Add sdk/core to both triggers and pr

### CODE REVIEW

**Comment by JianpingChen** [comment]
> For python, they have the convention of running multiple services against core PRs. For java, I believe they only run the core - ci builds against core changes, so this would be a larger behavioral change for this repo. I think we need someone from the java team to weigh in here.

Thanks for the info. What about JS? Is JS pipeline similar to Python? Or is it more like Java?

**Comment by mitchdenny** [comment]
@benbp is correct. If you make a core change, we actually build all the modules that are dependent on the ```azure-core-*``` modules using the ```-amd``` switch.

**Comment by alzimmermsft** [comment]
@mitchdenny, from what I'm able to re-call, the `-amd` switch was replaced by an external script which determines all libraries that need to be built for a run. The script generates an aggregate POM which is then install, then if the PR is not a `From Source` run the project list is ran for testing or if the PR is a `From Source` run the aggregate POM is used for testing. This change was made because there were cases where `-amd` was triggering much more testing that was required as `From Source` only needs to validate downstream dependencies still pass testing with code changes but `-amd` was also testing upstream dependencies.

This is the script: https://github.com/Azure/azure-sdk-for-java/blob/master/eng/scripts/generate_from_source_pom.py

**Comment by mitchdenny** [comment]
Ah thanks for refreshing my memory @alzimmermsft I had forgotten about that. But the effect is the same, we shouldn't have to add ```sdk/core``` to the list of triggers for ```sdk/communications```. Thanks!

**Pull request closed without merging**
