### PR TITLE
Disable public anonymous blob access for live resource tests

### PR DESCRIPTION
**Pull request by weshaggard**

### CODE REVIEW

**Review by ibrandes — APPROVED** [review]

**Review by ibrahimrabab — APPROVED** [review]

**Comment by weshaggard** [comment]
@ibrandes did you want to take this change as part of your PR https://github.com/Azure/azure-sdk-for-java/pull/40689? Or a follow-up as I suspect it will require updates to the test code to make functional.

**Comment by ibrandes** [comment]
@weshaggard We've already merged [this PR](https://github.com/Azure/azure-sdk-for-java/pull/41181) into main, marking the access policy tests as playback only, so I think we're good to go on this PR.

**Comment by weshaggard** [comment]
@ibrandes can you take a look at the test failures to see if they are related to the template update?

**Comment by ibrandes** [comment]
@weshaggard These failures are separate from the template update. A couple of them have been fixed in main already, and we are aware of the others, so we are good to merge :)

**Pull request merged**
