### PR TITLE
Add sample for write

### PR DESCRIPTION
**Pull request by arwinlashawn**
Was using this README to do Cosmos DB data migration with Azure Databricks and realized the sample code for write was missing. I think adding this would greatly help anyone learning to use Databricks for Cosmos DB data migration!

# Description

Please add an informative description that covers that changes made by the pull request and link all relevant issues.

If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.

# All SDK Contribution checklist:
- [ ] **The pull request does not introduce [breaking changes]**
- [ ] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [ ] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Review by kushagraThapar — COMMENTED** [review]
LGTM, thanks @arwinlashawn for the contributions. 
@FabianMeiswinkel can you please take a look as well?

**Comment by arwinlashawn** [comment]
Thanks for the prompt review @kushagraThapar ! @FabianMeiswinkel Please let me know if any changes are needed.

**Comment by arwinlashawn** [comment]
Hi @kushagraThapar , could you please take a look at this PR? Thanks!

**Comment by kushagraThapar** [comment]
@xinlian12  / @FabianMeiswinkel  - please take a look at this.

**Comment by arwinlashawn** [comment]
Hi @xinlian12, could you please have a look at this PR? Thanks!

**Review by FabianMeiswinkel — APPROVED** [review]
LGTM

**Pull request merged**
