### PR TITLE
Fixing SessionNotAvailableRetryTest for BE node without regional endpoint

### PR DESCRIPTION
**Pull request by simplynaveen20**
This will fix the below CI failure .

image

Root cause - Recently we are receiving some BE nodes without the regional suffix which is breaking the logic. Relying on gateway regional endpoint instead.

### CODE REVIEW

**Review by kushagraThapar — APPROVED** [review]
LGTM, thanks @simplynaveen20

**Review by FabianMeiswinkel — APPROVED** [review]
LGTM

**Pull request merged**
