### PR TITLE
[ServiceBus] Update SDK version to 3.0.0

### PR DESCRIPTION
**Pull request by bainian12345**
Update SDK version to 3.0.0 for RBAC breaking changes

### CODE REVIEW

**Comment by mitchdenny** [comment]
This means that you won't have ever published a 2.0.0 version (other than previews) - is that intentional?

**Comment by bainian12345** [comment]
There seems to be a 2.0.0 version released on 15-march-2019 isn't there?
[[https://search.maven.org/search?q=g:com.microsoft.azure%20AND%20a:azure-servicebus&core=gav](https://search.maven.org/search?q=g:com.microsoft.azure%20AND%20a:azure-servicebus&core=gav)](https://search.maven.org/search?q=g:com.microsoft.azure%20AND%20a:azure-servicebus&core=gav)

---
In reply to: [521100029](https://github.com/Azure/azure-sdk-for-java/pull/4978#issuecomment-521100029) [](ancestors = 521100029)

**Comment by mitchdenny** [comment]
My bad - so there is.

**Pull request closed without merging**
