### PR TITLE
Fixed a few typos and added a snippet in Java Storage readme

### PR DESCRIPTION
**Pull request by stevencl**
The readme contained a few typos and other mistakes that I fixed up during the recent UX study. I also added a snippet that shows how to check if a container exists already before creating it as this came up quite a lot during the study.

### CODE REVIEW

**Comment by JonathanGiles** [comment]
This PR is now conflicting. @stevencl and / or @alzimmermsft - could you please review if this PR is still relevant and update / merge or close as appropriate? Thanks!

**Comment by joshfree** [comment]
@amishra-dev can you please help get this azure-storage-blob/README.md merged?  It's been opened from @stevencl for ~5 months.  Thanks! 😄

**Comment by rickle-msft** [comment]
@joshfree There are merge conflicts that need to be resolved before we can merge it

**Comment by amishra-dev** [comment]
@stevencl would you be ok if my team picks up this PR and gets it in? If not, could you please resolve the merge conflicts and we will get it in ASAP. Thanks

**Comment by stevencl** [comment]
@amishra-dev - no problem at all, please feel free to pick this PR up. Whatever it takes to create a better experience for the end user :-)

**Comment by JonathanGiles** [comment]
@amishra-dev @rickle-msft What's the status on importing this content? Can this PR be closed yet?

**Pull request closed without merging**
