### PR TITLE
Added release notes and bump versions for azure-cosmos, azure-spring-data-cosmos and azure-cosmos-encryption

### PR DESCRIPTION
**Pull request by kushagraThapar**
* Release azure-cosmos, azure-spring-data-cosmos and azure-cosmos-encryption

### CODE REVIEW

**Comment by kushagraThapar** [comment]
@alzimmermsft - build analyze is failing - because of API reference not valid - 
`[404] broken link https://projectreactor.io/docs/core/release/api/`
Is it temporary and related to spring outage or should we change this reference? I checked on reactor's site, and almost all of their documentation is down and throwing 404

**Review by FabianMeiswinkel — APPROVED** [review]
LGTM

**Review by Pilchie — APPROVED** [review]

**Review by xinlian12 — APPROVED** [review]
LGTM, thanks

**Comment by alzimmermsft** [comment]
> @alzimmermsft - build analyze is failing - because of API reference not valid - `[404] broken link https://projectreactor.io/docs/core/release/api/` Is it temporary and related to spring outage or should we change this reference? I checked on reactor's site, and almost all of their documentation is down and throwing 404

Appears this was a transient outage on their site

**Pull request merged**
