### PR TITLE
External dependencies upgrade - Spring Boot 2.7.7 and Spring Cloud 2021.0.5

### PR DESCRIPTION
**Pull request by Netyyyy**
Updates external dependencies to align with Spring Boot version [2.7.7](https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-dependencies/2.7.7/spring-boot-dependencies-2.7.7.pom) from [2.7.6](https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-dependencies/2.7.6/spring-boot-dependencies-2.7.6.pom) and Spring Cloud version [2021.0.5](https://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-dependencies/2021.0.5/spring-cloud-dependencies-2021.0.5.pom) from [2021.0.5](https://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-dependencies/2021.0.5/spring-cloud-dependencies-2021.0.5.pom).
<details><summary>Release notes</summary><p><em>Sourced from <a href='https://github.com/spring-projects/spring-boot/releases/tag/v2.7.7'>spring-boot releases</a>.</em></p><h4> <g-emoji class="g-emoji" alias="lady_beetle" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f41e.png">  🐞 </g-emoji> Bug Fixes</h4><ul> <li>Fix typo in LocalDevToolsAutoConfiguration logging <a href="https://github.com/spring-projects/spring-boot/pull/33569" data-hovercard-type="pull_request" data-hovercard-url="/spring-projects/spring-boot/pull/33569/hovercard">#33569</a></li> <li>Web server fails to start due to "Resource location must not be null" when attempting to use a PKCS 11 KeyStore <a href="https://github.com/spring-projects/spring-boot/pull/32179" data-hovercard-type="pull_request" data-hovercard-url="/spring-projects/spring-boot/pull/32179/hovercard">#32179</a></li></ul><h4> <g-emoji class="g-emoji" alias="notebook_with_decorative_cover" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f4d4.png">  📔 </g-emoji> Documentation</h4><ul> <li>Improve gradle plugin tags documentation <a href="https://github.com/spring-projects/spring-boot/pull/33614" data-hovercard-type="pull_request" data-hovercard-url="/spring-projects/spring-boot/pull/33614/hovercard">#33614</a></li> <li>Improve maven plugin tags documentation <a href="https://github.com/spring-projects/spring-boot/pull/33609" data-hovercard-type="pull_request" data-hovercard-url="/spring-projects/spring-boot/pull/33609/hovercard">#33609</a></li> <li>Fix typo in tomcat accesslog checkExists doc <a href="https://github.com/spring-projects/spring-boot/pull/33460" data-hovercard-type="pull_request" data-hovercard-url="/spring-projects/spring-boot/pull/33460/hovercard">#33460</a></li> <li>Document that the shutdown endpoint is not intended for use when deploying a war to a servlet container <a href="https://github.com/spring-projects/spring-boot/issues/17398" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/17398/hovercard">#17398</a></li></ul><h4> <g-emoji class="g-emoji" alias="hammer" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f528.png">  🔨 </g-emoji> Dependency Upgrades</h4><ul> <li>Upgrade to Byte Buddy 1.12.20 <a href="https://github.com/spring-projects/spring-boot/issues/33570" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/33570/hovercard">#33570</a></li> <li>Upgrade to Dropwizard Metrics 4.2.14 <a href="https://github.com/spring-projects/spring-boot/issues/33571" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/33571/hovercard">#33571</a></li> <li>Upgrade to Elasticsearch 7.17.8 <a href="https://github.com/spring-projects/spring-boot/issues/33572" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/33572/hovercard">#33572</a></li> <li>Upgrade to HttpClient 4.5.14 <a href="https://github.com/spring-projects/spring-boot/issues/33573" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/33573/hovercard">#33573</a></li> <li>Upgrade to HttpCore 4.4.16 <a href="https://github.com/spring-projects/spring-boot/issues/33574" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/33574/hovercard">#33574</a></li> <li>Upgrade to Infinispan 13.0.14.Final <a href="https://github.com/spring-projects/spring-boot/issues/33575" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/33575/hovercard">#33575</a></li> <li>Upgrade to Jaybird 4.0.8.java8 <a href="https://github.com/spring-projects/spring-boot/issues/33576" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/33576/hovercard">#33576</a></li> <li>Upgrade to Jetty 9.4.50.v20221201 <a href="https://github.com/spring-projects/spring-boot/issues/33577" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/33577/hovercard">#33577</a></li> <li>Upgrade to MSSQL JDBC 10.2.2.jre8 <a href="https://github.com/spring-projects/spring-boot/issues/33578" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/33578/hovercard">#33578</a></li> <li>Upgrade to Neo4j Java Driver 4.4.11 <a href="https://github.com/spring-projects/spring-boot/issues/33579" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/33579/hovercard">#33579</a></li> <li>Upgrade to Netty 4.1.86.Final <a href="https://github.com/spring-projects/spring-boot/issues/33580" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/33580/hovercard">#33580</a></li> <li>Upgrade to Reactor 2020.0.26 <a href="https://github.com/spring-projects/spring-boot/issues/33543" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/33543/hovercard">#33543</a></li> <li>Upgrade to Spring Integration 5.5.16 <a href="https://github.com/spring-projects/spring-boot/issues/33581" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/33581/hovercard">#33581</a></li> <li>Upgrade to Spring Security 5.7.6 <a href="https://github.com/spring-projects/spring-boot/issues/33544" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/33544/hovercard">#33544</a></li> <li>Upgrade to Thymeleaf Extras SpringSecurity 3.0.5.RELEASE <a href="https://github.com/spring-projects/spring-boot/issues/33582" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/33582/hovercard">#33582</a></li> <li>Upgrade to Tomcat 9.0.70 <a href="https://github.com/spring-projects/spring-boot/issues/33583" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/33583/hovercard">#33583</a></li> <li>Upgrade to UnboundID LDAPSDK 6.0.7 <a href="https://github.com/spring-projects/spring-boot/issues/33584" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/33584/hovercard">#33584</a></li> <li>Upgrade to Undertow 2.2.22.Final <a href="https://github.com/spring-projects/spring-boot/issues/33585" data-hovercard-type="issue" data-hovercard-url="/spring-projects/spring-boot/issues/33585/hovercard">#33585</a></li></ul></details>

This PR is created by GitHub Actions: https://github.com/Azure/spring-cloud-azure-tools/actions/runs/3762084144

### CODE REVIEW

**Comment by Netyyyy** [comment]
Hi @alzimmermsft , please take a look

**Review by alzimmermsft — APPROVED** [review]
Updates look good to me. I checked the failing KeyVault tests against previous runs and these appear to have been happening for a while and what's failing in this PR is consistent with previous runs.

**Pull request merged**
