### PR TITLE
Add vmId to VirtualMachine

### PR DESCRIPTION
**Pull request by noamledany**
The vmId is exposed via REST but it is not part of the SDK

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@noaml2gitHub__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@noaml2gitHub__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by noaml2gitHub** [comment]
Hi guys,

Do you know when you can approve my change?

**Comment by jianghaolu** [comment]
Hi @noaml2gitHub 

Thanks for contributing! However, the code in this repo is generated from our REST API specs. Could you submit a pull request to https://github.com/Azure/azure-rest-api-specs/blob/master/arm-compute/2016-03-30/swagger/compute.json? The owners of the specs will review it and after that this can be included in our next 1.0.0-beta release.

Thanks,
Jianghao

**Comment by noaml2gitHub** [comment]
Hi @jianghaolu,

I'm not sure this will help me... please fix me if I'm wrong here.
The vmId field is available via REST - but it is not part of the SDK, to be more precise, the VirtualMachine object does not have a String vmId member, so when the REST call is returned, though available via REST, this value is not present on the virtual machine.
I need this value in order to uniquely identify this virtualMachine object - and I cannot use the id value since it is based on the vm's name.

Please let me know what I'm missing here.

Thanks,

Noam

**Comment by jianghaolu** [comment]
@noaml2gitHub 

What you are missing is we are not the owner of the VM functionalities. :) I know it's a little confusing but you can understand it as *we write the SDK based on what the virtual machine team tells us to do* and I don't personally have the expertise to modify what the properties are available.

I've filed the issue for you here: https://github.com/Azure/azure-rest-api-specs/issues/188 and that should get a more direct audience.

**Pull request closed without merging**
