### PR TITLE
Test version compatibility of spring-boot:v2.7.0-M3

### PR DESCRIPTION
**Pull request by Netyyyy**
As title,
refer to https://github.com/Azure/azure-sdk-for-java/issues/27864

### CODE REVIEW

**Comment by Netyyyy** [comment]
Hi @alzimmermsft , I'm testing the compatibility of 2.7.0, please take a look and fix this [error](https://dev.azure.com/azure-sdk/public/_build/results?buildId=1495229&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=ba3cf43a-b2bf-50f9-f95f-93049ca44ad1&l=1544), thanks

**Comment by alzimmermsft** [comment]
To fix the RevApi issue you need to add this as an exclusion in the RevApi configurations

```json
{
  "matcher": "java-package",
  "match": "/com\\.google\\.gson(\\..*)?/"
},
```

**Pull request closed without merging**
