### PR TITLE
fix sample to use correct listIncomingRelationships() overload

### PR DESCRIPTION
**Pull request by johngallardo**
# Description

Update sample to use correct overload of listIncomingRelationships.

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [ ] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Comment by v-xuto** [comment]
@johngallardo Any progress about this PR?

**Review by sjiherzig — APPROVED** [review]

**Comment by sjiherzig** [comment]
@v-xuto can you help merge this PR? We are seeing "Required status check "license/cla" was not set by the expected GitHub app.".

**Comment by johngallardo** [comment]
> @johngallardo Any progress about this PR?

It looks blocked by this... how do we resolve @v-xuto ?
image

**Comment by v-xuto** [comment]
@johngallardo Thanks for your prompt feedback. But I don't have permission to merge this PR either.

**Pull request merged**
