### PR TITLE
Enable Federated Auth

### PR DESCRIPTION
**Pull request by g2vinay**
Enabled federated auth by default in the eng sys template.

### CODE REVIEW

**Comment by benbp** [comment]
This PR should also remove the `tests.yml` lines where it's currently set to true: https://github.com/search?q=repo%3AAzure%2Fazure-sdk-for-java%20UseFederatedAuth&type=code

**Comment by g2vinay** [comment]
> This PR should also remove the `tests.yml` lines where it's currently set to true: https://github.com/search?q=repo%3AAzure%2Fazure-sdk-for-java%20UseFederatedAuth&type=code

Thanks,
Will be easier to do that per service in a follow up PR post validating their pipelines are picking up the global property.

Merging this now, will enforce it on any areas where it isn't enforced.

**Review by benbp — APPROVED** [review]

**Review by weshaggard — APPROVED** [review]

**Pull request merged**
