### PR TITLE
[BUG] Set secret operation of the Key Vault Secrets Client overrides the content type of the secret with application/json

### PR DESCRIPTION
**Pull request by nagyesta**
# Description

- Fixes sync and async implementations to use the contentType value set by the caller in the payload
- Adds entry to changelog

Resolves https://github.com/Azure/azure-sdk-for-java/issues/37019

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [ ] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Comment by nagyesta** [comment]
Hi,
I wasn't sure how to modify the test data for the mock/stub used. Could you please let me know how to add a new assertion?
Thank you in advance!

**Comment by vcolin7** [comment]
@nagyesta The root cause analysis is spot on and the proposed changes look good on principle, but they required a bit more tinkering to keep things working as they used to before the latest release. Additionally, there were other `setSecret...` and `updateSecret...` methods with this issue to update as well. I took the liberty of creating [a PR with these changes](https://github.com/nagyesta/azure-sdk-for-java/pull/2) against your branch to keep your authorship for when we eventually merge into `main`, feel free to review it and merge into your branch when you get a chance.

**Comment by vcolin7** [comment]
We auto-generate some of the code found in this library and I'm not 100% sure yet about if we'll need to account for that with these changes. If that's the case I will take care of it on a separate PR.

**Comment by nagyesta** [comment]
Hi @vcolin7 ,
thank you very much for the PR and apologies for missing those! I have merged your changes into my branch.
Please let me know in case anything comes up, I am happy to help!

**Comment by vcolin7** [comment]
@nagyesta No worries, thank you for opening the issue and taking things in the right direction! I added a couple of things I missed in my original PR and re-recorded our tests (we use test recordings to avoid testing against the service every time).

**Review by vcolin7 — APPROVED** [review]

**Pull request merged**
