### PR TITLE
fix bug of fetching paging info from Microsoft Graph API

### PR DESCRIPTION
**Pull request by yiliuTo**
Fix bug of issue #17120 
Ref: https://docs.microsoft.com/graph/paging?toc=./ref/toc.json&view=graph-rest-1.0
       https://docs.microsoft.com/en-us/previous-versions/azure/ad/graph/howto/azure-ad-graph-api-supported-queries-filters-and-paging-options#paging-support-
Modify the property to receive next page link of membership information from Graph API to support both `odata.nextLink`(Azure AD Graph API) and `@odata.nextLink`(Microsoft Graph API).

### CODE REVIEW

**Review by saragluna — APPROVED** [review]
LGTM.

**Comment by chenrujun** [comment]
Hi, @yiliuTo , could you please write unit test for this?
Seems we already have json file for this test: 
https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring/azure-spring-boot/src/test/resources/aad

**Pull request merged**
