### PR TITLE
CheckStyle Rule: ServiceClient naming

### LINKED ISSUE #3367: CheckStyle: Service Client Naming
All service clients should be named \<ServiceName\>AsyncClient or \<ServiceName\>Client.

### PR DESCRIPTION
**Pull request by mssfang**
Adding ServiceClient naming rule:

All service clients should be named \<ServiceName\>AsyncClient or \<ServiceName\>Client.

Fixes #3367

### CODE REVIEW

**Comment by JonathanGiles** [comment]
It is not correct to use the term 'instance' anywhere in this code - we are not checking the naming of instances of the type, we are checking on the naming of the type itself. In other words, is the class named correctly, not any specific instance created from that class.

**Comment by JonathanGiles** [comment]
@mssfang What is the status of this pull request?

**Comment by mssfang** [comment]
Haven't been pay attention to this thread for a long time. Since I am just free up from Event Hub Previous 1. I will be working on this item,

**Comment by mssfang** [comment]
No longer needed. This rule is implemented at #4250

**Pull request closed without merging**
