### PR TITLE
Update github account from chenrujun to rujche

### PR DESCRIPTION
**Pull request by rujche**
# Description

Update github account from **chenrujun** to **rujche**.

## Why creating a new github account
I can't use my previous github account because of 2 FA. After trying the methods provided in this page: [Recovering your account if you lose your 2FA credentials](https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa/recovering-your-account-if-you-lose-your-2fa-credentials), I still can't get my previous account (chenrujun) back. So I created a new account (rujche). 

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [x] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Comment by rujche** [comment]
Hi, @saragluna . 
1. Please help to review this PR.
2. The `java - codeowners-linter - ci` failed because I don't have this repo's write authority. To this this problem, I already asked to join this team: https://github.com/orgs/Azure/teams/azure-sdk-push-spring

**Review by saragluna — APPROVED** [review]

**Comment by Netyyyy** [comment]
Hi @rujche , please also update for [SB3](https://github.com/Azure/azure-sdk-for-java/blob/feature/spring-boot-3/.github/CODEOWNERS) branch

**Comment by weshaggard** [comment]
@rujche you need to make your account public in Azure org, and ensure you join azure-sdk-partners. See https://aka.ms/azsdk/access

**Comment by rujche** [comment]
@weshaggard 

Thank you for your information.
Now in this page: https://github.com/orgs/Azure/people?query=rujche
rujche is already a public member of Azure:
> image

But the pipeline still failed.
I suppose it's caused by some latency, I'll retry tomorrow.

**Pull request merged**
