### PR TITLE
Azure Media Services Content Protection updates and new features

### PR DESCRIPTION
**Pull request by mconverti**
- Upgrade targeted REST API version from 2.5 to 2.11 
- Support for ContentKeyAuthorizationPolicy entity
- Support for ContentKeyAuthorizationPolicyOptions entity
- Support for ContentKeyAuthorizationPolicyRestrictions complex type
- Support for AssetDeliveryPolicy entity
- Support for ContentKeyDeliveryType enumeration
- Support for ContentKeyType.EnvelopeEncryption enumeration value
- Update Asset entity
- Update ContentKey entity
- Add helpers for TokenRestrictionTemplate classes (TokenRestrictionTemplateSerializer)
  - Support for TokenType enumeration
  - Support for TokenClaim entity
  - Support for TokenVerificationKey entity
  - Support for SymmetricTokenVerificationKey entity
  - Support for AsymmetricTokenVerificationKey entity
  - Support for X509CertTokenVerificationKey entity
  - Support for TokenRestrictionTemplate entity
  - Implement serialize/deserialize on TokenRestrictionTemplateSerializer
  - Add GenerateTestToken helper method in TokenRestrictionTemplateSerializer (for both SWT and JWT formats)
- Add helpers for PlayReadyLicenseResponseTemplate classes (MediaServicesLicenseTemplateSerializer)
  - Support for UnknownOutputPassingOption entity
  - Support for ExplicitAnalogTelevisionRestriction entity
  - Support for AgcAndColorStripeRestriction entity
  - Support for ScmsRestriction entity
  - Support for PlayReadyContentKey entity (ContentEncryptionKeyFromHeader and ContentEncryptionKeyFromKeyIdentifier)
  - Support for PlayReadyLicenseType entity
  - Support for PlayReadyPlayRight entity
  - Support for PlayReadyLicenseTemplate entity
  - Support for PlayReadyLicenseResponseTemplate entity
  - Support for serialization-time validations in MediaServicesLicenseTemplateSerializer
- Add/Update unit/functional tests
- Update README.md listing new entities and operations

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@mconverti__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (geotri(EXTERNAL)). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by ljhljh235** [comment]
@azuresdkci add to whitelist

**Comment by mconverti** [comment]
It seems that there are some issues with the integration tests configuration in the build server. Are you using a valid set of Media Services and Storage accounts credentials?

All the unit/integration tests run without any issues in my local dev box.

Regards,
Mariano

**Comment by ljhljh235** [comment]
Do you have access to https://github.com/Azure/azure-sdk-for-java-pr?

**Comment by mconverti** [comment]
@ljhljh235 yes, I can see that private repo.

**Comment by ljhljh235** [comment]
Cool.

In fact, dev work goes into azure-sdk-for-java-pr repo and we have better support for testing over there. The testing setup of public is outdated and that’s why the current pull request is failing the check. When we release we merge from private to public. No, this is not sustainable but it’s about to change.
 
For now the pull request looks great as long as it can go against our private repo. What needs to be done is
 
1)      Add the private repo as a remote locally and fetch dev
2)      Merge the work in southworkscom:content-protection-update into this latest dev (conflicts should be minimal)
3)      Create a pull request against private repo
 
Sorry if this process is confusing before it gets cleared out.

**Comment by mconverti** [comment]
ACK, thanks for the details. I'll follow your instructions to send the pull request to the private repository.

I have more new features ready to publish as well, so I will include them in the new pull request against https://github.com/Azure/azure-sdk-for-java-pr.

Thanks,
Mariano

**Comment by mconverti** [comment]
@ljhljh235 should I close this pull request?

**Comment by ljhljh235** [comment]
@mconverti Sounds great! Let me know if anything else is needed.

Yes, feel free to close this one.

**Comment by mconverti** [comment]
@ljhljh235 I just wanted to let you know that I sent the final pull request to the private repository @ https://github.com/Azure/azure-sdk-for-java-pr/pull/1032

Regards,
Mariano

**Pull request closed without merging**
