### PR TITLE
Removes duplicate test suite to reduce the test CI running time.

### PR DESCRIPTION
**Pull request by moderakh**
- Query BackPressure tests rely on RxDocumentClientUnderTest. However RxDocumentClientUnderTest spy is only capable of capturing gw http requests. hence running BackPressure tests against Direct mode is not testing anything.
- We have dedicated test suite for multi master (fast and multi-master). Running long test suite against multi master account is not required as there is no specific test in this test suite which needs to be tested against a multi master account. see the long test suites bellow:
```bash
find .  | egrep "\.java$" | xargs grep long | grep groups
./implementation/TestSuiteBase.java:    @BeforeSuite(groups = {"simple", "long", "direct", "multi-master", "emulator", "non-emulator"}, timeOut = SUITE_SETUP_TIMEOUT)
./implementation/TestSuiteBase.java:    @AfterSuite(groups = {"simple", "long", "direct", "multi-master", "emulator", "non-emulator"}, timeOut = SUITE_SHUTDOWN_TIMEOUT)
./implementation/RetryThrottleTest.java:    @Test(groups = { "long" }, timeOut = LARGE_TIMEOUT, enabled = false)
./implementation/RetryThrottleTest.java:    @Test(groups = { "long" }, timeOut = TIMEOUT, enabled = false)
./implementation/RetryThrottleTest.java:    @AfterMethod(groups = { "long" }, enabled = false)
./implementation/RetryThrottleTest.java:    @BeforeClass(groups = { "long" }, timeOut = SETUP_TIMEOUT, enabled = false)
./implementation/RetryThrottleTest.java:    @AfterClass(groups = { "long" }, timeOut = SHUTDOWN_TIMEOUT, enabled = false)
./implementation/routing/LocationCacheTest.java:    @Test(groups = "long", dataProvider = "paramsProvider")
./implementation/routing/LocationCacheTest.java:    @Test(groups = "long")
./rx/UniqueIndexTest.java:    @Test(groups = { "long" }, timeOut = TIMEOUT)
./rx/UniqueIndexTest.java:    @Test(groups = { "long" }, timeOut = TIMEOUT * 1000)
./rx/UniqueIndexTest.java:    @Test(groups = { "long" }, timeOut = TIMEOUT)
./rx/UniqueIndexTest.java:    @BeforeClass(groups = { "long" }, timeOut = SETUP_TIMEOUT)
./rx/UniqueIndexTest.java:    @AfterClass(groups = { "long" }, timeOut = SHUTDOWN_TIMEOUT, alwaysRun = true)
./rx/TestSuiteBase.java:    @BeforeSuite(groups = {"simple", "long", "direct", "multi-master", "emulator", "non-emulator"}, timeOut = SUITE_SETUP_TIMEOUT)
./rx/TestSuiteBase.java:    @AfterSuite(groups = {"simple", "long", "direct", "multi-master", "emulator", "non-emulator"}, timeOut = SUITE_SHUTDOWN_TIMEOUT)
./rx/BackPressureCrossPartitionTest.java:    @Test(groups = { "long" }, dataProvider = "queryProvider", timeOut = 2 * TIMEOUT)
./rx/BackPressureCrossPartitionTest.java:    @Test(groups = { "long" }, dataProvider = "queryProvider", timeOut = 2 * TIMEOUT)
./rx/BackPressureCrossPartitionTest.java:    @BeforeClass(groups = { "long" }, timeOut = SETUP_TIMEOUT)
./rx/BackPressureCrossPartitionTest.java:    @AfterClass(groups = { "long" }, timeOut = 2 * SHUTDOWN_TIMEOUT, alwaysRun = true)
./rx/BackPressureTest.java:    @Test(groups = { "long" }, timeOut = 3 * TIMEOUT)
./rx/BackPressureTest.java:    @Test(groups = { "long" }, timeOut = 3 * TIMEOUT)
./rx/BackPressureTest.java:    @Test(groups = { "long" }, timeOut = 3 * TIMEOUT)
./rx/BackPressureTest.java:    @Test(groups = { "long" }, timeOut = 3 * TIMEOUT)
./rx/BackPressureTest.java:    @BeforeClass(groups = { "long" }, timeOut = 2 * SETUP_TIMEOUT)
./rx/BackPressureTest.java:    @AfterClass(groups = { "long" }, timeOut = 2 * SHUTDOWN_TIMEOUT, alwaysRun = true)
```

### CODE REVIEW

**Review by FabianMeiswinkel — APPROVED** [review]

**Review by kushagraThapar — APPROVED** [review]
Thanks @moderakh , LGTM

**Pull request merged**
