### PR TITLE
Update pipeline Python version

### PR DESCRIPTION
**Pull request by JimSuplizio**
1. Centralize the Python version used in the Java pipelines by adding PythonVersion it to globals.yml
2. Update the Java yml files to use the PythonVersion

I also did a release of the template libraries to ensure the changes to the release template were good.

### CODE REVIEW

**Review by alzimmermsft — APPROVED** [review]

**Comment by JimSuplizio** [comment]
I'm going to override check enforcer, the from source run has a couple of flaky tests (look at the pipeline history) that are most certainly not caused by the python version being updated.

**Pull request merged**
