### PR TITLE
addressing zonal VMSS offline review comments (#1930)

### PR DESCRIPTION
**Pull request by andrewchoi5**
* addressing zonal VMSS offline review comments

* addressing zonal VMSS offline review comments

### CODE REVIEW

**Comment by joshfree** [comment]
@yungezz could you help reviews this old `mgmt` PR from February?

**Comment by yungezz** [comment]
> @yungezz could you help reviews this old `mgmt` PR from February?

sure. thanks @joshfree for reminder.

**Comment by xccc-msft** [comment]
@andrewchoi5 It looks you worked on a quite old branch, could you please check the latest master branch and sync this PR or open a new one for your changes? Thanks.

**Comment by JonathanGiles** [comment]
No response from @andrewchoi5 in the last week. @xccc-msft and @yungezz If you want to accept this PR, it may require effort on your behalf. Do you plan to do this or otherwise, are you ok with closing this PR? Thanks!

**Comment by yungezz** [comment]
hi @andrewchoi5 thanks for your contribution. Since the branch diverged a lot, is it ok to close the PR for now, and feel free to create new one?

**Comment by yungezz** [comment]
close it for now. Feel free to create new one. thanks.

**Pull request closed without merging**
