### PR TITLE
Delete un-supported AAD features.

### LINKED ISSUE #23710: Implement azure-spring-security 4.0
Design doc:

 https://github.com/Azure/azure-sdk-for-java/wiki/Spring-Security-for-Azure-design

 - [x] https://github.com/Azure/azure-sdk-for-java/issues/23922
 - [x] https://github.com/Azure/azure-sdk-for-java/issues/23932
 - [x] https://github.com/Azure/azure-sdk-for-java/issues/23942
 - [x] https://github.com/Azure/azure-sdk-for-java/issues/24353

### LINKED ISSUE #23922: Delete un-supported AAD features.
Parent issue: #23710

Delete these features of AAD in azure-spring-boot-starter-active-directory:

1. group-name based access control. Discussed with AAD developers, they think that group-name should not used to authorize, because group-name can be changed in Azure AD. We should use [Role-based access control (RBAC)] instead.
2. group-id based access control. group-id is not human understandable when develop web-application. We should use [Role-based access control (RBAC)] instead.
3. AADAuthenticationFilter and AADAppRoleStatelessAuthenticationFilter. spring-security-oauth2-resource-server has provided resource-server feature, we should delete our resource-server implementation. The filter implementation was first add in  microsoft/azure-spring-boot#97 It's on 2017-08-07. At that time, there is no [spring-security-oauth2-resource-server]. 

[spring-security-oauth2-resource-server]: https://repo1.maven.org/maven2/org/springframework/security/spring-security-oauth2-resource-server/
[Role-based access control (RBAC)]: https://docs.microsoft.com/en-us/azure/active-directory/develop/custom-rbac-for-developers

### PR DESCRIPTION
**Pull request by chenrujun**
Resolve #23922

### CODE REVIEW

**Comment by stliu** [comment]
is this PR finished?
I can only see you deleted a bunch of staff

**Comment by chenrujun** [comment]
> is this PR finished?
> I can only see you deleted a bunch of staff

@stliu , 
No, It's not finished. 
But it's OK to review, If we review it after finished all parts, it will be difficult (too big) to review.
So I suggest to review commits. 

If the reviewer think current commits is OK to merge, I'll merge it.

**Comment by stliu** [comment]
but how to say "OK" safely with incompletable  information?

**Comment by chenrujun** [comment]
> but how to say "OK" safely with incompletable information?

One commit is a complete information, it's a stand alone task.
So I suggest reviewers review this PR by commits.

image

**Comment by stliu** [comment]
I can only see you deleted something in a commit, if that's the completed information, then of course I'd say no, why delete those files? don't we need them anymore?

**Comment by chenrujun** [comment]
> why delete those files? don't we need them anymore?

Yes, we don't need them any more.
These features are not suggested to use by Azure Active Directory team. (And it's not a standard usage.)
These features are already deprecated in version 3.x.x.
So I plan to delete them in version 4.0.0.

**Comment by stliu** [comment]
if so, wouldn't it be more appreciated to have separated PR for each task instead of all grouped into this general "implement azure spring security 4.0"?

for example, this removes some feature, I think it deserves its own github issue with detailed info of :
* why
* how to migrate

**Comment by chenrujun** [comment]
> if so, wouldn't it be more appreciated to have separated PR for each task instead of all grouped into this general "implement azure spring security 4.0"?


If I do like that, then PR2 depends on PR1, and PR3 depends on PR 2, etc..
We can let PR2 have commits of PR1, and PR3 depends on PR2. Do like this will have a problem: If PR 1 have more commits, the both PR2 and PR3 need rebase.

So I prefer to use one PR.


> how to migrate

My current plan is write doc after coding work finished.

**Comment by stliu** [comment]
NO, pull request is not working like what your describe.

One PR should do one specific change, having a corresponding issues link to it
in this case, I suggest you create a issue ( probably should be a sub-task of implementing azure spring security 4.0) to remove the code.
btw, this sub-task is what I asked "task list"

you can't use one PR to do all the works, that would make things untrackable.

**Comment by chenrujun** [comment]
Hi, @stliu .
I updated the PR's title, and created new issue to track this PR.

Hi, @saragluna , @zhichengliu12581 .
Could you please help to review this PR when you have time?

**Review by stliu — APPROVED** [review]

**Pull request merged**
