### PR TITLE
[For Test] Upgrade spring boot to 2.6.0-M1

### PR DESCRIPTION
**Pull request by ZhuXiaoBing-cn**
1. Update ROOT_POMS' version manually.
2. Run command "python .\sdk\spring\scripts\update_spring_managed_external_dependencies.py".
3. Run command "python .\eng\versioning\update_versions.py --ut external_dependency --sr".
4. Run command ".\eng\versioning\pom_file_version_scanner.ps1 -Debug". If there is error, fix it.

### CODE REVIEW

**Comment by ZhuXiaoBing-cn** [comment]
1. There is no need to pay attention to cosmos integration test failed items at present.
2. The failed integration test of keyvault certificate is currently being repaired [23549](https://github.com/Azure/azure-sdk-for-java/pull/23549).

**Comment by chenrujun** [comment]
Test passed. Closing this PR.

**Pull request closed without merging**
