### PR TITLE
Add `ARRAY_CONTAINS` CriteriaType

### PR DESCRIPTION
**Pull request by sleepo581**
This pull request adds support for [ARRAY_CONTAINS](https://docs.microsoft.com/en-us/azure/cosmos-db/sql-query-array-contains) function in cosmos template. Queries, which  use this function, can be generated by using `@Query` annotation, however this is not an option, when query needs to be dynamically constructed.

### CODE REVIEW

**Comment by kushagraThapar** [comment]
@sleepo581 - thank you for your contribution, we will review this PR shortly. We would appreciate if you can also add some test cases for `ARRAY_CONTAINS`. 

@mbhaskar - Can you please review it ?

**Comment by sleepo581** [comment]
> @sleepo581 - thank you for your contribution, we will review this PR shortly. We would appreciate if you can also add some test cases for `ARRAY_CONTAINS`.

Added integration test with new CriteriaType

**Review by kushagraThapar — CHANGES_REQUESTED** [review]
Please also add test cases for `BETWEEN` clause.

**Comment by sleepo581** [comment]
@kushagraThapar 
> Please also add test cases for `BETWEEN` clause.
Added a test for `BETWEEN` clause as well.

**Comment by mbhaskar** [comment]
@sleepo581 Thankyou for submitting the changes. ARRAY_CONTAINS is a function, dont you think this has to be added into CriteriaType.isFunction?
Thanks

**Comment by sleepo581** [comment]
@mbhaskar 
> @sleepo581 Thankyou for submitting the changes. ARRAY_CONTAINS is a function, dont you think this has to be added into CriteriaType.isFunction?
> Thanks

It's already added here https://github.com/Azure/azure-sdk-for-java/pull/15921/files#diff-07526f809d18ec84484aded7768c165cR183.

**Review by mbhaskar — APPROVED** [review]
Looks good to me

**Review by kushagraThapar — APPROVED** [review]

**Comment by totakura** [comment]
@sleepo581 can you please give an example of how to construct the repository method name to be able to use it?  I tried using `findByAgesArrayContains(int age)` but that didn't work.

**Pull request merged**
