### PR TITLE
Upgrade to spring boot 2.5.3

### PR DESCRIPTION
**Pull request by chenrujun**
Upgrade to spring boot 2.5.3.

### CODE REVIEW

**Comment by chenrujun** [comment]
Hi, @saragluna , please help to review this PR.

**Comment by chenrujun** [comment]
Hi, @vcolin7 .
Could you please fix this pipeline failure? https://dev.azure.com/azure-sdk/public/_build/results?buildId=1013308&view=logs&j=02b43782-5767-5741-285b-4998932e1f31&t=bf919cbc-d2ee-5807-2f85-d24cabc526e8&l=24

It's OK to fix it in another PR. 
I'll merge this PR, ignore the pipeline failure.

**Comment by chenrujun** [comment]
Hi, @yiliuTo, @backwind1233 , please help to review this PR.

**Comment by backwind1233** [comment]
@chenrujun it seems pipeline "java - tables - ci" failed

**Review by backwind1233 — APPROVED** [review]
LGTM

**Review by yiliuTo — APPROVED** [review]
LGTM

**Comment by chenrujun** [comment]
Ignore the test failures, because they are not caused by this PR.

**Pull request merged**
