### PR TITLE
[EngSys-CredScan] Remove some supppression and run the pipeline

### PR DESCRIPTION
**Pull request by mssfang**
Remove unused suppressions in the CredScan file.

### CODE REVIEW

**Review by weshaggard — APPROVED** [review]
The change looks good to me assuming we don't hit any issues because of it. I do like the direction though and we should try to consolidate down to as few placeholders as possible.

**Comment by sima-zhu** [comment]
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1927708&view=results

**Review by sima-zhu — APPROVED** [review]
No error reports. Safe to merge.

**Comment by benbp** [comment]
@mssfang you'll need to `/check-enforcer override`. There are no pipelines defined for this code path, so evaluate won't detect anything.

**Pull request merged**
