### PR TITLE
Adding LinkedIn ctl image upload in automation script

### PR DESCRIPTION
**Pull request by simplynaveen20**
Adding LinkedIn ctl image upload in automation script

### CODE REVIEW

**Review by kushagraThapar — APPROVED** [review]
LGTM!

**Review by danieljurek — APPROVED** [review]
Chatted w/ @simplynaveen20 

This scenario has been around for a while but this onboards the scenario into CI. Based on the pipeline configuration whenever a change happens in the default branch the CI will run and publish a new container. 

In the future this scenario should be renamed to describe what is testing and not necessarily who the testing is for.

**Pull request merged**
