### PR TITLE
SetProps/GetProps tests changed to Generic Exception to avoid ReactiveException

### PR DESCRIPTION
**Pull request by ibrahimrabab**
# Description

Changed tests for Blobs and DataLake ServiceApiTests.setPropsError and getPropsError to expect a generic error message.

### CODE REVIEW

**Review by alzimmermsft — APPROVED** [review]

**Comment by ibrahimrabab** [comment]
> /check-enforcer override

Overrided since the failing test in pipeline is unrelated to these changes.

**Pull request merged**
