### PR TITLE
Add "eng" folder to core path triggers

### PR DESCRIPTION
**Pull request by mikeharder**
- Core is a good pipeline to run on changes under "eng" folder
- Aligns Java with other languages

### CODE REVIEW

**Comment by alzimmermsft** [comment]
MacOS failure is unrelated to this change. Feel free to merge away.

**Comment by mikeharder** [comment]
> Could this be further scoped to code-quality-reports, spotbugs-aggregate, and the client specific YML templates in the future?

DevOps only supports triggering on folders, not individual files.  So it could be scoped to a more narrow set of folders if it exists.

**Comment by mikeharder** [comment]
> > Could this be further scoped to code-quality-reports, spotbugs-aggregate, and the client specific YML templates in the future?
> 
> DevOps only supports triggering on folders, not individual files. So it could be scoped to a more narrow set of folders if it exists.

Actually it looks like DevOps does support individual files and wildcards, but so far we have kept it simple and just used folders.

https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#paths

**Comment by mikeharder** [comment]
@alzimmermsft: If including all of "eng" causes too many unnecessary builds we can narrow the scope.

**Comment by weshaggard** [comment]
>Could this be further scoped to code-quality-reports, spotbugs-aggregate, and the client specific YML templates in the future?

What are you trying to avoid, under eng?

**Pull request merged**
