### PR TITLE
Use release version instead of current version in spring sample projects

### PR DESCRIPTION
**Pull request by chenrujun**

### CODE REVIEW

**Comment by chenrujun** [comment]
Hi, @saragluna , @JimSuplizio .
Please review. 🙏

**Comment by chenrujun** [comment]
@saragluna 
> will the versions in the sample projects be updated too when running the update_version script now?

Yes, this command will update versions in sample projects:
```
python eng/versioning/update_versions.py --ut library --bt client --sr
```

**Comment by chenrujun** [comment]
@JimSuplizio 

> I would like to start seeing descriptions in your PRs. This one is relatively straightforward, at least for the version changes, but I had to exhaustively go though to your changes to the scripts to effectively see what was going on there.

I write some information in the commit message. Like:


> The changes to both the update_versions.py and set_versions.py consist of 1 spelling error (externaly to external ), some formatting changes and some rearranging of the from/import (which is no more consistent to what was actually there). If there was a bug fix that would be fine but there isn't and as such, these changes do no belong in this PR. If you feel the need to reformat and update these then please do it in a separate PR.

Actually, for the scripts, there is not logic change, just format code or fix typo. I added message in the commit info.
When merge the PR, if the commits will not been squashed, I think it's OK to merge.
Since the commit info will be squashed, I'll recover the scripts in this PR.

**Comment by saragluna** [comment]
Hey @JimSuplizio, @chenrujun has tested these changes locally and the dependency versions could be updated correctly when we perform releases. So I'm going to approve this PR now and plan to merge it tomorrow. Let me know if you have any concerns.

**Review by saragluna — APPROVED** [review]
LGTM.

**Pull request merged**
