### PR TITLE
Updating root readme to simplify messaging

### PR DESCRIPTION
**Pull request by JonathanGiles**
Proposing a simplification to the root readme - let me know your thoughts. In particular, I'm proposing that we consider removing mention of the 'old' libraries, and the distinction with the 'new' libraries. Now we just have 'client' and 'management' libraries.

### CODE REVIEW

**Comment by lfraleigh** [comment]
Can we also make updates to ensure we're using stable, rather than GA, and beta, rather than preview? They are used inconsistently throughout the README.

I'm wondering if it would be worth a simple call out at the bottom, that says something like "If you're using libraries that start with microsoft-azure. or azure-mgmt, please migrate to the latest libraries."  I agree making the meat of the README simpler is better going forward, but having this as a "NOTE" or something similar at the bottom, after all other critical info, could benefit the older users.

**Review by lfraleigh — APPROVED** [review]
LGTM

**Review by joshfree — APPROVED** [review]

**Review by sandeep-sen — COMMENTED** [review]
Looks good to me

**Pull request merged**
