### PR TITLE
Should use the different storage account and eventhub namespace variables for live tests

### PR DESCRIPTION
**Pull request by moarychan**
Follow this PR [Upgrade Sinks api for eventhub/servicebus IT case](https://github.com/Azure/azure-sdk-for-java/pull/20343)'s comments, improve live test configuration for reducing resource creation.

Conclusion:
- We should use different eventhub namespaces and storage account for each IT class due to the different parameter 'baseName' value.
- Use junit 5 classes.

### CODE REVIEW

**Comment by moarychan** [comment]
@saragluna please help to commit the live test command, thanks.

**Comment by chenrujun** [comment]
Please check the pipeline log, make sure related integration tests are executed.

I'm fixing the problem that pipeline passed but tests are not executed.
Refs: https://github.com/Azure/azure-sdk-for-java/pull/20700

**Review by saragluna — APPROVED** [review]
LGTM.

**Comment by moarychan** [comment]
Hi @saragluna , I found the guide about [migration from Junit 4](https://junit.org/junit5/docs/current/user-guide/#migrating-from-junit4) and the other post of [Junt 5 architecture introduce](https://nipafx.dev/junit-5-architecture-jupiter/). Currently, the configuration will trigger all Junit test cases we used,   after upgrade all the Junit 4 test cases, it's possible to remove the `junit-vintage-engine` and `junit` dependencies in each pom.xml file.

**Pull request merged**
