### PR TITLE
Migrate azure security confidential ledger tests to use token auth.

### PR DESCRIPTION
**Pull request by anuchandy**

### CODE REVIEW

**Comment by g2vinay** [comment]
@anuchandy, we should validate the live tests too.

**Comment by anuchandy** [comment]
@g2vinay, sure, its green https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3920540&view=results

**Comment by anuchandy** [comment]
@g2vinay, the reason for the second live test run failure is, there is no quote left for a resource-group in test subscription.

**Review by g2vinay — APPROVED** [review]

**Comment by anuchandy** [comment]
@g2vinay - as discussed offline, I've removed the cert outputs from the ARM template as they are not needed.

**Pull request merged**
