### PR TITLE
Log request method in outgoing request to storage

### PR DESCRIPTION
**Pull request by SukruthKS**
Having request method helps with debugging.

### CODE REVIEW

**Comment by kurtzeborn** [comment]
Thanks for the suggestion/contribution!  @jianghaolu or @alzimmermsft should be able to review this for you.

**Comment by kurtzeborn** [comment]
Closing and reopening to kick of PR validation again.

**Comment by kurtzeborn** [comment]
@rickle-msft would you take a look at this please?  It's a change to the v11 code, so you're the best one to decide if this should be merged or not.

**Comment by rickle-msft** [comment]
@kurtzeborn I believe Snowflake has since moved off v11, and we are not planning on developing v11 further unless we really need to. Can @alzimmermsft or @jianghaolu verify if the request method is logged in Azure Core?

**Comment by kurtzeborn** [comment]
Marking this "Service Attention" since it is a change to track 1.5.  The storage team needs to review/merge this.

**Comment by rickle-msft** [comment]
We have verified that, depending on the log level, it is possible to log the HTTP request method in Azure Core, so this is supported in Storage v12. I am going to close this issue now as we are not actively developing v11.

@SukruthKS thank you very much for your contribution to this project. We look forward to continuing to work with you guys in the future!

**Pull request closed without merging**
