### PR TITLE
Added functionality to provide base unit for different vendors for client metrics

### PR DESCRIPTION
**Pull request by kushagraThapar**
Added functionality to provide base unit for different vendors for client metrics
Fixes: https://github.com/Azure/azure-sdk-for-java/issues/38828

### CODE REVIEW

**Comment by kushagraThapar** [comment]
Assigning @tvaron3 to take this forward.

**Review by FabianMeiswinkel — APPROVED** [review]
LGTM - Thanks

**Review by xinlian12 — APPROVED** [review]
LGTM, thanks

**Pull request closed without merging**
