### PR TITLE
Fix Cosmos DB Samples issue #31136

### PR DESCRIPTION
**Pull request by v-hongli1**
Fixes [#31136](https://github.com/Azure/azure-sdk-for-java/issues/31136)

@josefree, @KrzysztofCwalina, @kyle-patterson and @xinlian12 for notification.

### CODE REVIEW

**Comment by kushagraThapar** [comment]
@hongli750210 - why do we change this to 0? -1 should work. I wonder how you tested it?

**Comment by hongli750210** [comment]
@kushagraThapar

**Jar version:**
azure-cosmos: 4.37.0-alpha.20220926.2

**Test step as follows：**
1. Create Azure Cosmos DB for NoSQL in Azure portal.
2. Replace the properties of "CosmosClientBuilder" with the endpoint and primary key of the created Azure Cosmos DB
3. Run `main` method of test class `AnalyticalStorageCodeSnippet`

**Test Result:**
BadRequest exception occurs, exception infomation as follows:
Exception in thread "main" {"ClassName":"CosmosException","userAgent":"azsdk-java-cosmos/4.36.0-alpha.20220906.1 Windows11/10.0 JRE/17.0.4.1","statusCode":400,"resourceAddress":"https://cosmosdb4lh-westus.documents.azure.com:443/dbs/testDB/colls","error":"{\"code\":\"BadRequest\",\"message\":\"Message: {\\\"Errors\\\":[\\\"The input content is invalid - 'analyticalStorageTtl' is not a valid property in the current payload.\\\"]}\\r\\nActivityId: 0dd21efd-de4f-4f1d-b16e-1b126035f8e7, Request URI: /apps/6d65d659-c668-473c-a798-50083b67853c/services/8a8a2418-cb71-44f0-9615-d7e2adcf7a98/partitions/2b75256c-d3cc-4f29-89bd-5cb7e0b8c93f/replicas/133119468144684133p, RequestStats: , SDK: Microsoft.Azure.Documents.Common/2.14.0, StatusCode: BadRequest\",\"additionalErrorInfo\":null}","innerErrorMessage":"Message: {\"Errors\":[\"The input content is invalid - 'analyticalStorageTtl' is not a valid property in the current payload.\"]}\r\nActivityId: 0dd21efd-de4f-4f1d-b16e-1b126035f8e7, Request URI: /apps/6d65d659-c668-473c-a798-50083b67853c/services/8a8a2418-cb71-44f0-9615-d7e2adcf7a98/partitions/2b75256c-d3cc-4f29-89bd-5cb7e0b8c93f/replicas/133119468144684133p, RequestStats: , SDK: Microsoft.Azure.Documents.Common/2.14.0, StatusCode: BadRequest","causeInfo":null,"responseHeaders":"{Transfer-Encoding=chunked, x-ms-last-state-change-utc=Thu, 03 Nov 2022 11:00:17.017 GMT, x-ms-current-replica-set-size=4, Server=Microsoft-HTTPAPI/2.0, x-ms-request-duration-ms=1.674, x-ms-session-token=0:-1#15, lsn=15, x-ms-request-charge=0, x-ms-schemaversion=1.14, x-ms-transport-request-id=5224, x-ms-number-of-read-regions=1, x-ms-current-write-quorum=3, x-ms-cosmos-quorum-acked-llsn=15, x-ms-quorum-acked-lsn=15, Date=Fri, 04 Nov 2022 03:28:16 GMT, x-ms-activity-id=0dd21efd-de4f-4f1d-b16e-1b126035f8e7, Strict-Transport-Security=max-age=31536000, x-ms-xp-role=1, x-ms-global-Committed-lsn=15, x-ms-cosmos-llsn=15, x-ms-gatewayversion=version=2.14.0, x-ms-serviceversion=version=2.14.0.0, Content-Type=application/json}","requestHeaders":"[x-ms-cosmos-allow-tentative-writes=true, Accept=application/json, x-ms-date=Fri, 04 Nov 2022 03:28:15 GMT, Content-Type=application/json]","cosmosDiagnostics":{"userAgent":"azsdk-java-cosmos/4.36.0-alpha.20220906.1 Windows11/10.0 JRE/17.0.4.1","activityId":"0dd21efd-de4f-4f1d-b16e-1b126035f8e7","requestLatencyInMs":1189,"requestStartTimeUTC":"2022-11-04T03:28:15.377422300Z","requestEndTimeUTC":"2022-11-04T03:28:16.566755Z","responseStatisticsList":[],"supplementalResponseStatisticsList":[],"addressResolutionStatistics":{},"regionsContacted":["west us"],"retryContext":{"statusAndSubStatusCodes":null,"retryCount":0,"retryLatency":0},"metadataDiagnosticsContext":{"metadataDiagnosticList":null},"serializationDiagnosticsContext":{"serializationDiagnosticsList":[{"serializationType":"CONTAINER_SERIALIZATION","startTimeUTC":"2022-11-04T03:28:15.378422100Z","endTimeUTC":"2022-11-04T03:28:15.379422100Z","durationInMilliSecs":1.0}]},"gatewayStatistics":{"sessionToken":"0:-1#15","operationType":"Create","resourceType":"DocumentCollection","statusCode":400,"subStatusCode":0,"requestCharge":0.0,"requestTimeline":[{"eventName":"connectionCreated","startTimeUTC":"2022-11-04T03:28:15.379422100Z","durationInMilliSecs":929.2115},{"eventName":"connectionConfigured","startTimeUTC":"2022-11-04T03:28:16.308633600Z","durationInMilliSecs":0.0},{"eventName":"requestSent","startTimeUTC":"2022-11-04T03:28:16.308633600Z","durationInMilliSecs":1.9978},{"eventName":"transitTime","startTimeUTC":"2022-11-04T03:28:16.310631400Z","durationInMilliSecs":252.6953},{"eventName":"received","startTimeUTC":"2022-11-04T03:28:16.563326700Z","durationInMilliSecs":1.0282}],"partitionKeyRangeId":null,"exceptionMessage":"Message: {\"Errors\":[\"The input content is invalid - 'analyticalStorageTtl' is not a valid property in the current payload.\"]}\r\nActivityId: 0dd21efd-de4f-4f1d-b16e-1b126035f8e7, Request URI: /apps/6d65d659-c668-473c-a798-50083b67853c/services/8a8a2418-cb71-44f0-9615-d7e2adcf7a98/partitions/2b75256c-d3cc-4f29-89bd-5cb7e0b8c93f/replicas/133119468144684133p, RequestStats: , SDK: Microsoft.Azure.Documents.Common/2.14.0, StatusCode: BadRequest","exceptionResponseHeaders":"{Transfer-Encoding=chunked, x-ms-last-state-change-utc=Thu, 03 Nov 2022 11:00:17.017 GMT, x-ms-current-replica-set-size=4, Server=Microsoft-HTTPAPI/2.0, x-ms-request-duration-ms=1.674, x-ms-session-token=0:-1#15, lsn=15, x-ms-request-charge=0, x-ms-schemaversion=1.14, x-ms-transport-request-id=5224, x-ms-number-of-read-regions=1, x-ms-current-write-quorum=3, x-ms-cosmos-quorum-acked-llsn=15, x-ms-quorum-acked-lsn=15, Date=Fri, 04 Nov 2022 03:28:16 GMT, x-ms-activity-id=0dd21efd-de4f-4f1d-b16e-1b126035f8e7, Strict-Transport-Security=max-age=31536000, x-ms-xp-role=1, x-ms-global-Committed-lsn=15, x-ms-cosmos-llsn=15, x-ms-gatewayversion=version=2.14.0, x-ms-serviceversion=version=2.14.0.0, Content-Type=application/json}"},"systemInformation":{"usedMemory":"19034 KB","availableMemory":"4119974 KB","systemCpuLoad":"empty","availableProcessors":8},"clientCfgs":{"id":1,"machineId":"uuid:434d4ab0-9fea-401b-8556-ef576968718a","connectionMode":"DIRECT","numberOfClients":1,"clientEndpoints":{"https://cosmosdb4lh.documents.azure.com:443/":1},"connCfg":{"rntbd":"(cto:PT5S, nrto:PT5S, icto:PT0S, ieto:PT1H, mcpe:130, mrpc:30, cer:true)","gw":"(cps:1000, nrto:PT1M, icto:PT1M, p:false)","other":"(ed: true, cs: false, rv: false)"},"consistencyCfg":"(consistency: null, mm: true, prgns: [])"}}}

**Comment by kushagraThapar** [comment]
@hongli750210 - I just ran it locally and it works correctly for me, please see the below screenshot. Can you please try to set this property through azure portal directly and see how it works?
Also, worth pasting the complete stack trace of your exception. 

image

**Review by kushagraThapar — CHANGES_REQUESTED** [review]
Requesting changes until we figure out the root cause.

**Comment by hongli750210** [comment]
@kushagraThapar 
Atfer enable `Azure Synapse Link` of cosmos account, run `main` method of test class [`AnalyticalStorageCodeSnippet`](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos/src/samples/java/com/azure/cosmos/AnalyticalStorageCodeSnippet.java) again, the test case successfully. So I think occured `BadRequest` exception is related to this setting.

**Comment by kushagraThapar** [comment]
Thank you @hongli750210 for the investigation, appreciate you looking into this.

**Pull request closed without merging**
