### PR TITLE
azure-cosmos hotfix release 4.63.3 - avoiding possible CF hang

### PR DESCRIPTION
**Pull request by FabianMeiswinkel**
# Description

This PR is fixing a possible hang in `CosmosAsyncContainer.queryChangeFeed` under certain conditions. To cause a hang the following conditions need to be met
- The continuation token used has an even number of sub-ranges
- For all sub-ranges a 304/NotModified is returned
- One of the second or later sub-ranges is getting split

When any of the conditions above is not met (for example not for all sub-ranges a 304 is received or there is no sub-range being split, the hang would not have happened.

A test `CosmosContainerChangeFeedTest.split_only_notModified` has been added that describes and simulates the triggering conditions above to function as validation of the fix as well as regression test in the future.

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [x] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Review by kushagraThapar — APPROVED** [review]
LGTM, thanks @FabianMeiswinkel

**Review by xinlian12 — APPROVED** [review]
LGTM, thanks for the quick fix 👍

**Comment by xinlian12** [comment]
Run the following tests locally and passed:
readFeedDocumentsAfterSplit
readFeedDocumentsAfterSplit_maxScaleCount
tryGetAddresses_SuboptimalMasterPartition_Stale_DoRefresh

**Review by xinlian12 — APPROVED** [review]
LGTM, thanks

**Review by jeet1995 — APPROVED** [review]
LGTM - thanks!

**Comment by FabianMeiswinkel** [comment]
Manual test failures when executed locally run successfully. We have looked at the failures and are investigating especially the invalid first JSON character 0xab that is seen in several of the pipelines - but given the tests pass manually we will proceed with merging the PR.

**Pull request merged**
