### PR TITLE
Fix #31593: Proxy setting not work in Azure AD B2C web application

### LINKED ISSUE #31593: [BUG] Proxy setting not work in Azure AD B2C web application
### Context

1. https://github.com/Azure/azure-sdk-for-java/issues/31347
2. In [Azure AD B2C web application](https://github.com/Azure-Samples/azure-spring-boot-samples/tree/20cf052b184d8490eff4fd5551c7418b4b9fdbff/aad/spring-cloud-azure-starter-active-directory-b2c/aad-b2c-web-application), RestTemplate send the 2 http requests, both of them not supporting proxy setting.

> https://rujche220928.b2clogin.com/rujche220928.onmicrosoft.com/oauth2/v2.0/token?p=B2C_1_sign_in_sing_up
https://rujche220928.b2clogin.com/rujche220928.onmicrosoft.com/discovery/v2.0/keys?p=B2C_1_sign_in_sing_up

### Goal

Make sure all http requests send out by RestTemplate in [Azure AD B2C web application](https://github.com/Azure-Samples/azure-spring-boot-samples/tree/20cf052b184d8490eff4fd5551c7418b4b9fdbff/aad/spring-cloud-azure-starter-active-directory-b2c/aad-b2c-web-application) supporting configure Proxy.

### PR DESCRIPTION
**Pull request by chenrujun**
Fix #31593: Proxy setting not work in Azure AD B2C web application.

1. Fix proxy setting for RestOperation which send http request to **https://{directory-name}.b2clogin.com/{directory-name}.onmicrosoft.com/oauth2/v2.0/token?p={flow-name}**.
2. Fix proxy setting for RestOperation which send http request to **https://{directory-name}.b2clogin.com/{directory-name}.onmicrosoft.com/discovery/v2.0/keys?p={flow-name}**.
3. Add unit tests and refactor tests.

### CODE REVIEW

**Review by saragluna — COMMENTED** [review]
The circular dependency is not fixed in this PR, right?

**Comment by chenrujun** [comment]
@saragluna 

> The circular dependency is not fixed in this PR, right?

Yes.

**Comment by chenrujun** [comment]
Hi, @saragluna , @moarychan , please help to review this PR when you have time.

**Review by moarychan — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
