### PR TITLE
mgmt, delete track1 mgmt sdks

### PR DESCRIPTION
**Pull request by weidongxu-microsoft**
Archived as tag `mgmt-release-v2`

https://github.com/weidongxu-microsoft/azure-sdk-for-java/commit/327bc06a035ccf872d71988ea5a1108f51a92405 done by script https://github.com/weidongxu-microsoft/misc-automation/blob/master/sdk_clean.py

I cannot remove `jetty.xml` in project root, as it is referred in data-plane track1 SDKs e.g. https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/keyvault/microsoft-azure-keyvault/pom.xml#L164

### CODE REVIEW

**Review by ChenTanyi — APPROVED** [review]

**Comment by weshaggard** [comment]
Is it safe to remove things like https://github.com/azure/azure-sdk-for-java/blob/main/eng/pipelines/templates/stages/archetype-sdk-management.yml now as well?

**Comment by weshaggard** [comment]
Once this change goes in we probably also need to clean-up *-mgmt-* pipelines from Devops.

**Comment by weidongxu-microsoft** [comment]
Thanks @weshaggard , remove that `eng/pipelines/templates/stages/archetype-sdk-management.yml` as well.

**Review by weshaggard — APPROVED** [review]
It is impossible to review this PR but I took a scan through the branch and nothing else jumped out at me. There might be some more clean-up but that can be done as a follow-up.

**Pull request merged**
