### PR TITLE
Move response error to azure-core

### PR DESCRIPTION
**Pull request by srnagar**
After discussing with @JonathanGiles, renamed HttpResponseError to ResponseError and is now moved from experimental to azure-core package. Also, deleted TimeInterval from azure-core-experimental as the arch board feedback was to move this type to azure-monitor-query package.

### CODE REVIEW

**Review by vcolin7 — APPROVED** [review]
LGTM

**Comment by vcolin7** [comment]
Is there anything outside of core experimental using this type?

**Comment by srnagar** [comment]
> Is there anything outside of core experimental using this type?

Yes, azure-monitor-query is using it. I will update it in a separate PR to take an unreleased dependency on azure-core.

**Review by mssfang — APPROVED** [review]

**Review by vcolin7 — APPROVED** [review]
LGTM. Let's remember to remove the unreleased entry from `version_client.txt` once we release :)

**Pull request merged**
