### PR TITLE
Make nightly and weekly pipeline use different cloud configuration

### PR DESCRIPTION
**Pull request by backwind1233**
## Background
Now we have pipeline  `java - spring - tests-weekly` and `java - spring - tests`
The two pipelines will run tests on "Public,UsGov,China", which will take a lot of time and resources.

## Goal
We hope that  
- `java - spring - tests-weekly` run tests on "Public,UsGov,China"
- `java - spring - tests` run on only "Public"

this PR is for this purpose.

### CODE REVIEW

**Comment by saragluna** [comment]
So the `java - spring - tests-weekly` pipeline will pass the `Clouds` as `Public, US, China`?

**Review by saragluna — APPROVED** [review]

**Comment by backwind1233** [comment]
> So the `java - spring - tests-weekly` pipeline will pass the `Clouds` parameter as `Public, US, China`?

Yes, I think so

**Review by fangjian0423 — APPROVED** [review]

**Review by benbp — APPROVED** [review]

**Pull request merged**
