### PR TITLE
Fixing Spark samples (Typo in config name) and removing SqlQuerySpec.toPrettyString from public Api

### PR DESCRIPTION
**Pull request by FabianMeiswinkel**

### CODE REVIEW

**Review by kushagraThapar — APPROVED** [review]
LGTM, thanks @FabianMeiswinkel

**Review by moderakh — APPROVED** [review]
LGTM. Thanks

**Comment by FabianMeiswinkel** [comment]
/check-enforcer override

Flakiness in Encryption CI pipeline - unrelated to the payload being changed

**Pull request merged**
