### PR TITLE
Repo level repo has a slightly typo: `migraton guide` -> `migration guide`

### PR DESCRIPTION
**Pull request by richardpark-msft**

### CODE REVIEW

**Comment by richardpark-msft** [comment]
@srnagar: I'd like this to count towards my Java credits, which I will cash in later to buy several bouncy balls and possibly some gum.

**Review by srnagar — APPROVED** [review]
Thanks, @richardpark-msft! You're welcome to cash in your Java credits any time!

**Comment by richardpark-msft** [comment]
Overrode checkenforcer as no CI pipelines run for the readme update (apparently)

**Pull request merged**
