### PR TITLE
Fix issue with JDK HttpClient being used in Java 8

### PR DESCRIPTION
**Pull request by alzimmermsft**
# Description

Fixes an issue, until a new release of `azure-core` happens with more resilient service provider loading, where `azure-core-http-jdk-httpclient` is used in Java 8, failing tests as it requires a bytecode level of Java 11 (and runtime of Java 12+).

There are a mixture of fixes in this PR:

- Some libraries exclude `azure-core-jdk-httpclient` from `azure-core-test`, preventing it being on the classpath.
- Some libraries have fixes to test code to use the helper methods in `azure-core-test` which is resilient to service provider loading errors. There is also a follow-up PR into TypeSpec Java to use these APIs in generated test code https://github.com/microsoft/typespec/pull/4520
- Some libraries have fixes to test code to use mock `HttpClient`s when there isn't a real API call being made, such as just testing client building.

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [x] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Review by joshfree — APPROVED** [review]
Reviewed changes; largely global search and replace 👍

**Review by weidongxu-microsoft — APPROVED** [review]
LGTM on mgmt.

However there is some strange errors.
```
[ERROR] Errors: 
[ERROR]   VirtualMachineMockTests.listByVmssByIdWithNextLinkEncoded:61->mockComputeManager:81 IllegalAccess class com.azure.resourcemanager.compute.implementation.VirtualMachineMockTests (in module com.azure.resourcemanager.compute) cannot access class com.azure.core.http.netty.NettyAsyncHttpClientBuilder (in module com.azure.http.netty) because module com.azure.resourcemanager.compute does not read module com.azure.http.netty
```

**Comment by weidongxu-microsoft** [comment]
You can ignore the Analyze CI error in healthinsights. We didn't update generated code in healthinsights, to avoid conflict with their GA PR.

**Comment by XiaofeiCao** [comment]
> LGTM on mgmt.
> 
> However there is some strange errors. https://dev.azure.com/azure-sdk/public/_build/results?buildId=4167412&view=logs&j=897b348b-d674-5d99-9e0e-0245653618bd&t=2bb04035-1b59-5413-7d30-58278d7f92bf&l=2050
> 
> ```
> [ERROR] Errors: 
> [ERROR]   VirtualMachineMockTests.listByVmssByIdWithNextLinkEncoded:61->mockComputeManager:81 IllegalAccess class com.azure.resourcemanager.compute.implementation.VirtualMachineMockTests (in module com.azure.resourcemanager.compute) cannot access class com.azure.core.http.netty.NettyAsyncHttpClientBuilder (in module com.azure.http.netty) because module com.azure.resourcemanager.compute does not read module com.azure.http.netty
> ```
> 
> @XiaofeiCao Could you take a look?

I've replaced netty HttpClient with mock HttpClient. Should fix the error.

**Comment by alzimmermsft** [comment]
Given this PR runs so many pipelines, I'll have a follow-up PR to fix the failing steps in AppConfiguration. Identity and Resource Manager are failing with flaky issues that will just take re-runs to resolve.

**Pull request merged**
