### PR TITLE
Mgmt: remove catch exception Samples

### PR DESCRIPTION
**Pull request by ChenTanyi**
catch exception make playback harder to see the exception, so change

### CODE REVIEW

**Review by weidongxu-microsoft — APPROVED** [review]
Log the commit id when merge, be prepared to revert it after the playback issue get solved.

Testing issue is not a good reason for changing sample code.

**Comment by ChenTanyi** [comment]
I add the PR is because I think it should be changed. Otherwise, I would just close it. (I don't need such PR for testing)
I don't think catch a whole exception in `runSample` is a good choice (for running, actually the `main` function has another catch).

**Comment by ChenTanyi** [comment]
This mainly reason is for future playback, Since playback test errors in `Azure` and `Samples` can hardly find the reason in log.

**Comment by weidongxu-microsoft** [comment]
Then don't write such reason like
> catch exception make playback harder to see the exception, so change

if you do not do the change because of it.

Also, generally speaking, method throw `Exception` type is not recommended.

Personally, for try-catch in sample, it is reasonable to do so, if the try-catch actually is in a place that potentially have error (e.g. no permission, no access, file not found, failed to create credential, etc.), with good suggestion in message, which helps user to successfully run the sample. Though I guess none of us bother to improve this at present.

If all of these are just routine `catch` above `finally`, you are OK to remove them.

**Comment by ChenTanyi** [comment]
My main reason is for playback (future playback in pipeline) so I write it in the first comment.

throw `Exception` is because I don't want to add every exception manually. Is it any fast way to add such specific exception?

All remove `catch` blocks are directly followed by `return true` (with which I write the regex)

**Comment by ChenTanyi** [comment]
It seem the `UrlParer` has problem? 

Previously, I also saw another from it (cast error from HashMap#Node to HashMap#TreeNode)
Both are Java 8 on MacOS
image
image

**Comment by weidongxu-microsoft** [comment]
I guess majority of the samples does not need a `throws`, except for a few cases that got other than `RuntimeException`.

**Comment by ChenTanyi** [comment]
changed to specific exception

**Review by weidongxu-microsoft — APPROVED** [review]

**Pull request merged**
