### PR TITLE
fix: trim middle space in javadoc for checkstyle

### PR DESCRIPTION
**Pull request by ChenTanyi**
After do some checkstyle, I found it crazy to trim every middle space in comment. So I write a script to trim all together.

### CODE REVIEW

**Comment by weidongxu-microsoft** [comment]
Please keep you script safe. For newly migrated service, they might want to run that again. :-)

**Comment by ChenTanyi** [comment]
OK, I'll upload my script to.

**Comment by weidongxu-microsoft** [comment]
Just put it in your repo and let us know.

**Comment by ChenTanyi** [comment]
Done, here https://github.com/ChenTanyi/work-script/blob/master/trim_middle_space.py

**Pull request merged**
