### PR TITLE
mgmt, providerhub, add live tests

### PR DESCRIPTION
**Pull request by v-hongli1**
relate to https://github.com/Azure/azure-sdk-for-java/issues/35316

# Description

Please add an informative description that covers that changes made by the pull request and link all relevant issues.

If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.

# All SDK Contribution checklist:
- [ ] **The pull request does not introduce [breaking changes]**
- [ ] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [ ] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Review by weidongxu-microsoft — APPROVED** [review]
Do you have any doc what providerhub does?

**Comment by XiaofeiCao** [comment]
From Bing:
> Azure Provider Hub is a service that provides a set of APIs for managing Azure resource providers. It is used by Azure Resource Manager (ARM) to manage resource providers. The provider hub is responsible for managing the registration of resource providers and their associated operations. [It also provides a set of APIs for managing custom rollouts and default rollouts for resource providers](https://learn.microsoft.com/en-us/cli/azure/providerhub?view=azure-cli-latest)[1](https://learn.microsoft.com/en-us/cli/azure/providerhub?view=azure-cli-latest)[2](https://learn.microsoft.com/en-us/dotnet/api/overview/azure/ResourceManager.ProviderHub-readme?view=azure-dotnet)

Seems Hong's test is about defining ARM operations using providerhub SDK...

**Review by XiaofeiCao — APPROVED** [review]

**Comment by weidongxu-microsoft** [comment]
> From Bing:
> 
> > Azure Provider Hub is a service that provides a set of APIs for managing Azure resource providers. It is used by Azure Resource Manager (ARM) to manage resource providers. The provider hub is responsible for managing the registration of resource providers and their associated operations. [It also provides a set of APIs for managing custom rollouts and default rollouts for resource providers](https://learn.microsoft.com/en-us/cli/azure/providerhub?view=azure-cli-latest)[1](https://learn.microsoft.com/en-us/cli/azure/providerhub?view=azure-cli-latest)[2](https://learn.microsoft.com/en-us/dotnet/api/overview/azure/ResourceManager.ProviderHub-readme?view=azure-dotnet)
> 
> Seems Hong's test is about defining ARM operations using providerhub SDK...

Yeah, I just not think we have permission to modify that.

**Pull request merged**
