### PR TITLE
Increasing clone depth because some builds are failing.

### PR DESCRIPTION
**Pull request by mitchdenny**

### CODE REVIEW

**Comment by weshaggard** [comment]
Do we understand why some builds are failing because of depth 1?

**Comment by mitchdenny** [comment]
> Do we understand why some builds are failing because of depth 1?

My understanding (based on the [PR that first introduced shallow fetching](https://github.com/microsoft/azure-pipelines-agent/pull/620/files)) is that it is some kind of race condition where the pack that Git prepares for the client doesn't contain the commit that you end up wanting to check out. I'm not sure why it happens but I recall that increasing the depth seems to mitigate the issue.

**Comment by mitchdenny** [comment]
I'm closing this down. Looks like it might have just been a glitch it hasn't been happening since then.

**Pull request closed without merging**
