### PR TITLE
Fix bug: Registered the empty value for ineligible definition, it causes NPE when sending message via bean `StreamBridge`

### PR DESCRIPTION
**Pull request by moarychan**
# Description

Fixes https://github.com/Azure/azure-sdk-for-java/issues/43366

After [migration](https://github.com/Azure/azure-sdk-for-java/pull/42022/files#diff-481183b31f785de5ff5368f427726dabf1b0dde311c0c9c29f81628ea6e94143) to `azure-servicebus-jms` lib , the passwordless property source should be removed.

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [ ] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Review by saragluna — APPROVED** [review]

**Comment by ofirgrm** [comment]
Hi @moarychan would you be able to tell me in which version I will be able to get this fix? We are waiting to run the upgrade from Spring Boot 3.3.6 to 3.4.1 and this issue is blocking us.

Thanks.

**Comment by moarychan** [comment]
Hi @ofirgrm , it's 5.20.0, normally it would be released this month.

**Comment by kaliy** [comment]
Hi @moarychan any news on releasing 5.20.0? Thanks

**Comment by saragluna** [comment]
We are working on the release now, and it will take 1 or 2 days to complete. Please stay tuned.

**Pull request merged**
