### PR TITLE
Upgrade JCommander Version

### PR DESCRIPTION
**Pull request by alzimmermsft**
Upgrading JCommander from `1.58` to `1.78` to mitigate CVE associated with `1.58`.

### CODE REVIEW

**Review by conniey — APPROVED** [review]

**Comment by alzimmermsft** [comment]
@kushagraThapar could you verify that this doesn't affect the Cosmos benchmark libraries.

**Comment by moderakh** [comment]
@alzimmermsft I triggered the full test suite. It will run the benchmark tests as well.
I would expect to impact, but to be safe let's wait for the full test suite.

**Comment by mikeharder** [comment]
I needed to cancel this test run to free up build agents for releases.  I will reply on this PR when it's safe to run again.

**Comment by alzimmermsft** [comment]
@moderakh with the pipelines that were able to run do we believe we have enough information to validate that the change is safe? Looking at those which failed it seemed it was either test cases or installation steps that failed and not running the benchmarks.

**Comment by moderakh** [comment]
> @moderakh with the pipelines that were able to run do we believe we have enough information to validate that the change is safe? Looking at those which failed it seemed it was either test cases or installation steps that failed and not running the benchmarks.

the CIs which run the benchmark ares the ones ending in "_E2E" (there are 5) and none is completed. we should wait for at least one of those 5 CIs to complete.

**Comment by mikeharder** [comment]
It should be OK to run tests again.

**Review by moderakh — APPROVED** [review]
cosmos relevant tests passed. Thanks @alzimmermsft

**Pull request merged**
