### PR TITLE
Fixing http client spy framework for single argument http send method

### PR DESCRIPTION
**Pull request by simplynaveen20**
SpyClientUnderTestFactory throwing error on initHttpRequestCapture if cosmos client is using httpClient(HttpRequest) overload .
This is observed when current PRs failing on full CI with error in GoneAndRetryPolicyWithSpyClientTest.java.

It was visible after client telemetry PR where we using httpClient(HttpRequest) overload and not httpClient(HttpRequest, Duration). And as GoneAndRetryPolicyWithSpyClientTest runs only in full CI therefore it got went unnoticed.

Fixing the root problem to avoid this in future issue.

### CODE REVIEW

**Review by FabianMeiswinkel — APPROVED** [review]
Thanks - LGTM

**Review by kushagraThapar — CHANGES_REQUESTED** [review]
These changes have already been done in this PR - https://github.com/Azure/azure-sdk-for-java/pull/20721
Blocking this PR to avoid merge conflicts. 
Will close this once the other PR goes in. Hopefully today.

**Comment by kushagraThapar** [comment]
Closing this PR, as the other PR has been merged https://github.com/Azure/azure-sdk-for-java/pull/20721

**Pull request closed without merging**
